### ISSUE TITLE
Add RTMFP protocol based on MonaServer2 code 

### ISSUE THREAD

**Issue by al-sabr** [xia-chu/ZLMediaKit#225]
Greetings I would like to know if it possible with the current architecture to hook up the RTMFP protocol as a rendez-vous service for this project?

Reference :

https://github.com/MonaSolutions/MonaServer2/tree/master/MonaCore/sources/RTMP

**Comment by xiongziliang** [comment]
Thank you very much for your suggestion. I'm on vacation, so I'm sorry to reply to you now!
I will take the time to study the necessity and feasibility of implementing this feature later, thank you!

**Comment by gdeverlant** [comment]
Thank you for reply yeah it will be amazing if this goes into new features.

I made a mistake with the URL this is the right one.
https://github.com/MonaSolutions/MonaServer2/blob/master/MonaCore/sources/RTMFP/RTMFP.cpp

**Comment by gdeverlant** [comment]
Any update for this?

**Comment by xiongziliang** [comment]
There is no future for flash and RTMP protocols. I don't want to spend too much time and energy on them. Besides, I learned that rtmfp is a UDP based protocol, which has nothing to do with live stream media, so I do not decided to support the protocol. i am sorry for that I've been busy with other things recently and i didn't reply to you in time。

**Comment by gdeverlant** [comment]
Ohh that's not true concerning Flash. I can prove you that other than Browser Flash will run no problem without the Plugin.

Command line Actionscript : http://www.redtamarin.com/about/description
Desktop/Mobile : https://www.adobe.com/products/air.html
Web browser without plugin : https://royale.apache.org/
CheerpX : https://www.leaningtech.com/pages/cheerpx.html
Ruffle: https://github.com/ruffle-rs/ruffle

Don't trust the click bait about Actionscript & Flash.

**Comment by xiongziliang** [comment]
Thank you for your enthusiasm. I've decided to try to implement the rtmfp protocol in some days.

**Comment by al-sabr** [comment]
Thank you for the change of mind

**Comment by al-sabr** [comment]
Any update on this ?

**Comment by al-sabr** [comment]
Any update ?

**Comment by al-sabr** [comment]
I hope that all is going well for you!
If you are in difficult time then I pray for your well being.

**Comment by xia-chu** [comment]
I'm sorry that I'm very busy recently. I don't know how to reply to you. I have a lot of things to do now. I'm also an amateur to maintain this project. There are many more important things to do. I don't know when to realize your requirements.

So let you down. However, it may be that after some time, I will finish the task before I start to realize your requirement. However, I can't guarantee the date。

To tell you the truth, the demand you mentioned is not urgently needed by everyone. I now need a lot of time to fix bugs and improve projects, and I'm busy at work during the day. I really don't know how to answer you... 
But I won't close your issue until it is realized.

**Comment by xia-chu** [comment]
This project is developed all most by myself. I really don't have enough energy. Last year and the year before last, I had plenty of time, and the project's influence was not big enough, so I still have enough time. Starting this year, I feel that the time is running out. You can see that there are many demands in the issue, which are not completed

**Comment by al-sabr** [comment]
Ok no problem man I do understand and I am by your side. I don't know his project but if you guide me to show where to start I might help a bit. I will do my best if you support me with some wise guidance.

**Comment by al-sabr** [comment]
Actually you don't need to write anything it is just taking that other code and injecting it in the current structure of your code. All the work is done already but it was not design for this project only.

**Comment by xia-chu** [comment]
zlmediakit support udp socket,  this is simple udp sample:
https://github.com/xia-chu/ZLToolKit/blob/master/tests/test_udpSock.cpp

**Comment by xia-chu** [comment]
After a brief look at rtmfp protocol, I feel that it is a UDP signaling server, which seems not very complicated. However, there is little information about this on the Internet, and I don't know how to test it

**Comment by al-sabr** [comment]
> However, there is little information about this on the Internet, and I don't know how to test it

Don't worry about it: 

https://drive.google.com/file/d/0B21tGxCEiSXGcHpYTkNOMHVvXzg/view
https://tools.ietf.org/html/rfc7016
https://tools.ietf.org/html/rfc7425
https://www.ietf.org/proceedings/77/slides/tsvarea-1.pdf

I am also uploading videos for you :D

**Comment by al-sabr** [comment]
> I don't know how to test it

Don't worry I got your back on this one :

https://github.com/MonaSolutions/librtmfp

Test of the client RTMFP : https://github.com/MonaSolutions/librtmfp/tree/master/TestClient

**Comment by al-sabr** [comment]
<iframe width="640" height="360" frameborder="0" src="https://mega.nz/embed/yU9FSb6B#sp26Hgpz4vWSzN2rkjsEtMFWwkdb1yjHWg3xyWecmcs" allowfullscreen ></iframe>

**Comment by xia-chu** [comment]
You are such a serious and enthusiastic person. Thank you。
The above information is very useful。

**Comment by al-sabr** [comment]
Well I think that helping someone always gave me joy and gratitude. And what I can't do maybe you can achieve and what you can't achieve I might be able to help.

Helping others should be natural like breathing and I just had your missing parts concerning knowledge.

I'm telling you there is not coincidences :D 

I hope it can support you in the right way.

**Comment by al-sabr** [comment]
I forgot to link the following PDF document for your understanding.

[Group Audio Application with Flash Multicast Streaming Based on RTMFP.pdf](https://github.com/xia-chu/ZLMediaKit/files/5064336/Group.Audio.Application.with.Flash.Multicast.Streaming.Based.on.RTMFP.pdf)

**Comment by al-sabr** [comment]
Is there any documentation concerning the architecture of this project? Is there an introduction about how to understand the internal with Schemas or diagrams?

This might be a good opportunity to learn.

Kind Regards

**Comment by xia-chu** [comment]
Wikis are basically using related documents. I didn't write the architecture related documents.
Basically, the code related documents are not perfect. You can only look at the code to understand the overall structure. There are some comments in the code, but they are all in chinese.

Sorry, I don't have much time to maintain and develop this project, it takes a lot of time to develop new features and fix bugs, so i don't have much time to perfect documentation。

**Comment by al-sabr** [comment]
No problem for comments in Chinese I can use google translate :D
