### ISSUE TITLE
版主能详细解释下零拷贝原理和应用范围及zlmedaikit的应用范围

### ISSUE THREAD

**Issue by jingtian2163** [xia-chu/ZLMediaKit#287]
## 问题1
跨线程零内存拷贝我很好奇：是利用引用计数来实现 读写的时候自枷锁（不明白怎么能在跨线程的时候保证读写不在同一个内存地址），现在我们的内存模型，还是基于c98 的这种生产消费者模型，枷锁粒度可能比较小，可是做不到零拷贝，例如采集-》前处理-》编码-》h264数据分发，一帧数据起码要在这4个线程拷贝多次，能用零拷贝减少内存拷贝吗?

## 问题2
服务器实现的这些协议，我看可以直接用到公网，但是rtp这边是不是只能在局域网这边，因为udp这边没有qos协议，无法对抗网络抖动；（问这个问题主要是公司服务器太烂， 4核/8 g 或者2核/4g,带宽只敢开到300M ，上G 的带宽，造成负载也就500路以下，他们说是720P  2M 的带宽，所以 一台设备就500x2 = 1G ,这么多路视频，不可能每路都是720p，小分辨率居多，我觉得分发我们这边没有做灵活）

**Comment by xiongziliang** [comment]
## 1、问题1
### 回答
ZLMediaKit在分发数据时，不会存在内存拷贝 ，也就是说，在10个人播放时，和1000个人播放时，应用层内存拷贝的次数都是固定的。这样内存读写速度瓶颈的到来会晚很多，并不会由于播放人数的上升，导致内存拷贝次数的上升。

我们知道，ZLMediaKit是多线程的，一般而言，多线程的程序，线程间内存共享很难做线程安全，通常的做法是，每跨线程共享一遍就拷贝一次，每个线程只对自己拷贝的那份数据负责声明周期。

那么ZLMediaKit怎么来防止内存拷贝呢？答案是引用计数(智能指针)。流媒体的应用场景一般是1个生成者（1个推流器），多个消费者(多个播放器)，这样情况下，数据写线程只会有一个，但是读线程会有多个。但是读线程读的时间有早晚，我们要控制这块数据的释放时机很难，很可能其他线程还来不及读这个数据，就提前销毁了(这样势必导致访问悬垂指针)。

而C++11的智能指针(shared_ptr)能很好的解决这个问题，如果说，我们这些线程共享的不是这个数据本身，而是这个数据的智能指针，那么最晚持有这个数据的线程负责释放这块内存即可，这样既不用内存拷贝，也不用担心内存的生命周期问题，能很好的解决我们上述的难题。

智能指针通过引用计数来控制对象的生命周期，当引用计数为0时，说明没有任何对象(或者说栈)持有该内存，那么就可以释放该对象。智能指针每次拷贝一次(对象本身不拷贝)，引用计数加1，每析构一次，引用计数减1，这个技术是原子操作的，也就是线程安全的。

ZLMediaKit里面的数据包(包括RTP/RTMP)，都是用智能智能包裹的，在Socket层(ZLToolKit)同样采用智能指针对象管理，这些对象抽象为Buffer类，我们都用Buffer类的智能指针来发送数据包。

同时，我们在协议转发时，针对客户端类型的不同，我们也是尽量用Buffer对象接口标准的方式做数据偏移处理(而不是做内存拷贝)：
![image](https://user-images.githubusercontent.com/11495632/80578603-4bf0d780-8a3b-11ea-9a7c-ff0b2b979afa.png)
![image](https://user-images.githubusercontent.com/11495632/80578636-5d39e400-8a3b-11ea-88a9-e5af4aece4ac.png)


### 相关代码
 - ZLMediaKit的网络发送接口：
![image](https://user-images.githubusercontent.com/11495632/80576107-337ebe00-8a37-11ea-91a0-a1704e2eabfb.png)

 - 数据包对象定义：
![image](https://user-images.githubusercontent.com/11495632/80576206-5d37e500-8a37-11ea-95f1-66b25da24085.png)

 - sendmsg优化(减少系统调用)：
![image](https://user-images.githubusercontent.com/11495632/80576432-bf90e580-8a37-11ea-9d8c-57253f0fc659.png)

- 合并写(减少系统调用)：
![image](https://user-images.githubusercontent.com/11495632/80576535-f666fb80-8a37-11ea-8b7f-b40bdce1fbd8.png)

![image](https://user-images.githubusercontent.com/11495632/80576490-de8f7780-8a37-11ea-864f-81472b287ab0.png)

![image](https://user-images.githubusercontent.com/11495632/80576702-3a5a0080-8a38-11ea-8b4e-c0877304c524.png)

![image](https://user-images.githubusercontent.com/11495632/80576774-5a89bf80-8a38-11ea-9533-ee1dbf050b82.png)

**Comment by xiongziliang** [comment]
## 问题1补充回答
ZLMediaKit在跨线程共享RTP/RTMP包时，是通过批量线程切换的方式进行的，也是通过智能指针共享数据：

![image](https://user-images.githubusercontent.com/11495632/80579217-3c25c300-8a3c-11ea-82e1-a8ee88d822d0.png)

**Comment by xiongziliang** [comment]
##2、问题2
在公网情况下尽量不要用udp，因为现在开源的成熟的可靠 udp方案 比较少，而且都不是特别成熟和完善。

如果是RTC(视频互动)这种超低延时场景，或者追求压榨弱网情况下网络性能，那么可以考虑使用可靠udp方案(rudp)，否则没必要。

RTSP和GB28181中，如果使用udp传输rtp，那么很大记录会存在丢包花屏，应该这些协议都没有QOS相关设计。

**Comment by liuwen-nj** [comment]
pr.first->async([second, in, is_key]()
采用异步的方式转发数据，避免阻塞等待。这个因为是引用，所以没有拷贝，等待所有的调用结束之后，智能指针自动回收。
