### ISSUE TITLE
关于RTP格式PS视频流代理的支持建议

### ISSUE THREAD

**Issue by swwheihei** [xia-chu/ZLMediaKit#339]
在安防监控领域，上下级级联是很重要的一个应用场景。
即下级摄像头向下级ZLM推PS流，下级ZLM向上级ZLM推PS流，上级ZLM转换成WS-FLV等格式进行播放。
希望ZLM能够支持这种特性。
非常感谢！

**Comment by xiongziliang** [comment]
嗯 会抽时间搞这个的 只会支持纯粹ps-rtp转发 其他协议不会转ps-rtp

**Comment by swwheihei** [comment]
能提供大约的里程碑计划吗？
烦请实现之后在此issue中答复一下。
非常感谢！

**Comment by xiongziliang** [comment]
关了干嘛？开着吧，开着能提醒我做这些事

**Comment by swwheihei** [comment]
老大，求支持啊

**Comment by swwheihei** [comment]
其他协议不会转ps-rtp，是因为工作量还是技术上无法实现？

**Comment by xia-chu** [comment]
> 其他协议不会转ps-rtp，是因为工作量还是技术上无法实现？

工作量比较大老哥

**Comment by xiamuran1** [comment]
> > 其他协议不会转ps-rtp，是因为工作量还是技术上无法实现？
> 
> 工作量比较大老哥

最近急需要ZLM向外推送ps流国标流，目前大概的思路是：实现http接口，实例化自己实现的推送ps流类，绑定RtspMediaSource源获取rtp数据包，再把这个rtp包重组rtp+ps+视频数据然后使用tcp或者udp发送出去，poller是根据TcpClient或者Socket中直接获取的。rtp重组ps包、poller获取或者其他地方是否有问题？

**Comment by xia-chu** [comment]
你要所有协议支持rtp-ps推流也不是不可以，但是要实现以下功能：
1、从RtspMediaSource、RtmpMediaSource、HlsMediaSource(任一即可)中获取音视频 相关Track。
2、通过Track::addDelegate函数获取各个Track的Frame。
3、这些Frame打包成PS。
4、PS打包成RTP。
5、把RTP以UDP或TCP方式发送出去。

**Comment by xiamuran1** [comment]
> 你要所有协议支持rtp-ps推流也不是不可以，但是要实现以下功能：
> 
> * 1、从RtspMediaSource、RtmpMediaSource、HlsMediaSource(任一即可)中获取音视频 相关Track。
> * 2、通过Track::addDelegate函数获取各个Track的Frame。
> * 3、这些Frame打包成PS。
> * 4、PS打包成RTP。
> * 5、把RTP以UDP或TCP方式发送出去。

好的，我先按照这个思路整整看，多谢支持

**Comment by swwheihei** [comment]
@xia-chu 求大佬实现RTP代理推流，要实现级联功能了

**Comment by swwheihei** [comment]
纯粹的ps-rtp转发就行

**Comment by xia-chu** [comment]
#366 
该特性已经实现。
