### ISSUE TITLE
关于阶段性推送视频流的处理

### ISSUE THREAD

**Issue by swwheihei** [xia-chu/ZLMediaKit#340]
在安防监控场景中，大华NVR在使用录像回放时，其会集中推送3-5秒的数据流，然后停顿等待，再集中推送3-5秒的数据流，导致播放时会在快速播放、卡顿、快速播放、卡顿，用户体验非常差劲。
建议ZLM对这种情况进行优化处理

**Comment by xiongziliang** [comment]
目前zlm里面已经有相关逻辑，hls播放器支持这个特性，后面可以移植到ps-rtp相关模块，我后面加个配置，选择是否打开这个特性，因为这个特性比较消耗资源

**Comment by swwheihei** [comment]
能提供大约的里程碑计划吗？
烦请实现之后再次issue中答复一下。
非常感谢！

**Comment by xiongziliang** [comment]
关了干嘛？开着吧，开着能提醒我做这些事

**Comment by xia-chu** [comment]
这个停顿3~5秒，然后批量发送的特性，应该不至于导致播放器卡顿吧？播放器为了流畅，会缓存一定的数据的。

**Comment by xia-chu** [comment]
这个特性就是所谓的合并写嘛
