### ISSUE TITLE
是支持计划添加WEBRTC到RTMP服务器

### ISSUE THREAD

**Issue by zsinba** [xia-chu/ZLMediaKit#357]
通过WEBRTC推到RTMP服务器，然后通过RTMP或者RTSP或者FLV播放。

 是否有此计划？

**Comment by xiongziliang** [comment]
webrtc是个巨大的工作，目前不是个人能独立完成的，一是事件不允许，二是能力不允许啊。

**Comment by xiongziliang** [comment]
后面有机会通过其他开源webrtc服务器实现这一功能，不过看情况，毕竟我的时间很有限啊

**Comment by zsinba** [comment]
谢谢，你是最棒的。

**Comment by 648540858** [comment]
> 谢谢，你是最棒的。

推荐你当前可以使用janus。自带一个流插件，可以将视频流转化为webrtc播放

**Comment by xiongziliang** [comment]
我也在做janus插件 用cpp做的 它自带的插件代码太多了 阅读体验太差了 后面看情况能不能基于janus实现下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 648540858 <notifications@github.com&gt;
发送时间: 2020年7月16日 09:23
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357)





  
谢谢，你是最棒的。
  
推荐你当前可以使用janus。自带一个流插件，可以将视频流转化为webrtc播放

**Comment by wanghuan578** [comment]
找些人才一起做，srs现在就是在找人堆功能。

**Comment by xia-chu** [comment]
> 找些人才一起做，srs现在就是在找人堆功能。

你说的基本不现实 这样的人才凭什么不开个项目自己弄？

**Comment by xia-chu** [comment]
不关闭吧 开着提醒我做这个

**Comment by ywcai** [comment]
srs的也测试了一段时间，服务器经常出现崩溃，另外他的webrtc效果也不好，基本无法用于生产。
跪等楼主集成webrtc，如果能力允许原协助楼主做些工作。

**Comment by anzangun** [comment]
最近项目需要需要用到类似的功能。
我是用kurento和kurento-rtmp接入WEBRTC并输出成rtmp。如果需要转协议，可以使用工程的拉流功能关联起来。在这里记录一下另外一种接入思路。
kurento工程地址：https://github.com/Kurento/kurento-media-server
kurento-rtmp工程地址：https://github.com/godka/kurento-rtmp
还有一些其他的需求可以阅读kurento的官方文档按需求改造。
比如：https://blog.csdn.net/yunjinwang/article/details/78405737

**Comment by xia-chu** [comment]
其实你说的功能我早就失效了 只是工作产出 不能开源而已



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: anzangun <notifications@github.com&gt;
发送时间: 2020年12月4日 08:49
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357)





 
最近项目需要需要用到类似的功能。
 我是用kurento和kurento-rtmp接入WEBRTC并输出成rtmp。如果需要转协议，可以使用工程的拉流功能关联起来。在这里记录一下另外一种接入思路。
 kurento工程地址：https://github.com/Kurento/kurento-media-server
 kurento-rtmp工程地址：https://github.com/godka/kurento-rtmp
 还有一些其他的需求可以阅读kurento的官方文档按需求改造。
 比如：https://blog.csdn.net/yunjinwang/article/details/78405737

**Comment by ywcai** [comment]
kurento在某些使用场景我遇到一些较大的问题。1个他无法支持ACC的音频.2

**Comment by wanghuan578** [comment]
无所谓啦，webrtc基本上比较灵活，你们这种开源更新的程度注定是跟不上节奏的。我可以选择其他框架。mediasoup、janus、medooz。哈哈


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 上午9:37
收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;"欢"<57810140@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357)





 其实你说的功能我早就失效了 只是工作产出 不能开源而已 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: anzangun <notifications@github.com&amp;gt; 
 发送时间: 2020年12月4日 08:49 
 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt; 
 抄送: 夏楚 <771730766@qq.com&amp;gt;, State change <state_change@noreply.github.com&amp;gt; 
 主题: 回复：[xia-chu/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357) 
 
 
 
 
 
   
 最近项目需要需要用到类似的功能。 
  我是用kurento和kurento-rtmp接入WEBRTC并输出成rtmp。如果需要转协议，可以使用工程的拉流功能关联起来。在这里记录一下另外一种接入思路。 
  kurento工程地址：https://github.com/Kurento/kurento-media-server 
  kurento-rtmp工程地址：https://github.com/godka/kurento-rtmp 
  还有一些其他的需求可以阅读kurento的官方文档按需求改造。 
  比如：https://blog.csdn.net/yunjinwang/article/details/78405737

**Comment by wanghuan578** [comment]
不要用这个了，一堆垃圾代码，浪费时间


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 上午9:54
收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;"欢"<57810140@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357)





 
kurento在某些使用场景我遇到一些较大的问题。1个他无法支持ACC的音频.2

**Comment by xia-chu** [comment]
rtc本来就不支持aac 因为编码延时太高了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ywcai <notifications@github.com&gt;
发送时间: 2020年12月4日 09:54
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357)





 
kurento在某些使用场景我遇到一些较大的问题。1个他无法支持ACC的音频.2

**Comment by xia-chu** [comment]
zlm跟rtc兼容的编码包括264 711 opus，不过g711效果不行，直播支持也不好，opus虽然效果好 ，但是兼容性更差。所以要融合 ，基本避免不了转码。

**Comment by xia-chu** [comment]
目前看过几个开源项目，觉得mediasoup代码最好维护，janus最方便些业务插件。但是janus太多线程和阻塞了 ，其实不好维护。

**Comment by xia-chu** [comment]
老实讲 ，实现一个基本的rtc应该是可以做到的，就像srs那样，几千行代码就行。但是这么不成熟的东西，我觉得放进master分支不合适，做了也不成熟，还不如不做。还不如专心跟其他rtc框架融合

**Comment by ywcai** [comment]
mediasoup没看过。kurento的代码研究了很久，太复杂，底层协议的拆封包也完全是调用gstream的库，完全没有修改的余地。

**Comment by ywcai** [comment]
srs的webrtc确实没发用。所以现在最好的webrtc方案还是挂1个mediasoup？rtmp最新的google好像已经不能支持了，web端播放是个麻烦问题。

**Comment by xia-chu** [comment]
> srs的webrtc确实没发用。所以现在最好的webrtc方案还是挂1个mediasoup？rtmp最新的google好像已经不能支持了，web端播放是个麻烦问题。
> 
> 

现在基本用mse实现 flv fmp4都可以的
还有webasm方案 后面估计还有webcodec方案

**Comment by zzt8899** [comment]
我感觉JITSI不错，可以考虑接入。

**Comment by gushenjie** [comment]
janus的rtp_forward 似乎没办法和这个开源框架配合使用？大佬们有思路吗？想做janus的旁路直播

**Comment by zsinba** [comment]
> 我感觉JITSI不错，可以考虑接入。

我已经接入了，还做了一个产品。

**Comment by gushenjie** [comment]
我用的是janus,将rtp包退给ZLM,发现它不支持说是类型不支持，应该是janus的sdp中视频编码格式和ZLM没有兼容




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 上午10:19
收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;". o坏﹏楠孩"<791127866@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] 是支持计划添加WEBRTC到RTMP服务器 (#357)





  
我感觉JITSI不错，可以考虑接入。
  
我已经接入了，还做了一个产品。

**Comment by xia-chu** [comment]
这个要稍微修改点zlm的代码才行

**Comment by xia-chu** [comment]
现在该特性已经支持了 在dev分支 不过现在还不成熟 仅供演示测试
