### ISSUE TITLE
是否支持GB28181的H.264 over RTP（没有PS封装）？

### ISSUE THREAD

**Issue by hxl-dy** [xia-chu/ZLMediaKit#360]

**Comment by xiongziliang** [comment]
一个udp端口是没法知道收到的rtp具体是什么格式，必须有其他信令告知才行。
所以，假定我开个端口，然后指定这个端口的rtp是H264, 那么你觉得这种意义打不？在代码里面，没法根据rtp获知是否为H264。

**Comment by xiongziliang** [comment]
payloadType=98是dynamic payload type, 理论上可以是任何负载，光这个不足以得知是否为H264

**Comment by hxl-dy** [comment]
> payloadType=98是dynamic payload type, 理论上可以是任何负载，光这个不足以得知是否为H264

GBT28181规定SDP协商时98是H.264

**Comment by hxl-dy** [comment]
换了个问法

**Comment by xiongziliang** [comment]
那这样可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hxl-dy <notifications@github.com&gt;
发送时间: 2020年6月23日 12:05
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 支持GB28181的payloadType=98（H.264 over RTP）么？ (#360)





  
payloadType=98是dynamic payload type, 理论上可以是任何负载，光这个不足以得知是否为H264
  
GBT28181规定SDP协商时98是H.264

**Comment by xiongziliang** [comment]
这个issue先不关闭，后续实现该特性了我再关闭

**Comment by xia-chu** [comment]
嗨 这个特性真的需要吗？ GB摄像头哪个不支持PS的？

**Comment by anzangun** [comment]
![2020-09-30 16-54-23屏幕截图](https://user-images.githubusercontent.com/10048915/94664723-d49ed700-033d-11eb-8d4c-6962b4923ca4.png)
@xia-chu 根据GB/T 28181-2016标准6.3明确说明应该使用PS格式，这个特性意义不大。

**Comment by hxl-dy** [comment]
> ![2020-09-30 16-54-23屏幕截图](https://user-images.githubusercontent.com/10048915/94664723-d49ed700-033d-11eb-8d4c-6962b4923ca4.png)
> @xia-chu 根据GB/T 28181-2016标准6.3明确说明应该使用PS格式，这个特性意义不大。

6.3说的是录制，这个issue指4.3.6的媒体传输

**Comment by hxl-dy** [comment]
> 嗨 这个特性真的需要吗？ GB摄像头哪个不支持PS的？

有的行业不用PS

**Comment by wusopp** [comment]
有些小厂商是不封装的，海思出来什么就直接用了~不过这应该算私有协议了吧

**Comment by xia-chu** [comment]
已经支持 PT限制为98。
