### ISSUE TITLE
请问ZlMediaKit支持GB28181的Sip信令以及级联到上级平台吗？

### ISSUE THREAD

**Issue by chatop2020** [xia-chu/ZLMediaKit#366]

**Comment by SnowfallDan** [comment]
ZL没有国标信令服务的功能，你可以关注一下README里有小伙伴的参考案例：https://github.com/swwheihei/wvp-GB28181

**Comment by xiongziliang** [comment]
后续ZLMediaKit会添加推送GB28181 RTP流到上级平台的http api

**Comment by xia-chu** [comment]
sip部分ZLMediaKit预计不会去尝试实现，ZLMediaKit会专注于流媒体部分，现已经支持国标rtp推流客户端
