### ISSUE TITLE
是否可以支持websocket-fmp4?

### ISSUE THREAD

**Issue by netjune** [xia-chu/ZLMediaKit#385]
fmp4: fragment mp4, 适合在线流传输. 优点:

1. 支持h265. 
2. 浏览器可以直接播放, 不需要像flv一样做转换.

**Comment by xiongziliang** [comment]
你说的对 这个确实蛮多优势，你的issue先不关闭  后续有机会实现下

**Comment by chuyue86** [comment]
强烈支持！！！

**Comment by xia-chu** [comment]
我真的没那么多时间兄弟们😂；我也不知道什么时候能实现这个，我又不是全职搞这个啊，今年我开发时间严重减少了！

**Comment by xia-chu** [comment]
已实现该特性，url格式请参考wiki url规则篇

**Comment by netjune** [comment]
太强了!

**Comment by caojunwei1988** [comment]
赞
