### ISSUE TITLE
有计划对opus全面支持吗？

### ISSUE THREAD

**Issue by lyg1949** [xia-chu/ZLMediaKit#402]
opus对比aac还是有一些优势的。不知道实现起来是否困难？

**Comment by xiongziliang** [comment]
opus在rtc领域确实比较流行，但是在直播和监控领域，基本没什么播放器支持的

**Comment by xiongziliang** [comment]
后面如果要支持webrtc，那么会加入opus的支持的

**Comment by xia-chu** [comment]
除hls外已经全部实现对opus的支持，请查看最新的readme与[wiki](https://github.com/xia-chu/ZLMediaKit/wiki/RTMP%E5%AF%B9H265%E5%92%8COPUS%E7%9A%84%E6%94%AF%E6%8C%81)

**Comment by lyg1949** [comment]
赞👍



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年8月1日 10:37
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: lyg1949 <zh.ghlong@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 有计划对opus全面支持吗？ (#402)






除hls外已经全部实现对opus的支持，请查看最新的readme与wiki
