### ISSUE TITLE
使用DevChannel，监听不到kBroadcastStreamNoneReader事件

### ISSUE THREAD

**Issue by chenxihai** [xia-chu/ZLMediaKit#423]
使用tests中DeviceHK例子进行推流，播放正常，但是关闭所有播放器，却接收不到kBroadcastStreamNoneReader事件。而采用PlayerProxy方式可以收到事件。请问是哪配置问题吗？
```c++
DeviceHK::Ptr hkdev(new DeviceHK());
mediakit::connectInfo info("172.16.30.64",8000, "admin", "admin123456");
hkdev->connectDevice(info,[hkdev](bool success, const connectResult &res){
                if(success){
                    hkdev->addChannel(1, true);
                }
            });
            s_deviceMap[key] = hkdev;
```
回调数据inputH264后，播放正常，关闭播放，接收不到无人观看事件，请指点，谢谢！

**Comment by xiongziliang** [comment]
应该不会的 你在MediaSource.cpp 第442 、444、462行打断点测试下

**Comment by chenxihai** [comment]
设置断点无法命中！执行WebApi的close_stream命令也不成功。
调试发现：
1、执行close_stream，触发MediaSource.cpp（88行）的bool MediaSource::close(bool force)，但是linsterner==null，直接return false 了。
2、关闭播放器20秒后，触发MediaSource.cpp（96行）的void MediaSource::onNoneReader()，但和关闭流一样，linsterner==null，return 了；

**Comment by xiongziliang** [comment]
那kBroadcastStreamNoneReader事件还是触发了嘛 只是close事件你没实现 所以无法关闭啊 因为我没法关闭你这个DeviceHK对象啊，所以要你自己实现
