### ISSUE TITLE
GB28181 H265 推流成功，但http flv只有音频tag

### ISSUE THREAD

**Issue by yzxliu** [xia-chu/ZLMediaKit#427]
使用国标推流成功，rtsp,hls可以使用vlc正常，httpflv,wsflv播放只有音频（0x08），没有视频(0x09)，请检查一下？

**Comment by xiongziliang** [comment]
因为flv播放器不支持265



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yzxliu <notifications@github.com&gt;
发送时间: 2020年7月22日 07:55
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] GB28181 H265 推流成功，但http flv只有音频tag (#427)





 
使用国标推流成功，rtsp,hls可以使用vlc正常，httpflv,wsflv播放只有音频（0x08），没有视频(0x09)，请检查一下？

**Comment by yzxliu** [comment]
跟flv播放器无关，现在是flv流输出不带视频数据，flv.js目前是不支持h265的，但第三方有asm方案可以软解h265，关键是flv流得输出视频包吧。。。

**Comment by yzxliu** [comment]
既然rtmp支持h265扩展，为啥httpflv 不支持h265呢？

**Comment by yzxliu** [comment]
不好意思，刚翻了一下国标2016文档，发现还未支持h265跟flv协议一样，没有给编号,但在海康ps流封装中设定了 h265编号=0x24

**Comment by xiongziliang** [comment]
> 既然rtmp支持h265扩展，为啥httpflv 不支持h265呢？

因为浏览器不支持H265,flv也不支持

**Comment by xiongziliang** [comment]
> 不好意思，刚翻了一下国标2016文档，发现还未支持h265跟flv协议一样，没有给编号,但在海康ps流封装中设定了 h265编号=0x24

H265应该支持的 这个应该有人测试过了，我看到过别人的ps流被识别出265了

**Comment by yzxliu** [comment]
既然 rtmp协议支持了 h265,希望也加上httpflv支持,虽然在h265编码上都没有标准，有总比没有好..

**Comment by xiongziliang** [comment]
> 既然 rtmp协议支持了 h265,希望也加上httpflv支持,虽然在h265编码上都没有标准，有总比没有好..

ZLMediaKit能生成H265的flv，但是浏览器、播放器都不支持啊！
