### ISSUE TITLE
GB28181推流RTCP保活问题

### ISSUE THREAD

**Issue by bulexx** [xia-chu/ZLMediaKit#429]
RTP包的response 抓包到ICMP unreachable，可否进行RTCP回复收到信息，目前导致无法连续播放，谢谢。

**Comment by xia-chu** [comment]
ICMP unreachable说明对端udp端口未打开

**Comment by bulexx** [comment]
主要是摄像机有一个保活检测，需要周期性发送保活消息，没有收到就断流不推送。

**Comment by xia-chu** [comment]
ZLMediaKit会发保活心跳包的

**Comment by bulexx** [comment]
这个具体是哪一块；我实际抓包没有抓到RTCP的包，所以后面发现这个原因在摄像机端关闭了保活检测才能连续播放。

**Comment by xia-chu** [comment]
![image](https://user-images.githubusercontent.com/11495632/88358411-6b30a400-cda1-11ea-843f-5f2ba28e2b6a.png)

**Comment by bulexx** [comment]
除了config.ini 中的端口之外，linux部署还有哪些端口要开放，TCP还是UDP&TCP，建议文档加入要开放的端口信息。

**Comment by bulexx** [comment]
上面的图片看不到。。。
![image](https://user-images.githubusercontent.com/26913840/88494408-935e1400-cfe8-11ea-9ed6-bbb9c6cfb3ef.png)

**Comment by xia-chu** [comment]
tcp开放rtsp端口，udp开放所有端口

**Comment by SillyFlame** [comment]
感觉你俩说的不是一个问题，提问者表诉的应该是摄像机向ZLMediaServer RTP proxy 推RTP流时，同时还发送了RTCP SR，但是ZL没有回复这个RTCP消息；
摄像机以这个RTCP作为保活机制，一段时间后没有收到回复，摄像机就主动断流了；
我也发现类似问题，但这个国标的保活机制，本身就很模糊

**Comment by xia-chu** [comment]
嗯嗯 我理解成了rtsp中的rtcp保活了🙂😅😂🤣

**Comment by bulexx** [comment]
在摄像机端把保活开关关闭就能正常的连续播放。。。
![image](https://user-images.githubusercontent.com/26913840/88647882-0d7dbe00-d0f9-11ea-96af-d75fa9e6cd93.png)

**Comment by xia-chu** [comment]
GB28181 保活又说用rtcp的也又说用sip的，具体怎么保活的 我也不清楚。

**Comment by chengxiaosheng** [comment]
国标保活我看比较多的还是会使用RTCP , 一般都是RTP为偶数端口, RTCP 端口= rtp端口+1

PS: 10000 RTP
10001 RTCP

10002 RTP
10003 RTCP

这样成对出现,由下级平台主动发送RTCP, 上级平台回复.

**Comment by SillyFlame** [comment]
GB28181保活分两种：
  平台级别的保活，使用sip信令，这个没有争议；
  流级别保活：
    TCP使用连接就可以判断，不用保活；
    UDP规定是需要保活，但是没有明确说明怎么保活；
    我遇到的是，RTP接流端口是偶数，RTCP端口时RTP端口+1，例如10000端口接rtp流，10001接RTCP，和楼上说的一样。

**Comment by xia-chu** [comment]
设备会发RTCP吗？设备发RTCP后服务器是否只要ping pong回去即可？

**Comment by SillyFlame** [comment]
某些平台会发送SR, 要求回复RR就行。。。

**Comment by machh** [comment]
改一下标题吧， GB28181对接通过UDP方式传输视频流，下级平台要求通过RTCP做流保活， 否则会断流。

国标的rtcp保活 和rtsp类似， RTP接流端口是偶数，RTCP端口是RTP端口+1
下级平台（发送方）发SR,  ZL回复RR即可

**Comment by xia-chu** [comment]
> 改一下标题吧， GB28181对接通过UDP方式传输视频流，下级平台要求通过RTCP做流保活， 否则会断流。
> 
> 国标的rtcp保活 和rtsp类似， RTP接流端口是偶数，RTCP端口是RTP端口+1
> 下级平台（发送方）发SR, ZL回复RR即可

rtcp端口能不能不必须为RTP端口+1？ 我想所有的rtcp共用一个端口，因为openRtpServer接口可能会创建很多个rtp端口

**Comment by chengxiaosheng** [comment]
在国标的 Invite 的SDP描述中只能去指定接收流的RTP 端口 ,并没有提供RTCP接收端口的字段 .
发流端默认会向 RTP+1 发送 RTCP 进行流保活 , 所以在国标中 是两个端口一路流.(只能成对出现),无法实现共用 一个RTCP 端口

**Comment by wkdepth** [comment]
我现在也是遇到这个问题，有些下级域不让关闭流保活，所以那边没办法对接。。。。

**Comment by swwheihei** [comment]
各位有什么解决方案吗？

**Comment by zhang2349** [comment]
openRtpServer端口限定用偶数端口 然后rtcp用+1端口

**Comment by machh** [comment]
> > 改一下标题吧， GB28181对接通过UDP方式传输视频流，下级平台要求通过RTCP做流保活， 否则会断流。
> > 国标的rtcp保活 和rtsp类似， RTP接流端口是偶数，RTCP端口是RTP端口+1
> > 下级平台（发送方）发SR, ZL回复RR即可
> 
> rtcp端口能不能不必须为RTP端口+1？ 我想所有的rtcp共用一个端口，因为openRtpServer接口可能会创建很多个rtp端口

你现在不是通过openRtpServer接口，指定了rtp的接收端口么，一路流一个rtp端口，那么rtcp在这个端口上+1就行呀。

如果zlm 非要rtcp共用一个端口，那就得让所有摄像机都向zlm的固定的端口发送rtp，比如10000， 那么rtcp都是用1001

也就是说，国标的Invite 发送给所有摄像机的SDP描述中，RTP接收流端口，都是用zlm的10000端口即可

**Comment by xia-chu** [comment]
四种方案：
- 1、rtcp端口唯一，大家共享一个rtcp端口
- 2、rtcp端口跟rtp端口一样，端口复用，通过数据判断是rtcp还是rtp
- 3、每个rtp端口对应一个rtcp端口，但是rtcp端口号随机
- 4、每个rtp端口对应一个rtcp端口，rtcp端口号为rtp端口+1,且为奇数

**Comment by xia-chu** [comment]
目前qq群里面反应，摄像头一般只认4方案

**Comment by machh** [comment]
> 目前qq群里面反应，摄像头一般只认4方案

可以的，就按方案4搞起来

**Comment by hctym1995** [comment]
一人血书添加 rtp server端口+1用作国标rtcp流保活功能

**Comment by shanyuanzz** [comment]
请求大佬增加rtcp流保活功能。

**Comment by sharcv** [comment]
这问题解决了吗，我好像也是类似问题：https://github.com/xia-chu/ZLMediaKit/issues/632
抓包后发现 rtp 刚开始正常推送，后面就断了，抓包里面有一条：
ICMP Destinatiion unreachable (Port unreachable)

**Comment by xia-chu** [comment]
请pull最新master分支并打上该patch测试，测试通过了我合并到master分支 谢谢：
```patch
Index: src/Rtp/RtpServer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/RtpServer.cpp	(revision bba18156ea1ab93744a0e226ccca8e9e0154be2e)
+++ src/Rtp/RtpServer.cpp	(revision 0d757a834c278ad3d93fed251fb8f5b74a8d4bba)
@@ -11,6 +11,7 @@
 #if defined(ENABLE_RTPPROXY)
 #include "RtpServer.h"
 #include "RtpSelector.h"
+#include "Rtcp/RtcpContext.h"
 namespace mediakit{
 
 RtpServer::RtpServer() {
@@ -22,20 +23,82 @@
     }
 }
 
+class RtcpHelper : public RtcpContext, public std::enable_shared_from_this<RtcpHelper> {
+public:
+    using Ptr = std::shared_ptr<RtcpHelper>;
+
+    RtcpHelper(Socket::Ptr rtcp_sock, uint32_t sample_rate) : RtcpContext(sample_rate, true){
+        _rtcp_sock = std::move(rtcp_sock);
+        _sample_rate = sample_rate;
+    }
+
+    void onRecvRtp(const Buffer::Ptr &buf, struct sockaddr *addr, int addr_len){
+        //统计rtp接受情况，用于发送rr包
+        auto header = (RtpHeader *) buf->data();
+        onRtp(ntohs(header->seq), ntohl(header->stamp) * uint64_t(1000) / _sample_rate, buf->size());
+        sendRtcp(ntohl(header->ssrc), addr, addr_len);
+    }
+
+    void startRtcp(){
+        weak_ptr<RtcpHelper> weak_self = shared_from_this();
+        _rtcp_sock->setOnRead([weak_self](const Buffer::Ptr &buf, struct sockaddr *addr, int addr_len) {
+            //用于接受rtcp打洞包
+            auto strong_self = weak_self.lock();
+            if (!strong_self) {
+                return;
+            }
+            if (!strong_self->_rtcp_addr) {
+                //只设置一次rtcp对端端口
+                strong_self->_rtcp_addr = std::make_shared<struct sockaddr>();
+                memcpy(strong_self->_rtcp_addr.get(), addr, addr_len);
+            }
+        });
+    }
+
+private:
+    void sendRtcp(uint32_t rtp_ssrc, struct sockaddr *addr, int addr_len){
+        //每5秒发送一次rtcp
+        if (_ticker.elapsedTime() < 5000) {
+            return;
+        }
+        _ticker.resetTime();
+
+        auto rtcp_addr = _rtcp_addr.get();
+        if (!rtcp_addr) {
+            //默认的，rtcp端口为rtp端口+1
+            ((sockaddr_in *) addr)->sin_port = htons(ntohs(((sockaddr_in *) addr)->sin_port) + 1);
+            //未收到rtcp打洞包时，采用默认的rtcp端口
+            rtcp_addr = addr;
+        }
+        _rtcp_sock->send(createRtcpRR(rtp_ssrc + 1, rtp_ssrc), rtcp_addr, addr_len);
+    }
+
+private:
+    Ticker _ticker;
+    Socket::Ptr _rtcp_sock;
+    uint32_t _sample_rate;
+    std::shared_ptr<struct sockaddr> _rtcp_addr;
+};
+
 void RtpServer::start(uint16_t local_port, const string &stream_id,  bool enable_tcp, const char *local_ip) {
     //创建udp服务器
     Socket::Ptr udp_server = Socket::createSocket(nullptr, true);
+    Socket::Ptr rtcp_server = Socket::createSocket(nullptr, true);
     if (local_port == 0) {
         //随机端口，rtp端口采用偶数
-        Socket::Ptr rtcp_server = Socket::createSocket(nullptr, true);
         auto pair = std::make_pair(udp_server, rtcp_server);
         makeSockPair(pair, local_ip);
         //取偶数端口
         udp_server = pair.first;
+        rtcp_server = pair.second;
     } else if (!udp_server->bindUdpSock(local_port, local_ip)) {
         //用户指定端口
-        throw std::runtime_error(StrPrinter << "bindUdpSock on " << local_ip << ":" << local_port << " failed:" << get_uv_errmsg(true));
+        throw std::runtime_error(StrPrinter << "创建rtp端口 " << local_ip << ":" << local_port << " 失败:" << get_uv_errmsg(true));
+    } else if(!rtcp_server->bindUdpSock(udp_server->get_local_port() + 1, local_ip)) {
+        // rtcp端口
+        throw std::runtime_error(StrPrinter << "创建rtcp端口 " << local_ip << ":" << local_port << " 失败:" << get_uv_errmsg(true));
     }
+
     //设置udp socket读缓存
     SockUtil::setRecvBuf(udp_server->rawFD(), 4 * 1024 * 1024);
 
@@ -51,7 +114,10 @@
     if (!stream_id.empty()) {
         //指定了流id，那么一个端口一个流(不管是否包含多个ssrc的多个流，绑定rtp源后，会筛选掉ip端口不匹配的流)
         process = RtpSelector::Instance().getProcess(stream_id, true);
-        udp_server->setOnRead([udp_server, process](const Buffer::Ptr &buf, struct sockaddr *addr, int) {
+        RtcpHelper::Ptr helper = std::make_shared<RtcpHelper>(std::move(rtcp_server), 90000);
+        helper->startRtcp();
+        udp_server->setOnRead([udp_server, process, helper](const Buffer::Ptr &buf, struct sockaddr *addr, int addr_len) {
+            helper->onRecvRtp(buf, addr, addr_len);
             process->inputRtp(true, udp_server, buf->data(), buf->size(), addr);
         });
     } else {

```

**Comment by Huachao** [comment]
> 四种方案：
> 
> - 1、rtcp端口唯一，大家共享一个rtcp端口
> 
> - 2、rtcp端口跟rtp端口一样，端口复用，通过数据判断是rtcp还是rtp
> 
> - 3、每个rtp端口对应一个rtcp端口，但是rtcp端口号随机
> 
> - 4、每个rtp端口对应一个rtcp端口，rtcp端口号为rtp端口+1,且为奇数
> 
> 

@xia-chu 夏楚大佬，这里提到的方案一，也就是所有rtp流端口复用的场景下，例如10000，那么所有rtcp都往10001发送的话，ZLM能正确区分并回复吗，谢谢

**Comment by xia-chu** [comment]
> @xia-chu 夏楚大佬，这里提到的方案一，也就是所有rtp流端口复用的场景下，例如10000，那么所有rtcp都往10001发送的话，ZLM能正确区分并回复吗，谢谢

不能 单端口模式不支持rtcp，因为没法区分来自哪个设备的rtcp 如果要回复 也是随便回复 但是设备可能对rtcp回复内容敏感

**Comment by Huachao** [comment]
@xia-chu 夏楚大佬，您上面提到的无法区分哪个设备的RTCP原因是什么，因为RTCP的SR里面是包含SSRC的，通过这个得到stream_id是不是可以判断？我也不是很熟悉，说的不一定对

**Comment by xia-chu** [comment]
> @xia-chu 夏楚大佬，您上面提到的无法区分哪个设备的RTCP原因是什么，因为RTCP的SR里面是包含SSRC的，通过这个得到stream_id是不是可以判断？我也不是很熟悉，说的不一定对

勉强可以实现 不过 我觉得没什么必要 就没去做
