### ISSUE TITLE
websocket无法断开

### ISSUE THREAD

**Issue by genouswhy** [xia-chu/ZLMediaKit#430]
你好，我的网页客户端会与服务端同时保持多个websocket连接，现在想用ws.close()断开某个连接，但发现服务端是在数分钟后才能断开，请问如何能比较快速的断开websocket连接。
我也查看了kick_session接口，那个会把客户端所有的连接都断了，不太符合使用场景。
感谢

**Comment by xia-chu** [comment]
现在ZLMediaKit处理了websocket的close信令请求，也做了回复。但是没有强制关闭tcp连接。你可以先在客户端销毁对象以便关闭tcp链接

**Comment by genouswhy** [comment]
销毁的对象是指播放视频的video对象么，刚才试了销毁video对象，也没有关闭链接

**Comment by xia-chu** [comment]
websocket对象跟video标签有啥关系啊老哥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: genouswhy <notifications@github.com&gt;
发送时间: 2020年7月24日 21:00
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] websocket无法断开 (#430)





 
销毁的对象是指播放视频的video对象么，刚才试了销毁video对象，也没有关闭链接

**Comment by xia-chu** [comment]
不过这个问题我会改进下，也不是什么大问题

**Comment by genouswhy** [comment]
嗯嗯好的，那现在有可以临时方案么，我看config文件里一些延时时间的设置，有可以调整的么

**Comment by xia-chu** [comment]
<img width="1158" alt="图片" src="https://user-images.githubusercontent.com/11495632/88527570-0b036180-d030-11ea-9741-d90968bdc08e.png">

**Comment by xia-chu** [comment]
问题已修复

**Comment by zzzzmayday** [comment]
![image](https://user-images.githubusercontent.com/21163786/89496726-7a760f80-d7ed-11ea-8585-8da2b7a163c4.png)
@xia-chu 你好，我在h5里使用了flvjs播放ws链接，同一个video窗口切换了几个视频，控制台看到的情况是切换地址之后前一个地址还是需要几分钟才能断开，flvjs里的destroy函数调用了ws.close()也把ws对象置成null了，请问还有别的方法能在close之后直接把ws的连接断开吗？已经更新了最新的代码

**Comment by xia-chu** [comment]
这个问题是个缺陷 等我周末更新代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zzzzmayday <notifications@github.com&gt;
发送时间: 2020年8月6日 14:15
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] websocket无法断开 (#430)





 

 @xia-chu 你好，我在h5里使用了flvjs播放ws链接，同一个video窗口切换了几个视频，控制台看到的情况是切换地址之后前一个地址还是需要几分钟才能断开，flvjs里的destroy函数调用了ws.close()也把ws对象置成null了，请问还有别的方法能在close之后直接把ws的连接断开吗？已经更新了最新的代码

**Comment by xia-chu** [comment]
之前没考虑到浏览器在close websocket链接后竟然不会释放tcp连接！

**Comment by zzzzmayday** [comment]
好哒谢谢
