### ISSUE TITLE
如何实现录像定位的功能

### ISSUE THREAD

**Issue by cngun** [xia-chu/ZLMediaKit#432]
需求如下：对一个推流进行录像，然后可以通过时间信息，例如20200725083600  直接定位到录像的时间点进行播放
我尝试进行mp4录像，发现录像结束前是无法播放的。
请问现在版本是否支持这个功能？

**Comment by xia-chu** [comment]
MP4在关闭前是没法播放的，因为mp4依赖索引信息，这些信息在录制结束时才能产生。
flv/ts才能边录制边播放

**Comment by cngun** [comment]
isRecording?app=live&stream=2&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost&type=0
我使用type=0进行录像，录像文件找不到。这个录制的文件在哪里？
PS  我用的是docker镜像直接运行的

**Comment by xia-chu** [comment]
你就mp4录制吧，hls录制基本不可用，跟hls直播是 冲突 的
