### ISSUE TITLE
HLS录像存储位置

### ISSUE THREAD

**Issue by cngun** [xia-chu/ZLMediaKit#433]
我使用的docker镜像启动的服务
通过API启动了录像
/index/api/startRecord?app=live&stream=2&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost&type=0
通过API查询是否录像
/index/api/isRecording?app=live&stream=2&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost&type=0

返回
{
   "code" : 0,
   "status" : true
}

两个问题
1）如何通过API获取录像的文件的地址
2）我进入docker 容器内，没有找到录像文件。第一次用mp4录像的，文件存放于/www/record/,HLS录像存放于什么位置?

**Comment by xia-chu** [comment]
hls位置就是hls直播位置，在www/app/stream/xxxxxx
