### ISSUE TITLE
isRecording接口返回不正确

### ISSUE THREAD

**Issue by suisou** [xia-chu/ZLMediaKit#437]
/index/api/isRecording?type=1&vhost=__defaultVhost__&app=proxy&stream=1&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
返回
{
   "code" : 0,
   "status" : false
}
但是百分百确认，这个stream在录制，因为record/proxy/1/2020-07-28下面还在增加文件。

**Comment by xia-chu** [comment]
建议你调试下 ，我没你的环境 很难判断怎么回事

**Comment by suisou** [comment]
CloseStreams接口 在matche  app  和stream 时不正确。
百分百确认，app  和steam 是正确的，但是这个接口却关闭不了。
{
   "code": 0,
   "count_closed": 0,
   "count_hit": 0
}
当去掉了app和stream ，只使用vhost可以匹配到，并关闭掉。

**Comment by xia-chu** [comment]
> CloseStreams接口 在matche app 和stream 时不正确。
> 百分百确认，app 和steam 是正确的，但是这个接口却关闭不了。
> {
> "code": 0,
> "count_closed": 0,
> "count_hit": 0
> }
> 当去掉了app和stream ，只使用vhost可以匹配到，并关闭掉。

应该不会啊 这个问题也就你反馈过啊, 我看代码也没什么问题啊：
<img width="980" alt="图片" src="https://user-images.githubusercontent.com/11495632/89137126-789c1a00-d569-11ea-807b-5e1daa3bcef5.png">

**Comment by xia-chu** [comment]
先关闭了 我觉得代码没啥问题
