### ISSUE TITLE
addFFmpegSource报permission denied

### ISSUE THREAD

**Issue by s546328100** [xia-chu/ZLMediaKit#438]
#### pid=10610,cmd=ffmpeg -re -i http://127.0.0.1:8080/rtp/0004E2C9/hls.m3u8 -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://127.0.0.1:1935/live/0004E2C9 #####

fork process failed:-13(permission denied)

**Comment by xia-chu** [comment]
你关闭时，应该说下解决方法

**Comment by wsinbol** [comment]
遇到相同问题,  应该是配置文件没有指定正确的FFmpeg路径.需要注意的是
> zlm使用的配置文件在MediaServer可执行程序当前文件夹下的config.ini。源码中的conf/config.ini是配置文件说明

大佬的原话

**Comment by Krehizi** [comment]
修改config.ini的[ffmpeg]标签的bin值：
bin=ffmpeg
为
/usr/bin/ffmpeg
