### ISSUE TITLE
ssrc转stream_id的规则是什么

### ISSUE THREAD

**Issue by wkdepth** [xia-chu/ZLMediaKit#439]
在网上找了些资料，对接GB28181时ZL的stream_id是通过将ssrc做16进制处理之后得到的。通过检测程序发现ZL转换的stream_id与其他方式转换的16进制不一样：
ssrc：0103007377
zl：062440D0
java：0623C491

c++只会一点基础的，看了下代码没找到转换的地方，能否告知一下原理，或者告诉我在什么地方，我去仔细研究一下。
谢谢

**Comment by xia-chu** [comment]
你是UDP推流还是TCP？ 0103007377是你抓包分析得到的吗还是sdp中你设置的而已？

**Comment by wkdepth** [comment]
udp推流，0103007377应该是sdp中设置的吧，sip命令发给下级域的

**Comment by wkdepth** [comment]
麻烦问一下，像这种我设置的和下级域返回的不一样的情况，怎么才能把两个信息关联上呢。

**Comment by xia-chu** [comment]
你可以使用openRtpServer http api接口创建单独的端口来接收这一路流，请查看wiki

**Comment by wkdepth** [comment]
好 我看一下   谢谢啊
