### ISSUE TITLE
websocket解包问题

### ISSUE THREAD

**Issue by dengchaowen-cx** [xia-chu/ZLMediaKit#440]
您好 请教一下 当前代码可以直接解客户端发给zl的websocket数据吗 我拜读了代码 有解包的代码实现 在HttpRequestSplitter::input里面有入口 但是我测试了没有进去  还有就是websock粘包问题是在解包的里面做的吗 谢谢

**Comment by xia-chu** [comment]
websocket协议本身就能防止粘包。
ZLMediaKit完整的实现了websocket客户端和服务器，建议你查看tests目录下的测试程序。

**Comment by dengchaowen-cx** [comment]
我需要在ZLMediaKit 里面参考test实现自己的应用处理吗

**Comment by xia-chu** [comment]
当然需要 ，你可以认为websocket就是浏览器上的tcp。那么你要做应用协议就要自己开发。

**Comment by dengchaowen-cx** [comment]
好的 非常感谢 您帮我解答

**Comment by dengchaowen-cx** [comment]
您好 我还有一个问题，我查看了websocket例子，在EchoSession类中可以调用httpsession里面的成员吗，我c++不怎么会，看了半天也不知道怎么用，因为我想把websocket接收的数据做为一个源。或者可以给我个建议 非常感谢
