### ISSUE TITLE
265推流支持转264吗

### ISSUE THREAD

**Issue by ouzhou** [xia-chu/ZLMediaKit#441]
因为微信小程序只支持264rtmp播放，但是这边设备推的265，就很尴尬

**Comment by ouzhou** [comment]
希望有个配置能同时提供265和264

**Comment by xia-chu** [comment]
流媒体服务器一般通过外挂FFmpeg进程方式实现转码。也就是先拉流然后转码推回去，你可以看看addFFmpegSource接口，在wiki restful api篇
