### ISSUE TITLE
音视频的编码信息等变化后，需要重新创建媒体源吗？

### ISSUE THREAD

**Issue by lyg1949** [xia-chu/ZLMediaKit#442]
在使用lib的时候，我先用mk_media_create创建一个媒体源，并分别调用mk_media_init_video和mk_media_init_audio初始化音视频，通过mk_media_input_h264等传入音视频数据，可以正常播放。

我想问的是，如果在播放过程中，传如的数据类型（如编码、帧率、分辨率等）发生变化，是不是必须关闭该媒体源并重新创建呢？
能不能不关闭当前媒体源呢？

谢谢！

**Comment by xia-chu** [comment]
要看协议或者播放器支不支持
一般来说都支持的

**Comment by lyg1949** [comment]
谢谢！
