### ISSUE TITLE
使用docker镜像访问IP:8080出现404错误

### ISSUE THREAD

**Issue by Liuzizai** [xia-chu/ZLMediaKit#443]

**Comment by xia-chu** [comment]
你访问的什么api？你确定访问的是zlm的http服务器？

**Comment by Liuzizai** [comment]
我用8080映射zlm的80端口，访问http://ip:8080/index/api/listRtpServer?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc，出现404您访问的资源不存在！

**Comment by xia-chu** [comment]
说明你的代码版本不是最新的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liuzizai <notifications@github.com&gt;
发送时间: 2020年8月3日 22:19
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 使用docker镜像访问IP:8080出现404错误 (#443)





 
我用8080映射zlm的80端口，访问http://ip:8080/index/api/listRtpServer?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc，出现404您访问的资源不存在！
