### ISSUE TITLE
如何将该项目作为SDK集成使用

### ISSUE THREAD

**Issue by toskeyfine** [xia-chu/ZLMediaKit#444]
目前想使用ZLMediaKit中的RTMP Server的模块，集成到现有项目中，因为已经实现了RTP/RTSP/WebRTC等，所以希望只使用RTMP这块功能，不希望全部引用，具体应该怎么做呢

**Comment by xia-chu** [comment]
没必要裁剪 用 C SDK即可。你不用其他功能，不占用cpu开销,无非多占用几MB内存而已
