### ISSUE TITLE
closeRtpServer的bug

### ISSUE THREAD

**Issue by zhang2349** [xia-chu/ZLMediaKit#447]
终于看懂了崩溃的bug

https://github.com/xia-chu/ZLMediaKit/blob/1e397ce963bac79f5f08fd8ae52abca46717a869/server/WebApi.cpp#L791

在s_rtpServerMap.erase成功后 会触发RtpServer释放，就进入下面

https://github.com/xia-chu/ZLMediaKit/blob/1e397ce963bac79f5f08fd8ae52abca46717a869/server/WebApi.cpp#L777

这里s_rtpServerMap又erase了

就崩掉了
这要怎么改呢

**Comment by xia-chu** [comment]
改成这样：
```C++
    api_regist1("/index/api/closeRtpServer",[](API_ARGS1){
        CHECK_SECRET();
        CHECK_ARGS("stream_id");

        lock_guard<recursive_mutex> lck(s_rtpServerMapMtx);
        auto it = s_rtpServerMap.find(allArgs["stream_id"]);
        if(it == s_rtpServerMap.end()){
            val["hit"] = 0;
            return;
        }
        auto server = it->second;
        val["hit"] = s_rtpServerMap.erase(it);
    });
```

**Comment by xia-chu** [comment]
这个在mac下没崩溃，你是在gcc下吧？在map::erase函数中，再erase相同的key，可能会引起崩溃，这个跟stl实现有关系

**Comment by xia-chu** [comment]
明天我会提交下

**Comment by zhang2349** [comment]
嗯 我是用vc下试的

**Comment by xia-chu** [comment]
应该修复了 我先关闭issue了
