### ISSUE TITLE
关于录像的HOOK事件？

### ISSUE THREAD

**Issue by jiang6883** [xia-chu/ZLMediaKit#448]
1、在部署的时候开启推流自动录像。关闭推流的时候没有收到on_record_mp4的事件？

**Comment by xia-chu** [comment]
我认为是你哪里没用对，这个接口我是测试过的

**Comment by xia-chu** [comment]
关闭mp4时长比较长，所以你会延后收到hook，可能十几秒后或者更晚

**Comment by jiang6883** [comment]
我这边测试时间在长一下，观察一下



jiang6883@163.com
 
发件人： 夏楚
发送时间： 2020-08-12 10:05
收件人： xia-chu/ZLMediaKit
抄送： jiang6883; Author
主题： Re: [xia-chu/ZLMediaKit] 关于录像的HOOK事件？ (#448)
关闭mp4时长比较长，所以你会延后收到hook，可能十几秒后或者更晚
