### ISSUE TITLE
windows平台 addFFmpegSource 添加流后，无法使用closeStreams API 关闭流

### ISSUE THREAD

**Issue by FengChueng** [xia-chu/ZLMediaKit#449]
windows平台下，调用addFFmpegSource可以推流成功，但是如果摄像头此时断网，推流进程ffmpeg没有关闭，并且卡住了，并且过一段时间重连后，然后就无法播放视频流了。我当时的思路是想在摄像头掉线后，调用close_streams，关闭推流进程。然后发现关闭之后程序又会fork一个子进程ffmpeg推流，但是还是无法播放。
![image](https://user-images.githubusercontent.com/25821572/89889477-3ecfb100-dc04-11ea-9084-98cee64be3dc.png)
使用addStreamProxy是可以正常推流和正常关闭流的。

windows命令：
ffmpeg -i "rtsp://admin:sc123456@192.168.1.154:554/cam/realmonitor?channel=1&subtype=0" -vcodec copy -an -f flv rtmp://192.168.1.189/live/154

linux下使用addFFmpegSource正常推流，close_streams可以关闭流
ffmpeg -s 1920*1080 -vcodec h264 -i "/dev/video0" -vcodec copy -f flv rtmp://localhost/supercube/live

**Comment by xia-chu** [comment]
close_streams在流注册后才有效的，你可以用delFFmpegSource接口删除。
另外，你可以观察下FFmpeg的日志，看看为什么没法关闭进程，或者看看zlm的日志。

问我刚看了下代码，windows下不太可能无法杀死FFmpeg进程的。

**Comment by xia-chu** [comment]
以下是杀进程的代码：
```c++
static void s_kill(pid_t pid, void *handle, int max_delay, bool force) {
    if (pid <= 0) {
        //pid无效
        return;
    }
#ifdef _WIN32
    //windows下目前没有比较好的手段往子进程发送SIGTERM或信号
    //所以杀死子进程的方式全部强制为立即关闭
    force = true;
    if(force){
        //强制关闭子进程
        TerminateProcess(handle, 0);
    }else{
        //非强制关闭，发送Ctr+C信号
        signalCtrl(pid, CTRL_C_EVENT);
    }
#else
    if (::kill(pid, force ? SIGKILL : SIGTERM) == -1) {
        //进程可能已经退出了
        WarnL << "kill process " << pid << " failed:" << get_uv_errmsg();
        return;
    }
#endif // _WIN32

    if (force) {
        //发送SIGKILL信号后，阻塞等待退出
        s_wait(pid, handle, nullptr, true);
        DebugL << "force kill " << pid << " success!";
        return;
    }

    //发送SIGTERM信号后，2秒后检查子进程是否已经退出
    WorkThreadPool::Instance().getPoller()->doDelayTask(max_delay, [pid, handle]() {
        if (!s_wait(pid, handle, nullptr, false)) {
            //进程已经退出了
            return 0;
        }
        //进程还在运行
        WarnL << "process still working,force kill it:" << pid;
        s_kill(pid, handle, 0, true);
        return 0;
    });
}

```

**Comment by xia-chu** [comment]
看了你的日志截图，你的用法是错的!

**Comment by xia-chu** [comment]
close_streams在关闭推给自己的的流时，才有效。也就是你的推流地址必须是rtmp://127.0.0.1:port/.
因为你用其他地址，zlm可以认为是推给其他服务器，所以close_streams接口只能掐断FFmpeg的推流，
代码不知道流是推给自己的，所以没有关闭FFmpeg的进程

**Comment by xia-chu** [comment]
推流给自己一定要用127.0.0.1

**Comment by xia-chu** [comment]
加了个补丁，算是防呆设计， 你打上去：
```c++
Index: server/FFmpegSource.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- server/FFmpegSource.cpp	(revision d986b1d36c43be2e7c9cdd38f832cc034ae80882)
+++ server/FFmpegSource.cpp	(date 1597282136342)
@@ -14,6 +14,7 @@
 #include "Util/File.h"
 #include "System.h"
 #include "Thread/WorkThreadPool.h"
+#include "Network/sockutil.h"
 
 namespace FFmpeg {
 #define FFmpeg_FIELD "ffmpeg."
@@ -45,6 +46,18 @@
     DebugL;
 }
 
+static bool is_local_ip(const string &ip){
+    if (ip == "127.0.0.1" || ip == "localhost") {
+        return true;
+    }
+    auto ips = SockUtil::getInterfaceList();
+    for (auto &obj : ips) {
+        if (ip == obj["ip"]) {
+            return true;
+        }
+    }
+    return false;
+}
 
 void FFmpegSource::play(const string &src_url,const string &dst_url,int timeout_ms,const onPlay &cb) {
     GET_CONFIG(string,ffmpeg_bin,FFmpeg::kBin);
@@ -60,7 +73,7 @@
     _process.run(cmd,ffmpeg_log.empty() ? "" : File::absolutePath("",ffmpeg_log));
     InfoL << cmd;
 
-    if(_media_info._host == "127.0.0.1"){
+    if (is_local_ip(_media_info._host)) {
         //推流给自己的，通过判断流是否注册上来判断是否正常
         if(_media_info._schema != RTSP_SCHEMA && _media_info._schema != RTMP_SCHEMA){
             cb(SockException(Err_other,"本服务只支持rtmp/rtsp推流"));

```

**Comment by FengChueng** [comment]
好的，谢谢大佬，我这边儿先试一下

**Comment by FengChueng** [comment]
好的，谢谢大佬，我这边儿先试一下

**Comment by FengChueng** [comment]
一、如果ffmpeg给本机推流，如果ip不使用127.0.0.1，而使用本机的局域网的ip，192.168.1.5，就会出现上述问题，问题已解决。

二、如果ffmpeg给本机推流，使用用127.0.0.1是可以关闭流的。在测试中遇到了下面的现象。
1.如果流断了，会先把之前的ffmpeg进程关掉，然后重新启动一个ffmpeg进程推流。
![image](https://user-images.githubusercontent.com/25821572/90113920-9563f900-dd84-11ea-9110-3bd283368dfc.png)
2.此时调用关闭流接口，返回{"code": 0,"count_closed": 1,"count_hit": 2}。但是还是会重新启动一个ffmpeg进程推流。直至推流成功
3.摄像头重连后,推流成功，但是此时调用关流接口，日志打印，会重启一个ffmpeg进程推流
![image](https://user-images.githubusercontent.com/25821572/90114181-f5f33600-dd84-11ea-84e1-199d18f8f54a.png)
4.再调用关闭流接口才能关闭流，需要调用两次，才能关闭流

思考：如果推流源断开了，是否是需要ZLM来重启。我觉得可以把这块业务放到业务层来处理。由业务层来重试推流。业务层先检测摄像头是否在线，再决定是否推流。但是如果使用的人没有使用web_hook_api，那么就还是得ZLM来做了，中间件太难做了。

**Comment by xia-chu** [comment]
你再更新下代码，上次给你的patch修复的不彻底
