### ISSUE TITLE
开启hook之后，GB28181无法播放

### ISSUE THREAD

**Issue by wkdepth** [xia-chu/ZLMediaKit#450]
今天排查了一天的问题，最终发现hook开启之后，GB28181的视频无法播放，关闭之后才能播放。抓包发现没有ps流的包，全是udp协议的包，不知道是干什么的。
正常抓包
<img width="1080" alt="2" src="https://user-images.githubusercontent.com/18206718/89904139-26b75c00-dc1b-11ea-9aa3-92ccce71a652.png">
不正常抓包
<img width="1010" alt="1" src="https://user-images.githubusercontent.com/18206718/89904226-3cc51c80-dc1b-11ea-9af1-7fc21e25feef.png">

**Comment by xia-chu** [comment]
开不开启hook不会影响你摄像头的数据发送啊 你摄像头发送什么数据 不是ZLMediaKit说了算的

**Comment by wkdepth** [comment]
我的问题    先推流再调用openRtpServer接口

**Comment by chengxiaosheng** [comment]
1. 如果你是TCP推流，先推流再调用openRtpServer接口，你会推流失败

2. 如果你是UDP推流，先推流再调用openRtpServer接口，不会有影响，另外：在你的两个抓包截图里面 你认为的不正常的抓包也不一定不正常，从数据包来看也有可能是UDP的视频流包，你可以尝试 使用 wirshake 强制将其解析为RTP，我猜测那些大的数据包应该就是RTP

3. 题外话：从逻辑上来说应该不会存在先推流再调用 openRtpServer接口的情况，收流端口是在Invite SDP协商时定义的，所以你应该是先尝试开启一个端口 再告诉对方平台你的端口 。

**Comment by wkdepth** [comment]
好的  谢谢
