### ISSUE TITLE
调用 /index/api/addStreamProxy,流中断后可否重连？

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#455]
streamProxy可以把别的rtmp流拉过来再进行转发，是非常好的功能。
但是在某些情况，比如：rtmp源播放结束后重新开启， 或网络暂时不稳定，造成拉流中断，导致此项服务停止。
此处是否可以加入自动重试功能？比如1分钟内重试？让服务可以持续提供。

#204 

thanks for this good software !

**Comment by xia-chu** [comment]
你打下这个补丁：
```c++
Index: src/Rtsp/RtspPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtsp/RtspPlayer.cpp	(revision 42559146132d2e752fd4a94c3a6d34b3948a2b8d)
+++ src/Rtsp/RtspPlayer.cpp	(date 1598230843859)
@@ -733,6 +733,11 @@
 }
 
 void RtspPlayer::onPlayResult_l(const SockException &ex , bool handshakeCompleted) {
+    if(ex.getErrCode() == Err_shutdown){
+        //主动shutdown的，不触发回调
+        return;
+    }
+
     WarnL << ex.getErrCode() << " " << ex.what();
 
     if(!ex){
Index: src/Rtmp/RtmpPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtmp/RtmpPlayer.cpp	(revision 42559146132d2e752fd4a94c3a6d34b3948a2b8d)
+++ src/Rtmp/RtmpPlayer.cpp	(date 1598230817430)
@@ -92,6 +92,11 @@
 }
 
 void RtmpPlayer::onPlayResult_l(const SockException &ex , bool handshakeCompleted) {
+    if(ex.getErrCode() == Err_shutdown){
+        //主动shutdown的，不触发回调
+        return;
+    }
+
     WarnL << ex.getErrCode() << " " << ex.what();
 
     if(!ex){
@@ -128,7 +133,7 @@
         onResume();
     }
 
-    if(ex){
+    if (ex) {
         teardown();
     }
 }

```

**Comment by xia-chu** [comment]
这个问题算是一个bug

**Comment by alongL** [comment]
试了一下，没有起作用。

**Comment by xia-chu** [comment]
你到底是要rtmp推流还是rtmp拉流代理啊？

**Comment by xia-chu** [comment]
现在我们讨论的是zlm的内置拉流代理是否能应对拉流失败的问题

**Comment by alongL** [comment]
要拉流代理。  脚本是产生要拉的rtmp流的方法。

**Comment by xia-chu** [comment]
重试次数从10跳到12、14这种错误还存在吗？

**Comment by alongL** [comment]
重试次数好了。 0 1 2 3 ...

**Comment by xia-chu** [comment]
那怎么后面不再重新拉流了呢？

**Comment by alongL** [comment]
RtmpPlayer::onPlayResult_l   这个函数在程序不输出ts的时候并未被调用。
程序一直在拉rtmp流，但是拉到的没有输出。

**Comment by xia-chu** [comment]
我觉得没问题啊 每次播放后都会创建新的对象的 不可能存在你说的问题 我本地也测试了下 重试后能生成hls正常的

**Comment by xia-chu** [comment]
你是不是二次开发啊？

**Comment by alongL** [comment]
ffmpeg ->  srs    ->   mediaproxy拉流  ->  .ts
ffmpeg 推rtmp流给srs
mediaproxy从srs拉流生成hls
ffmpeg 暂停1秒后继续， mediaproxy一直在接收数据，但生成.ts失败。
在我这里很容易复现。 调试了很久，但是没找到问题所在。

**Comment by xia-chu** [comment]
这个问题不好重现 我本地简单测试下也没重现，相关代码我做了一点修改，issue先关闭。你测试新代码还有问题的话，我们可以qq沟通下。

**Comment by alongL** [comment]
这个问题解决了。解决办法是在 
src/Rtmp/RtmpPlayerImp.h 
onCheckMeta() 函数中加入对 _delegate为空的判断，只有为空的时候才reset()。 

整个过程示意图：
ffmpeg -> srs  -> mediaproxy -> .m3u8 

问题产生的原因是，本来媒体流在正常播放，但此时ffmpeg重新推流了，服务端会发送onMetaData，最终执行到这个onCheckMeta函数，如果不加if，则 _delegate 被reset，后续hls生成的时候就不继续了。
这个问题可能导致mediaProxy因rtmp源临时改变推流来源而停止生成hls （rtmp输出是正常的） 

···
    bool onCheckMeta(const AMFValue &val) override {
        _rtmp_src = dynamic_pointer_cast<RtmpMediaSource>(_pMediaSrc);
        if (_rtmp_src) {
            _rtmp_src->setMetaData(val);
            _set_meta_data = true;
        }
        _delegate.reset(new RtmpDemuxer);
        _delegate->loadMetaData(val);
        return true;
    }
···
After modified ：
```
    bool onCheckMeta(const AMFValue &val) override {
        _rtmp_src = dynamic_pointer_cast<RtmpMediaSource>(_pMediaSrc);
        if (_rtmp_src) {
            _rtmp_src->setMetaData(val);
            _set_meta_data = true;
        }
		if (!_delegate) {
			_delegate.reset(new RtmpDemuxer);
			_delegate->loadMetaData(val);
		}
		return true;
    }
```

源切换时的程序调用stack
![error](https://user-images.githubusercontent.com/5533883/94131720-d9244500-fe90-11ea-9600-e25066048847.png)

**Comment by xia-chu** [comment]
在MediaPlayer对象中，每播放一次 ，就会重新创建 RtmpPlayerImp对象。我真不觉得这个改动 会有什么实质性修改。

**Comment by alongL** [comment]
触发的条件是， rtmp源端发送 onMetaData , 此时不会重新创建RtmpPlayerImp。 
这个改动真实的解决了问题。  解决了生成hls中断的问题。

**Comment by xia-chu** [comment]
你从什么服务器拉流的？

**Comment by alongL** [comment]
srs 3.0

**Comment by xia-chu** [comment]
我知道原因了 srs推流端停止推流了 播放器链接不会断开和重置，然后重新推流了，又重新发metaData和config帧给播放器。

**Comment by xia-chu** [comment]
srs这个特性说实话有点傻

**Comment by alongL** [comment]
ffmpeg -> srs  ->  (onMetaData)
这个是不是可以这样理解。   ffmpeg推流中断了一下，又开始推新的流，新的流可以跟前一个流完全不一样， 所以要发一个onMetaData  告知客户端

**Comment by xia-chu** [comment]
srs一经推流后 这个源就不会总动释放，如果推流端关闭，播放器也没法知道 ，只能等接受超时

**Comment by xia-chu** [comment]
而且如果推流端假设分辨率变了 或者少了音频 少了视频什么的 播放器还要重置一切。

**Comment by xia-chu** [comment]
这样吧 如果重新推送metadata了 那么zlm强制断开连接 只能重连了

**Comment by xia-chu** [comment]
> 这样吧 如果重新推送metadata了 那么zlm强制断开连接 只能重连了

这样做能保险点 因为很多协议和容器没法支持分辨率变更

**Comment by alongL** [comment]
重连太暴力了吧。 加个if就可以了

**Comment by xia-chu** [comment]
那你怎么判断metadata和config帧不变化？ 这个没法判断的，

**Comment by xia-chu** [comment]
或者这样 就像你修改的那样 不管他这些关键数据变不变

**Comment by xia-chu** [comment]
修改编码器参数短时间内再推流的情况毕竟比较少 就算出点错 也关系不大

**Comment by alongL** [comment]
嗯。一般不会随意换一个流推。
