### ISSUE TITLE
已经有设备直播rtsp地址了，如何做拉流转推，推出rtmp地址

### ISSUE THREAD

**Issue by ouzhou** [xia-chu/ZLMediaKit#456]
是使用test_pusher.cpp这个文件吗
用ffmpeg可以吗？

**Comment by FengChueng** [comment]
index/api/addStreamProxy
这个接口不能满足你的需求吗？通过这个接口来拉取摄像头rtsp流，然后可以推出rtmp ,http-flv,ws-flv

**Comment by xia-chu** [comment]
他是想 ZLMediaKit拉流后 然后再rtsp/rtmp推出去

**Comment by chatop2020** [comment]
为什么不直接用ffmpeg呢
