### ISSUE TITLE
有转分辨率的方法么

### ISSUE THREAD

**Issue by wkdepth** [xia-chu/ZLMediaKit#458]
现在拿到的视频流想在手机上播放，分辨率太高带宽不够。请问有方法实现转分辨率推流么。

**Comment by xia-chu** [comment]
可以用FFmpeg实现转码， 不过zlm对转码的支持不够好

**Comment by xia-chu** [comment]
addFFmpegSource接口你可以了解下

**Comment by wkdepth** [comment]
分辨率是在配置文件里面改这个位置么
[ffmpeg]
#FFmpeg可执行程序绝对路径
bin=/usr/local/bin/ffmpeg
#FFmpeg拉流再推流的命令模板，通过该模板可以设置再编码的一些参数
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
#FFmpeg生成截图的命令，可以通过修改该配置改变截图分辨率或质量
snap=%s -i %s -y -f mjpeg -t 0.001 %s
#FFmpeg日志的路径，如果置空则不生成FFmpeg日志
#可以为相对(相对于本可执行程序目录)或绝对路径
log=./ffmpeg/ffmpeg.log

**Comment by xia-chu** [comment]
转码基本都是fork FFmpeg进程 ，拉流后再推流后实现的，你修改这个ffmpeg.cmd配置，就能修改推流码率和分辨率了

**Comment by wkdepth** [comment]
设置分辨率可以动态的么，根据接口来确定分辨率到底多少

**Comment by xia-chu** [comment]
不能 FFmpeg命令参数目标是配置文件设置的 主要是为了安全着想
