### ISSUE TITLE
mk_media相关接口录像回放场景咨询

### ISSUE THREAD

**Issue by baiyfcu** [xia-chu/ZLMediaKit#459]
目前已有接口回放，SEEK功能都已经具备，PAUSE和RESUME没有找到接口，目前个人实现是重载RtspSession处理实现，是否可以在MediaSourceEvent中增加PAUSE和RESUME事件通知数据源相应操作

**Comment by xia-chu** [comment]
rtsp协议有明确的pause指令，
但是播放、seek、resume都是公用play指令，它是通过Range字段来控制时间轴的，
所以rtsp只要实现seek事件就行，seek后自动继续播放。

rtmp有专门的seek、play、play2、pause指令，
其中play是开始播放，play2是继续播放，可以完美实现seek、paus、resume事件。

但是我觉得resume事件貌似没啥必要，直接共用seek事件就行。seek(-1)可以认为是继续播放，这样简单点。


其实流媒体服务器不太合适做paus和seek，毕竟涉及到多人播放，而且paus后超时管理也不好做。
目前zlm收到paus后只是丢掉了数据，并没有从源头暂停数据。seek目前由于跨线程的问题，做的也有些问题。

**Comment by xia-chu** [comment]
用rtsp和rtmp做点播是非常不建议的一种方案 点播还是http合适

**Comment by baiyfcu** [comment]
resume可以不需要，但是这个pause从流媒体框架角度来考虑，从录像服务器取流，客户端暂停时，服务端不可能一直取流不停

**Comment by baiyfcu** [comment]
从视频监控方向考虑，继续播放时，是恢复继续发送数据包，不能存在丢包

**Comment by baiyfcu** [comment]
> 用rtsp和rtmp做点播是非常不建议的一种方案 点播还是http合适

以适应各种项目场景，并不能随意选方案，只能走通用点的block存储方案

**Comment by baiyfcu** [comment]
没有resume问题到是不大，可以通过play指令转为seekto实现继续播放，pause事件从代码上看可以在MediaSource和MediaSourceEvent中扩展接口pause带到上层去处理

**Comment by xia-chu** [comment]
你可以加下 不过我感觉蛮多副作用的

**Comment by baiyfcu** [comment]
我先加上去，接口加上应该不会影响现有逻辑，这个pause事件不透到上层去，还得重载RtspSession，动静有点大，，，上层知道这个seekto pause事件了方便很多

**Comment by xia-chu** [comment]
目前MediaSourceEvent这个类和相关代码改动比较大，建议你先同步下最新代码，否则合并可能会有冲突

**Comment by baiyfcu** [comment]
已合并，期待下次暴风雨来临。。。

**Comment by xia-chu** [comment]
先关闭issue了，有问题再在此讨论

**Comment by 15927566740** [comment]
请问您的录像回放接口是怎么做的？方便指点一下吗？
