### ISSUE TITLE
使用守护进程启动，调用getSnap接口会导致ffmpeg运行卡死

### ISSUE THREAD

**Issue by cooldudu** [xia-chu/ZLMediaKit#460]
hello，我在使用ZLMediaKit中，发现如果不以-d 启动，调用getSnap这种调用ffmpeg的接口的时候，没有任何问题，但是当我以-d 方式启动服务后，再调用getSnap接口后，发现ffmpeg运行进程会卡死，而且会影响到其他接口也无法正常调用，使用操作系统ubuntu18.
![image](https://user-images.githubusercontent.com/41182849/91277067-ecba8e00-e7b4-11ea-9aa9-0c27a7518f87.png)

**Comment by xia-chu** [comment]
你应该 MediaServer &运行后马上exit终端。
现在输出在shell启动FFmpeg会导致一些问题，目前还不明确原因

**Comment by cooldudu** [comment]
夏楚，
&nbsp; &nbsp; 您好，
使用nohup + ffmpeg命令的方式，经测试，好像可以解决目前出现的这个问题，期待您的测试结果。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 下午4:15
收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;"706686151"<706686151@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] 使用守护进程启动，调用getSnap接口会导致ffmpeg运行卡死 (#460)





 
你应该 MediaServer &amp;运行后马上exit终端。
 现在输出在shell启动FFmpeg会导致一些问题，目前还不明确原因

**Comment by xia-chu** [comment]
nohup能脱离stdout, 所以能正常运行的

**Comment by xia-chu** [comment]
这个问题不是很严重的问题，建议采用nohup方式运行。issue先关闭，后面这个问题有空再跟踪下。
