### ISSUE TITLE
解析rtp进程假死或者挂掉

### ISSUE THREAD

**Issue by zxxtyj** [xia-chu/ZLMediaKit#461]
你好！我在测试gb28181国标的时候 50路摄像头运行一段时间后进程会假死和挂掉。日志分析初是rtp 解析出问题就崩掉了

**Comment by xia-chu** [comment]
是的 目前有这个问题 已经收到该问题的3次反馈(包括你) 从core文件分析bug发生在ps rtp解析相关代码。
这个bug可能是第三方库的问题，也可能是zlm的问题，很难说。
由于我没有相关测试环境，该问题很难复现，你可以用 valgrind或asan测试下，看看是不是由于其他内存越界导致的问题，
如果不知道怎么下手，可以联系我qq。

**Comment by zxxtyj** [comment]
你好这是我qq号526057117 烟雨江南 我们qq联系吧

**Comment by zxxtyj** [comment]
我这边有测试环境我们可以电话或者qq沟通下 我电话是15811203732

**Comment by xia-chu** [comment]
这个rtp解包的代码我重写了 周末更新git 到时再测试新代码吧

**Comment by zxxtyj** [comment]
👌

**Comment by zxxtyj** [comment]
加个qq或者微信吧！我们是做视频监控ai这块的！有机会可以交流下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;夏楚&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月2日(星期三) 上午9:17
收件人:&nbsp;&quot;xia-chu/ZLMediaKit&quot;<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;&quot;张星星(felix.zhang)&quot;<526057117@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] 解析rtp进程假死或者挂掉 (#461)

**Comment by xia-chu** [comment]
rtp解包代码重写了 ，现在应该不会再有这个bug了，你更新代码测试下。
issue先关闭了，有问题在此反馈。
