### ISSUE TITLE
播放rtmp vlc崩溃

### ISSUE THREAD

**Issue by wanghuan578** [xia-chu/ZLMediaKit#462]

**Comment by xia-chu** [comment]
vlc崩溃还是zlm崩溃？为什么崩溃不讲讲吗？崩溃有日志或core文件吗

**Comment by wanghuan578** [comment]
第一次播放莫名终止，然后vlc重试播放直接崩溃。稳定性跟srs、nginx-rtmp还有一定差距，楼主加油！！！！

**Comment by xia-chu** [comment]
不能这么讲啊 如果这么脆弱 那zlm不要在开源界混了

**Comment by xia-chu** [comment]
zlm在我们公司也是部署了几年啊 rtmp用的非常多 没你说的这么脆弱啊 目前线上运行 我还没遇到过一次core dump事故

**Comment by wanghuan578** [comment]
2020-08-30 22:28:01.142 W MediaServer[1964] RtmpSession.cpp:31 onError | 140472408862232(192.168.22.122:53595) RTMP播放器(__defaultVhost__/live/apple)断开:rtmp ring buffer detached,耗时(s):34

**Comment by wanghuan578** [comment]
vlc崩溃，zm server只是报错，应该是vlc播放视频结尾遇到错误

**Comment by xia-chu** [comment]
vlc崩溃跟zlm有啥关系啊

**Comment by xia-chu** [comment]
而且我停止推流 vlc也不会崩溃啊
