### ISSUE TITLE
HLS的TS切片时间不准确

### ISSUE THREAD

**Issue by seven-lfz** [xia-chu/ZLMediaKit#463]
Hi，在HlsMaker.cpp的flushLastSegment成员方法中，TS切片的时间是根据本地文件的创建时间与关闭时间来计算的：
    //文件创建到最后一次数据写入的时间即为切片长度
    auto seg_dur = _ticker.elapsedTime() - _ticker_last_data.elapsedTime();
    if(seg_dur <= 0){
        seg_dur = 100;
    }
但是录制的源基本是来自网络，网络的延迟/丢包/抖动肯定会造成TS的pts/dts与本地ticker计算的时间不一致的

**Comment by xia-chu** [comment]
是的 确实有这个问题 后面可以修改下

**Comment by xia-chu** [comment]
已经改了
