### ISSUE TITLE
调用addFFmpegSource报错

### ISSUE THREAD

**Issue by z-feiyu** [xia-chu/ZLMediaKit#465]
# request:
GET /index/api/addFFmpegSource?src_url=rtsp://admin:admin@192.168.14.59:554/h264/ch41/main/av_stream&dst_url=rtmp://192.168.14.57:1935/live/aa&secret=1035c73f7-bb6b-4889-a715-d9eb2d1925cc&timeout_ms=30000
# content:

# args:
dst_url : rtmp://192.168.14.57:1935/live/aa
secret : 1035c73f7-bb6b-4889-a715-d9eb2d1925cc
src_url : rtsp://admin:admin@192.168.14.59:554/h264/ch41/main/av_stream
timeout_ms : 30000
# response:
{
   "code" : 0,
   "data" : {
      "key" : "44e73851aeb5d56243f4f739cc38846f"
   }
}

MediaServer(7) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 120
2020-09-04 04:28:51.233 W | onError 139790917885216(192.168.14.54:61632) session timeouted
MediaServer(7) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 38
2020-09-04 04:28:51.233 T | ~HttpSession 139790917885216(192.168.14.54:61632) 
MediaServer(7) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 120
2020-09-04 04:28:51.533 W | onError 139790850724832(192.168.14.54:61633) session timeouted
MediaServer(7) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 38
2020-09-04 04:28:51.533 T | ~HttpSession 139790850724832(192.168.14.54:61633)

**Comment by xia-chu** [comment]
看你日志没有任何 报错

**Comment by xia-chu** [comment]
你更新最新代码试试

**Comment by z-feiyu** [comment]
感谢您的回复，问题已解决，我改用addStreamProxy就可以了
