### ISSUE TITLE
关于大华y=000000及commit "完善GB28181推流"的疑问

### ISSUE THREAD

**Issue by graphnj** [xia-chu/ZLMediaKit#466]
@xia-chu  您好，在8 Jul的"完善GB28181推流"中看你重新“使用ssrc为流id”
这么一来对于大华等ssrc（y=000000）的情况继续为流id了，从而造成据此识别的地址dismatch
请问这个基于什么考虑，如何解决大华等y=000000的情况，谢谢

_Originally posted by @graphnj in https://github.com/xia-chu/ZLMediaKit/issues/338#issuecomment-686920391_

**Comment by xia-chu** [comment]
你使用openRtpServer接口创建单独的端口吧。请查看wiki关于restful api的文章

**Comment by zhang2349** [comment]
是兼容了两种方式，即支持单独端口一个流 也支持 一个端口 多个ssrc流

**Comment by xia-chu** [comment]
issue想关闭了 有什么问题继续在此issue说。
