### ISSUE TITLE
20.04-runtime-ubuntu18.04镜像支持rtmp的H265编码吗

### ISSUE THREAD

**Issue by z-feiyu** [xia-chu/ZLMediaKit#467]
你好，我用的是20.04-runtime-ubuntu18.04镜像，拉取rtsp（H265），推到rtmp，视频无法播放，请问，那个镜像不支持吗？

**Comment by z-feiyu** [comment]
我自己编译了个最新的ffmpeg。里面有依赖了H265，替换了原理的ffmpeg，然后重启镜像，还是无法播放？假如使用新的代码，重新打包一个镜像，是否支持rtsp（H265）转rtmp的功能。

**Comment by z-feiyu** [comment]
![image](https://user-images.githubusercontent.com/33253773/92225438-c8a62d80-eed5-11ea-925b-cf1d2ad1700a.png)

这个是我的ffmpeg，是有H265的，但是无法播放rtmpH265的视频

**Comment by xia-chu** [comment]
rtmp原生不支持265 你需要定制版ffmpeg

**Comment by z-feiyu** [comment]
**您说的定制版ffmpeg是指以下这个操作吗？**

![image](https://user-images.githubusercontent.com/33253773/92262537-e1323a00-ef0d-11ea-92e4-453132c41ea7.png)

**Comment by z-feiyu** [comment]
HTTP-FLV是否支持h265推流？

**Comment by xia-chu** [comment]
你可以使用这个定制版本的FFmpeg：https://gitee.com/xia-chu/FFmpeg
ZLMediaKit支持输出h265的HTTP-FLV流。

**Comment by z-feiyu** [comment]
是否编译这个定制版本的FFmpeg，然后放进docker里即可？

**Comment by xia-chu** [comment]
docker镜像不是我做的 我也不会做 ，也不想去维护docker镜像。

**Comment by xia-chu** [comment]
issue我先关闭了  你有什么问题继续在此issue提吧。

**Comment by z-feiyu** [comment]
你好，https://gitee.com/xia-chu/FFmpeg这个定制的ffpmeg的镜像我已经打包好了，但是不清楚这个依赖是在哪个路径下，由于我的个非C++研发，所以问的问题可能有点低级，请见谅。

**Comment by AlucardNosferatu** [comment]
这个项目根本没用到ffmpeg，没编译ffmpeg都能用，跟ffmpeg有啥关系。。。？

**Comment by z-feiyu** [comment]
假如想要让rtmp支持H265的话，除了要引入定制的ffmpeg外，代码需要改吗

**Comment by z-feiyu** [comment]
总结下：

**Comment by z-feiyu** [comment]
总结
