### ISSUE TITLE
当前视频录像文件是否支持 fmp4 格式？ 

### ISSUE THREAD

**Issue by chuyue86** [xia-chu/ZLMediaKit#469]
H5 下 fmp4 格式 组合预览比较方便 .. 我查了下代码当前好像是不支持？
我现在的方案是监听 mp4 文件的事件回调，然后用 ffmpeg 转一下，这样 CPU/IO 性能都有些损失

**Comment by xia-chu** [comment]
嗯 支持http-fmp4或ws-fmp4是个方向 不过现在还没时间去弄

**Comment by xia-chu** [comment]
#385

**Comment by chuyue86** [comment]
嗯嗯 好的 .... 大牛辛苦
