### ISSUE TITLE
addFFmpegSource拉流方式，想设置tcp支持吗

### ISSUE THREAD

**Issue by z-feiyu** [xia-chu/ZLMediaKit#470]

**Comment by xia-chu** [comment]
支持 需要你修改FFmpeg拉流命令，在配置文件中

**Comment by z-feiyu** [comment]
报错：GET /index/api/addStreamProxy?vhost=192.168.238.128:8080&app=proxy&stream=0&enable_rtsp=1&enable_rtmp=1&url=rtsp://admin:123456@192.168.56.111:5541&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
# content:

# args:
app : proxy
enable_rtmp : 1
enable_rtsp : 1
secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
stream : 0
url : rtsp://admin:123456@192.168.56.111:5541
vhost : 192.168.238.128:8080
# response:
{
   "code" : -1,
   "msg" : "play rtsp timeout"
}


MediaServer(6) /opt/media/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp 80
2020-09-09 08:15:16.419 W | operator() Socket not set errCB
MediaServer(6) /opt/media/ZLMediaKit/src/Rtsp/RtspPlayerImp.h 33
2020-09-09 08:15:16.419 D | ~RtspPlayerImp 
MediaServer(6) /opt/media/ZLMediaKit/src/Rtsp/RtspPlayer.cpp 39
2020-09-09 08:15:16.419 D | ~RtspPlayer 
MediaServer(6) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 120
2020-09-09 08:15:22.998 W | onError 140143440696112(172.17.0.1:54734) session timeouted
MediaServer(6) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 38
2020-09-09 08:15:22.999 T | ~HttpSession 140143440696112(172.17.0.1:54734)

**Comment by xia-chu** [comment]
检查下rtsp://admin:123456@192.168.56.111:5541能否播放

**Comment by z-feiyu** [comment]
# request:
GET /index/api/addStreamProxy?vhost=192.168.14.64:11935&app=proxy&stream=1&enable_rtsp=1&enable_rtmp=1&url=rtsp://admin:123456@192.168.56.111:5541&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
# content:

# args:
app : proxy
enable_rtmp : 1
enable_rtsp : 1
secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
stream : 1
url : rtsp://admin:zww123456.@192.168.56.111:5541
vhost : 192.168.14.64:11935
# response:
{
   "code" : -1,
   "msg" : "host is unreachable"
}


MediaServer(7) /opt/media/ZLMediaKit/src/Rtsp/RtspPlayerImp.h 33
2020-09-11 02:09:34.524 D | ~RtspPlayerImp 
MediaServer(7) /opt/media/ZLMediaKit/src/Rtsp/RtspPlayer.cpp 39
2020-09-11 02:09:34.524 D | ~RtspPlayer

**Comment by z-feiyu** [comment]
![image](https://user-images.githubusercontent.com/33253773/92843534-6db19080-f417-11ea-9826-9adf8f254912.png)

**Comment by xia-chu** [comment]
zlm没法访问192.168.56.111

**Comment by z-feiyu** [comment]
![image](https://user-images.githubusercontent.com/33253773/92844361-59ba5e80-f418-11ea-841b-b3526c7bba71.png)

**Comment by xia-chu** [comment]
你可以在docker里面抓下包看看为什么tcp连接不上

**Comment by wasphin** [comment]
> # request:
> GET /index/api/addStreamProxy?vhost=192.168.14.64:11935&app=proxy&stream=1&enable_rtsp=1&enable_rtmp=1&url=rtsp://admin:123456@192.168.56.111:5541&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
> 
> # content:
> # args:
> app : proxy
> enable_rtmp : 1
> enable_rtsp : 1
> secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
> stream : 1
> url : rtsp://admin:zww123456.@192.168.56.111:5541

和这个地址有没有关系? 两次都是 192.168.56.111:5541，一次是 timeout 一次是 unreachable，和 @ 前面这个点有没关系？

> vhost : 192.168.14.64:11935
> 
> # response:
> {
> "code" : -1,
> "msg" : "host is unreachable"
> }

**Comment by xia-chu** [comment]
我觉得这个是你使用不当或者环境配置异常导致，这个很明显的问题 如果是bug，别人早就反馈了。
