### ISSUE TITLE
Rtp视频流获取关键帧和宽高的问题

### ISSUE THREAD

**Issue by zhang2349** [xia-chu/ZLMediaKit#473]
https://github.com/xia-chu/ZLMediaKit/blob/9c96f8d31a4a95b470f5aa7d049635c725aa7e5d/src/Rtp/RtpProcess.cpp#L169
在这里的frame->keyFrame()为什么都是false？

https://github.com/xia-chu/ZLMediaKit/blob/9c96f8d31a4a95b470f5aa7d049635c725aa7e5d/src/Rtp/RtpProcess.cpp#L178
这里的track是VideoTrack的时候 getVideoWidth() 和 getVideoHeight() 为什么都是0

要想获取关键帧 和 宽高信息要怎么获取呢？

**Comment by xia-chu** [comment]
track要ready状态才能获取宽高信息。
frame->keyFrame()肯定不会一直是false的

**Comment by zhang2349** [comment]
frame->keyFrame() 确实都是false   看流都是正常的

addTrack 只是触发了一次  那什么时候 在哪里会变成ready呢？

**Comment by xia-chu** [comment]
你看到地方不对，ts中，sps pps idr会打包在一起，还没split，所以frame->keyFrame()一直是false。
你应该在MediaSink对象里面看，里面会统一split并且会等待ready

**Comment by zhang2349** [comment]
我写了一个muxer继承 MediaSink，然后把inputFrame，他会把一个I帧分成了四个包， 大小分别为 9 21 9  68581
然后第四个包 keyFrame是true
我用ffmpeg来解码，只把第四个包 放进去 是解码不出来的
要把完整的四个包放进去 才能解码出来

如果是P帧 就不会拆成几个包

这里拆的逻辑是不是有点问题

**Comment by zhang2349** [comment]
看了下  前面三帧是 SPS PPS SEI  没这几帧 ffmpeg貌似解码不出来 
现在想只解码I帧 我要怎么判断 也把这三种帧也放进 ffmpeg？

**Comment by xia-chu** [comment]
ZLMediaKit里面会分成一帧一帧的，但是FFmpeg要求 sps pps idr一起输进去解码(但是我实测好像不需要)

**Comment by zhang2349** [comment]
我用tests里的FFMpegDecoder测试的   不输入 pps 或 不输入 sei  都解码不出来
不输入sps倒是可以解码出来

**Comment by xia-chu** [comment]
要输入sps pps的 只是不要求和idr一起输入



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhang2349 <notifications@github.com&gt;
发送时间: 2020年9月30日 11:26
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] Rtp视频流获取关键帧和宽高的问题 (#473)





 
我用tests里的FFMpegDecoder测试的   不输入 pps 或 不输入 sei  都解码不出来
 不输入sps倒是可以解码出来

**Comment by zhang2349** [comment]
现在的问题是 Frame怎么判断是sps pps之类的  没找到有类型

**Comment by xia-chu** [comment]
你参考test_player这个测试程序吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhang2349 <notifications@github.com&gt;
发送时间: 2020年9月30日 11:36
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] Rtp视频流获取关键帧和宽高的问题 (#473)





 
现在的问题是 Frame怎么判断是sps pps之类的  没找到有类型

**Comment by zhang2349** [comment]
哦 按dts合并回去
