### ISSUE TITLE
rtsp转hls，addStreamProxy实现原理

### ISSUE THREAD

**Issue by yuezhongxin** [xia-chu/ZLMediaKit#476]
你好，我想问下，rtsp转hls，addStreamProxy实现原理是什么？rtsp拉流转成hls，是使用FFmpeg推流的吗？

**Comment by xia-chu** [comment]
不是 rtsp拉流后会解复用成音视频帧、然后再生成hls

**Comment by yuezhongxin** [comment]
好的，这个性能怎么样？能达到下面描述的那样吗（方式不同）？
![image](https://user-images.githubusercontent.com/6800671/92893206-11b52f00-f44c-11ea-9c20-1ca04fb2c09c.png)

**Comment by xia-chu** [comment]
hls根磁盘io性能关系很大&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 蟋蟀 <notifications@github.com&gt;
发送时间: 2020年9月11日 16:31
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] rtsp转hls，addStreamProxy实现原理 (#476)





 
好的，这个性能怎么样？能达到下面描述的那样吗（方式不同）？

**Comment by yuezhongxin** [comment]
好的，这个做过测试没？是不是和cpu没关系？一般固态硬盘能支撑多少个？

**Comment by xia-chu** [comment]
这个要你自己测试啊

**Comment by yuezhongxin** [comment]
好的
