### ISSUE TITLE
Centos 7编译报错

### ISSUE THREAD

**Issue by yuezhongxin** [xia-chu/ZLMediaKit#480]
你好，我参考的这个教程：https://blog.csdn.net/sunsixy/article/details/105411647

Centos 7编译报错：

```
[root@xxxx ZLMediaKit]# ./build_for_linux.sh
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Debug版本
-- found library:/usr/lib64/libssl.so;/usr/lib64/libcrypto.so,ENABLE_OPENSSL defined
-- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION
-- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION - Failed
-- MySQL not found.
-- ENABLE_HLS defined
You have called ADD_LIBRARY for library mpeg without any source files. This typically indicates a problem with your CMakeLists.txt file
-- ENABLE_MP4 defined
You have called ADD_LIBRARY for library mov without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library flv without any source files. This typically indicates a problem with your CMakeLists.txt file
-- ENABLE_RTPPROXY defined
You have called ADD_LIBRARY for library zltoolkit without any source files. This typically indicates a problem with your CMakeLists.txt file
-- add c api tester:server
-- add c api tester:websocket
-- test_player ingored, please install sdl2 ffmpeg/libavcodec ffmpeg/libavutil
-- add test:bom
-- add test:tab
-- add test:test_benchmark
-- add test:test_httpApi
-- add test:test_httpClient
-- add test:test_pusher
-- add test:test_pusherMp4
-- add test:test_rtp
-- add test:test_server
-- add test:test_wsClient
-- add test:test_wsServer
-- Configuring done
CMake Error: Cannot determine link language for target "zltoolkit".
CMake Error: CMake can not determine linker language for target: zltoolkit
CMake Error: Cannot determine link language for target "flv".
CMake Error: CMake can not determine linker language for target: flv
CMake Error: Cannot determine link language for target "mov".
CMake Error: CMake can not determine linker language for target: mov
CMake Error: Cannot determine link language for target "mpeg".
CMake Error: CMake can not determine linker language for target: mpeg
-- Generating done
-- Build files have been written to: /home/admin/ZLMediaKit-depend/ZLMediaKit/linux_build
Scanning dependencies of target mov
Scanning dependencies of target mpeg
Scanning dependencies of target zltoolkit
Scanning dependencies of target flv
make[2]: *** No rule to make target `CMakeFiles/zltoolkit.dir/build'.  Stop.
make[2]: *** No rule to make target `CMakeFiles/mov.dir/build'.  Stop.
make[1]: *** [CMakeFiles/zltoolkit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/mov.dir/all] Error 2
make[2]: *** No rule to make target `CMakeFiles/mpeg.dir/build'.  Stop.
make[2]: *** No rule to make target `CMakeFiles/flv.dir/build'.  Stop.
make[1]: *** [CMakeFiles/mpeg.dir/all] Error 2
make[1]: *** [CMakeFiles/flv.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by xia-chu** [comment]
麻烦你好好看看wiki



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 蟋蟀 <notifications@github.com&gt;
发送时间: 2020年9月14日 15:50
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] Centos 7编译报错 (#480)





 
你好，我参考的这个教程：https://blog.csdn.net/sunsixy/article/details/105411647
 
Centos 7编译报错：
 [root@xxxx ZLMediaKit]# ./build_for_linux.sh -- The C compiler identification is GNU 5.4.0 -- The CXX compiler identification is GNU 5.4.0 -- Check for working C compiler: /usr/local/bin/gcc -- Check for working C compiler: /usr/local/bin/gcc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done -- Check for working CXX compiler: /usr/local/bin/g++ -- Check for working CXX compiler: /usr/local/bin/g++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Detecting CXX compile features -- Detecting CXX compile features - done -- Debug版本 -- found library:/usr/lib64/libssl.so;/usr/lib64/libcrypto.so,ENABLE_OPENSSL defined -- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION -- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION - Failed -- MySQL not found. -- ENABLE_HLS defined You have called ADD_LIBRARY for library mpeg without any source files. This typically indicates a problem with your CMakeLists.txt file -- ENABLE_MP4 defined You have called ADD_LIBRARY for library mov without any source files. This typically indicates a problem with your CMakeLists.txt file You have called ADD_LIBRARY for library flv without any source files. This typically indicates a problem with your CMakeLists.txt file -- ENABLE_RTPPROXY defined You have called ADD_LIBRARY for library zltoolkit without any source files. This typically indicates a problem with your CMakeLists.txt file -- add c api tester:server -- add c api tester:websocket -- test_player ingored, please install sdl2 ffmpeg/libavcodec ffmpeg/libavutil -- add test:bom -- add test:tab -- add test:test_benchmark -- add test:test_httpApi -- add test:test_httpClient -- add test:test_pusher -- add test:test_pusherMp4 -- add test:test_rtp -- add test:test_server -- add test:test_wsClient -- add test:test_wsServer -- Configuring done CMake Error: Cannot determine link language for target "zltoolkit". CMake Error: CMake can not determine linker language for target: zltoolkit CMake Error: Cannot determine link language for target "flv". CMake Error: CMake can not determine linker language for target: flv CMake Error: Cannot determine link language for target "mov". CMake Error: CMake can not determine linker language for target: mov CMake Error: Cannot determine link language for target "mpeg". CMake Error: CMake can not determine linker language for target: mpeg -- Generating done -- Build files have been written to: /home/admin/ZLMediaKit-depend/ZLMediaKit/linux_build Scanning dependencies of target mov Scanning dependencies of target mpeg Scanning dependencies of target zltoolkit Scanning dependencies of target flv make[2]: *** No rule to make target `CMakeFiles/zltoolkit.dir/build'.  Stop. make[2]: *** No rule to make target `CMakeFiles/mov.dir/build'.  Stop. make[1]: *** [CMakeFiles/zltoolkit.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... make[1]: *** [CMakeFiles/mov.dir/all] Error 2 make[2]: *** No rule to make target `CMakeFiles/mpeg.dir/build'.  Stop. make[2]: *** No rule to make target `CMakeFiles/flv.dir/build'.  Stop. make[1]: *** [CMakeFiles/mpeg.dir/all] Error 2 make[1]: *** [CMakeFiles/flv.dir/all] Error 2 make: *** [all] Error 2 [root@net-forward ZLMediaKit]# yum install sdl2 ffmpeg/libavcodec ffmpeg/libavutil Loaded plugins: fastestmirror Loading mirror speeds from cached hostfile No package sdl2 available.   * Maybe you meant: SDL2 No package ffmpeg/libavcodec available. No package ffmpeg/libavutil available. Error: Nothing to do

**Comment by yuezhongxin** [comment]
好的，看到了，大意了。。。

**Comment by wasphin** [comment]
像是没下载子模块, 参考[快速开始](https://github.com/xia-chu/ZLMediaKit/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)应该更靠谱些.

**Comment by xia-chu** [comment]
@wasphin 大佬 在qq群里面at你怎么不说话啊
