### ISSUE TITLE
HttpSession Input数据太快可能会导致客户端接收数据不完整？

### ISSUE THREAD

**Issue by ChnPhantom** [xia-chu/ZLMediaKit#481]
程序基于C接口实现，数据输入接口为mk_media_input_h264，当数据input太快，httpsession内部报session timeouted，从而导致客户端没有收完数据就被迫关闭了

**Comment by xia-chu** [comment]
你是http-flv播放吗

**Comment by ChnPhantom** [comment]
是的，局域网测试是可以的，可能是因为接收端也很快的原因，线上的话每次接收的数据大小都不固定，但都不完整




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夏楚"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 上午9:05
收件人: "xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;; 
抄送: "┽龍行天下┾"<295850318@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xia-chu/ZLMediaKit] HttpSession Input数据太快可能会导致客户端接收数据不完整？ (#481)





 
你是http-flv播放吗

**Comment by xia-chu** [comment]
那不应该是session timeouted，应该是Socket send timeout才对啊

**Comment by ChnPhantom** [comment]
我看了一下源码，好像是那个timer超时导致的。

**Comment by xia-chu** [comment]
实时上 这个session timeouted是输入数据太慢导致的 如果你连续15秒不输入任何数据，那么就会触发session timeouted

**Comment by ChnPhantom** [comment]
哦。可能是这个原因，我这边数据推完了，所以超时了。

**Comment by xia-chu** [comment]
你不是直播吗？

**Comment by ChnPhantom** [comment]
不是直播，应该是类似于点播

**Comment by ChnPhantom** [comment]
用直播走的录像

**Comment by xia-chu** [comment]
那你发送速度不对啊。ZLMediaKit也支持MP4转http-flv点播啊，你为什么要自己再做一遍呢

**Comment by ChnPhantom** [comment]
我们是私有协议转成flv的，而且我们录像是存在NVS上的，可以认为是从远端拉过来的裸数据

**Comment by xia-chu** [comment]
那你输入速度不应该按照时间戳输入吗

**Comment by ChnPhantom** [comment]
如果要用按需拉流的方式实现按需点播，怎么样实现比较好呢？

**Comment by xia-chu** [comment]
播时间戳慢慢输入到zlm



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: freesky <notifications@github.com&gt;
发送时间: 2020年9月15日 10:52
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] HttpSession Input数据太快可能会导致客户端接收数据不完整？ (#481)





 
如果要用按需拉流的方式实现按需点播，怎么样实现比较好呢？

**Comment by xia-chu** [comment]
先关闭issue了，有问题再在此讨论
