### ISSUE TITLE
在线分享可执行程序

### ISSUE THREAD

**Issue by xia-chu** [xia-chu/ZLMediaKit#483]
此issue保存常开，大家编译最新版本的zlm后可以把可执行文件以zip的方式上传至此。
希望大家能踊跃上传，包括但不限于windows、linux、mac、android版本。

**本项目不对用户上传至此的可执行文件的安全负责，用户请谨慎下载和使用。**

**Comment by xia-chu** [comment]
macos版本二进制文件：git hash: 00a7414f678abdd739f0e92c7d2ffa1d0ae99024
[macos.zip](https://github.com/xia-chu/ZLMediaKit/files/5224720/macos.zip)

**Comment by hh-kai** [comment]
ZLM源码编译未修改_VS2019x64_Release版本_可执行文件
[ZLM源码编译未修改_VS2019x64_Release版本_可执行文件.zip](https://github.com/xia-chu/ZLMediaKit/files/5229182/ZLM._VS2019x64_Release._.zip)

**Comment by xia-chu** [comment]
> ZLM源码编译未修改_VS2019x64_Release版本_可执行文件
> [ZLM源码编译未修改_VS2019x64_Release版本_可执行文件.zip](https://github.com/xia-chu/ZLMediaKit/files/5229182/ZLM._VS2019x64_Release._.zip)

对应的git hash值是多少？

**Comment by CrazyRico** [comment]
CentOS7.3 版本文件
a3e51f5ee856290866c7b1e63ad9fb72  debug.zip
[Debug.zip](https://github.com/xia-chu/ZLMediaKit/files/5229270/Debug.zip)

**Comment by xia-chu** [comment]
> CentOS7.3 版本文件
> a3e51f5ee856290866c7b1e63ad9fb72 debug.zip
> [Debug.zip](https://github.com/xia-chu/ZLMediaKit/files/5229270/Debug.zip)

大佬 这个Git hash不存在啊

**Comment by dlgcy** [comment]
Windows 版本：https://gitee.com/DLGCY_GB28181/ZLMediaKit/releases

**Comment by hh-kai** [comment]
> > ZLM源码编译未修改_VS2019x64_Release版本_可执行文件
> > [ZLM源码编译未修改_VS2019x64_Release版本_可执行文件.zip](https://github.com/xia-chu/ZLMediaKit/files/5229182/ZLM._VS2019x64_Release._.zip)
> 
> 对应的git hash值是多少？

啊 这个文件是直接拖上去的 没什么hash值啊...

**Comment by xia-chu** [comment]
我是说对应的代码的git提交hash



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kai <notifications@github.com&gt;
发送时间: 2020年9月16日 18:01
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 在线分享可执行程序 (#483)





   
ZLM源码编译未修改_VS2019x64_Release版本_可执行文件
 ZLM源码编译未修改_VS2019x64_Release版本_可执行文件.zip
  
对应的git hash值是多少？
  
啊 这个文件是直接拖上去的 没什么hash值啊...

**Comment by chuyue86** [comment]
ubuntu 20.04 GCC 9.3.0 Release:
*2020.09.17*
git hash *84b84ab97941d8d1229cf2d095492b4cfe818ee3*

>* enbale mp4
>* enable C API
>* enable C++ API
>* with jemalloc

[Linux generic x86-64](https://github.com/xia-chu/ZLMediaKit/files/5235744/zlmk_2020.09.17_x68_64.tar.gz)
[Linux ubuntu raspi aarch64](https://github.com/xia-chu/ZLMediaKit/files/5235745/zlmk_2020.09.17_aarch64.tar.gz)

**Comment by CrazyRico** [comment]
> > CentOS7.3 版本文件
> > a3e51f5ee856290866c7b1e63ad9fb72 debug.zip
> > [Debug.zip](https://github.com/xia-chu/ZLMediaKit/files/5229270/Debug.zip)
> 
> 大佬 这个Git hash不存在啊

这是打包后zip的md5sum  晕了

**Comment by CrazyRico** [comment]
CentOS Linux release 7.3.1611 (Core)
2020.09.17
git hash [00a7414](https://github.com/xia-chu/ZLMediaKit/commit/00a7414f678abdd739f0e92c7d2ffa1d0ae99024)
[Debug.zip](https://github.com/xia-chu/ZLMediaKit/files/5236551/Debug.zip)

**Comment by zhuangdx** [comment]
有windows下的test_player程序吗

**Comment by linshangqiang** [comment]
> 有windows下的test_player程序吗
win下默认不编译test_player,需要自行下载SDL2的依赖包和ffmpeg的avcodec、avutil这两个模块，然后用cmake-gui编译

**Comment by ywcai** [comment]
移植到海思3536平台 , 仅开启了rtsp\rtmp，关闭了所有api和webhook #

**Comment by xia-chu** [comment]
- 平台： windows-x64-release
- 编译工具：vs2017
- git hash: a9be01fbecd564c6bfd15c7e667f060a75dddc36
- 特性：包含OpenSSL
[zlm-Windows版本20210112.zip](https://github.com/xia-chu/ZLMediaKit/files/5799640/zlm-Windows.20210112.zip)

**Comment by xia-chu** [comment]
issue

**Comment by zengzhiying** [comment]
平台：ARM64
系统：CentOS 7.9
[media-server-aarch64-20210617.tar.gz](https://github.com/ZLMediaKit/ZLMediaKit/files/6730454/media-server-aarch64-20210617.tar.gz)

**Comment by 174001602** [comment]
平台：x86_64
系统：CentOS8
https://cp.dawawg.com/filesroot/update/ZLMediaKit/CentOS8/master_2021-11-18_MediaServer_f5bdd60

**Comment by MrSheng** [comment]
平台： windows-x64-release
编译工具：vs2019
特性：包含WebRtc
[MediaServer_windows64_2022_01_20.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8045392/MediaServer_windows64_2022_01_20.zip)

**Comment by leo94666** [comment]
Android版本 WebRTC播放库：
![image](https://user-images.githubusercontent.com/71742460/183577963-dcc951cd-ba00-47d0-8b44-bdfbccd8018d.png)
![@P6`K4J~~48$839((67NF9V](https://user-images.githubusercontent.com/71742460/183578358-b2885675-9491-49cf-a06c-f812620fb100.jpg)

[直达](https://github.com/leo94666/FuckAndroidAVSample/blob/master/app/src/main/java/com/top/av/webrtc/ZLMAndroidWebRTCClient.kt)

**Comment by AvenSun** [comment]
ZLMediaKit for windows 64bit based on [a1000da](https://github.com/ZLMediaKit/ZLMediaKit/commit/a1000da71f4d2a35869c8c3305da37e04c59aa70) committed on **Aug 12, 2022**


- MediaServer included.
- all test apps included.
- c++ api sdk included.
- webrtc support included.

please download files via [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases/tag/windows)

**Comment by xia-chu** [comment]
@AvenSun thank you!

**Comment by AvenSun** [comment]
@xia-chu 
I just did what I could, compared with your efforts,  It's nothing.

**Comment by leo94666** [comment]
Android版本 WebRTC播放器：
[Apk下载地址](https://github.com/leo94666/ZLMediaKit/blob/master/webrtc_player/android/app-debug.apk)
![Screenshot_2022-09-25-10-06-59-444_com zlmediakit webrtc](https://user-images.githubusercontent.com/71742460/192126273-c70ca54d-58d4-4ebb-8a9f-3ad496d15931.jpg)
测试结果
Android端，webrtc拉流播放，广域网实测400ms上下
[](https://user-images.githubusercontent.com/71742460/183578358-b2885675-9491-49cf-a06c-f812620fb100.jpg)

**Comment by AvenSun** [comment]
ZLMediaKit for windows 64bit based on [d2c64b1](https://github.com/ZLMediaKit/ZLMediaKit/commit/d2c64b1f097106d7182996663f136923cab62d92) committed on **Ocr 31, 2022**
> 
> 1. MediaServer included.
> 2. all test apps included.
> 3. c api sdk included.
> 4. webrtc support included.
> 5. OpenSSL library included.
> 
> you can get latest files via this link [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases)
> 
> It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.
> 
> I'll try my best to make it up to date.

**Comment by AvenSun** [comment]
ZLMediaKit for windows 64bit based on [9fd5152](https://github.com/ZLMediaKit/ZLMediaKit/commit/9fd5152aa116ea0c896d40fdd20ccceb9731b828) committed on **Nov 19, 2022**

1. MediaServer included.
2. all test apps included.
3. c api sdk included.
4. webrtc support included.
5. OpenSSL library included.

It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.

- **there's some break changes in config file committed on [9bb6a2f ](https://github.com/ZLMediaKit/ZLMediaKit/commit/9bb6a2f8288a5becd261267cbb722162bf9d338c) Nov 12, 2022, you might have to make modifications manually**

**Comment by gemone** [comment]
`Linux` 静态编译 `ZLMediaKit`: [gemone/ZLMediaKitBuild/releases](https://github.com/gemone/ZLMediaKitBuild/releases)

```shell
    cmake -B"${build_path}" "${src_path}" \
        -DCMAKE_INSTALL_PREFIX="${prefix_path}" \
        -DENABLE_WEBRTC:BOOL="0" \
        -DENABLE_SRT:BOOL="1" \
        -DCMAKE_EXE_LINKER_FLAGS:STRING="-static" \
        -DENABLE_API_STATIC_LIB:BOOL="1" \
        -DENABLE_JEMALLOC_STATIC:BOOL="1" \
        -DENABLE_X264:BOOL="0" \
        -DENABLE_FFMPEG:BOOL="1" \
        -DENABLE_PLAYER:BOOL="1" \
        -DENABLE_RTPPROXY:BOOL="0" \
        -DCMAKE_BUILD_TYPE:STRING="Release" 
```

**Comment by AvenSun** [comment]
ZLMediaKit for windows 64bit based on [f6cba98](https://github.com/ZLMediaKit/ZLMediaKit/commit/f6cba98a8ed7a9adedf85162e34265eb92c31838) committed on **Feb 6, 2023**

1. MediaServer included.
2. all test apps included.
3. c api sdk included.
4. webrtc support included.
5. OpenSSL library included.

 you can get latest files via this link [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases)

It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.

- **there's some break changes in config file committed on [9bb6a2f ](https://github.com/ZLMediaKit/ZLMediaKit/commit/9bb6a2f8288a5becd261267cbb722162bf9d338c) Nov 12, 2022, you might have to make modifications manually**

**Comment by puzzle9** [comment]
> 

研究了半天 https://github.com/ZLMediaKit/ZLMediaKit/issues/1172 最后发现关闭了这个 ENABLE_RTPPROXY

**Comment by pubpy2015** [comment]
> ZLMediaKit for windows 64bit based on [f6cba98](https://github.com/ZLMediaKit/ZLMediaKit/commit/f6cba98a8ed7a9adedf85162e34265eb92c31838) committed on **Feb 6, 2023**
> 
>     1. MediaServer included.
> 
>     2. all test apps included.
> 
>     3. c api sdk included.
> 
>     4. webrtc support included.
> 
>     5. OpenSSL library included.
> 
> 
> you can get latest files via this link [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases)
> 
> It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.
> 
>     * **there's some break changes in config file committed on [9bb6a2f ](https://github.com/ZLMediaKit/ZLMediaKit/commit/9bb6a2f8288a5becd261267cbb722162bf9d338c) Nov 12, 2022, you might have to make modifications manually**

@AvenSun Can you build with "Enable Jemalloc Static". 
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/0dbd6aee-4c4c-4452-afac-149cb89cb8fc)

I have a problem with memory, can happen if the frame drops many times, with 64 streams the memory will increase from 200MB to 4.5GB.

**Comment by AvenSun** [comment]
@pubpy2015 
I tried but failed to build Jemalloc static library on windows currently.
I made a benchmark on stream pushing (6Mb*150 IPC), It takes about 800 MB RAM on windows, 
 It looks good to me. I will try it later when I'm free. 
you can have a try the [latest build.](https://github.com/AvenSun/ZLMediaKit/releases)
![200](https://github.com/ZLMediaKit/ZLMediaKit/assets/5615543/45a42797-f302-445a-bef9-e83f33c47dd7)

**Comment by ILoveLin** [comment]
> Android版本 WebRTC播放器： [Apk下载地址](https://github.com/leo94666/ZLMediaKit/blob/master/webrtc_player/android/app-debug.apk) ![Screenshot_2022-09-25-10-06-59-444_com zlmediakit webrtc](https://user-images.githubusercontent.com/71742460/192126273-c70ca54d-58d4-4ebb-8a9f-3ad496d15931.jpg) 测试结果 Android端，webrtc拉流播放，广域网实测400ms上下 ![](https://user-images.githubusercontent.com/71742460/183578358-b2885675-9491-49cf-a06c-f812620fb100.jpg)

亲,有你这播放器的Demo链接吗?

**Comment by zhafree** [comment]
> 移植到海思3536平台 , 仅开启了rtsp\rtmp，关闭了所有api和webhook # [MediaServer.zip](https://github.com/xia-chu/ZLMediaKit/files/5744189/MediaServer.zip
应用跑不起来，有没有源码包？

**Comment by AvenSun** [comment]
ZLMediaKit for windows 64bit based on [f69f3b3](https://github.com/ZLMediaKit/ZLMediaKit/commit/f69f3b302971edb539fa256c514c0678af6c3169) committed on **Sep 9, 2023**

1. MediaServer included.
2. all test apps included.
3. c api sdk included.
4. webrtc support included.
5. OpenSSL library included.

 you can get latest files via this link [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases)

It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.

- **there's some break changes in config file committed on [9bb6a2f ](https://github.com/ZLMediaKit/ZLMediaKit/commit/9bb6a2f8288a5becd261267cbb722162bf9d338c) Nov 12, 2022, you might have to make modifications manually**

**Comment by conlaychan** [comment]
git hash:9f69303
windows x64 release
[MediaServer.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12744998/MediaServer.zip)

**Comment by sdvdxl** [comment]
git hash: c7f2f9e8

https://www.123pan.com/s/xaeEjv-UVNA3.html提取码:y0bh

**Comment by LuPeng0830** [comment]
基于 windows 系统的编译教程：[ZLMediaKit 流媒体服务器编译 - Windows系统](https://juejin.cn/post/7322010571360370703)，感兴趣的可以看看（非编译好的包）。

**Comment by zhang-chuanfeng** [comment]
> ZLMediaKit for windows 64bit based on [1b709f6](https://github.com/ZLMediaKit/ZLMediaKit/commit/1b709f665a8be35fc54af251805c6e8ef3841dc8) committed on **Mar 2, 2024**
> 
> 1. MediaServer included.
> 2. all test apps included.
> 3. c api sdk included.
> 4. webrtc support included.
> 5. OpenSSL library included.
> 
> you can get latest files via this link [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases)
> 
> It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.
> 
> * **there's some break changes in config file committed on [9bb6a2f ](https://github.com/ZLMediaKit/ZLMediaKit/commit/9bb6a2f8288a5becd261267cbb722162bf9d338c) Nov 12, 2022, you might have to make modifications manually**

我尝试了你这里编译的windows版本webrtc，webrtc播放一直转圈播放不出来。看日志应该发送数据了，应该使用的UDP发送的。开启关闭我看是正常的

**Comment by AvenSun** [comment]
@zhang-chuanfeng 

首先用到的端口都要在防火墙放行，再一个externIP要设。
如果这些没问题，请检查你的视频格式

**Comment by AvenSun** [comment]
ZLMediaKit for windows 64bit based on [64fdd78](https://github.com/ZLMediaKit/ZLMediaKit/commit/64fdd78330226afbad8a061fc5419040c54a7509) committed on **May 6, 2024**

1. MediaServer included.
2. all test apps included.
3. c api sdk included.
4. header files included.
5. webrtc support included.
6. OpenSSL library included.
7. Dependecies of **test_player** uploaded separately.

 you can get latest files via this link [ZLMediaKit for windows](https://github.com/AvenSun/ZLMediaKit/releases)

- It's built by Visual Studio 2019, so [VC Runtime ](https://aka.ms/vs/17/release/vc_redist.x64.exe) might be needed.
- **for dependecies of test_player, the release before today should choose FFMPEG-5, otherwise FFMPEG-6**

**Comment by AvenSun** [comment]
@floralhoop 

you should enable SSL firstly.  you can refer to this [link](https://github.com/ZLMediaKit/ZLMediaKit/wiki/zlm%E5%90%AF%E7%94%A8webrtc%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97#%E6%B5%8B%E8%AF%95) .

**Comment by taojin1122** [comment]
- 下载地址：https://github.com/taojin1122/ZLMediaKit/releases/tag/ZLMediaKit-7.0
- 分支：7.0
- 编译环境：windows10

**Comment by alan-su-jetfuel** [comment]
> * 下载地址: [Windows_master_2024-08-22](https://github.com/ZLMediaKit/ZLMediaKit/actions/runs/10508797851/artifacts/1842353978)
> * 分支: master
> * git hash: [c409fc5](https://github.com/ZLMediaKit/ZLMediaKit/commit/c409fc57545599a8d4dac2cbf179ce3e57d4a6ff)
> * 编译日期: 2024-08-22
> * 编译记录: [10508797851](https://github.com/ZLMediaKit/ZLMediaKit/actions/runs/10508797851)
> * 打包ci名: Windows
> * 开启特性: openssl/webrtc/datachannel
> * 说明: 此二进制为x64版本

為什麼會外連？

159.65.138.85

![1](https://github.com/user-attachments/assets/e1f75395-bce9-4c65-bb07-bc140e1de42c)

unassigned.psychz.net

![截圖 2024-08-27 下午5 28 40](https://github.com/user-attachments/assets/0b7204fa-3692-43d4-8438-dc10c33aab57)

通常要等一下，大概幾分鐘後會出現，出現後大概一陣子又會消失，然後再等一陣子又會出現，不斷循環，而且也發現在aws ec2 windows 會有人嘗試登入，這個就不知道是不是使用 MediaServer 的原因，無法直接證明

8/14有這問題，所以抓最新，最新一樣有這問題

**Comment by xuejianxuanyuan** [comment]
> * 下载地址: [Windows_master_2026-09-08](https://github.com/ZLMediaKit/ZLMediaKit/actions/runs/34197606105/artifacts/10044846855)
> * 分支: master
> * git hash: [5793bb5](https://github.com/ZLMediaKit/ZLMediaKit/commit/5793bb56fe5e01e8ecc19d7b35f9e3d49867d428)
> * 编译日期: 2026-09-08
> * 编译记录: [34197606105](https://github.com/ZLMediaKit/ZLMediaKit/actions/runs/34197606105)
> * 打包ci名: Windows
> * 开启特性: openssl/webrtc/datachannel
> * 说明: 此二进制为x64版本

为什么启动报粗呢？还需要安装什么插件吗？
