### ISSUE TITLE
是否支持rtsp + vp9?

### ISSUE THREAD

**Issue by jim-king-2000** [xia-chu/ZLMediaKit#485]
可否支持vp9编码的rtsp?现在推vp9的rtsp流，服务器会打印`mediakit::Factory::getTrackBySdp 暂不支持该sdp:VP9`。我们目前使用rtsp转webrtc来实现在浏览器中显示视频流。Webrtc支持的最优编码只能是vp9，它不支持hevc。

**Comment by jim-king-2000** [comment]
服务器是支持vp9的。是我没看清文档。

**Comment by xia-chu** [comment]
不能转协议而已 。你在搞rtc吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月16日 16:26
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





 
服务器是支持vp9的。是我没看清文档。

**Comment by yuezhongxin** [comment]
@jim-king-2000 `我们目前使用rtsp转webrtc来实现在浏览器中显示视频流`老哥，rtsp转webrtc你们怎么做的？有做p2p吗？

**Comment by jim-king-2000** [comment]
我们也正在使用RTSP转WebRTC的方案来实现在web中显示视频流。我们目前采用kurento来做转换。但是kurento不支持RTSP + H.265。而开源播放器VLC不支持RTSP + VP9。看来RTSP在web中显示是一个很大的难题。

**Comment by xia-chu** [comment]
可以强制客户端为H264。

**Comment by yuezhongxin** [comment]
> 我们也正在使用RTSP转WebRTC的方案来实现在web中显示视频流。我们目前采用kurento来做转换。但是kurento不支持RTSP + H.265。而开源播放器VLC不支持RTSP + VP9。看来RTSP在web中显示是一个很大的难题。

是的，我们目前也在搞这一块，RTSP直接浏览器播放，除了VXG Media Player插件，没有其他好的方式，除非转码，所以我们现在就转HLS来播放的，其实更好的方式可以转WebRTC，然后结合P2P，https://github.com/anyRTC-UseCase/ArRtspTool 这个看过没？

**Comment by yuezhongxin** [comment]
> 我们也正在使用RTSP转WebRTC的方案来实现在web中显示视频流。我们目前采用kurento来做转换。但是kurento不支持RTSP + H.265。而开源播放器VLC不支持RTSP + VP9。看来RTSP在web中显示是一个很大的难题。

是的，我们目前也在搞这一块，RTSP直接浏览器播放，除了VXG Media Player插件，没有其他好的方式，除非转码，所以我们现在就转HLS来播放的，其实更好的方式可以转WebRTC，然后结合P2P，https://github.com/anyRTC-UseCase/ArRtspTool 这个看过没？

**Comment by jim-king-2000** [comment]
> 可以强制客户端为H264。

不行。客户要求客户端必须为H.265。如果RTSP + VP9可以奏效，我还打算建议客户用VP9，毕竟压缩率与H.265差不多。可RTSP + VP9竟然连VLC都不能播放……

**Comment by xia-chu** [comment]
rtsp倒是支持265



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月17日 20:52
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





  
可以强制客户端为H264。
  
不行。客户要求客户端必须为H.265。如果RTSP + VP9可以奏效，我还打算建议客户用VP9，毕竟压缩率与H.265差不多。可RTSP + VP9竟然连VLC都不能播放……

**Comment by jim-king-2000** [comment]
> > 我们也正在使用RTSP转WebRTC的方案来实现在web中显示视频流。我们目前采用kurento来做转换。但是kurento不支持RTSP + H.265。而开源播放器VLC不支持RTSP + VP9。看来RTSP在web中显示是一个很大的难题。
> 
> 是的，我们目前也在搞这一块，RTSP直接浏览器播放，除了VXG Media Player插件，没有其他好的方式，除非转码，所以我们现在就转HLS来播放的，其实更好的方式可以转WebRTC，然后结合P2P，https://github.com/anyRTC-UseCase/ArRtspTool 这个看过没？

我调研过web播放RTSP几乎所有的方案，没有一种是可用的。
1. 不能用插件，因此所有的插件方案排除。
2. 转成RTMP，不支持H.265，而且RTMP的web player大都依赖flash，flash马上就要被全面禁止了。因此转RTMP排除。
3. 转HLS，实测延时太大，画质也不够好。排除。
4. 转WebRTC，有kurento方案，但是不支持H.265。RTSP实测基本上不支持VP9。打算尝试更新的av1，浏览器号称都支持，可是RTSP不支持。
5. FFMPEG + WASM，在网页上拿到YUV直接渲染到Canvas，没有成熟开源方案，即使有，由于无法使用硬解码，CPU占用率高得吓人，同时看16路监控估计八成要挂。

2020年了，人类都能探测火星了，H5还不支持RTSP，真是令人沮丧。

**Comment by xia-chu** [comment]
http-ts要不要试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月17日 21:02
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





   
我们也正在使用RTSP转WebRTC的方案来实现在web中显示视频流。我们目前采用kurento来做转换。但是kurento不支持RTSP + H.265。而开源播放器VLC不支持RTSP + VP9。看来RTSP在web中显示是一个很大的难题。
  
是的，我们目前也在搞这一块，RTSP直接浏览器播放，除了VXG Media Player插件，没有其他好的方式，除非转码，所以我们现在就转HLS来播放的，其实更好的方式可以转WebRTC，然后结合P2P，https://github.com/anyRTC-UseCase/ArRtspTool 这个看过没？
  
我调研过web播放RTSP几乎所有的方案，没有一种是可用的。
  
不能用插件，因此所有的插件方案排除。 

转成RTMP，不支持H.265，而且RTMP的web player大都依赖flash，flash马上就要被全面禁止了。因此转RTMP排除。 

转HLS，实测延时太大，画质也不够好。排除。 

转WebRTC，有kurento方案，但是不支持H.265。RTSP实测基本上不支持VP9。打算尝试更新的av1，浏览器号称都支持，可是RTSP不支持。 

FFMPEG + WASM，在网页上拿到YUV直接渲染到Canvas，没有成熟开源方案，即使有，由于无法使用硬解码，CPU占用率高得吓人，同时看16路监控估计八成要挂。 
 
2020年了，人类都能探测火星了，H5还不支持RTSP，真是令人沮丧。

**Comment by jim-king-2000** [comment]
http-ts, http-flv等，严格来讲不算是实时监控。在理论上好像他们都是存储一小段视频，然后一份一份下载到浏览器上。因此我个人不是非常倾向于他们。不过如果ZLMediaKit原生就能支持http-ts的话，我还是愿意尝试一下的。
我个人比较倾向的方案有两个。第一个是H5 video标签直接支持RTSP，<video src='rtsp://xxxx' type='rtsp' />。第二个是RTSP + H.265可以被转换成WebRTC + VP9(AV1也行，实在不行VP8也能接受)。但估计这两个方案得等到地老天荒。

**Comment by xia-chu** [comment]
http-ts和http-flv做直播延时很低的 握手也很少 非常适合做直播 zlm马上支持http-ts直播了 敬请期待



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月17日 21:18
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





 
http-ts, http-flv等，严格来讲不算是实时监控。在理论上好像他们都是存储一小段视频，然后一份一份下载到浏览器上。因此我个人不是非常倾向于他们。不过如果ZLMediaKit原生就能支持http-ts的话，我还是愿意尝试一下的。
 我个人比较倾向的方案有两个。第一个是H5 video标签直接支持RTSP，。第二个是RTSP + H.265可以被转换成WebRTC + VP9(AV1也行，实在不行VP8也能接受)。但估计这两个方案得等到地老天荒。

**Comment by jim-king-2000** [comment]
希望能支持H.256。

**Comment by xia-chu** [comment]
支持的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月17日 21:58
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





 
希望能支持H.256。

**Comment by yuezhongxin** [comment]
> > > 我们也正在使用RTSP转WebRTC的方案来实现在web中显示视频流。我们目前采用kurento来做转换。但是kurento不支持RTSP + H.265。而开源播放器VLC不支持RTSP + VP9。看来RTSP在web中显示是一个很大的难题。
> > 
> > 
> > 是的，我们目前也在搞这一块，RTSP直接浏览器播放，除了VXG Media Player插件，没有其他好的方式，除非转码，所以我们现在就转HLS来播放的，其实更好的方式可以转WebRTC，然后结合P2P，https://github.com/anyRTC-UseCase/ArRtspTool 这个看过没？
> 
> 我调研过web播放RTSP几乎所有的方案，没有一种是可用的。
> 
> 1. 不能用插件，因此所有的插件方案排除。
> 2. 转成RTMP，不支持H.265，而且RTMP的web player大都依赖flash，flash马上就要被全面禁止了。因此转RTMP排除。
> 3. 转HLS，实测延时太大，画质也不够好。排除。
> 4. 转WebRTC，有kurento方案，但是不支持H.265。RTSP实测基本上不支持VP9。打算尝试更新的av1，浏览器号称都支持，可是RTSP不支持。
> 5. FFMPEG + WASM，在网页上拿到YUV直接渲染到Canvas，没有成熟开源方案，即使有，由于无法使用硬解码，CPU占用率高得吓人，同时看16路监控估计八成要挂。
> 
> 2020年了，人类都能探测火星了，H5还不支持RTSP，真是令人沮丧。

哈哈，确实是这样的，但rtsp转webRTC方案有很多啊，除了kurento，还有WebRTC-streamer，janus等

**Comment by jim-king-2000** [comment]
我正在调研GStreamer的WebRTC，看看能不能支持RTSP + H.265。Janus就没精力去调研了。

**Comment by xia-chu** [comment]
webrtc又不支持265

**Comment by xia-chu** [comment]
rtsp就别想被浏览器支持了

**Comment by jim-king-2000** [comment]
> webrtc又不支持265

所以需要设法把RTSP + H.265转成WebRTC + VP9。

**Comment by jim-king-2000** [comment]
> rtsp就别想被浏览器支持了，浏览器只会支持http协议簇，当然rtsp也支持rtsp over http

浏览器永远不支持RTSP没问题。但浏览器应该通过某些便捷的方法（类似WASM等）支持扩展。现在已经是2020年了，基本上是everything on web的时代。大家支付用web，看电影用web，聊天用web，就连手机端的app，也已经渐渐过渡到webview + mobile web了。可是现在标准委员会却好像无所作为，真是让人失望。

**Comment by yuezhongxin** [comment]
> > rtsp就别想被浏览器支持了，浏览器只会支持http协议簇，当然rtsp也支持rtsp over http
> 
> 浏览器永远不支持RTSP没问题。但浏览器应该通过某些便捷的方法（类似WASM等）支持扩展。现在已经是2020年了，基本上是everything on web的时代。大家支付用web，看电影用web，聊天用web，就连手机端的app，也已经渐渐过渡到webview + mobile web了。可是现在标准委员会却好像无所作为，真是让人失望。

是的，webRTC也不支持rtsp，之前很多人提过，但是webRTC委员会就是死活不加，https://groups.google.com/forum/#!topic/discuss-webrtc/fKL2dJ1-l-Y

**Comment by jim-king-2000** [comment]
唉，这帮人尸位素餐，给开发者带来无尽的痛苦。想当年，H5/CSS3没有出来之前，垂直居中都需要奇技淫巧。H5/CSS3出现之后，所有这些代码都废了。现在，历史又开始重复。大家想尽各种办法来实现RTSP web player。一旦H5的video开始支持RTSP(或其它web标准支持RTSP)，前面的代码又全废了。

**Comment by xia-chu** [comment]
支持rtsp基本不可能，rtsp有组播、udp、tcp、http等各种传输方式，容易格式、编码格式也是五花八门，支持起来本来就比较困难。
而且浏览器除了webrtc这个另类，还支持非http协议簇吗 ？ 谷歌把webrtc强推进web标准，本来就不符合浏览器的设计原则，
完全是为了自己的利益。现在chrome死活不支持H265, 却支持笑话一样的VP8/VP9, 谷歌还搞了一个webm的标准，你说谷歌不夹杂私货可能吗？

谷歌为了推广自己的浏览器，在油管上做手脚，让ie edge Firefox运行不流畅，发热； 自家的服务估计搞的和其他浏览器不兼容。
谷歌还敢恬不知耻妄言说不作恶，你看看谷歌的产品，什么谷歌新闻，什么油管，你一注册就给你推送反中的新闻和视频，谷歌当年是屠龙少年，革掉了ie的命，现在自己却成为了恶龙。

我现在都不用chrom了，改用Firefox了，谷歌太恶心了。

**Comment by jim-king-2000** [comment]
哈哈哈，公司嘛，都是为了自身利益。标榜”不作恶“，也是为了自身利益。坐等哥们儿你的http-ts哈。

**Comment by xia-chu** [comment]
推送更新了

**Comment by jim-king-2000** [comment]
> 推送更新了

是已经支持了http-ts吗?

**Comment by xia-chu** [comment]
对 还支持httpfmp4



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月22日 10:37
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





  
推送更新了
  
是已经支持了http-ts吗?

**Comment by jim-king-2000** [comment]
赞啊。有没有文档告诉我们如何使用http-ts和http-mp4?

**Comment by xia-chu** [comment]
看wiki url规则篇



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月22日 10:41
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





 
赞啊。有没有文档告诉我们如何使用http-ts和http-mp4?

**Comment by jim-king-2000** [comment]
看到了。我马上尝试。

**Comment by jim-king-2000** [comment]
您这边有编译好的docker镜像吗?我们使用的是ubuntu 20.04，上次拉代码编了一下，挂了。如果您这边没有编译好的docker镜像的话，我就创建一个ubuntu 18的docker镜像，自己编。

**Comment by jim-king-2000** [comment]
我看到了。docker镜像也更新了。我马上尝试。

**Comment by xia-chu** [comment]
有 readme上更新了docker源 是最新代码了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年9月22日 10:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持rtsp + vp9? (#485)





 
您这边有编译好的docker镜像吗?我们使用的是ubuntu 20.04，上次拉代码编了一下，挂了。如果您这边没有编译好的docker镜像的话，我就创建一个ubuntu 18的docker镜像，自己编。

**Comment by jim-king-2000** [comment]
哥们儿，大赞啊。你做的fMP4，可以直接用H5的`<video />`tag来播放。此外，H.265的fMP4，在Microsoft New Edge浏览器上，是能够播放的。太棒了。从此，RTSP可以在网页上看了。去它xxx的客户端！！！

**Comment by yuezhongxin** [comment]
@jim-king-2000 兄弟，我rtsp转的hls，转fMP4有啥优点吗？

**Comment by jim-king-2000** [comment]
优点大概就是可以直接用H5的<video />tag来播放吧。

**Comment by yuezhongxin** [comment]
hls也`<video />`也可以的

**Comment by jim-king-2000** [comment]
赞。那HLS和fMP4有啥差异啊?

**Comment by yuezhongxin** [comment]
我也不知道呀，只知道HLS会有延迟，fMP4没了解

**Comment by jim-king-2000** [comment]
我用VLC测过，在局域网内，HLS和fMP4的延迟差不太多。

**Comment by xia-chu** [comment]
hls被淘汰了 用fmp4没错

**Comment by jim-king-2000** [comment]
那TS跟fMP4有啥区别?

**Comment by xia-chu** [comment]
> 那TS跟fMP4有啥区别?
区别就是fmp4浏览器支持更好而已

**Comment by jim-king-2000** [comment]
赞。我们打算去掉webrtc，直接用fMP4了。

**Comment by xia-chu** [comment]
如果不是交互的 那么fmp4是可以的

**Comment by xia-chu** [comment]
你们提了这么多问题 star都不给个 下次遇到不给star直接提issue的
我不回答了😂

**Comment by yuezhongxin** [comment]
@xia-chu 老哥，我star了，帮忙看下我的问题，感谢~~~  https://github.com/xia-chu/ZLMediaKit/issues/505

**Comment by jim-king-2000** [comment]
> 你们提了这么多问题 star都不给个 下次遇到不给star直接提issue的
> 我不回答了😂

亲，忘记了。刚刚给了star。

**Comment by jim-king-2000** [comment]
个人做了一个小捐赠，以表谢意。希望zlmediakit越来越好。

**Comment by xia-chu** [comment]
@jim-king-2000  大佬 你这个捐赠着实吓我一跳  收到最大的一笔 谢谢了！

**Comment by jim-king-2000** [comment]
亲，你客气了。这是你们东西做的好，应得的。未来希望多多支持。
