### ISSUE TITLE
HEVC MP4 Recoder 本地录像文件 关键帧标签 异常的问题

### ISSUE THREAD

**Issue by chuyue86** [xia-chu/ZLMediaKit#487]
ffmpeg -show_packets 分析本地录像文件，显示所有视频帧的 flag 都为关键帧，源码流为 hevc rtsp。

源码流为 h264，录像文件无异常。

附测试视频文件
[14-56-20.zip](https://github.com/xia-chu/ZLMediaKit/files/5231441/14-56-20.zip)

**Comment by xia-chu** [comment]
不是zlm的录制的吧？你看我录制的，完全正常啊
[09-37-51.mp4.zip](https://github.com/xia-chu/ZLMediaKit/files/5235735/09-37-51.mp4.zip)

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/93412209-4eab7680-f8cf-11ea-85a5-5b1517cd6135.png)
触发了ffmpeg的这个判断后，每个帧都会标记为关键字，触发条件时整个mp4文件都没有关键帧。
你发的那个视频里面一个关键帧都没被标记为关键帧(但是实际是有关键帧)。

**Comment by chuyue86** [comment]
我又用 MediaServer 进行了测试：

>* 使用 ffmpeg 推流方式，录像文件无异常
推流命令： ffmpeg -rtsp_transport tcp  -i rtsp://192.168.3.201:554/h264/ch33/main/av_stream  -vcodec copy -an -f rtsp rtsp://127.0.0.1/live/test2

>* 使用 WEB API /index/api/addStreamProxy 注册代理，录像文件 key flags 即出现问题
URL: http://127.0.0.1/index/api/addStreamProxy?vhost=__defaultVhost__&app=live&stream=test1&enable_rtsp=1&enable_mp4=1&enable_rtmp=1&url=rtsp://192.168.3.200:554/h264/ch33/main/av_stream

>* 调用 C++ API，使用 PlayerProxy, 录像文件 key flags 出现同样的问题

>* 所有录像文件均可正常解码，解码后 frame 标签及类型均正常

附测试文件：
[ffmpeg 推流录像文件](https://github.com/xia-chu/ZLMediaKit/files/5235995/ffmpeg_push.zip)
[proxy 代理录像文件](https://github.com/xia-chu/ZLMediaKit/files/5236001/proxy_stream.zip)
[原始裸码流文件](https://github.com/xia-chu/ZLMediaKit/files/5236073/src.zip)

**Comment by xia-chu** [comment]
> 不是zlm的录制的吧？你看我录制的，完全正常啊
> [09-37-51.mp4.zip](https://github.com/xia-chu/ZLMediaKit/files/5235735/09-37-51.mp4.zip)

这个文件就是我用addStreamProxy接口拉rtsp录制的

**Comment by chuyue86** [comment]
这么神奇的吗  ...  难道是我的相机有问题？我再查查看  ...

**Comment by xia-chu** [comment]
<img width="1043" alt="图片" src="https://user-images.githubusercontent.com/11495632/93417125-da2a0500-f8d9-11ea-803b-f2cb13739c5b.png">
你加点日志吧

**Comment by chuyue86** [comment]
日志这里显示的确是每两秒一个关键帧的，但是不知道为什么录像文件里就不对了  ... 
修改代码:
![image](https://user-images.githubusercontent.com/7552624/93421771-dc459100-f8e4-11ea-8a3b-0b2eb67b7f2a.png)

运行日志如下：
![image](https://user-images.githubusercontent.com/7552624/93421729-bcae6880-f8e4-11ea-8c20-a3c7fd12b0a2.png)

**Comment by xia-chu** [comment]
那可能第三方库有点问题。

**Comment by xia-chu** [comment]
这个问题我反馈给作者了 我觉得这个问题不大 不影响播放啊。

**Comment by xia-chu** [comment]
issue我先关闭了，后面再在此沟通
