### ISSUE TITLE
海康 RTMP推流摄像头推流报错“暂不支持该Amf:.mp3”？

### ISSUE THREAD

**Issue by doodoocoder** [xia-chu/ZLMediaKit#488]
三种场景下的测试(延时算法不标准，参考)：

服务端用的docker镜像（ubuntu16.04-runtime）

1.在局域网内，用obs推流，VLC拉流是没问题的，VLC延时大概4秒左右。

2.在局域网内，用obs推流，test_player拉流是没问题的，test_player延时大概2秒左右。

3.在局域网内，用海康的RTMP推流摄像头推流，test_player拉流，在ZLMediaKit服务端和test_player报相同的警告：暂不支持该Amf:.mp3.

**Comment by xia-chu** [comment]
嗯 音频不能解复用 但是视频应该没问题 还是能播放吧？

**Comment by doodoocoder** [comment]
我用的最新版本编译的是能使用的呢，海康的配置中视频类型选择的是复合流，拉流用的是test_player,几乎没延迟。如下：
![image](https://user-images.githubusercontent.com/26543224/93427715-deade800-f8f0-11ea-9286-acf356c01afe.png)



音频不能解复用是指码流中没有只有图像没有带音频吗？啥时候能支持呢？期待。

**Comment by xia-chu** [comment]
就是mp3的包会直接被丢弃 不响应其他的

**Comment by doodoocoder** [comment]
丢弃mp3包等于丢弃声音不（也就是视频没声音）？

**Comment by xia-chu** [comment]
对啊 就是没声音了 其他不影响

**Comment by doodoocoder** [comment]
大神，怎样才能支持有声音呢？有啥思路没？我对这方面不是太熟悉。

**Comment by xia-chu** [comment]
要加很多代码才行

**Comment by doodoocoder** [comment]
RTMP:笔记本上用OBS推流，VLC拉流，然后VLC上播放都有声音的。而用海康的RTMP摄像头，没有声音，应该是我这个海康的摄像头有个AUDIO的插孔没连接音频采样设备的原因吧。我觉得应该不是ZLMediaKit的原因。

**Comment by xia-chu** [comment]
嗯 rtmp推mp3,如果你播放的也是rtmp，那么不管什么编码都是支持的

**Comment by doodoocoder** [comment]
解决问题
