### ISSUE TITLE
GB28181是否会触发on_publish事件？

### ISSUE THREAD

**Issue by QiulinZhan** [xia-chu/ZLMediaKit#489]
您好，大神，请问ZLMediaKit收到相机通过国标协议发过来的视频流，是否会触发on_publish事件？
目前实况、回放都好用，但是想通过on_publish控制哪些视频流录制MP4，目前没有触发on_publish。

**Comment by xia-chu** [comment]
会的

**Comment by QiulinZhan** [comment]
2020-09-17 15:45:39.588 - INFO  [nio-7891-exec-3] c.z.s.g.t.c.i.SipCommander     : 发送invite >>> INVITE sip:10000000001320000071@192.168.2.248:5061 SIP/2.0
Call-ID: 4c96ba5ba52212cceb9f87d033af1b45@192.168.2.240
CSeq: 1 INVITE
From: <sip:10000000002000000001@192.168.2.240:7890>;tag=1acf5210cd3c4a19a69f3fe30e030be0
To: <sip:10000000001320000071@192.168.2.248:5061>
Via: SIP/2.0/UDP 192.168.2.240:7890
Max-Forwards: 70
Contact: <sip:10000000002000000001@192.168.2.240:7890>,<sip:10000000002000000001@192.168.2.240:7890>
Subject: 10000000001320000071:0,10000000002000000001:0
Content-Type: Application/SDP
Content-Length: 270

v=0
o=10000000001320000071 0 0 IN IP4 192.168.2.240
s=Playback
u=10000000001320000071:0
c=IN IP4 192.168.2.240
t=1595295848 1595562113
m=video 10000 RTP/AVP 96 97 98
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:97 MPEG4/90000
a=rtpmap:98 H264/90000
y=1000006453

2020-09-17 15:45:39.594 - INFO  [ntScannerThread] .g.t.r.i.InviteResponseHandler : invite >>> SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.2.240:7890;branch=z9hG4bK-383232-9ab79217c6e4a4a88f07f042a3542ed7
Call-ID: 4c96ba5ba52212cceb9f87d033af1b45@192.168.2.240
From: <sip:10000000002000000001@192.168.2.240:7890>;tag=1acf5210cd3c4a19a69f3fe30e030be0
To: <sip:10000000001320000071@192.168.2.248:5061>
CSeq: 1 INVITE
Content-Length: 0


2020-09-17 15:45:39.671 - INFO  [ntScannerThread] .g.t.r.i.InviteResponseHandler : invite >>> SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.2.240:7890;branch=z9hG4bK-383232-9ab79217c6e4a4a88f07f042a3542ed7
Call-ID: 4c96ba5ba52212cceb9f87d033af1b45@192.168.2.240
From: <sip:10000000002000000001@192.168.2.240:7890>;tag=1acf5210cd3c4a19a69f3fe30e030be0
To: <sip:10000000001320000071@192.168.2.248:5061>;tag=1017d880
CSeq: 1 INVITE
Contact: <sip:10000000001320000071@192.168.2.248:5061>
User-Agent: IMOS/V3
Content-Type: application/sdp
Content-Length: 215

v=0
o=10000000001320000071 0 0 IN IP4 192.168.2.248
s=Playback
c=IN IP4 192.168.2.248
t=1595295848 1595562113
m=video 24658 RTP/AVP 96
a=rtpmap:96 PS/90000
a=sendonly
y=1000000203
f=v/2/4/25/1/2000a/1/8/1

2020-09-17 15:45:42.888 - INFO  [nio-7891-exec-5] c.z.s.m.ZLMHttpHook            : on_stream_changed(rtsp/rtmp流注册或注销时触发此事件)，参数：{"app":"rtp","schema":"rtsp","vhost":"__defaultVhost__","stream":"3B9ACACB","regist":true}
2020-09-17 15:45:42.906 - INFO  [nio-7891-exec-6] c.z.s.m.ZLMHttpHook            : on_stream_changed(rtsp/rtmp流注册或注销时触发此事件)，参数：{"app":"rtp","schema":"rtmp","vhost":"__defaultVhost__","stream":"3B9ACACB","regist":true}
2020-09-17 15:45:47.896 - INFO  [nio-7891-exec-9] c.z.s.m.ZLMHttpHook            : on_stream_changed(rtsp/rtmp流注册或注销时触发此事件)，参数：{"app":"rtp","schema":"hls","vhost":"__defaultVhost__","stream":"3B9ACACB","regist":true}
2020-09-17 15:46:02.904 - INFO  [nio-7891-exec-4] c.z.s.m.ZLMHttpHook            : on_stream_none_reader(流无人观看时事件)，参数：{"app":"rtp","schema":"rtmp","vhost":"__defaultVhost__","stream":"3B9ACACB"}
2020-09-17 15:46:02.911 - INFO  [nio-7891-exec-4] c.z.s.g.t.c.i.SipCommander     : send bye >>> BYE sip:10000000001320000071@192.168.2.248:5061 SIP/2.0
Via: SIP/2.0/UDP 192.168.2.240:7890;branch=z9hG4bK-383232-6b84a7cf4d1f69df27bdbc42013f0eb2
CSeq: 2 BYE
From: <sip:10000000002000000001@192.168.2.240:7890>;tag=1acf5210cd3c4a19a69f3fe30e030be0
To: <sip:10000000001320000071@192.168.2.248:5061>;tag=1017d880
Call-ID: 4c96ba5ba52212cceb9f87d033af1b45@192.168.2.240
Max-Forwards: 70
Content-Length: 0


2020-09-17 15:46:02.917 - INFO  [ntScannerThread] z.s.g.t.r.i.ByeResponseHandler : response >>> SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.2.240:7890;branch=z9hG4bK-383232-6b84a7cf4d1f69df27bdbc42013f0eb2
Call-ID: 4c96ba5ba52212cceb9f87d033af1b45@192.168.2.240
From: <sip:10000000002000000001@192.168.2.240:7890>;tag=1acf5210cd3c4a19a69f3fe30e030be0
To: <sip:10000000001320000071@192.168.2.248:5061>;tag=1017d880
CSeq: 2 BYE
User-Agent: IMOS/V3
Content-Length: 0


2020-09-17 15:46:02.941 - INFO  [nio-7891-exec-2] c.z.s.m.ZLMHttpHook            : on_record_mp4(录制mp4完成后通知事件)，参数：{"app":"rtp","file_path":"/opt/media/bin/www/record/rtp/3B9ACACB/2020-09-17/07-45-42.mp4","start_time":1600328742,"time_len":20,"vhost":"__defaultVhost__","folder":"/opt/media/bin/www/record/rtp/3B9ACACB/","stream":"3B9ACACB","file_name":"07-45-42.mp4","file_size":2437840,"url":"record/rtp/3B9ACACB/2020-09-17/07-45-42.mp4"}
2020-09-17 15:46:02.948 - INFO  [nio-7891-exec-5] c.z.s.m.ZLMHttpHook            : on_stream_changed(rtsp/rtmp流注册或注销时触发此事件)，参数：{"app":"rtp","schema":"hls","vhost":"__defaultVhost__","stream":"3B9ACACB","regist":false}
2020-09-17 15:46:02.948 - INFO  [nio-7891-exec-3] c.z.s.m.ZLMHttpHook            : on_stream_changed(rtsp/rtmp流注册或注销时触发此事件)，参数：{"app":"rtp","schema":"rtsp","vhost":"__defaultVhost__","stream":"3B9ACACB","regist":false}
2020-09-17 15:46:02.948 - INFO  [nio-7891-exec-7] c.z.s.m.ZLMHttpHook            : on_stream_changed(rtsp/rtmp流注册或注销时触发此事件)，参数：{"app":"rtp","schema":"rtmp","vhost":"__defaultVhost__","stream":"3B9ACACB","regist":false}

**Comment by xia-chu** [comment]
你是不是没设置zlm的配置文件中的on_publish

**Comment by QiulinZhan** [comment]
{
    "code": 0,
    "data": [
        {
            "api.apiDebug": "1",
            "api.secret": "035c73f7-bb6b-4889-a715-d9eb2d1925cc",
            "ffmpeg.bin": "/usr/bin/ffmpeg",
            "ffmpeg.cmd": "%s -re -i \"%s\" -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
            "ffmpeg.log": "./ffmpeg/ffmpeg.log",
            "general.addMuteAudio": "1",
            "general.enableVhost": "0",
            "general.flowThreshold": "1024",
            "general.maxStreamWaitMS": "15000",
            "general.publishToHls": "1",
            "general.publishToMP4": "0",
            "general.publishToRtxp": "1",
            "general.resetWhenRePlay": "1",
            "general.streamNoneReaderDelayMS": "20000",
            "general.ultraLowDelay": "1",
            "hls.fileBufSize": "65536",
            "hls.filePath": "./www",
            "hls.segDur": "2",
            "hls.segNum": "3",
            "hls.segRetain": "5",
            "hook.admin_params": "secret=123131231231231231231",
            "hook.enable": "1",
            "hook.on_flow_report": "http://192.168.2.240:7891/hook/zlm/on_flow_report",
            "hook.on_http_access": "http://192.168.2.240:7891/hook/zlm/on_http_access",
            "hook.on_play": "http://192.168.2.240:7891/hook/zlm/on_play",
            "hook.on_publish": "http://192.168.2.240:7891/hook/zlm/on_publish",
            "hook.on_record_mp4": "http://192.168.2.240:7891/hook/zlm/on_record_mp4",
            "hook.on_rtsp_auth": "http://192.168.2.240:7891/hook/zlm/on_rtsp_auth",
            "hook.on_rtsp_realm": "http://192.168.2.240:7891/hook/zlm/on_rtsp_realm",
            "hook.on_server_started": "http://192.168.2.240:7891/hook/zlm/on_server_started",
            "hook.on_shell_login": "http://192.168.2.240:7891/hook/zlm/on_shell_login",
            "hook.on_stream_changed": "http://192.168.2.240:7891/hook/zlm/on_stream_changed",
            "hook.on_stream_none_reader": "http://192.168.2.240:7891/hook/zlm/on_stream_none_reader",
            "hook.on_stream_not_found": "http://192.168.2.240:7891/hook/zlm/on_stream_not_found",
            "hook.timeoutSec": "10",
            "http.charSet": "utf-8",
            "http.keepAliveSecond": "15",
            "http.maxReqSize": "4096",
            "http.notFound": "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit-5.0(build in Apr  6 2020 15:11:12)</center></body></html>",
            "http.port": "80",
            "http.rootPath": "./www",
            "http.sendBufSize": "65536",
            "http.sslport": "443",
            "multicast.addrMax": "239.255.255.255",
            "multicast.addrMin": "239.0.0.0",
            "multicast.udpTTL": "64",
            "record.appName": "record",
            "record.fastStart": "0",
            "record.fileBufSize": "65536",
            "record.filePath": "./www",
            "record.fileRepeat": "0",
            "record.fileSecond": "3600",
            "record.sampleMS": "500",
            "rtmp.handshakeSecond": "15",
            "rtmp.keepAliveSecond": "15",
            "rtmp.modifyStamp": "0",
            "rtmp.port": "1935",
            "rtp.audioMtuSize": "600",
            "rtp.clearCount": "10",
            "rtp.cycleMS": "46800000",
            "rtp.maxRtpCount": "50",
            "rtp.videoMtuSize": "1400",
            "rtp_proxy.checkSource": "1",
            "rtp_proxy.dumpDir": "",
            "rtp_proxy.port": "10000",
            "rtp_proxy.timeoutSec": "15",
            "rtsp.authBasic": "0",
            "rtsp.directProxy": "1",
            "rtsp.handshakeSecond": "15",
            "rtsp.keepAliveSecond": "15",
            "rtsp.port": "554",
            "rtsp.sslport": "332",
            "shell.maxReqSize": "1024",
            "shell.port": "9000"
        }
    ]
}

**Comment by QiulinZhan** [comment]
``` json
{
    "code": 0,
    "data": [
        {
            "api.apiDebug": "1",
            "api.secret": "035c73f7-bb6b-4889-a715-d9eb2d1925cc",
            "ffmpeg.bin": "/usr/bin/ffmpeg",
            "ffmpeg.cmd": "%s -re -i \"%s\" -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
            "ffmpeg.log": "./ffmpeg/ffmpeg.log",
            "general.addMuteAudio": "1",
            "general.enableVhost": "0",
            "general.flowThreshold": "1024",
            "general.maxStreamWaitMS": "15000",
            "general.publishToHls": "1",
            "general.publishToMP4": "0",
            "general.publishToRtxp": "1",
            "general.resetWhenRePlay": "1",
            "general.streamNoneReaderDelayMS": "20000",
            "general.ultraLowDelay": "1",
            "hls.fileBufSize": "65536",
            "hls.filePath": "./www",
            "hls.segDur": "2",
            "hls.segNum": "3",
            "hls.segRetain": "5",
            "hook.admin_params": "secret=123131231231231231231",
            "hook.enable": "1",
            "hook.on_flow_report": "http://192.168.2.240:7891/hook/zlm/on_flow_report",
            "hook.on_http_access": "http://192.168.2.240:7891/hook/zlm/on_http_access",
            "hook.on_play": "http://192.168.2.240:7891/hook/zlm/on_play",
            "hook.on_publish": "http://192.168.2.240:7891/hook/zlm/on_publish",
            "hook.on_record_mp4": "http://192.168.2.240:7891/hook/zlm/on_record_mp4",
            "hook.on_rtsp_auth": "http://192.168.2.240:7891/hook/zlm/on_rtsp_auth",
            "hook.on_rtsp_realm": "http://192.168.2.240:7891/hook/zlm/on_rtsp_realm",
            "hook.on_server_started": "http://192.168.2.240:7891/hook/zlm/on_server_started",
            "hook.on_shell_login": "http://192.168.2.240:7891/hook/zlm/on_shell_login",
            "hook.on_stream_changed": "http://192.168.2.240:7891/hook/zlm/on_stream_changed",
            "hook.on_stream_none_reader": "http://192.168.2.240:7891/hook/zlm/on_stream_none_reader",
            "hook.on_stream_not_found": "http://192.168.2.240:7891/hook/zlm/on_stream_not_found",
            "hook.timeoutSec": "10",
            "http.charSet": "utf-8",
            "http.keepAliveSecond": "15",
            "http.maxReqSize": "4096",
            "http.notFound": "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit-5.0(build in Apr  6 2020 15:11:12)</center></body></html>",
            "http.port": "80",
            "http.rootPath": "./www",
            "http.sendBufSize": "65536",
            "http.sslport": "443",
            "multicast.addrMax": "239.255.255.255",
            "multicast.addrMin": "239.0.0.0",
            "multicast.udpTTL": "64",
            "record.appName": "record",
            "record.fastStart": "0",
            "record.fileBufSize": "65536",
            "record.filePath": "./www",
            "record.fileRepeat": "0",
            "record.fileSecond": "3600",
            "record.sampleMS": "500",
            "rtmp.handshakeSecond": "15",
            "rtmp.keepAliveSecond": "15",
            "rtmp.modifyStamp": "0",
            "rtmp.port": "1935",
            "rtp.audioMtuSize": "600",
            "rtp.clearCount": "10",
            "rtp.cycleMS": "46800000",
            "rtp.maxRtpCount": "50",
            "rtp.videoMtuSize": "1400",
            "rtp_proxy.checkSource": "1",
            "rtp_proxy.dumpDir": "",
            "rtp_proxy.port": "10000",
            "rtp_proxy.timeoutSec": "15",
            "rtsp.authBasic": "0",
            "rtsp.directProxy": "1",
            "rtsp.handshakeSecond": "15",
            "rtsp.keepAliveSecond": "15",
            "rtsp.port": "554",
            "rtsp.sslport": "332",
            "shell.maxReqSize": "1024",
            "shell.port": "9000"
        }
    ]
}
```

**Comment by xia-chu** [comment]
<img width="779" alt="图片" src="https://user-images.githubusercontent.com/11495632/93656359-5187a200-fa5c-11ea-9a88-024a5dcaf7ef.png">
你应该wvp哪里设置异常了。
你可以用wireshark抓包，wvp日志不能表明什么
