### ISSUE TITLE
关于startSendRtp问题

### ISSUE THREAD

**Issue by westwindwintercome** [xia-chu/ZLMediaKit#492]
当打开hook时，使用startSendRtp API,第一次请求获取不到流，并且最终会触发无人观看

**Comment by xia-chu** [comment]
startSendRtp API是服务器主动推流啊 
你说的`第一次请求获取不到流`是什么意思？
startSendRtp启动后同样会触发无人观看事件，就像mp4录制开启后也会触发无人观看事件一样。

在ps-rtp推流时，你可以选择忽略无人观看事件

**Comment by xia-chu** [comment]
startSendRtp API是服务器主动推流啊 
你说的`第一次请求获取不到流`是什么意思？
startSendRtp启动后同样会触发无人观看事件，就像mp4录制开启后也会触发无人观看事件一样。

在ps-rtp推流时，你可以选择忽略无人观看事件

**Comment by westwindwintercome** [comment]
摄像头把流推给ZLMediaKit，然后我的程序先调用getRtpInfo，调用成功后再调用startSendRtp，但是第一调用startSendRtp后获取不到流，第二次调用就能收到；如果把hook关闭，还是这个流程就没有问题

**Comment by xia-chu** [comment]
那肯定啊 你要流注册后才能推流啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: west-wind <notifications@github.com&gt;
发送时间: 2020年9月18日 12:02
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 关于startSendRtp问题 (#492)





 
摄像头把流推给ZLMediaKit，然后我的程序先调用getRtpInfo，调用成功后再调用startSendRtp，但是第一调用startSendRtp后获取不到流，第二次调用就能收到；如果把hook关闭，还是这个流程就没有问题

**Comment by westwindwintercome** [comment]
就是说getRtpInfo成功了并不能代表流已经注册成功了？

**Comment by xia-chu** [comment]
对 你要监听事件才行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: west-wind <notifications@github.com&gt;
发送时间: 2020年9月18日 12:15
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 关于startSendRtp问题 (#492)





 
就是说getRtpInfo成功了并不能代表流已经注册成功了？

**Comment by westwindwintercome** [comment]
好的，回头试一下，感谢解答

**Comment by xia-chu** [comment]
先关闭issue了 有问题在此答复
