### ISSUE TITLE
从海康摄像头拉取sd卡中的录像（rtsp）时开始时间参数没用，拉取的流总是默认的开始时间

### ISSUE THREAD

**Issue by wanghouting123** [xia-chu/ZLMediaKit#493]
从海康摄像头拉取sd卡中的录像时开始时间参数没用

流地址： rtsp://admin:lootom8888@192.168.88.64:554/Streaming/tracks/102?starttime=20200916t120000z
从vlc 拉流显示的时间是从9月16号20点开始的，ffmpeg 也一样
zlm拉流则显示的时间是 rtsp://admin:lootom8888@192.168.88.64:554/Streaming/tracks/102 拉流的结果，应该是最早开始录像的时候，starttime参数没效果

**Comment by xia-chu** [comment]
你url里面带问号了 需要转义，否则会 被认为是http参数的一部分

**Comment by xia-chu** [comment]
issue先关闭，有问题请在此回复
