### ISSUE TITLE
为何不集成gstreamer?

### ISSUE THREAD

**Issue by alexliyu7352** [xia-chu/ZLMediaKit#496]
作者这个项目非常棒!!!!
我看了下基本上作者自己写了好多协议转换的代码, 所以就有一个疑问.
为何不直接集成gstreamer来实现转码或者封装转换呢?这样连ffmpeg都不需要了.
是因为性能问题么?
我看gstreamer的stream IO可以直接使用阿, 并不会多增加IO的负担.

抱歉这块不熟悉, 所以只能请教大神了.
另外如果集成gstreamer是否很复杂?

**Comment by xia-chu** [comment]
我觉得应该问 你为什么不直接用gstreamer呢？

**Comment by alexliyu7352** [comment]
我是诚心请教阿...看你的回复意思是没必要是么?

我知道gstreamer是一个媒体框架. 但是明显他不能替代ZLM阿.
我只是希望了解gstreamer为何不能和zlm结合, 用于全格式的转码或者转封装.
这样不就少了很多的代码量了么?
或者是这样会导致性能降低?还是什么?

**Comment by xia-chu** [comment]
zlm是个流媒体服务器框架 直播流媒体协议也就那么几种 我要那么多封装干嘛？
转码也不是流媒体服务器的核心，没必要挂一大坨那么东西，像NGINX-rtmp和srs那样fork FFmpeg进程的方式更简单轻便解耦，稳定性也有保障。

况且zlm的定位是全平台支持，交叉编译简单，轻量，我觉得如果要和gstreamer结合，完全可以把zlm做成sdk给gstreamer使用就行了。

zlm提供简单的c api, 完全不会喧宾夺主，可以很方便集成到其他代码里面去，所以问题应该是，其他代码怎么集成zlm。

**Comment by alexliyu7352** [comment]
哦, 明白了....
主要我是看到了这个项目https://fastocloud.com/
他和您的项目有些类似,而他使用的就是gstreamer
所以我才有这个疑问.

**Comment by xia-chu** [comment]
issue先关闭了
