### ISSUE TITLE
addFFmpegSource日志报错

### ISSUE THREAD

**Issue by yuasa1hiromi** [xia-chu/ZLMediaKit#499]
调用addFFmpegSource接口，返回    "code": -1, "msg": "等待超时"
ffmpeg.log日志是：

#### pid=45138,cmd=nohup /usr/local/bin/ffmpeg -re -i rtsp://admin:admin123@10.16.123.237:554/h264/ch1/main/av_stream -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://localhost/live/20212 & #####

fork process failed:-2(no such file or directory)

但是在shell可以用ffmpeg命令：
(base) root@zijaing:/usr/local/bin# nohup /usr/local/bin/ffmpeg -re -i rtsp://admin:admin123@10.16.123.237:554/h264/ch1/main/av_stream -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://localhost/live/20212 &
[1] 45225
(base) root@zijaing:/usr/local/bin# nohup: 忽略输入并把输出追加到'nohup.out'

(base) root@zijaing:/usr/local/bin# jobs
[1]+  运行中               nohup /usr/local/bin/ffmpeg -re -i rtsp://admin:admin123@10.16.123.237:554/h264/ch1/main/av_stream -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://localhost/live/20212 &

请问怎么解决这个调用addFFmpegSource接口的问题，非常感谢

**Comment by xia-chu** [comment]
不要nohup ， 配置文件中指定FFmpeg路径就行了
