### ISSUE TITLE
rstp流的密码为特殊符号“+”的话不支持播放，可以帮忙优化下吗

### ISSUE THREAD

**Issue by z-feiyu** [xia-chu/ZLMediaKit#500]
POST /index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&url=rtsp://mmyy:mmyz12345+@192.168.56.58:554/cam/realmonitor?channel=11&subtype=sub&vhost=http://192.168.56.58:8912&app=dhlive&stream=9&enable_rtsp=0&enable_rtmp=1
# content:
{}
# args:
app : dhlive
enable_rtmp : 1
enable_rtsp : 0
secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
stream : 9
subtype : sub
url : rtsp://mmyy:mmyz12345 @192.168.56.58:554/cam/realmonitor?channel=11
vhost : http://192.168.56.58:8912
# response:
{
   "code" : -1,
   "msg" : "DESCRIBE:401 Unauthorized"
}

**Comment by xia-chu** [comment]
你需要转意 不知道怎么弄 就用postman操作



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: z-feiyu <notifications@github.com&gt;
发送时间: 2020年9月24日 11:20
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] rstp流的密码为特殊符号“+”的话不支持播放，可以帮忙优化下吗 (#500)





 
POST /index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;url=rtsp://mmyy:mmyz12345+@192.168.56.58:554/cam/realmonitor?channel=11&amp;subtype=sub&amp;vhost=http://192.168.56.58:8912&amp;app=dhlive&amp;stream=9&amp;enable_rtsp=0&amp;enable_rtmp=1
 
content:
 
{}
 
args:
 
app : dhlive
 enable_rtmp : 1
 enable_rtsp : 0
 secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
 stream : 9
 subtype : sub
 url : rtsp://mmyy:mmyz12345 @192.168.56.58:554/cam/realmonitor?channel=11
 vhost : http://192.168.56.58:8912
 
response:
 
{
 "code" : -1,
 "msg" : "DESCRIBE:401 Unauthorized"
 }

**Comment by z-feiyu** [comment]
可以了，谢谢
