### ISSUE TITLE
API getMediaInfo return FPS = 0

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#502]
Hi,

With some rtsp source, when call API getMediaInfo, the MediaServer always return FPS = 0.
my rtsp url: rtsp://admin:Admin@2020@210.245.49.29:25554/onvif/media?profile=Profile1
Here is my log:
# response:

{
   "app" : "proxy",
   "code" : 0,
   "online" : true,
   "readerCount" : 0,
   "schema" : "rtsp",
   "stream" : "cam8",
   "totalReaderCount" : 0,
   "tracks" : [
      {
         "codec_id" : 0,
         "codec_id_name" : "CodecH264",
         "codec_type" : 0,
         "fps" : 0,
         "height" : 1944,
         "ready" : true,
         "width" : 2592
      },
      {
         "channels" : 1,
         "codec_id" : 4,
         "codec_id_name" : "CodecG711U",
         "codec_type" : 1,
         "ready" : true,
         "sample_bit" : 16,
         "sample_rate" : 8000
      }
   ],
   "vhost" : "__defaultVhost__"
}
[2020-09-24.zip](https://github.com/xia-chu/ZLMediaKit/files/5274575/2020-09-24.zip)

**Comment by xia-chu** [comment]
Yes, there is a problem in the code of parsing SPS PPS to get FPS。
Because getting the width / height / FPS is not very important for ZLMediaKit, so I didn't pay much attention to this problem. Is this very important to you?

**Comment by lenhatvu** [comment]
Yes, 

I am using this property of to decide stream is normal or error.
If you have time, please solve this problem.
Thank you for your support.

**Comment by pubpy2015** [comment]
Hi,
can you tell me where is the code of parsing SPS PPS to get FPS ?
I will try to debug and report to you.

**Comment by xia-chu** [comment]
https://github.com/xia-chu/ZLMediaKit/blob/master/src/Extension/SPSParser.c

I'm very sorry I've been so busy recently that I forgot to reply you
