### ISSUE TITLE
Is any way to split log file to multi files by size

### ISSUE THREAD

**Issue by lenhatvu** [xia-chu/ZLMediaKit#504]
Hi,

Because client always get media info, size of the log file increase to GB and difficult to open. 
Is any way to limit size of each log file ? if size reach to 50 MB, Media Server will create a new log file.

**Comment by xia-chu** [comment]
Hi, your need is not very satisfying to be honest because the change will affect others.
I suggest you close some logs, such as modifying the config file like this `api.apiDebug=0`,
 or setting the log level like this `MediaServer -l 1`.

**Comment by lenhatvu** [comment]
Thank, 
I will try it.
