### ISSUE TITLE
https证书配置无效

### ISSUE THREAD

**Issue by yuezhongxin** [xia-chu/ZLMediaKit#505]
你好，我想问下ZLMediaKit 80端口，https证书怎么配置？

**Comment by xia-chu** [comment]
请仔细阅读这篇文章：
https://github.com/xia-chu/ZLMediaKit/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%90%AF%E5%8A%A8%E4%B8%8E%E5%85%B3%E9%97%AD

**Comment by yuezhongxin** [comment]
好的

**Comment by yuezhongxin** [comment]
你好，我设置了证书，MediaServer启动日志：
```
2020-09-25 14:05:47.051 D MediaServer[20147] SSLBox.cpp:192 setContext | add certificate of: *.test.com
2020-09-25 14:05:47.051 D MediaServer[20147] util.cpp:315 operator() | Stamp thread started!
```

但是在hls播放的时候，还是不行，比如这个地址：https://xxxx.test.com:55555/test/80/hls.m3u8?vhost=__defaultVhost__

![image](https://user-images.githubusercontent.com/6800671/94233285-3c1de680-ff3a-11ea-9b78-5319608ba39d.png)

http是可以播放的。

**Comment by yuezhongxin** [comment]
是不是我端口配的55555，并非80端口的问题？

**Comment by xia-chu** [comment]
证书加载成功了 难道你https端口错误？

**Comment by yuezhongxin** [comment]
https端口错误啥意思？证书和端口应该没啥问题吧？我配的55555端口

**Comment by xia-chu** [comment]
配置文件中http.sslport是55555?



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 蟋蟀 <notifications@github.com&gt;
发送时间: 2020年9月27日 09:35
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书配置无效 (#505)





 
https端口错误啥意思？证书和端口应该没啥问题吧？我配的55555端口

**Comment by yuezhongxin** [comment]
不是，http.sslport=443，http.port=55555

**Comment by xia-chu** [comment]
你修改配置文件不看注释吗？你不看wiki吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 蟋蟀 <notifications@github.com&gt;
发送时间: 2020年9月27日 09:39
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书配置无效 (#505)





 
不是，http.sslport=443，http.port=55555

**Comment by yuezhongxin** [comment]
```
#http服务器监听端口
port=80
#http文件服务器根目录
#可以为相对(相对于本可执行程序目录)或绝对路径
rootPath=./www
#http文件服务器读文件缓存大小，单位BYTE，调整该参数可以优化文件io性能
sendBufSize=65536
#https服务器监听端口
sslport=443
```
看了，这个不能改吗？

**Comment by xia-chu** [comment]
你用https协议访问http端口？那https端口拿来干嘛呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 蟋蟀 <notifications@github.com&gt;
发送时间: 2020年9月27日 09:42
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书配置无效 (#505)





 #http服务器监听端口 port=80 #http文件服务器根目录 #可以为相对(相对于本可执行程序目录)或绝对路径 rootPath=./www #http文件服务器读文件缓存大小，单位BYTE，调整该参数可以优化文件io性能 sendBufSize=65536 #https服务器监听端口 sslport=443  
看了，这个不能改吗？

**Comment by yuezhongxin** [comment]
😓 如果http.port我配置的不是80端口，要支持https，http.sslport改怎么配呢？还是只能80和443端口？

我这样配是为了一个服务器运行两个ZLMediaKit，然后http端口不一样。

**Comment by xia-chu** [comment]
你应该用https协议访问http.sslport端口。

**Comment by yuezhongxin** [comment]
懂了，我试试

**Comment by yuezhongxin** [comment]
可以了，感谢~~~
