### ISSUE TITLE
谁在使用ZLMediaKit

### ISSUE THREAD

**Issue by xia-chu** [xia-chu/ZLMediaKit#511]
**本issue保持常开且随时更新，欢迎大家介绍使用本项目的公司和项目，**
**开设本issue的目的是宣传ZLMediaKit，让更多人知道和信任本项目，**
**同时也可以宣传您的公司、项目、产品，甚至也可以同时发出您的招聘。**

您可以按照此格式书写：

- 公司名称：xxxxx有限责任公司
- 项目介绍：本项目基于ZLMediaKit实现了xxxx视频监控平台xxxxx
- 产品介绍：(假如有粘贴)
- 效果图片：(假如有粘贴)
- 招聘广告: (假如有粘贴)

书写格式不是强制的，如果太潦草，我会编辑一下

**Comment by tanningzhong** [comment]
Tencent
项目介绍: 咱不能介绍哦

**Comment by lakegrass** [comment]
**公司名称**：南京达素科技有限责任公司
**项目介绍**：本项目基于ZLMediaKit初步实现了SIP客户端注册、前端UI视频预览功能，视频录像和回放还没实现，还在摸索中
**产品介绍**：项目主要基于WVP+ZLMediaKit+ZLMediaKit_UI实现，在原来基础上做了部分优化，准备实现从SIP代理注册，设备管理，实时视频预览，录像，录像回放等功能。
项目还处在摸索中，争取能够实现本地部署、云化部署，支持局域网和互联网监控
效果图片：不知道怎么贴图

**Comment by tsingeye** [comment]
公司名称：tsingeye开源团队--FreeEHome
项目介绍：本项目基于海康ehome协议，视频流在ZLMediakit基础上进行二次开发，实现海康设备主动上云，目前发布1.0版本已支持实时视频，其他功能待开放。

招聘广告: tsingeye团队招聘一名兼职前端开发，技术栈: vue或者react,具体可以联系Q18675721

**Comment by feidie436** [comment]
公司名称：北方激光研究院有限公司广西分公司
项目介绍：项目基于WVP+ZLMediaKit+MediaServerUI搭建，主要实现公司内及数据中心监控摄像头的实时视频预览。其它更深层次的功能还在探索中。。。
效果图片：
![Uploading image.png…]()

**Comment by sunhui2013** [comment]
公司名称：上海熙凌科技股份有限公司
项目介绍：GB28181接入平台，提供RTSP/RTMP/HTTP-FLV/HLS/WS-FLV协议给前端

**Comment by chatop2020** [comment]
项目名称：StreamNode-GB28181开源项目
项目介绍： 项目是基于ZLMediaKit的流媒体控制管理接口平台，整合了SIP网关以支持GB28181的设备推流及PTZ控制；
                   支持RTSP、GB28181摄像头自动上线，自动发现，自动拉流，自动录制等功能。

**Comment by addriumruss** [comment]
公司名称：南京神虎科技有限公司
项目介绍：基于ZLMediaKit实现了无人机巡检视频服务平台。但是国标流的支持还没完成，在探索中。
感谢作者！

**Comment by hurricanezj** [comment]
公司名称：宁波博登智能科技有限责任公司(www.boden.ai)
项目介绍：基于ZLMediaKit实现了超级分辨率项目的开发。
产品介绍:   支持RTSP直播、视频流、直播流等流媒体的实时和离线超级分辨率、插帧、去噪等算法的接入。
效果图片：
![2020-12-09 20_23_45-超分Live - 超分](https://user-images.githubusercontent.com/14449551/101629612-979d4200-3a5c-11eb-8c49-cfb524021f9f.png)

**Comment by chatop2020** [comment]
> 感谢 xia-chu!
> 公司名称：宁波博登智能科技有限责任公司([www.boden.ai](http://www.boden.ai))
> 项目介绍：基于ZLMediaKit实现了超级分辨率项目的开发。
> 产品介绍: 支持RTSP直播、视频流、直播流等流媒体的实时和离线超级分辨率、插帧、去噪等算法的接入。
> 效果图片：
> ![2020-12-09 20_23_45-超分Live - 超分](https://user-images.githubusercontent.com/14449551/101629612-979d4200-3a5c-11eb-8c49-cfb524021f9f.png)
> 
> 招聘广告: BODEN AI团队招聘精通C++、JAVA后端，具体可以联系QQ 392870690

同是宁波的兄弟

**Comment by SillyFlame** [comment]
公司名称：百度
项目名称：安防监控流媒体集群
产品：基于ZLMediaKit开发的GB28181流媒体集群，接入城市安防摄像头2000路，用于后续智能分析。

**Comment by huangankun** [comment]
公司名称：北京数字智通科技有限公司
项目名称：视频中台
产品：以ZLMediaKit为流媒体服务开发的以GB28181\海康\大华\浪潮流媒体\JT808\JT1078等多种源输入，输出标准前端可播放的视频流、集成强大视频集成能力的视频中台作为公司的基础城管视频应用，作为视频AI中台的流媒体部分提供稳定视频流做算法分析。

**Comment by NangenX** [comment]
公司名称：成都奥瑞视讯科技有限公司
项目名称：社区、酒店IPTV系统，OTT系统
产品：把zlmediakit的丰富音视频协议作为底层来对接编码器、转码器等信源设备，利用丰富的接口和Hook功能打造切片管理工具，实时监控输入流的状态和情况。

**Comment by godlike10** [comment]
公司名称:深圳金智凌轩视讯技术有限公司
项目介绍：基于zlmediakit实现了gb28181的接入以及私有协议的推流接入，提供flv/rtmp/hls等到前端，同时提供rtsp给其他公司。

**Comment by wujincheng2333** [comment]
感谢 xia-chu!
公司名称：广州风雨雷科技有限公司
项目介绍：基于zlmediakit实现了gb28181的接入以及rtmp推流接入，转出 http-flv/rtmp/webrtc。结合webhook实现分辨率码率动态更新。
产品介绍: 野外灾害监控。

**Comment by abcd19886** [comment]
公司名称：重庆环问问科技有限公司
项目介绍：智慧环保管理系统，zlmediakit 接入国标28181，对视频进行播放，存储，分析，增加ai边缘计算设备，使用yolov5算法，对废水、废气、固危废等视频进行分析。
产品介绍: 智慧环保

**Comment by HTKing** [comment]
感谢 xia-chu!
公司名称：重庆富沛和科技有限公司
项目介绍：基于ZLMediaKit实现了实时低延迟视频预览的开发。
产品介绍: 支持RTSP直播、视频流、直播流等流媒体的低延迟实时视频预览

**Comment by jiachaofrms** [comment]
公司名称：武汉东智科技股份有限公司
项目介绍：视频云平台，基于ZLMediaKit进行二次开发，将内网中的摄像机视频推送到互联网云平台，供客户进行观看，支持onvif，gb28181,等私有协议
产品介绍: 视频监控

**Comment by jim-king-2000** [comment]
公司名称：上海缓存命中科技有限公司
项目介绍：执法仪云平台。基于ZLMediaKit进行二次开发，传输RTSP + H.265视频流。
产品介绍：公安系统安防监控

**Comment by hany-dev** [comment]
公司名称：烟台艾睿光电科技有限公司
    项目介绍：本项目基于ZLMediaKit实现了融合媒体云平台

**Comment by cqtukun** [comment]
> * 公司名称：坤典智慧农场系统（重庆坤典科技有限公司）
> * 项目介绍：本项目基于ZLMediaKit开发，主要接入支持GB28181设备的视频监控摄像头，实现了智慧农业、数字化农场可视化管理农场；另外开心农场、认养农业让用户在小程序/APP上租地种有机蔬菜和认养果树，通过GB视频监控实时查看种植的蔬菜与认养的果树，同时实现了rtmp转RTC低延迟方案，解决了用户远程操作云台交互体验；目前已经接入了4000+国标设备数量。
> * 产品介绍：[官网产品介绍www.cqkundian.com](https://www.cqkundian.com)
> * 效果图片：官方小程序演示体验
 ![扫码演示小程序](https://kundian.farmkd.com/album/202202/10/153029tz959r2rcke20kds.jpg)
![效果](https://kundian.cqkundian.com/farm/1/png/20220217/05539f69122dbe6de112863c55bc274e1645073230.png)
![效果](https://kundian.cqkundian.com/farm/1/jpg/20220217/eb887356c62a1547cad5a8fc6eee22fe1645073387.jpg)

**Comment by taojishou** [comment]
公司名称：安徽小互科技有限公司
项目介绍：项目1.基于ZLMediaKit实现监控国标平台采用go语言，实现ai分析，国标级联回放，云录像云回放等功能
产品介绍：XHGBS
![gbs平台](https://user-images.githubusercontent.com/20332592/154409338-4f287b9a-df91-4ff2-b697-861bde8a49e5.png)
![国标](https://user-images.githubusercontent.com/20332592/154409354-1505cf51-587f-4193-aace-a36232e2744a.png)
![录像计划](https://user-images.githubusercontent.com/20332592/154409362-b237c42e-4954-40d9-bda7-39db7833fc46.png)
![gb](https://user-images.githubusercontent.com/20332592/154409366-ca293331-af8d-4511-8d0e-4ac8c5b6e5b3.png)
![2](https://user-images.githubusercontent.com/20332592/154409376-ad8e7a42-a00f-4299-965a-9e14a088ae8d.png)
项目介绍：项目2.基于ZLMediaKit实现直播CDN系统
产品介绍：LIVECDN，基于ZLMediakit和fastcfs实现直播cdn系统，包括直播转码，点播回放，云存储等。以实现总带宽100多G直播验证,ZLMediakit单机并发过50G
![cdn](https://user-images.githubusercontent.com/20332592/154409626-a24a9d39-334b-49d9-a471-42e9eff998e0.jpg)
![webwxgetmsgimg](https://user-images.githubusercontent.com/20332592/154409675-22423f88-befb-41f0-8596-2d874dffb63c.jpg)
![2](https://user-images.githubusercontent.com/20332592/154409773-f0896850-1235-49a6-a021-b544226acf4c.jpg)
![3](https://user-images.githubusercontent.com/20332592/154409932-3d4edacd-2149-4a42-8922-3657d4b08c85.jpg)
![webwxgetmsgimg (3)](https://user-images.githubusercontent.com/20332592/154409983-c075f25d-5a7c-4350-b19d-8617c5406889.jpg)

**Comment by xiaochong0302** [comment]
### 酷瓜云课堂局域网版

基于`ZLMediaKit`实现了内网课程直播，没有使用云服务，无相关营销功能，是腾讯云版的本地化实现

### 酷瓜云课堂腾讯云版

![酷瓜云课堂](https://portal-1255691183.file.myqcloud.com/img/content/61dd395c053e5.png)

### 系统介绍

酷瓜云课堂，依托腾讯云基础服务架构，采用C扩展框架Phalcon开发，GPL-2.0开源协议，致力开源网课系统，开源网校系统，开源知识付费系统，开源在线教育系统。

![star](https://koogua.com/gitee/badge?user=koogua&project=course-tencent-cloud&type=star)
![fork](https://koogua.com/gitee/badge?user=koogua&project=course-tencent-cloud&type=fork)
![license](https://koogua.com/gitee/badge?user=koogua&project=course-tencent-cloud&type=license)
![release](https://koogua.com/gitee/badge?user=koogua&project=course-tencent-cloud&type=release)

### 系统功能

实现了点播、直播、专栏、面授、问答、会员、群组、微聊、积分、秒杀等。

### 项目组件

- 后台框架：[phalcon 3.4.5](https://phalcon.io)
- 前端框架：[layui 2.6.8](https://layui.com)， [layim 3.9.8](https://www.layui.com/layim)（已授权）
- 全文检索：[xunsearch 1.4.9](http://www.xunsearch.com)
- 即时通讯：[workerman 3.5.22](https://workerman.net)
- 基础依赖：[php7.3](https://php.net)， [mysql5.7](https://mysql.com)， [redis5.0](https://redis.io)

### 项目文档

- [运行环境搭建](https://koogua.com/page/wiki)
- [系统服务配置](https://koogua.com/page/wiki)
- [客户终端配置](https://koogua.com/page/wiki)

**Comment by stn-sudo** [comment]
公司名称：浪潮软件科技有限公司。
项目介绍：基于ZLMediaKit实现了水利设施监控。
产品介绍: 实现RTSP直播、视频流、直播流等流媒体的低延迟实时视频预览。

**Comment by malegend** [comment]
公司名称: 无
项目名称: [ZLMediaKit.Autogen](https://github.com/malegend/ZLMediaKit.Autogen)
项目地址: https://github.com/malegend/ZLMediaKit.Autogen
项目介绍: 开源。ZLMediaKit的 C# API 封装。采用 CppSharp 对 ZLMediaKit 进行解析，并进行微调和修改，基于 ZLMediaKit 项目的调用原始风格，各位网友可以参照 ZLMediaKit 原始项目文档编写应用程序。

**Comment by malegend** [comment]
公司名称：烟台淼盾物联技术有限公司
项目介绍：基于ZLMediaKit实现远程视频预览。
产品介绍：实现RTSP直播、视频流、直播流等流媒体的低延迟实时视频预览。

**Comment by wpeng0802** [comment]
感谢 xia-chu!
公司名称：沈阳双杰网络科技集团有限公司
项目介绍：本项目基于ZLMediaKit开发，互联网主要接入支持GB28181设备的视频监控设备，专网/内网采用rtsp拉流接入视频监控设备，实现了食品安全监管的后厨直播、历史回看、违规行为/场景的AI分析。
产品介绍：校园食品安全监管，家长和老师实时了解食堂后厨食材生产加工过程
效果图片：
![互联网+明厨亮灶](https://user-images.githubusercontent.com/16471790/169634136-51035ca0-6429-4fcc-8bb1-66888a810673.png)

**Comment by CrossBoneMan** [comment]
你好，我想查詢一下有關於能否在stream key那邊設置白名單嗎？
謝謝。

**Comment by oaup** [comment]
感谢 xia-chu！
公司名称：北京观川科技有限公司
项目介绍：基于zlmediakit实现视频远程监控以及点播/录播功能，支持手机直接观看。
落地应用于雪亮工程/智慧校园和文化遗产监控，面向不可移动文物保护的监控。

**Comment by v354412101** [comment]
> 公司名称：百度 项目名称：安防监控流媒体集群 产品：基于ZLMediaKit开发的GB28181流媒体集群，接入城市安防摄像头2000路，用于后续智能分析。

你好，可以交流下大规模集群的方案吗？

**Comment by urmyfaith** [comment]
公司名称：普宙科技有限公司
项目介绍：GB28181接入平台，提供RTSP/RTMP/HTTP-FLV/HLS/WS-FLV协议给前端和算法。

设备数量200左右。


落地应用于荆州段，新洲段长江保护安防算法应用场景。

**Comment by urmyfaith** [comment]
> 公司名称：普宙科技有限公司 项目介绍：GB28181接入平台，提供RTSP/RTMP/HTTP-FLV/HLS/WS-FLV协议给前端和算法。
> 
> 设备数量200左右。
> 
> 落地应用于荆州段，新洲段长江保护安防算法应用场景。

支持 webrtc/h264  rtsp/rtmp  ws-flv.

H265 暂时为支持webrtc

**Comment by lsc102** [comment]
公司名称：上海熙菱信息技术有限公司
项目名称：视频网关
产品：GB28181接入平台，提供RTSP/RTMP/HTTP-FLV/HLS/WS-FLV协议给前端。
公司地址: https://www.sit.com.cn/

**Comment by china4sq** [comment]
公司名称：深圳市几米物联有限公司
项目介绍：本项目基于ZLMediaKit实现了基于DVR的车队管理视频监控平台途强在线
产品介绍：基于定位器和DVR，实现专业的车队管理功能
效果图片：(假如有粘贴)
招聘广告：常年招聘流媒体工程师、Java开发工程师

**Comment by WangSiwang** [comment]
公司 : 杭州熙菱信息技术有限公司
产品： 视频接入平台（还么得产品）
ext:  1. 上面那家是我们的股东大大
       2.  创业公司不怎么招人，除非你强的离谱，我们会用更离谱的价格挖你

**Comment by chdahuzi** [comment]
公司名称：中电信数字城市科技有限公司
项目介绍：本项目基于ZLMediaKit实现了GB28181视频监控平台
产品介绍：实现GB28181协议接入，推流拉流，接入2000+摄像头
<img width="1243" alt="微信截图_20230216150646" src="https://user-images.githubusercontent.com/10302924/219293076-e2524be9-c5a3-427a-b4c4-5dfcf4cf322e.png">

**Comment by wangran99** [comment]
> 中电信数字城市科技有限公司
> 项目介绍：本项目基于ZLMediaKit实现

GB28181用的mvp-28181项目的接口实现的吗？

**Comment by a-ucontrol** [comment]
Company: "НИЦ Технологии", https://www.nic-tech.ru/
In the developed line of IP cameras we use ZLM

**Comment by ixingqiao** [comment]
感谢 xia-chu!
公司名称：杭州宇泛智能科技有限公司
项目介绍：视频分析终端，接入RTSP厂家监控设备，提供RTSP/RTMP/HTTP-FLV/HLS/WS-FLV协议给前端和算法。
公司官网：https://www.uni-ubi.com/

**Comment by 308207109** [comment]
公司名称：西安爱铭网络科技有限公司
项目介绍：本项目基于ZLMediaKit实现了SIP客户端注册、前端UI视频预览功能，视频录像和回放，还在摸索中
基于ZLMediaKit开发的GB28181流媒体集群，输出标准前端可播放的视频流、集成强大视频集成能力的视频中台作为公司的基础市场监管系统视频应用，作为视频AI中台的流媒体部分提供稳定视频流做算法分析。用于后续智能分析，监管分析等
[公司官网：](https://www.amingg.com) (https://www.51620.net)

**Comment by lff2413** [comment]
公司名称：广州烽云信息科技有限公司
项目介绍：项目基于WVP+ZLMediaKit+MediaServerUI搭建，支持SIP代理、设备管理、实时预览、录像、RTMP拉流等功能，目前正在进行定制化需求二次开发中

**Comment by edyang** [comment]
公司名称：重庆斯碧仕软件技术有限公司
产品介绍：按需拉流GB28181到zlm的MediaServer后，转协议为 http-flv/hls/webrtc 供Web端调用。通过http hook和restful api实现，包括实时流和回放流。

**Comment by codingmaning** [comment]
公司名称：济南鲁科安全设备有限公司
项目介绍：本项目基于ZLMediaKit实现了安防-视频监控平台
产品介绍：在某地市部署 对接IPC rtsp流，录像回放，预览 性能一流，非常稳定，零问题。
感谢大佬的优秀、无私的开源和技术问题的回答。
感谢 xia-chu 大佬！

**Comment by KevinForever** [comment]
公司名称：上海顶昂科技
 项目介绍：本项目基于ZLMediaKit实现了安防视频监控平台
 产品介绍：流媒体基于ZLMediakit对接海康大华IPC NVR以及私有协议摄像头的流转发预览回放截图
感谢大佬的优秀、无私的开源和技术问题的回答。

**Comment by leoagle** [comment]
公司名称：卡莱特
产品介绍：基于ZLMediaKit实现了分布式坐席系统（孵化中）
项目介绍：使用到了rtsp推拉流功能
感谢ZL大佬的优秀、无私的开源精神

**Comment by chutianhua** [comment]
公司名称：山东微图数字科技
项目介绍：基于ZLMediaKit实现了智慧化工园区产品和企业安全生产信息管理平台，GB28181 视频设备和移动视频设备的集中对接
感谢ZL大佬的优秀，无私的开源精神

**Comment by tangxinqi0218** [comment]
公司名称：江苏金陵体育科技有限公司
项目介绍：项目基于ZLMediaKit实现杭州亚运会钉钉直播和回放。
产品介绍：机房部署了10台实体流媒体服务器，千兆网卡，128G内存，48核CPU，海康摄像头和编码器作为视频源，经测试单台服务器能满足支持400路视频源的拉流和生成mp4监控录像，性能高且运行稳定。
直播使用http-hls协议，m3u8文件存放于NAS服务器，通过多台nginx发布服务器读取hls，播放流畅稳定。
感谢大佬无私奉献开源的精神。
![Uploading 微信截图_20231012145904.png…]()

**Comment by chenchaoyun0** [comment]
公司名称：百度
项目名称：AIR云平台
产品：基于ZLMediaKit开发视频平台，接入交通监控摄像头100路，用于事件检测分析与视频监控。

**Comment by todd841026** [comment]
公司名称：东方国信
项目名称：数字人
产品：基于ZLMediaKit研发数字人的推流

**Comment by TristingChen** [comment]
公司名称：润建
项目名称：部分监控场景的使用
产品：基于zlm的做的监控平台底座

**Comment by evaxige** [comment]
公司名称：聚图网络
项目名称：国标媒体服务器终端产品
产品：使用RK3568主控开发的1U规格的流媒体服务器终端，产品介绍地址（https://item.taobao.com/item.htm?spm=a21n57.1.0.0.ad6a523cnPaBWc&id=684630477200&ns=1&abbucket=2#detail）

**Comment by zoopnin** [comment]
公司名称：华科智能
项目名称：行为分析
产品：       基于国标GB28181设备采集视频流数据

**Comment by fuyun996** [comment]
公司名称：曙光云计算集团有限公司
项目名称：国标28181视频汇聚及对外视频接口提供
产品：基于国标28181的视频汇聚平台

**Comment by wanghuan2054** [comment]
> 公司名称：曙光云计算集团有限公司 项目名称：国标28181视频汇聚及对外视频接口提供 产品：基于国标28181的视频汇聚平台

hello , 我也是曙光云计算的，方便的话加一下微信交流一下，wh499218471

**Comment by victording123456** [comment]
公司名称：北京中天灏景科技有限公司（www.converse3d.com)
项目名称：基于webrtc的云渲染
产 品： 实现3d引擎的云渲染，使用webrtc推流将桌面软件的画面流推送到浏览器端。

你们辛苦了，谢谢各位大佬。

**Comment by lihaogis** [comment]
> 公司名称：百度 项目名称：AIR云平台 产品：基于ZLMediaKit开发视频平台，接入交通监控摄像头100路，用于事件检测分析与视频监控。

请问视频分析主要用哪些技术，比如人脸和车牌抓拍，是基于实时视频进行的吗？

**Comment by wangran99** [comment]
> 请问视频分析主要用哪些技术，比如人脸和车牌抓拍，是基于实时视频进行的吗？

yolo v8就行

**Comment by xiaokxluoshu** [comment]
公司名称：鉴微数字科技(重庆)有限公司
项目介绍：本项目基于ZLMediaKit实现了视频流平台
产品介绍：基于ZL做视频流汇聚，转码，标注，向下或向上推流平台

谢谢各位大佬的开源。

**Comment by scdn** [comment]
> 公司名称：上海顶昂科技 项目介绍：本项目基于ZLMediaKit实现了安防视频监控平台 产品介绍：流媒体基于ZLMediakit对接海康大华IPC NVR以及私有协议摄像头的流转发预览回放截图 感谢大佬的优秀、无私的开源和技术问题的回答。

<img width="1341" alt="image" src="https://github.com/user-attachments/assets/8bfa2d00-b8a9-4c63-9ff4-fd64516db0ac">
那这是不是欠妥

**Comment by winc-link** [comment]
公司名称：深圳赢创万联科技有限公司
项目介绍：基于国标GB28181设备采集视频流数据
产品介绍: 蜂鸟物联网平台

**Comment by cody111115** [comment]
公司名称：南京云行数智信息技术有限公司
项目介绍：在我们公司的AI盒子产品以及服务器端都使用ZLMediaKit，作为监控摄像头以及AI分析流 接入流媒体服务器
产品介绍：1. AI盒子，主要面向定制化场景，为替代产线需要人工视觉判断的场景提供AI智能化支持。通过ZLMediaKit实现讲原始流与AI算法分析过的流同时展示给客户看；
2. 服务器版本，基本上与AI盒子功能相同，适用于有比较强的算力服务器的客户。

**Comment by zhou-hao** [comment]
公司名称: 重庆旱獭(tǎ)信息技术有限公司  www.jetlinks.cn
项目介绍: JetLinks 企业版视频中心功能使用ZLMedia作为流媒体服务提供流媒体接入相关能力.
产品介绍:  JetLinks 基于Java,Spring Boot ,WebFlux,Netty,Vert.x,Reactor等开发, 是一个全响应式的企业级物联网平台。支持统一物模型管理,多种设备,多种厂家,统一管理。统一设备连接管理,多协议适配(TCP,MQTT,UDP,CoAP,HTTP等),屏蔽网络编程复杂性,灵活接入不同厂家不同协议等设备。实时数据处理,设备告警,消息通知,数据转发。地理位置,数据可视化等。能帮助你快速建立物联网相关业务系统。

**Comment by Tushn123** [comment]
公司名称：申通快递
项目介绍：本项目基于ZLMediaKit实现了基于视觉识别的，物流监控和包裹检测系统。
产品介绍：我司（准确的是我组）基于ZLMediaKit做了相当多的改造，我们不止当做流媒体服务器使用，有时也会裁剪后当做c++服务器使用。我本人从ZLMediaKit上学习了很多知识，让我印象深刻的是，智能指针的各种妙用。最后再次感谢夏楚的开源精神。
