### ISSUE TITLE
MP4 playback

### ISSUE THREAD

**Issue by lenhatvu** [xia-chu/ZLMediaKit#512]
Hi,

Follow your istruction in Wiki, I can playback mp4 file when copy it to record folder.
http://somedomain.com/record/0.mp4

Can I modify your config or code to play MP4 file from anywhere ?

**Comment by xia-chu** [comment]
You can do this by modifying the configuration file：
<img width="786" alt="图片" src="https://user-images.githubusercontent.com/11495632/95530817-6a5af600-0a11-11eb-98a6-949d4317dfc4.png">

**Comment by lenhatvu** [comment]
Thanks,

So with files from other locations, i must move or copy to record folder ?

Can i modify your code to do this ?

**Comment by xia-chu** [comment]
The app name of the playback url is limited here：
<img width="1191" alt="图片" src="https://user-images.githubusercontent.com/11495632/95531406-fde0f680-0a12-11eb-8733-cc5c8a943a61.png">

This is the absolute path of MP4  playback：
<img width="1493" alt="图片" src="https://user-images.githubusercontent.com/11495632/95532049-37196680-0a13-11eb-8f82-024965f2cb65.png">

**Comment by thaibienbac** [comment]
Thanks,

I will try

**Comment by lenhatvu** [comment]
Yes

**Comment by lenhatvu** [comment]
Hi,

I am testing by replace MP4 file in url "http://127.0.0.1:10248/record/**637360394418756020.mp4**" by a other file **637371662655252472.mp4**. but nothing change.

![ảnh](https://user-images.githubusercontent.com/59004953/95573943-69988300-0a56-11eb-9c6d-f4ba8db318a0.png)
