### ISSUE TITLE
realloc    core 

### ISSUE THREAD

**Issue by khw934** [xia-chu/ZLMediaKit#513]
程序运行的时候偶尔会出现 core ， 信息如下：

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./MediaServer -d'.
Program terminated with signal 6, Aborted.
#0  0x00007f6999de8337 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_7.2.x86_64 libcom_err-1.42.9-16.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007f6999de8337 in raise () from /lib64/libc.so.6
#1  0x00007f6999de9b68 in abort () from /lib64/libc.so.6
#2  0x00007f6999e2ae87 in __libc_message () from /lib64/libc.so.6
#3  0x00007f6999e317c4 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f6999e36ac0 in _int_realloc () from /lib64/libc.so.6
#5  0x00007f6999e38162 in realloc () from /lib64/libc.so.6
#6  0x0000000000d7cbb5 in rtp_payload_write ()
#7  0x0000000000d76545 in rtp_decode_ps ()
#8  0x0000000000d7609b in rtp_payload_decode_input ()
#9  0x0000000000cf39eb in mediakit::RtpDecoder::decodeRtp(void const*, int) ()
#10 0x0000000000c80de4 in mediakit::RtpProcess::onRtpSorted(std::shared_ptr<mediakit::RtpPacket> const&, int) ()
#11 0x0000000000c987e7 in mediakit::RtpReceiver::sortRtp(std::shared_ptr<mediakit::RtpPacket> const&, int) ()
#12 0x0000000000c97d97 in mediakit::RtpReceiver::handleOneRtp(int, mediakit::TrackType, int, unsigned char*, unsigned int) ()
#13 0x0000000000c8091f in mediakit::RtpProcess::inputRtp(std::shared_ptr<toolkit::Socket> const&, char const*, int, sockaddr const*, unsigned int*) ()
#14 0x0000000000bd0fef in mediakit::RtpSession::onRtpPacket(char const*, unsigned long) ()
#15 0x0000000000bd1721 in mediakit::RtpSplitter::onRecvHeader(char const*, unsigned long) ()
#16 0x0000000000b1e736 in mediakit::HttpRequestSplitter::input(char const*, unsigned long) ()
#17 0x0000000000bd09c3 in mediakit::RtpSession::onRecv(std::shared_ptr<toolkit::Buffer> const&) ()
#18 0x0000000000a1d78b in toolkit::TcpServer::onAcceptConnection(std::shared_ptr<toolkit::Socket> const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const ()
#19 0x0000000000a25115 in std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), toolkit::TcpServer::onAcceptConnection(std::shared_ptr<toolkit::Socket> const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) ()
#20 0x0000000000d1228b in std::function<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)>::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const ()
#21 0x0000000000d0959c in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#22 0x0000000000d08d70 in toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}::operator()(int) const ()
#23 0x0000000000d0d897 in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int) ()
#24 0x0000000000d121e4 in std::function<void (int)>::operator()(int) const ()
#25 0x0000000000d220da in toolkit::EventPoller::runLoop(bool, bool) ()
#26 0x0000000000d312cc in void std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)>::operator()<bool, bool, void>(toolkit::EventPoller*, bool&&, bool&&) const ()
#27 0x0000000000d310e3 in void std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) ()
#28 0x0000000000d30e23 in std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::operator()() ()
#29 0x0000000000d30b6c in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)> >::_M_run() ()
#30 0x00007f699a74d070 in ?? () from /lib64/libstdc++.so.6
#31 0x00007f699a9a6e65 in start_thread () from /lib64/libpthread.so.0
#32 0x00007f6999eb088d in clone () from /lib64/libc.so.6
(gdb) 

本机内存情况:
[xvep@ecs-b752 Debug]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15886        2895         265          80       12725       12580
Swap:          4095          27        4068
[xvep@ecs-b752 Debug]$ 

操作系统：
[xvep@ecs-b752 Debug]$ uname -a
Linux ecs-b752.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[xvep@ecs-b752 Debug]$

**Comment by xia-chu** [comment]
#497

**Comment by xia-chu** [comment]
这个issue先关闭了 复现了请在此答复。
