### ISSUE TITLE
https证书问题

### ISSUE THREAD

**Issue by dengchaowen-cx** [xia-chu/ZLMediaKit#516]
您好，我现在想用https，但是我之前没有搞过加密的东西，我可以用代码里面自带的证书吗ssl.p12。

**Comment by xia-chu** [comment]
你要用有效的证书 还要有个对应的域名

**Comment by dengchaowen-cx** [comment]
我在网上查了一下，证书都要收费的 有免费的怎么获取

**Comment by xia-chu** [comment]
那你就花钱买证书啊

**Comment by dengchaowen-cx** [comment]
我看网上有教程可以用openssl生成证书是什么意思 因为不用https网页不能调用摄像头和麦克风 很是纠结

**Comment by xia-chu** [comment]
那是自签名证书

**Comment by dengchaowen-cx** [comment]
Zl可以用吗

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月14日 10:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)





 
那是自签名证书

**Comment by xia-chu** [comment]
可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dengchaowen-cx <notifications@github.com&gt;
发送时间: 2020年10月14日 10:56
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)





 Zl可以用吗 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 夏楚 <notifications@github.com&amp;gt; 
 发送时间: 2020年10月14日 10:46 
 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt; 
 抄送: dengchaowen-cx <1020443551@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516) 
 
 
 
 
 
   
 那是自签名证书

**Comment by dengchaowen-cx** [comment]
非常感谢你的解答



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月14日 10:57
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)

**Comment by xia-chu** [comment]
issue先关闭了 有其他回复请在此答复

**Comment by dengchaowen-cx** [comment]
我用了nginx反向代理 就没有去折腾证书了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月15日 09:25
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)





 
issue先关闭了 有其他回复请在此答复

**Comment by Luosh** [comment]
大神， 用工具mkcert 生成的证书无法加载识别， 主要用在局域网。附件:
[192.168.31.90.p12.zip](https://github.com/xia-chu/ZLMediaKit/files/5493584/192.168.31.90.p12.zip), 望指点什么原因？
@xia-chu

**Comment by xia-chu** [comment]
证书里面需要有公钥和私钥，而且不能有密码。
你的证书怎么域名是zlmediakit？证书需要配合域名使用的，你在局域网中你有域名吗

**Comment by dengchaowen-cx** [comment]
没有 我用nginx代理 跑起来了&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年11月6日 09:25
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)





 
证书里面需要有公钥和私钥，而且不能有密码。
 你的证书怎么域名是zlmediakit？证书需要配合域名使用的，你在局域网中你有域名吗

**Comment by Luosh** [comment]
> 证书里面需要有公钥和私钥，而且不能有密码。
> 你的证书怎么域名是zlmediakit？证书需要配合域名使用的，你在局域网中你有域名吗

附件里的证书是我用mkcert生成的，我看了不是zlmediakit,  mkcert 生成的证书没有CN字段， 程序无法加载。局域网都是用ip访问的。 我改了下代码， 把vhost 为空的加载证书设置到 default  里了， 不然不能访问https.

**Comment by dengchaowen-cx** [comment]
你是不是弄错人了 我没有发证书给你确实哦 是不是还有其他人 也提了这个问题的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Luosh <notifications@github.com&gt;
发送时间: 2020年11月6日 09:39
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)





  
证书里面需要有公钥和私钥，而且不能有密码。
 你的证书怎么域名是zlmediakit？证书需要配合域名使用的，你在局域网中你有域名吗
  
附件里的证书是我用mkcert生成的，我看了不是zlmediakit,  mkcert 生成的证书没有CN字段， 程序无法加载。局域网都是用ip访问的。 我改了下代码， 把vhost 为空的加载证书设置到 default  里了， 不然不能访问https.

**Comment by Luosh** [comment]
> 你是不是弄错人了 我没有发证书给你确实哦 是不是还有其他人 也提了这个问题的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Luosh <notifications@github.com&gt; 发送时间: 2020年11月6日 09:39 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516) 证书里面需要有公钥和私钥，而且不能有密码。 你的证书怎么域名是zlmediakit？证书需要配合域名使用的，你在局域网中你有域名吗 附件里的证书是我用mkcert生成的，我看了不是zlmediakit, mkcert 生成的证书没有CN字段， 程序无法加载。局域网都是用ip访问的。 我改了下代码， 把vhost 为空的加载证书设置到 default 里了， 不然不能访问https. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@dengchaowen-cx  哈哈， 是我这边借楼提问的， 夏神是回复我的问题， 不好意思弄错了哈～

**Comment by dengchaowen-cx** [comment]
哦 我也没有注意看 哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Luosh <notifications@github.com&gt;
发送时间: 2020年11月6日 09:44
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516)





  
你是不是弄错人了 我没有发证书给你确实哦 是不是还有其他人 也提了这个问题的 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Luosh <notifications@github.com&gt; 发送时间: 2020年11月6日 09:39 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] https证书问题 (#516) 证书里面需要有公钥和私钥，而且不能有密码。 你的证书怎么域名是zlmediakit？证书需要配合域名使用的，你在局域网中你有域名吗 附件里的证书是我用mkcert生成的，我看了不是zlmediakit, mkcert 生成的证书没有CN字段， 程序无法加载。局域网都是用ip访问的。 我改了下代码， 把vhost 为空的加载证书设置到 default 里了， 不然不能访问https. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
@dengchaowen-cx  哈哈， 是我这边借楼提问的， 夏神是回复我的问题， 不好意思弄错了哈～
