### ISSUE TITLE
rtsp 转rtmp [test_rtmpPusher.cpp](https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_rtmpPusher.cpp);这个还是拉流rtsp/rtmp后再以rtmp方式推流;

### ISSUE THREAD

**Issue by microsoftBoy** [xia-chu/ZLMediaKit#517]
rtsp 转rtmp [test_rtmpPusher.cpp](https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_rtmpPusher.cpp);这个还是拉流rtsp/rtmp后再以rtmp方式推流;

还可以参考[test_server.cpp](https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_server.cpp)；这个是拉流rtsp/rtmp后再转换成rtsp/rtmp/hls/http-flv直播；

编译android工程也是比较简单的,如果你要实例工程 我可以发给你

_Originally posted by @xia-chu in https://github.com/xia-chu/ZLMediaKit/issues/1#issuecomment-399339450_

请问拉流rtsp/rtmp后再以rtmp方式推流这个有demo可以给参考一下吗？

**Comment by xia-chu** [comment]
test_rtmpPusher.cpp不就是demo吗

**Comment by xia-chu** [comment]
你不回答我只能先关闭issue了 有其他答复请在此回复。
