### ISSUE TITLE
webhook触发事件是否会携带相关参数？

### ISSUE THREAD

**Issue by st-client** [xia-chu/ZLMediaKit#519]
你好，请问webhook触发事件是否会下发请求参数到第三方接口，我这边是java搭建的后台，触发鉴权事件以及无人观看事件等接口，都无法接收到相应的参数。

**Comment by xia-chu** [comment]
鉴权事件会有播放url参数的，在json的params字段中。
无人观看事件没有，因为那个是事件是流产生的事件，跟播放器无关。

**Comment by xia-chu** [comment]
你要知道推流url参数吗

**Comment by xia-chu** [comment]
你这种态度我只能禁止你以后提issue了

**Comment by st-client** [comment]
不好意思，问题自己解决了，怕你太忙就自己把issue关了没有回复，怕放在那里影响别人的帖子置顶，抱歉。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夏楚"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 下午3:05
收件人: "xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;; 
抄送: "林树涛"<913910275@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xia-chu/ZLMediaKit] webhook触发事件是否会携带相关参数？ (#519)





 
你这种态度我只能禁止你以后提issue了

**Comment by st-client** [comment]
作为一名开发者，知道作者开源不容易，能自己解决就自己想办法解决，回复不全请作者见谅！
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夏楚"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 下午3:05
收件人: "xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;; 
抄送: "林树涛"<913910275@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xia-chu/ZLMediaKit] webhook触发事件是否会携带相关参数？ (#519)





 
你这种态度我只能禁止你以后提issue了

**Comment by xia-chu** [comment]
你能解释清楚就ok了 如果方便 可以把解决方法附带上来 谢谢

**Comment by st-client** [comment]
Java第三方事件接口接webhook参数用HttpServletRequest，用输入流getInputStream的方式可以接收触发事件传来的参数，例如：播放流的ID，正常用springboot控制器的方法传参是接收不到参数的，也无法封装到实体类中，各位做java开发的可以参考一下，给作者带来不便请见谅。

**Comment by xia-chu** [comment]
谢谢 我误会你了

**Comment by st-client** [comment]
已附上我问题的解决方法，参数接收方式不对，各位java开发者需要留意一下。



 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夏楚"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 下午3:18
收件人: "xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;; 
抄送: "林树涛"<913910275@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xia-chu/ZLMediaKit] webhook触发事件是否会携带相关参数？ (#519)





 
你能解释清楚就ok了 如果方便 可以把解决方法附带上来 谢谢
