### ISSUE TITLE
ffmpeg命令

### ISSUE THREAD

**Issue by wkdepth** [xia-chu/ZLMediaKit#522]
麻烦问下   想压缩视频   ffmpeg这样写对么
%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -s 320:-1 -c:v libx264 -f flv %s

**Comment by xia-chu** [comment]
这个应该对的 你可以在shell里面先测试下你的命令：
```bash
ffmpeg -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -s 320:-1 -c:v libx264 -f flv rtmp://xxxx/xxxx/xxxx
```

**Comment by xia-chu** [comment]
这个应该只是转换分辨率的 你好像没限制视频的码率

**Comment by wkdepth** [comment]
昨天从测试这个命令的时候   这个命令导致进程死了
还有请问下怎么设置码率呢/

**Comment by wkdepth** [comment]
ffmpeg -re -i rtsp://xxxx/xxx/xxx -c:a aac -strict -2 -ar 44100 -ab 48k -s 640x320 -c:v libx264 -f flv rtmp://xxxx/xxxx/xxxx

**Comment by wkdepth** [comment]
测试了下  这种方式可以
