### ISSUE TITLE
播放监控视频的时候，控制台一直打印这个日志帮忙麻烦看一下

### ISSUE THREAD

**Issue by wkdepth** [xia-chu/ZLMediaKit#525]
![WechatIMG230](https://user-images.githubusercontent.com/18206718/96367043-0efdd600-117e-11eb-91c3-87844d59193d.jpeg)

**Comment by wkdepth** [comment]
![WechatIMG231](https://user-images.githubusercontent.com/18206718/96367340-d52dcf00-117f-11eb-8cad-52e1431b25ad.png)
使用 ffmpeg命令转视频的时候一直提示等待超时，另外个 播放器播放的看原地址是可以看的

**Comment by xia-chu** [comment]
你自己看看ffmpeg的日志





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wkdepth <notifications@github.com&gt;
发送时间: 2020年10月18日 20:24
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 播放监控视频的时候，控制台一直打印这个日志帮忙麻烦看一下 (#525)





 

 使用 ffmpeg命令转视频的时候一直提示等待超时，另外个 播放器播放的看原地址是可以看的

**Comment by wkdepth** [comment]
刚刚用ffmpeg直接 执行命令     返回 cannot read rtmp handshake  response

**Comment by xia-chu** [comment]
那你先确保ffmpeg执行命令能ok再用zlm测试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wkdepth <notifications@github.com&gt;
发送时间: 2020年10月18日 20:33
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 播放监控视频的时候，控制台一直打印这个日志帮忙麻烦看一下 (#525)





 
刚刚用ffmpeg直接 执行命令     返回 cannot read rtmp handshake  response
