### ISSUE TITLE
Some serious questions regarding this repo - Any help would be appreciated!

### ISSUE THREAD

**Issue by xoraingroup** [xia-chu/ZLMediaKit#530]
I have few queries.

1. Is there support for forwarding stream to edge? If Yes how? The config file does not provide any information about that. 
2. Is there any support for RTMP Redirect? 
3. How do we pull stream from edge? This question is dependent on question 1.
4. How many concurrent connections 1 instance can take? I am sure, its not multi-threaded i.e. it uses only 1 core. Having 64 core machines how we can fully utilize it for ingestion or pull?

I have thoroughly navigated this repo and couldn't find the above information. Any help or info will be highly appreciated. :)

**Comment by xia-chu** [comment]
- 1. It does not support streaming to the edge server. You can implement the proxy in the edge server by tracing the source and actively pulling the stream.
- 2. Redirection is not supported. In fact, it can be supported. However, no one mentioned this requirement, so it was not done.
- 3. I don't understand what you're saying
- 4. zlmediakit supports multi-core CPUs. It is multithreaded. On a 64 core CPU machine, zlmediakit can squeeze out the computing power of each core CPU by a single process.

**Comment by xia-chu** [comment]
Do you confuse  [SRS](https://github.com/ossrs/srs) zlmediakit?

**Comment by xoraingroup** [comment]
So it means we cannot forward stream to another server. What do you mean by proxy implementation? Do you mean developing the proxy for this?
> * 1. It does not support streaming to the edge server. You can implement the proxy in the edge server by tracing the source and actively pulling the stream.

Ok, It can be a requirement for you then 👍 
> * 1. Redirection is not supported. In fact, it can be supported. However, no one mentioned this requirement, so it was not done.

What my use case is 
Origin (forwards stream) --> Edge <-- User Pull stream from edge
> * 1. I don't understand what you're saying

This is awesome... Love it... :)
> * 1. zlmediakit supports multi-core CPUs. It is multithreaded. On a 64 core CPU machine, zlmediakit can squeeze out the computing power of each core CPU by a single process.

**Comment by xoraingroup** [comment]
> Do you confuse [SRS](https://github.com/ossrs/srs) with zlmediakit?

Actually I had been checking srs. It has some problems and major ones. Trying to find an alternative for our use case. Do you provide technical consulting as well? I mean if we have to ask for customisation for a fee?

Thank you

**Comment by xia-chu** [comment]
In fact, zlmediakit supports forward stream to another server.
It's just that this is a relatively separate function. I haven't integrated it into the main process of MediaServer。

Moreover, the live broadcast is shared with the edge server, which can also make the edge server pull stream from origin server.

**Comment by xia-chu** [comment]
Please read [this](https://github.com/xia-chu/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy)

**Comment by xia-chu** [comment]
> Actually I had been checking srs. It has some problems and major ones. Trying to find an alternative for our use case. Do you provide technical consulting as well? I mean if we have to ask for customisation for a fee?

In fact, I'll take on some custom development things. 
But our language communication may not be very smooth, and I don't know how to receiving fees. You know there are many things in China that are different from you

**Comment by xoraingroup** [comment]
Its perfectly ok. We will find a way forward. We can discuss and there is no problem at all. Just send me your email address and i will be in contact with you. What do you say?

**Comment by xoraingroup** [comment]
> Please read [this](https://github.com/xia-chu/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy) and [this](https://github.com/xia-chu/ZLMediaKit/wiki/ZLMediaKit%E5%AE%9E%E7%8E%B0%E6%8C%89%E9%9C%80%E6%8B%89%E6%B5%81)

So when i send rtmp stream, then do i have to add stream proxy. Sorry i am translating chinese to english using google translate but then you have a flow diagram which has components in chinese language and it can't be translated. Do you have some english version of that diagram. It will clear things up. Waiting for your kind reply.

**Comment by xoraingroup** [comment]
> In fact, zlmediakit supports forward stream to another server.
> It's just that this is a relatively separate function. I haven't integrated it into the main process of MediaServer。
> 
Do you think it will take long time to integrate. This is usually one of the core feature of streaming servers that can forward stream to any destination. 

> Moreover, the live broadcast is shared with the edge server, which can also make the edge server pull stream from origin server.
I think this is some what related to /index/api/addStreamProxy ????

**Comment by xia-chu** [comment]
> Its perfectly ok. We will find a way forward. We can discuss and there is no problem at all. Just send me your email address and i will be in contact with you. What do you say?

771730766@qq.com

**Comment by xia-chu** [comment]
Yes , you can use api ` /index/api/addStreamProxy` to pull a stream to edge server from origin server.

**Comment by xia-chu** [comment]
Please use `addStreamProxy` like this:
<img width="807" alt="图片" src="https://user-images.githubusercontent.com/11495632/96968440-91eaac00-1543-11eb-821c-a6b18d421752.png">

**Comment by xoraingroup** [comment]
> > Its perfectly ok. We will find a way forward. We can discuss and there is no problem at all. Just send me your email address and i will be in contact with you. What do you say?
> 
> [771730766@qq.com](mailto:771730766@qq.com)

I will be in touch by monday. :+1:

**Comment by xoraingroup** [comment]
> Please use `addStreamProxy` like this:
> <img alt="image" width="807" src="https://user-images.githubusercontent.com/11495632/96968440-91eaac00-1543-11eb-821c-a6b18d421752.png">

How do you do push stream on demand? There was another diagram, but its also in chinese. It would be great if you can make english translation as well for that.

Also I have successfully built ZLMediaKit for testing. HLS were not generated at all. Here is the config.

```javascript
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[ffmpeg]
bin=ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
enableVhost=1
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=NUaRzSQp5TYJHyRF
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000

[hls]
broadcastRecordTs=0
fileBufSize=65536
filePath=./data
segDur=2
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
enable=0
on_flow_report=https://127.0.0.1/index/hook/on_flow_report
on_http_access=https://127.0.0.1/index/hook/on_http_access
on_play=https://127.0.0.1/index/hook/on_play
on_publish=https://127.0.0.1/index/hook/on_publish
on_record_mp4=https://127.0.0.1/index/hook/on_record_mp4
on_record_ts=https://127.0.0.1/index/hook/on_record_ts
on_rtsp_auth=https://127.0.0.1/index/hook/on_rtsp_auth
on_rtsp_realm=https://127.0.0.1/index/hook/on_rtsp_realm
on_server_started=https://127.0.0.1/index/hook/on_server_started
on_shell_login=https://127.0.0.1/index/hook/on_shell_login
on_stream_changed=https://127.0.0.1/index/hook/on_stream_changed
on_stream_none_reader=https://127.0.0.1/index/hook/on_stream_none_reader
on_stream_not_found=https://127.0.0.1/index/hook/on_stream_not_found
timeoutSec=10

[http]
charSet=utf-8
dirMenu=1
keepAliveSecond=15
maxReqSize=4096
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit-5.0(build in Oct 23 2020 08:22:16)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
clearCount=10
cycleMS=46800000
maxRtpCount=50
videoMtuSize=1400

[rtp_proxy]
checkSource=1
dumpDir=
port=10000
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=332

[shell]
maxReqSize=1024
port=9000

; } ---
```

I noticed one error in chinese, but couldn't make sense of it.

![image](https://user-images.githubusercontent.com/17129052/97003755-98c5ee80-1544-11eb-9cf4-3a7c37de12b1.png)

Any help would be appreciated :)

**Comment by xoraingroup** [comment]
Anything?

**Comment by xia-chu** [comment]
Sorry to forget to reply you，HLS files are not generated until you play HLS url.

**Comment by xia-chu** [comment]
Another sequence diagram, I'll translate it for you. Wait a moment

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/97249500-f016d800-183e-11eb-9433-c97cd346fb0e.png)

**Comment by xoraingroup** [comment]
Thank you very much for this. The above diagram is one of good use case, but what I was expecting that we can configure ZLMediaKit server using config file or through an api to request it to push stream to another server. I believe there is an FFMPEG way of doing this, but what I am expecting is that it could be done with out ffmpeg like SRS does it. Any idea on that?

**Comment by xia-chu** [comment]
As a matter of fact, ZLMediaKit has such functions, which I just haven't exposed to restful API

**Comment by xoraingroup** [comment]
Is it too much work to expose it via API?

**Comment by xia-chu** [comment]
> Is it too much work to expose it via API?

No, it's just that demand is rare

**Comment by xoraingroup** [comment]
Demand is created by the feature a product has. If this project is lacking feature, of course people will just go to the next project. Its my own opinion. Also this is a kind of feature almost every rtmp server has.

**Comment by xoraingroup** [comment]
Can you implement this please?

**Comment by xoraingroup** [comment]
@xia-chu waiting for your reply. Can you please have a look at it and find some time to implement this feature? I am keenly interested in this project and would like it to out grow. I can do all tests including stress tests.

**Comment by xia-chu** [comment]
I'm busy recently. Sorry!
Can I do this when I'm free？

**Comment by xoraingroup** [comment]
Yes sure, but If you can find some short time from your busy schedule and implement it, then it would be really really great. I am eagerly waiting for this. please. Thank you

**Comment by xoraingroup** [comment]
Any updates on this?

**Comment by xia-chu** [comment]
Sorry, i don't have time to add new features, Many things have to do recently. My full-time job is not to do this.
You can refer to this [branch](https://github.com/monktan89/ZLMediaKit), which implements the active streaming API

**Comment by xoraingroup** [comment]
There is no documentation for active push. Can you pin point me to the correct document in that repository on how I can use it. I can close this issue aftewards. Also many thanks for your support. Really appreciate that.

**Comment by xoraingroup** [comment]
Ok I got it. Thank you very much for your time and support. I really appreciate your hard work effort you have put into this. Thank you once again. Closing it for now. 👍

**Comment by xia-chu** [comment]
http://127.0.0.1/index/api/addStreamPusherProxy?schema=rtmp&vhost=__defaultVhost__&app=proxy&stream=0&dst_url=rtmp://127.0.0.1/live/obs

https://github.com/monktan89/ZLMediaKit/blob/master/server/WebApi.cpp#L676
