### ISSUE TITLE
web api application/json 获取content   allArgs无数据 

### ISSUE THREAD

**Issue by hh-kai** [xia-chu/ZLMediaKit#531]
提示如下：
2020-10-22 15:29:56.045 T MediaServer.exe[18368] HttpSession.cpp:24 HttpSession | 2822865689120(127.0.0.1:3251)
2020-10-22 15:29:56.046 W MediaServer.exe[18368] WebApi.cpp:139 getAllArgs | Type is not convertible to string
2020-10-22 15:29:56.046 D MediaServer.exe[18368] WebApi.cpp:187 operator () |

      stringstream ss(parser.Content());
            Value jsonArgs;
            ss >> jsonArgs;
            auto keys = jsonArgs.getMemberNames();
            for (auto key = keys.begin(); key != keys.end(); ++key) {
                //allArgs[*key] = jsonArgs[*key].toStyledString();
                allArgs[*key] = jsonArgs[*key].asString();
            }

使用toStyledString()能拿到数据 
asString()是jsoncpp内部提示转换失败

**Comment by xia-chu** [comment]
嗯  说你你json传的字段不是string

**Comment by hh-kai** [comment]
我是用Postman这个工具来测试的 
截图如下：
![无标题](https://user-images.githubusercontent.com/19390025/96951927-36f38d80-1520-11eb-9745-33442fd2376d.png)

**Comment by xia-chu** [comment]
zlm的restful api支持json传参，但是仅限一级object，也就是json里面不能嵌套json object.
这样做的目的是兼容application/x-www-form-urlencoded类型的参数

**Comment by hh-kai** [comment]
那使用toStyledString()会不会有问题 目前使用toStyledString()可以拿到多级的json obj。
如果实在不行 就只能使用application/x-www-form-urlencoded来传多级的json obj

**Comment by xia-chu** [comment]
> 那使用toStyledString()会不会有问题 目前使用toStyledString()可以拿到多级的json obj。
> 
> 如果实在不行 就只能使用application/x-www-form-urlencoded来传多级的json obj

这玩意没法传多级对象

**Comment by hh-kai** [comment]
那只能按键值对来传了
