### ISSUE TITLE
RTSP 直接代理模式开启后，RTSP 断线无法收到通知事件？

### ISSUE THREAD

**Issue by chuyue86** [xia-chu/ZLMediaKit#532]
打开 rtsp 代理模式（directProxy=1），若此时 rtsp 视频源掉线，无法收到 rtsp 媒体注销事件。此时 hls/rtmp 等其他媒体协议注销事件正常。

**Comment by xia-chu** [comment]
你说的这个问题确实存在



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ethan <notifications@github.com&gt;
发送时间: 2020年10月22日 18:23
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] RTSP 直接代理模式开启后，RTSP 断线无法收到通知事件？ (#532)

**Comment by xia-chu** [comment]
已修复
