### ISSUE TITLE
性能测试问题

### ISSUE THREAD

**Issue by dengchaowen-cx** [xia-chu/ZLMediaKit#535]
你好这是我的电脑配置
[root@localhost ~]# cat /proc/cpuinfo | grep name
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
model name      : Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
[root@localhost ~]# cat /proc/meminfo | head -4
MemTotal:       65236612 kB
MemFree:        60895468 kB
MemAvailable:   63060248 kB
Buffers:            2764 kB
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# rpm -q centos-release
centos-release-8.1-1.1911.0.8.el8.x86_64
[root@localhost ~]# df -h
文件系统             容量  已用  可用 已用% 挂载点
devtmpfs              32G     0   32G    0% /dev
tmpfs                 32G     0   32G    0% /dev/shm
tmpfs                 32G  115M   31G    1% /run
tmpfs                 32G     0   32G    0% /sys/fs/cgroup
/dev/mapper/cl-root   50G  6.1G   44G   13% /
/dev/sda2            976M  140M  770M   16% /boot
/dev/mapper/cl-home  1.1T   17G 1018G    2% /home
/dev/sda1            599M  6.8M  593M    2% /boot/efi
tmpfs                6.3G   16K  6.3G    1% /run/user/42
tmpfs                6.3G  4.0K  6.3G    1% /run/user/0
[root@localhost ~]# 
以上是我电脑配置 安装的centos系统
推流端是海康摄像头 国标 分辨率720p 码率是1M，我在winds上面用vs2017同时建立了1024个websocket链接，用websocket-flv直播只接收音视频流不播放，服务端会频繁打印take time:13ms, thread may be overloaded 同时我再用http://cloud.liveqing.com:10080/#/liveplayer 查看视频会卡顿有时候会卡死，是不是是我测试的方法有问题
还有一个问题就是 我在winds上面跑1024个websocket链接 然后关闭所有链接后 内存占用会 恢复到原来水平 但是在Linux上面top命令 res的值一直没有恢复到原来水平

**Comment by xia-chu** [comment]
windows和linux的内存管理机制不一样 程序free内存后 c运行时可能并不会立即返还给内核

**Comment by dengchaowen-cx** [comment]
为什么我的内存占用 一直 没有下来 在winds跑 又是正常的降下来了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月23日 18:20
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)





 
那句警告日志是正常的 只要不是太频繁就行

**Comment by xia-chu** [comment]
1024个播放器很少了 windows下性能也是够用的 你确定一个播放器时就播放流畅吗

**Comment by xia-chu** [comment]
没事的 不用担心 zlm没有内存泄漏的问题

**Comment by dengchaowen-cx** [comment]
那句 负载重的 打印很平凡 我看wiki上面有性能测试报告 一般 并发多少 就会频繁打印那条日志了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月23日 18:21
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)





 
windows和linux的内存管理机制不一样 程序free内存后 c运行时可能并不会立即返还给内核

**Comment by dengchaowen-cx** [comment]
嗯 我先 挂着不关机看看 多久可以恢复到正常水平



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月23日 18:24
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)





 
没事的 不用担心 zlm没有内存泄漏的问题

**Comment by dengchaowen-cx** [comment]
VmHWM:	  937200 kB
VmRSS:	  930508 kB
您好我这边程序 内存一直没有释放 不知道什么原因

**Comment by xia-chu** [comment]
这个不是内存泄露 不信你多跑断时间  要有业务

**Comment by dengchaowen-cx** [comment]
你好 我又测试了一下 用obs推流，websock-flv观看，播放器都是看同一视频源， 得到了一个规律，比如我拉500路流观看，此时内存占用是360M，关闭播放器后内存占用会一直是360M，之后拉流只要少女500路，内存占用不会增加也不会减少。但是我去拉流600路观看时 内存占用会增加到400M。也就是说只要并发路说比之前的最大并发还大内存就会增加，但是也不会释放， 如果下一次的并发路数比之前最大并发数下的话 内存不会增加 关闭播放器内存也不会下降 ， 能帮忙解答一下是什么原因吗 谢谢
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "xia-chu/ZLMediaKit" <notifications@github.com&gt;;
 发送时间:&nbsp;2020年10月24日(星期六) 晚上10:47
 收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
 抄送:&nbsp;"1020443551"<1020443551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [xia-chu/ZLMediaKit] 性能测试问题 (#535)

 

 

 
这个不是内存泄露 不信你多跑断时间 要有业务

**Comment by xia-chu** [comment]
跟你们同事沟通过了  是你们开启了asan的缘故，关闭它就正常了

**Comment by dengchaowen-cx** [comment]
你是不是发错了哦🙄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月26日 11:45
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)





 
跟你们同事沟通过了  是你们开启了asan的缘故，关闭它就正常了

**Comment by xia-chu** [comment]
你不是百度的吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dengchaowen-cx <notifications@github.com&gt;
发送时间: 2020年10月26日 12:10
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)





 你是不是发错了哦🙄 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 夏楚 <notifications@github.com&amp;gt; 
 发送时间: 2020年10月26日 11:45 
 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt; 
 抄送: dengchaowen-cx <1020443551@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535) 
 
 
 
 
 
   
 跟你们同事沟通过了  是你们开启了asan的缘故，关闭它就正常了

**Comment by dengchaowen-cx** [comment]
不是呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年10月26日 12:17
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)





 你不是百度的吗？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: dengchaowen-cx <notifications@github.com&amp;gt; 
 发送时间: 2020年10月26日 12:10 
 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt; 
 抄送: 夏楚 <771730766@qq.com&amp;gt;, State change <state_change@noreply.github.com&amp;gt; 
 主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535) 
 
 
 
 
 
  你是不是发错了哦🙄  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: 夏楚 <notifications@github.com&amp;amp;gt;  
  发送时间: 2020年10月26日 11:45  
  收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;amp;gt;  
  抄送: dengchaowen-cx <1020443551@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt;  
  主题: 回复：[xia-chu/ZLMediaKit] 性能测试问题 (#535)  
   
   
   
   
   
     
  跟你们同事沟通过了  是你们开启了asan的缘故，关闭它就正常了

**Comment by dengchaowen-cx** [comment]
&nbsp;你好 我用的编译器gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)和g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5) 
 请问asan怎么关闭在哪里关闭 我晚上查了一下 他是编译器的参数配置项 直接用源代码的里面的cmake编译的 不知道在哪里关闭
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "xia-chu/ZLMediaKit" <notifications@github.com&gt;;
 发送时间:&nbsp;2020年10月26日(星期一) 中午11:45
 收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
 抄送:&nbsp;"1020443551"<1020443551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [xia-chu/ZLMediaKit] 性能测试问题 (#535)

 

 

 
跟你们同事沟通过了 是你们开启了asan的缘故，关闭它就正常了

**Comment by wasphin** [comment]
> &nbsp;你好 我用的编译器gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)和g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5) 请问asan怎么关闭在哪里关闭 我晚上查了一下 他是编译器的参数配置项 直接用源代码的里面的cmake编译的 不知道在哪里关闭
> […](#)

默认编译是没有开启 asan 的, 应该不是一个问题.

**Comment by dengchaowen-cx** [comment]
我不知道这到底是不是内存泄漏，我用websocket-flv拉流和rtmp拉流都测试了一下 情况是一样的一直没有降下去 还下载了git上面的最新的代码测试了情况也一样
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "xia-chu/ZLMediaKit" <notifications@github.com&gt;;
 发送时间:&nbsp;2020年10月26日(星期一) 下午4:37
 收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
 抄送:&nbsp;"1020443551"<1020443551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [xia-chu/ZLMediaKit] 性能测试问题 (#535)

 

 

  
�0�2你好 我用的编译器gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)和g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5) 请问asan怎么关闭在哪里关闭 我晚上查了一下 他是编译器的参数配置项 直接用源代码的里面的cmake编译的 不知道在哪里关闭
…
 
默认编译是没有开启 asan 的, 应该不是一个问题.
