### ISSUE TITLE
DevChannel类调用initVideo函数出现段错误

### ISSUE THREAD

**Issue by mxmini** [xia-chu/ZLMediaKit#537]
[Switching to Thread 0x7fff26fed700 (LWP 3581)]
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: yum debuginfo-install libgcc-8.3.1-4.5.el8.x86_64 libstdc++-8.3.1-4.5.el8.x86_64 libuuid-2.32.1-17.el8.x86_64 sssd-client-2.2.0-19.el8.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff0607b6c in mediakit::MultiMediaSourceMuxer::addTrack(std::shared_ptr<mediakit::Track> const&) () from ./libStreamSvr.so
#2  0x00007ffff05de937 in mediakit::DevChannel::initVideo(mediakit::VideoInfo const&) () from ./libStreamSvr.so
#3  0x00007ffff05845eb in StreamChannel::set_avinfo (this=0x7fff7800a680, vi=0x7fff26febca0, ai=0x7fff26febb80) at StreamChannel.cpp:69
#4  0x00007ffff058cff2 in StreamServer::set_session_stream_info (this=0x9d7360, session=140735206696576, vi=0x7fff26febca0, ai=0x7fff26febb80) at StreamServer.cpp:160
#5  0x00007ffff0582023 in iSOC_SetSession (server=10318688, session=140735206696576, vi=0x7fff26febca0, ai=0x7fff26febb80) at rtspsdk.cpp:55
#6  0x00007ffff28db42a in XhRealstreamServo::ParseMonRealStreamReqInfo (this=0x7fff70442ce0, pParams=0x7fff26fec700) at ../XhRealstreamServo.cpp:3155
#7  0x00007ffff28d9755 in XhRealstreamServo::ParseOder (this=0x7fff70442ce0, pParams=0x7fff26fec700) at ../XhRealstreamServo.cpp:2683
#8  0x00007ffff28d6117 in XhRealstreamServo::proc_cmd_buff (this=0x7fff70442ce0, pBuffer=..., nBufLen=@0x7fff26fec81c: 773) at ../XhRealstreamServo.cpp:1649
#9  0x00007ffff28d63d5 in XhRealstreamServo::pull_and_proc_cmd_from_fifo (this=0x7fff70442ce0) at ../XhRealstreamServo.cpp:1687
#10 0x00007ffff2976238 in boost::_mfi::mf0<int, XhRealstreamServo>::call<boost::shared_ptr<XhRealstreamServo> > (this=0x7fff26feca80, u=...) at /opt/include/boost/bind/mem_fn_template.hpp:40
#11 0x00007ffff2975e41 in boost::_mfi::mf0<int, XhRealstreamServo>::operator()<boost::shared_ptr<XhRealstreamServo> > (this=0x7fff26feca80, u=...) at /opt/include/boost/bind/mem_fn_template.hpp:55
#12 0x00007ffff29759a5 in boost::_bi::list1<boost::_bi::value<boost::shared_ptr<XhRealstreamServo> > >::operator()<int, boost::_mfi::mf0<int, XhRealstreamServo>, boost::_bi::list0> (this=0x7fff26feca90, 
    f=..., a=...) at /opt/include/boost/bind/bind.hpp:249

**Comment by xia-chu** [comment]
这个问题 我觉得是你使用的bug 这么明显的bug肯定不是ZLMediaKitde 你可以用Valgrind或address sanitizer 排除内存相关的bug

**Comment by mxmini** [comment]
ZLMediaKit2.0版本按照这个流程使用就完全正常，目前clone最新的代码编译后调用这个函数后就会出现这个问题。

**Comment by xia-chu** [comment]
这个bug可能是调用顺序不对 或者线程安全的问题，这个mk_media的api，我也用过，我不认为这个是zlm的bug。
你先用Valgrind或address sanitizer 检查下你的代码是否有bug吧 issue 我先关闭了
