### ISSUE TITLE
/index/api/startSendRtp接口回调出发送源端口问题

### ISSUE THREAD

**Issue by tsingeye** [xia-chu/ZLMediaKit#538]
国标上级点播时，sip信令中需要携带本机发送源的ip和端口，目前`/index/api/startSendRtp`返回值没有给出来发送源端口，求加

**Comment by tsingeye** [comment]
想了一下 这个需要跟业务对接，流程不太好控制

**Comment by xia-chu** [comment]
那到底要还是不要啊

**Comment by tsingeye** [comment]
不好搞啊， 国标是推流前就要通过sdp告知对方法流的源端口，然后才进行发流。这样的话，至少需要得进行与zlm的交互了啊。
另外，不确定有些国标平台是否会验证这个源port。。。纠结。。。

**Comment by musicwood** [comment]
可以通过在/index/api/startSendRtp接口指定源端口来实现吧

**Comment by musicwood** [comment]
linux 可以设置预留一部分端口，自己的业务代码里面管理这些端口使用和释放。

**Comment by tsingeye** [comment]
> 可以通过在/index/api/startSendRtp接口指定源端口来实现吧

是的， 这样最好啦

**Comment by xia-chu** [comment]
那本地网卡要不要指定？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tsingeye <notifications@github.com&gt;
发送时间: 2020年10月28日 10:52
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] /index/api/startSendRtp接口回调出发送源端口问题 (#538)





  
可以通过在/index/api/startSendRtp接口指定源端口来实现吧
  
是的， 这样最好啦

**Comment by tsingeye** [comment]
> 那本地网卡要不要指定？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: tsingeye <notifications@github.com&gt; 发送时间: 2020年10月28日 10:52 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] /index/api/startSendRtp接口回调出发送源端口问题 (#538) 可以通过在/index/api/startSendRtp接口指定源端口来实现吧 是的， 这样最好啦 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

不用啊。 sdp里面指定了 推流的ip了。

**Comment by tsingeye** [comment]
预先知道流媒体IP的， 只是推流的端口不能预先设置。

**Comment by xia-chu** [comment]
我是说  多网卡的情况下 有时要选择网卡才能udp推流出去

**Comment by tsingeye** [comment]
哦哦 那指定ip和port /滑稽

**Comment by xia-chu** [comment]
已实现，指定本机网卡的功能未实现，有多网卡时该接口无法使用时再说吧
