### ISSUE TITLE
RTMP推流性能不足

### ISSUE THREAD

**Issue by seven-lfz** [xia-chu/ZLMediaKit#540]
在RTMP处理中的RtmpProtocol.cpp中使用std::string _recv_data_buf， 有频繁的append/erase处理，对CPU消耗特别多。
实际测试中使用5000路4Mbps的码流就需要消耗60 cores。
可以考虑使用内存、读写游标及memmove来优化CPU性能

**Comment by xia-chu** [comment]
额 推流确实没着重优化性能的 zlm主要优化性能的点在分发 也就是可以接收很多个播放器。

**Comment by xia-chu** [comment]
你按照jemalloc库，然后编译Release模式，再测试性能。
你现在的数据偏低

**Comment by xia-chu** [comment]
你说的虽然影响性能  但是不至于那么大

**Comment by seven-lfz** [comment]
拿了两台服务器跑的实际测试数据，即使编译release模式， 估计提升也不太大
使用内存及读写游标的话， 在内存不足的时候再使用memmove或expand memory，性能提升很多，5000路4Mbps的推流消耗可以控制在5-6 cores

**Comment by xia-chu** [comment]
有几倍的性能提升 不过你这个性能参数还是不够看  群里面有人 测试5000路1080P推流啊

**Comment by xia-chu** [comment]
最近优化了下 性能提升了20倍 明天推送代码

**Comment by xia-chu** [comment]
代码已经推送 极大的降低了cpu和内存占用。
