### ISSUE TITLE
最新版本vs2019编译报错

### ISSUE THREAD

**Issue by enjoyaday** [xia-chu/ZLMediaKit#541]
[1/92] Building CXX object CMakeFiles\zlmediakit.dir\src\Rtp\RtpSplitter.cpp.obj
  FAILED: CMakeFiles/zlmediakit.dir/src/Rtp/RtpSplitter.cpp.obj 
  C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe  /nologo /TP -DDBUG_OFF -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DMP4V2_NO_STDINT_DEFS -DOS_WINDOWS -DWIN32_LEAN_AND_MEAN -I..\..\..\3rdpart\ZLToolKit\src -I..\..\..\src -I..\..\..\3rdpart -I"C:\Program Files\OpenSSL-Win64\include" -I..\..\..\3rdpart\media-server\libmpeg\include -I..\..\..\3rdpart\media-server\libmov\include -I..\..\..\3rdpart\media-server\libflv\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG   /wd4819 /wd4996 /wd4018 /wd4267 /wd4244 /wd4101 /wd4828 /wd4309 /wd4573 /showIncludes /FoCMakeFiles\zlmediakit.dir\src\Rtp\RtpSplitter.cpp.obj /FdCMakeFiles\zlmediakit.dir\zlmediakit.pdb /FS -c ..\..\..\src\Rtp\RtpSplitter.cpp
E:\project\test\video\zlm\src\Rtp\RtpSplitter.cpp(12): fatal error C1083: 无法打开包括文件: “netinet/in.h”: No such file or directory
  [2/92] Building CXX object CMakeFiles\zlmediakit.dir\src\Rtsp\RtspSplitter.cpp.obj

**Comment by xia-chu** [comment]
这个issue有人刚提过了 你删除一条include就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: enjoyaday <notifications@github.com&gt;
发送时间: 2020年10月28日 11:31
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 最新版本vs2019编译报错 (#541)





 
[1/92] Building CXX object CMakeFiles\zlmediakit.dir\src\Rtp\RtpSplitter.cpp.obj
 FAILED: CMakeFiles/zlmediakit.dir/src/Rtp/RtpSplitter.cpp.obj
 C:\PROGRA2\MIB0551\2019\PROFES1\VC\Tools\MSVC\14271.291\bin\Hostx64\x64\cl.exe  /nologo /TP -DDBUG_OFF -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DMP4V2_NO_STDINT_DEFS -DOS_WINDOWS -DWIN32_LEAN_AND_MEAN -I......\3rdpart\ZLToolKit\src -I......\src -I......\3rdpart -I"C:\Program Files\OpenSSL-Win64\include" -I......\3rdpart\media-server\libmpeg\include -I......\3rdpart\media-server\libmov\include -I......\3rdpart\media-server\libflv\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG   /wd4819 /wd4996 /wd4018 /wd4267 /wd4244 /wd4101 /wd4828 /wd4309 /wd4573 /showIncludes /FoCMakeFiles\zlmediakit.dir\src\Rtp\RtpSplitter.cpp.obj /FdCMakeFiles\zlmediakit.dir\zlmediakit.pdb /FS -c ......\src\Rtp\RtpSplitter.cpp
 E:\project\test\video\zlm\src\Rtp\RtpSplitter.cpp(12): fatal error C1083: 无法打开包括文件: “netinet/in.h”: No such file or directory
 [2/92] Building CXX object CMakeFiles\zlmediakit.dir\src\Rtsp\RtspSplitter.cpp.obj

**Comment by enjoyaday** [comment]
谢谢
