### ISSUE TITLE
海康摄像头时间倒置问题

### ISSUE THREAD

**Issue by allenzhuyi** [xia-chu/ZLMediaKit#542]
有时候在用zlmediakit推流，摄像机是海康IPC，发现播放的视频流上的当前时间有时间会回跳下，视频流上的显示时间会有短暂的几帧倒退的问题，退回到上一秒，请问是流的顺序问题吗

**Comment by xia-chu** [comment]
你是什么推流？

**Comment by allenzhuyi** [comment]
28181推流到zlmediakit

**Comment by xia-chu** [comment]
花屏么

**Comment by allenzhuyi** [comment]
也不是花屏，就是播放的时候会短暂的回帧，主要是在显示的字母时间上，显示的秒数会短暂回转，初步测试感觉可能是海康显示时间的问题，用了其他的流媒体软件也会发现

**Comment by xia-chu** [comment]
那应该是摄像头问题 如果流媒体有问题 会花屏的 你可以用海康的工具看下视频是否同样回退

**Comment by allenzhuyi** [comment]
好的，我先看下原因，谢谢

**Comment by allenzhuyi** [comment]
海康上界面看的不明显，发现主要是28181推流的时候会有问题

**Comment by xia-chu** [comment]
先关闭了 有其他反馈 请在此回复
