### ISSUE TITLE
hls流注销了，rtmp和rtsp流没有注销

### ISSUE THREAD

**Issue by longegit** [xia-chu/ZLMediaKit#543]
录像停止后，出现这个错误，hls流注销了，但是rtsp和rtmp依旧正常，公网环境udp的

[34m2020-10-28 10:47:30.407 T MediaServer[4116] HttpSession.cpp:118 onError | 139910640057232(121.28.219.118:36227) end of file[0m
[34m2020-10-28 10:47:30.407 T MediaServer[4116] HttpSession.cpp:38 ~HttpSession | 139910640057232(121.28.219.118:36227) [0m
[34m2020-10-28 10:47:30.430 T MediaServer[4116] HttpSession.cpp:30 HttpSession | 139910640057232(121.28.219.118:36229) [0m
[36m2020-10-28 10:47:30.431 I MediaServer[4116] MediaSource.cpp:326 emitEvent | 媒体注销:hls __defaultVhost__ rtp 06146A24[0m

**Comment by xia-chu** [comment]
你用restful api关闭hls是这样的
