### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Allenisme** [xia-chu/ZLMediaKit#546]
ninja: build stopped: subcommand failed.

**Comment by xia-chu** [comment]
不要提这样莫名其妙的问题好不？

**Comment by Allenisme** [comment]
> 不要提这样莫名其妙的问题好不？

不好意思。是这样的，按照wiki里的快速开始，在windows下用visua studio 2019编译，提示生成失败：ninja: build stopped: subcommand failed.

**Comment by wasphin** [comment]
需要找到 ninja 编译失败的具体编译步命令 仅是一个类似 "我的程序崩溃了" 或 "编译失败了", 是没办法提供任何有效建议的.

可以考虑修改项目根目录下的 ``CMakeLists.txt`` 添加:
```cmake
set(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "Enable verbose output." FORCE)
```
然后再进行编译并粘贴全部编译输出到 issue 中来进行进一步排查.

同时有看到 #539 #541 有报编译失败的, 可以看一下是否类似.

**Comment by Allenisme** [comment]
和另外两个issue是同一个问题，谢谢了！-------- 原始邮件 --------发件人： Xiaofeng Wang <notifications@github.com>日期： 2020年10月30日周五 上午9:47收件人： xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com>抄送： Allenisme <allenisme520@163.com>, Author <author@noreply.github.com>主    题： Re: [xia-chu/ZLMediaKit] 编译报错 (#546)

需要找到 ninja 编译失败的具体编译步命令 仅是一个类似 "我的程序崩溃了" 或 "编译失败了", 是没办法提供任何有效建议的.

可以考虑修改项目根目录下的 CMakeLists.txt 添加:

set(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "Enable verbose output." FORCE)

然后再进行编译并粘贴全部编译输出到 issue 中来进行进一步排查.

同时有看到 #539 #541 有报编译失败的, 可以看一下是否类似.
