### ISSUE TITLE
GB28181录制MP4失败

### ISSUE THREAD

**Issue by thornhhh** [xia-chu/ZLMediaKit#547]
大神请教个问题，
国标协议下载视频到zlmedia保存为MP4,  h264+g711的音视频流录制没有问题.
仅有h264的视频录制失败，偶尔一次两次成功过。
下面是同一段视频第一次录制视频失败
MediaServer[7] RtpProcess.cpp:89 inputRtp | 59684BD3(10.172.63.30:18540) bind to address:10.172.11.15:18540
MediaServer[7] RtpProcess.cpp:257 operator() | 59684BD3(10.172.63.30:18540) 允许RTP推流
MediaServer[7] RtpProcess.cpp:159 onRtpDecode | 59684BD3(10.172.11.15:18540) judged to be PS
MediaServer[7] Decoder.cpp:126 onDecode | got video track: H264
W MediaServer[7] RtpSelector.cpp:100 onManager | RtpProcess timeout:59684BD3
W MediaServer[7] RtpProcess.cpp:64 ~RtpProcess | 59684BD3(10.172.63.30:18540) RTP推流器(__defaultVhost__/rtp/59684BD3)断开,耗时(s):0

第二次录制视频失败
MediaServer[7] RtpProcess.cpp:89 inputRtp | 59684BD4(10.172.63.30:18566) bind to address:10.172.11.15:18566
MediaServer[7] RtpProcess.cpp:257 operator() | 59684BD4(10.172.63.30:18566) 允许RTP推流
MediaServer[7] RtpProcess.cpp:159 onRtpDecode | 59684BD4(10.172.63.30:18566) judged to be PS
MediaServer[7] Decoder.cpp:126 onDecode | got video track: H264
W MediaServer[7] RtpSelector.cpp:100 onManager | RtpProcess timeout:59684BD4
W MediaServer[7] RtpProcess.cpp:64 ~RtpProcess | 59684BD4(10.172.63.30:18566) RTP推流器(__defaultVhost__/rtp/59684BD4)断开,耗时(s):0

第三次失败
MediaServer[7] RtpProcess.cpp:89 inputRtp | 59684BD6(10.172.63.30:19336) bind to address:10.172.11.15:19336
MediaServer[7] RtpProcess.cpp:257 operator() | 59684BD6(10.172.63.30:19336) 允许RTP推流
MediaServer[7] RtpProcess.cpp:159 onRtpDecode | 59684BD6(10.172.63.30:19336) judged to be PS
W MediaServer[7] RtpSelector.cpp:100 onManager | RtpProcess timeout:59684BD6
W MediaServer[7] RtpProcess.cpp:64 ~RtpProcess | 59684BD6(10.172.63.30:19336) RTP推流器(__defaultVhost__/rtp/59684BD6)断开,耗时(s):0

**Comment by xia-chu** [comment]
你的 GB28181推流有点问题 zlm接收超时

**Comment by thornhhh** [comment]
> 你的 GB28181推流有点问题 zlm接收超时

感谢，我还是先检查我的推流代码。
但是通过抓包确实能收到rtp流。
