### ISSUE TITLE
好何在添加拉流地址后立即开始拉流，而不是等到用户访问的时候再拉流？

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#550]
请教一下大神：

MediaServer对addStreamProxy的处理是否可以 立即开始拉流，不用等到有人访问时才拉流？

无人访问时不停止拉流的功能，是不是响应hook.on_stream_none_reader即可？

**Comment by xia-chu** [comment]
你在on_not_found事件时调用addStreamProxy开始拉流，在触发on_stream_none_reader时返回close即可
