### ISSUE TITLE
DevChannel问题，请求一个正确的demo

### ISSUE THREAD

**Issue by double7123456** [xia-chu/ZLMediaKit#554]
当我在使用DevChannel对象时，发现在创建DevChannel时，如果构造函数中的stream_id值长度过长时，会导致段错误程序崩溃，然后在查看你的DeviceHK时 发现里面的DevChannel的构造时只有两个参数，搞的我一头雾水，不知道是不是我写的有问题下面是我的demo
```

#include <map>
#include <iostream>

#include "ZLMediaKit/Network/TcpServer.h"
#include "ZLMediaKit/Common/config.h"
#include "ZLMediaKit/Rtmp/RtmpSession.h"
#include "ZLMediaKit/Rtsp/RtspSession.h"
#include "ZLMediaKit/Http/HttpSession.h"
#include "ZLMediaKit/Rtp/RtpSelector.h"
#include "ZLMediaKit/Common/Device.h"
#include <boost/thread/thread.hpp>
std::string schema_;

std::shared_ptr<DevChannel> devchannel_;

void m_send_fream(MediaInfo args)
{
       //我提前录制好的h264文件
	FILE* input_fime = fopen("/home/zhoutao/h264_11_03_20_23", "rb");
	if (input_fime == nullptr)
	{
		printf("error ");
	}
	int buf_size = 0;
	int ret = 0;
	while(1)
	{
		ret = fread(&buf_size,1,sizeof(int),input_fime);
		if (ret == 0)
		{
			printf("buf_size error");
			continue;
		}
		std::shared_ptr<char> h264buf(new char[buf_size]);

		//buf = new char[buf_size];
		ret = fread(h264buf.get(), 1,buf_size, input_fime);
		if (ret == 0)
		{
			printf("buf_size error");
			continue;
		}
		devchannel_->inputH264(h264buf.get(),buf_size,0);
		usleep(44444);
	}
	
}

void on_new_stream(const MediaInfo &args, SockInfo &sender)
{
	if (schema_ != args._schema) {
		std::cerr << "schema:" << args._schema << "not belong this:" << std::endl;
		return;
	}
    //发现如果_streamid的值长度超过15位时，程序会崩，调试后发现MultiMuxerPrivate::Ptr _muxer;这个的虚表发生了变化，不能正常使用
	devchannel_ = make_shared<DevChannel>(args._host, args._app, args._streamid, 0, false, false);
	mediakit::VideoInfo zl_vinfo;
	zl_vinfo.iFrameRate = 15;
	zl_vinfo.iHeight = 1080;
	zl_vinfo.iWidth = 1920;
	devchannel_->initVideo(zl_vinfo);
	boost::thread thrd(&m_send_fream, args);
}
int main()
{
	toolkit::TcpServer::Ptr rtsp_srv_(new TcpServer());
	rtsp_srv_->start<mediakit::RtmpSession>(2935);
	schema_ = RTMP_SCHEMA;
	NoticeCenter::Instance().addListener(nullptr, Broadcast::kBroadcastNotFoundStream,
		[&](const MediaInfo& args, const string& realm, const string& user_name, const bool& must_no_encrypt, const RtspSession::onAuth& invoker, SockInfo& sender)
		{
			on_new_stream(args, sender);
		});
	while (1)
	{
		sleep(1);
	}
    return 0;
}
```

**Comment by xia-chu** [comment]
打个 kBroadcastNotFoundStream事件的参数不是 `const MediaInfo& args, const string& realm, const string& user_name, const bool& must_no_encrypt, const RtspSession::onAuth& invoker, SockInfo& sender`.

你不知道有哪些参数，请用BroadcastNotFoundStreamArgs宏

**Comment by xia-chu** [comment]
我删除那个相同的issue了 我们在这里说。

**Comment by xia-chu** [comment]
你觉得我定义参数列表的宏是吃饱了撑着了吗？
<img width="1182" alt="图片" src="https://user-images.githubusercontent.com/11495632/98195580-11717580-1f5d-11eb-8c7d-9f37cfe1b829.png">

**Comment by double7123456** [comment]
替换BroadcastNotFoundStreamArgs后程序依然会崩

**Comment by xia-chu** [comment]
你可以用gdb调试下 ，或者valgrind或者Address Sanitizer分析下。ZLMediaKit应该没bug的

**Comment by double7123456** [comment]
我刚刚测试了下  我直接用C语言同样流程没有崩溃，然后我就按照你封装c API的方式写了一个类 还是崩溃了，能帮我看下不
```

class m_MediaHelper : public MediaSourceEvent, public std::enable_shared_from_this<m_MediaHelper> {
public:
	typedef std::shared_ptr<m_MediaHelper> Ptr;
	template<typename ...ArgsType>
	m_MediaHelper(ArgsType &&...args) {
		_channel = std::make_shared<DevChannel>(std::forward<ArgsType>(args)...);
	}
	~m_MediaHelper() {
	}

	int init_v(int track_id, int width, int height, int fps) 
	{
		_channel->setMediaListener(shared_from_this());

		VideoInfo info;
		info.codecId = (CodecId)track_id;
		info.iFrameRate = fps;
		info.iWidth = width;
		info.iHeight = height;
		_channel->initVideo(info);
		return 0;
	}
	int init_a(int track_id, int sample_rate, int channels, int sample_bit) {
		AudioInfo info;
		info.codecId = (CodecId)track_id;
		info.iSampleRate = sample_rate;
		info.iChannel = channels;
		info.iSampleBit = sample_bit;
		_channel->initAudio(info);
		return 0;
	}
	//初始化完成
	void mk_media_init_complete() {
		_channel->addTrackCompleted();
	}

	void setOnClose(on_mk_media_close cb, void* user_data) {
		_on_close = cb;
		_on_close_data = user_data;
	}

	void setOnSeek(on_mk_media_seek cb, void* user_data) {
		_on_seek = cb;
		_on_seek_data = user_data;
	}

	void setOnRegist(on_mk_media_source_regist cb, void* user_data) {
		_on_regist = cb;
		_on_regist_data = user_data;
	}
	// 观看总人数
	int totalReaderCount(MediaSource& sender) override {
		return _channel->totalReaderCount();
	}


	void mk_media_input_h264(void* data, int len, uint32_t dts, uint32_t pts) {
		_channel->inputH264((char*)data, len, dts, pts);
	}

	void mk_media_input_h265(void* data, int len, uint32_t dts, uint32_t pts) {
		_channel->inputH265((char*)data, len, dts, pts);
	}

	void mk_media_input_aac(void* data, int len, uint32_t dts, void* adts) {
		_channel->inputAAC((char*)data, len, dts, (char*)adts);
	}

	void mk_media_input_pcm(void* data, int len, uint32_t pts) {
#ifdef ENABLE_FAAC
		assert(ctx && data && len > 0);
		MediaHelper::Ptr* obj = (MediaHelper::Ptr*) ctx;
		(*obj)->getChannel()->inputPCM((char*)data, len, pts);
#else
		WarnL << "aac编码未启用,该方法无效,编译时请打开ENABLE_FAAC选项";
#endif //ENABLE_FAAC
	}

	void mk_media_input_audio(void* data, int len, uint32_t dts) {
		_channel->inputAudio((char*)data, len, dts);
	}


protected:
	// 通知其停止推流
	bool close(MediaSource& sender, bool force) override {
		if (!force && _channel->totalReaderCount()) {
			//非强制关闭且正有人在观看该视频
			return false;
		}
		if (!_on_close) {
			//未设置回调，没法关闭
			WarnL << "请使用mk_media_set_on_close函数设置回调函数!";
			return false;
		}
		//请在回调中调用mk_media_release函数释放资源,否则MediaSource::close()操作不会生效
		_on_close(_on_close_data);
		WarnL << "close media:" << sender.getSchema() << "/" << sender.getVhost() << "/" << sender.getApp() << "/" << sender.getId() << " " << force;
		return true;
	}

	bool seekTo(MediaSource& sender, uint32_t ui32Stamp) override {
		if (!_on_seek) {
			return false;
		}
		return _on_seek(_on_seek_data, ui32Stamp);
	}
	
	void onRegist(MediaSource& sender, bool regist) override {
		if (_on_regist) {
			_on_regist(_on_regist_data, &sender, regist);
		}
	}

private:
	DevChannel::Ptr _channel;
	on_mk_media_close _on_close = nullptr;
	on_mk_media_seek _on_seek = nullptr;
	on_mk_media_source_regist _on_regist = nullptr;
	void* _on_seek_data;
	void* _on_close_data;
	void* _on_regist_data;
};
```

**Comment by xia-chu** [comment]
我也不知道 我也要用工具调试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: double7123456 <notifications@github.com&gt;
发送时间: 2020年11月5日 18:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] DevChannel问题，请求一个正确的demo (#554)





 
我刚刚测试了下  我直接用C语言同样流程没有崩溃，然后我就按照你封装c API的方式写了一个类 还是崩溃了，能帮我看下不
  class m_MediaHelper : public MediaSourceEvent, public std::enable_shared_from_this<m_MediaHelper&gt; { public: typedef std::shared_ptr<m_MediaHelper&gt; Ptr; template<typename ...ArgsType&gt; m_MediaHelper(ArgsType &amp;&amp;...args) { _channel = std::make_shared<DevChannel&gt;(std::forward<ArgsType&gt;(args)...); } ~m_MediaHelper() { } int init_v(int track_id, int width, int height, int fps)  { _channel-&gt;setMediaListener(shared_from_this()); VideoInfo info; info.codecId = (CodecId)track_id; info.iFrameRate = fps; info.iWidth = width; info.iHeight = height; _channel-&gt;initVideo(info); return 0; } int init_a(int track_id, int sample_rate, int channels, int sample_bit) { AudioInfo info; info.codecId = (CodecId)track_id; info.iSampleRate = sample_rate; info.iChannel = channels; info.iSampleBit = sample_bit; _channel-&gt;initAudio(info); return 0; } //初始化完成 void mk_media_init_complete() { _channel-&gt;addTrackCompleted(); } void setOnClose(on_mk_media_close cb, void* user_data) { _on_close = cb; _on_close_data = user_data; } void setOnSeek(on_mk_media_seek cb, void* user_data) { _on_seek = cb; _on_seek_data = user_data; } void setOnRegist(on_mk_media_source_regist cb, void* user_data) { _on_regist = cb; _on_regist_data = user_data; } // 观看总人数 int totalReaderCount(MediaSource&amp; sender) override { return _channel-&gt;totalReaderCount(); } void mk_media_input_h264(void* data, int len, uint32_t dts, uint32_t pts) { _channel-&gt;inputH264((char*)data, len, dts, pts); } void mk_media_input_h265(void* data, int len, uint32_t dts, uint32_t pts) { _channel-&gt;inputH265((char*)data, len, dts, pts); } void mk_media_input_aac(void* data, int len, uint32_t dts, void* adts) { _channel-&gt;inputAAC((char*)data, len, dts, (char*)adts); } void mk_media_input_pcm(void* data, int len, uint32_t pts) { #ifdef ENABLE_FAAC assert(ctx &amp;&amp; data &amp;&amp; len &gt; 0); MediaHelper::Ptr* obj = (MediaHelper::Ptr*) ctx; (*obj)-&gt;getChannel()-&gt;inputPCM((char*)data, len, pts); #else WarnL << "aac编码未启用,该方法无效,编译时请打开ENABLE_FAAC选项"; #endif //ENABLE_FAAC } void mk_media_input_audio(void* data, int len, uint32_t dts) { _channel-&gt;inputAudio((char*)data, len, dts); } protected: // 通知其停止推流 bool close(MediaSource&amp; sender, bool force) override { if (!force &amp;&amp; _channel-&gt;totalReaderCount()) { //非强制关闭且正有人在观看该视频 return false; } if (!_on_close) { //未设置回调，没法关闭 WarnL << "请使用mk_media_set_on_close函数设置回调函数!"; return false; } //请在回调中调用mk_media_release函数释放资源,否则MediaSource::close()操作不会生效 _on_close(_on_close_data); WarnL << "close media:" << sender.getSchema() << "/" << sender.getVhost() << "/" << sender.getApp() << "/" << sender.getId() << " " << force; return true; } bool seekTo(MediaSource&amp; sender, uint32_t ui32Stamp) override { if (!_on_seek) { return false; } return _on_seek(_on_seek_data, ui32Stamp); } void onRegist(MediaSource&amp; sender, bool regist) override { if (_on_regist) { _on_regist(_on_regist_data, &amp;sender, regist); } } private: DevChannel::Ptr _channel; on_mk_media_close _on_close = nullptr; on_mk_media_seek _on_seek = nullptr; on_mk_media_source_regist _on_regist = nullptr; void* _on_seek_data; void* _on_close_data; void* _on_regist_data; };

**Comment by andrewli2** [comment]
我对使用Devchannel也感兴趣， 这两天调试了一下你最初的程序。好像你的code的问题是general的错误，跟ZLMedia无关。
简化成下面这样也会出错：
//thread.cpp 
//g++ thread.cpp -o tt -lpthread
#include <iostream>
#include <chrono>
#include <thread>
void m_send_fream()
{
  	while(1){
            std::cout <<"m_send_fream\n";
            std::this_thread::sleep_for(std::chrono::milliseconds(400));
    }
}
void on_new_stream()
{
    std::thread thrd(m_send_fream);
}
int main()
{
	on_new_stream();
        //std::thread thrd(m_send_fream);
	while (1)
            std::this_thread::sleep_for(std::chrono::milliseconds(400));
    return 0;
}

问题出在main()调用on_new_stream（）后立即返回， on_new_stream中的thrd会被丢弃而引起crash错误。
在main()里直接std::thread thrd(&m_send_fream, args);就不会出错,like this
int main()
{
	//on_new_stream();
        std::thread thrd(m_send_fream);
	while (1)
            std::this_thread::sleep_for(std::chrono::milliseconds(400));
    return 0;
}
知道错误在哪里，我想你应该知道怎么修改了。

**Comment by andrewli2** [comment]
3 includes like this：
#include iostream
#include chrono
#include thread

**Comment by andrewli2** [comment]
顺便感谢 xia-chu的奉献！

**Comment by xia-chu** [comment]
> 我对使用Devchannel也感兴趣， 这两天调试了一下你最初的程序。好像你的code的问题是general的错误，跟ZLMedia无关。
> 
> 简化成下面这样也会出错：
> 
> //thread.cpp 
> 
> //g++ thread.cpp -o tt -lpthread
> 
> #include <iostream>
> 
> #include <chrono>
> 
> #include <thread>
> 
> void m_send_fream()
> 
> {
> 
>   	while(1){
> 
>             std::cout <<"m_send_fream\n";
> 
>             std::this_thread::sleep_for(std::chrono::milliseconds(400));
> 
>     }
> 
> }
> 
> void on_new_stream()
> 
> {
> 
>     std::thread thrd(m_send_fream);
> 
> }
> 
> int main()
> 
> {
> 
> 	on_new_stream();
> 
>         //std::thread thrd(m_send_fream);
> 
> 	while (1)
> 
>             std::this_thread::sleep_for(std::chrono::milliseconds(400));
> 
>     return 0;
> 
> }
> 
> 
> 
> 问题出在main()调用on_new_stream（）后立即返回， on_new_stream中的thrd会被丢弃而引起crash错误。
> 
> 在main()里直接std::thread thrd(&m_send_fream, args);就不会出错,like this
> 
> int main()
> 
> {
> 
> 	//on_new_stream();
> 
>         std::thread thrd(m_send_fream);
> 
> 	while (1)
> 
>             std::this_thread::sleep_for(std::chrono::milliseconds(400));
> 
>     return 0;
> 
> }
> 
> 知道错误在哪里，我想你应该知道怎么修改了。

是的 这个thread不是deatch的 所以在函数返回时 对象销毁了 但是又没thread join 所以会出现异常

**Comment by double7123456** [comment]
我想andrewli2 应该没有看问题吧，  我在是创建Devchannel的时候导致程序崩溃的，不过还是谢谢大家，我想我找到问题的所在了。问题应该是Devchannel中的一些预编译宏导致的，在xia-chu的C API中由于使用的全部是xia-chu编译的Devchannel，所以预编译宏是一样的，Devchannel的在内存中的大小也是一样的，所以我直接使用C API是没有问题的，但是我的代码在编译的时候由于没有定义这些宏，导致Devchannel的大小和原本的大小不对，所以在使用的过程中stream_id的长度可能会导致程序崩溃，这两天我测试了下，将我代码中的Devchannel变大，就可以解决这个问题

**Comment by xia-chu** [comment]
嗯 这个确实也会导致这个问题 所在设计api时 还是要避免暴露构造函数 用工厂模式创建对象 就不会有这个问题了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: double7123456 <notifications@github.com&gt;
发送时间: 2020年11月9日 09:17
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] DevChannel问题，请求一个正确的demo (#554)

**Comment by double7123456** [comment]
我发上来的代码只是一个简单的测试demo，在测试过程中也没有发现你们所说的问题 ，因为线程并没有结束，只是对象被析构了
，所以线程依然能够正常的运行。但这个并不是只要的BUG。在我们的正式程序中是没有这个问题的。
主要问题还是在Devchannel中的一些宏定义，导致使用过程中Devchannel的大小不一样，而出现在创建Devchannel的时候会出现段错误。

**Comment by xia-chu** [comment]
所以一般来说  宏定义不能蔓延到头文件。第三方库的C++对象也尽量不要在库之外的工程创建他的栈变量。
所以还是建议大家用c api，或者直接在zlm的工程内部开发。

**Comment by double7123456** [comment]
建议xia-chu 可以将这些用尽量迁移到CPP文件中。这里感谢 xia-chu的贡献

**Comment by xia-chu** [comment]
倒是把构造函数私有化 加个工厂函数就行了

**Comment by double7123456** [comment]
嗯  谢谢 @xia-chu

**Comment by andrewli2** [comment]
@double7123456 
根据我调试的经历，还是有必要澄清一下：
你说"发上来的代码只是一个简单的测试demo，在测试过程中也没有发现你们所说的问题 ，因为线程并没有结束，只是对象被析构了，所以线程依然能够正常的运行".
我不知道你如何做到的，但我在Ubuntu20.01/g++9.3.0下每次运行你的最开始的demo和我自己简化了的demo，都会crash。我刚刚又重新编译/运行并确认了。所以我调试的结论，就是因为创建thread的函数立即返回造成的。去除这个bug后(注释掉你的demo里boost::thread thrd(&m_send_fream, args);这一行)，把demo.cpp放在tests/目录下编译测试则运行正常，不会crash，没有你说的“Devchannel中的一些宏定义，导致使用过程中Devchannel的大小不一样”这样的问题。
总结：crash是因为thread thrd() 错误造成，与“Devchannel中的一些宏定义“没有关系。用你自己最开始的demo，还有我简化的demo程序很容易验证。

**Comment by double7123456** [comment]
@andrewli2 你没看懂我说的什意思，  我的代码还没有执行到创建线程的哪一行程序已经崩溃了，所以就不可能是哪线程变量被析构的问题，压根就还没创建他就崩溃了。

**Comment by andrewli2** [comment]
我们俩是不是在说同一个程序？
我说的自始至终都是你在本帖最开始贴出的程序。此程序已经很完整了。我基本不用修改，copy/paste as ./tests/test_deviceServer.cpp,
then:
cd build
cmake ..
make clean
make -j8
../release/linux/Debug/test_deviceServer
能够正常运行，哪里有你说的“ 我的代码还没有执行到创建线程的哪一行程序已经崩溃了”？
如果这个demo不做任何修改，在另一个cmdline窗口里运行  ffplay  rtmp://127.0.0.1/live/0， 就会crash。因为运行到了这一行。
如果注释掉你的demo里boost::thread thrd(&m_send_fream, args);这一行，就不会crash。
所以，我测试的结果，crash唯一的原因，就是这一句。
我已经在刚刚验证过了。与其争论，你自己能不能再次测试一下自己的这个demo？你编译运行我的demo又是什么结果？只有区区十几行代码，编译运行很容易。

**Comment by double7123456** [comment]
@andrewli2 代码中确实有你说的问题，但是，我问的问题和那个并没有任何关系。还有
	boost::thread thrd(&m_send_fream, args);
这行代码中的 thrd只是一个线程的句柄，他的释放并不会影响到线程的执行，下面是测试结果
```
void m_send_fream()
{
	for (int i = 0; i < 10; i++)
	{
		sleep(1);
		printf("test :%d\n", i);
	}
	return;
}

int main()
{
	{
		boost::thread thrd(&m_send_fream);
	}
	sleep(5);
	return 0;
}
```
下面是程序输出
```
[root@localhost Release]# ./zltest.out 
test :0
test :1
test :2
test :3
test :4
[root@localhost Release]# 
```

**Comment by andrewli2** [comment]
我不熟悉boost，我编译你boost::thread语句会出错，所以我用std::thred,不知道这是不是引起我们看到的结果不一致的原因。
我用std::thread()相似程序会crash。
你的上面程序改成下面这样,会怎样？
void m_send_fream()
{
	for (int i = 0; i < 10; i++)
	{
		sleep(1);
		printf("test :%d\n", i);
	}
	return;
}
void test()
	{
		boost::thread thrd(&m_send_fream);
	}

int main()
{
       test();
	sleep(5);
	return 0;
}

**Comment by double7123456** [comment]
@andrewli2 首先我自己的demo都是我自己测试过才发出来的，才发出来的，这是一个程序猿基本的准则，也是对作者的尊重。然后我不知道你有没有了解过编译时宏，这个东西只是在编译时才会添加，其次我们是在讨论问题，希望你能心平气和。
下面是我用c实现的代码
```

#include<iostream>
#include<pthread.h>
#include<stdlib.h>
#include<stdio.h>
#include<inttypes.h>
#include <unistd.h>
using namespace std;


void* m_send_fream(void* arg) {
	for (int i = 0; i < 10; i++)
	{
		sleep(1);
		printf("test :%d\n", i);
	}
	return NULL;
}

void test()
{
	pthread_t tid;
	pthread_create(&tid, NULL, m_send_fream, NULL);
	return;
}

int main(int argc, char* argv[]) {
	test();
	sleep(5);
	return 0;
}
```
下面是编译和程序输出
```
[root@localhost zltest]# g++ mian.cpp  -lpthread
[root@localhost zltest]# ./a.out 
test :0
test :1
test :2
test :3
```

**Comment by double7123456** [comment]
@andrewli2 我知道你的问题出在哪里了，
我使用的是BOOST 和C的创建线程，不会出现线程句柄被释放时影响到线程本身，但是C++的却会
https://www.cnblogs.com/5iedu/p/11660039.html
这篇文章上有说明
下面是测试代码
```

#include<iostream>
#include<pthread.h>
#include<stdlib.h>
#include<stdio.h>
#include<inttypes.h>
#include <unistd.h>
#include <thread>
using namespace std;


void m_send_fream(int n) {
	for (int i = 0; i < 10; i++)
	{
		sleep(1);
		printf("test :%d\n", i);
	}
	return ;
}
//std::thread *t2;
void test()
{
	//pthread_t tid;
	//pthread_create(&tid, NULL, m_send_fream, NULL);
	//t2 = new std::thread(m_send_fream,1);
	std::thread t2(m_send_fream, 1);
	t2.detach();
	printf("test :%d\n", 1);
	return;
}

int main(int argc, char* argv[]) {
	test();
	printf("test :%d\n", 1);
	sleep(5);
	printf("test :%d\n", 1);
	return 0;
}
```
下面是输出
```
[root@localhost zltest]# g++ mian.cpp  -lpthread
[root@localhost zltest]# ./a.out 
test :1
test :1
test :0
test :1
test :2
test :3
test :1
[root@localhost zltest]# 
```
 在c++创建线程中  需要显示调用detach，将线程对象于线程分割开，在释放线程对象的时候线程才不会被影响

**Comment by double7123456** [comment]
@andrewli2  这个东西以前用过，后边用大多都用的 c 和 boost 的，好久没用，完忘记了······

**Comment by andrewli2** [comment]
我确实有点急，对不起! 我们来这里是为澄清问题，互相帮助。
我们还是集中在C++和你的demo为啥crash。好像不用再去讨论c/pthread_create()。
我还是想知道我上面的代码你能否正确运行？如果使用std::thread()结果又如何？
还有我刚才问过的，你最初的demo，按我刚才的方法，放在tests目录下编译运行如何？换成使用std::thread()结果又如何？
你刚刚给出的代码，没有t2.detach();是不是会crash？你的demo里是没有t2.detach();这一句的。

**Comment by double7123456** [comment]
@andrewli2 你的代码肯定不能正常运行，因为在C++中的std::thread()对象是和线程绑定的，所以在std::thread()对象被析构的时候，线程也会被释放，所以你运行是就会出错，可以通过std::thread()对象的detach，将他们分开。在我上面的测试demo中如果不使用detach，也会崩溃。
在你的环境下就不会出错了。因为你多半是在ZLMediaKit的目录下编译的吧。编译时宏用的应该和ZLMediaKit库的宏是一样的，所以没有问题。
但是在我的环境下，没有使用一些编译时宏，所在就会出错。
下面是我写的一个编译时宏的demo，你可以把它设想成一个库文件，宏是定义在头文件中的，然后我们去使用这个库文件。或者你也可以自己写一个静态库测试一下
代码
```
class test_class 
{
public:
#ifdef DEBUG
	int value1;
#endif
public :
	int value;
};

int main()
{
	printf("test_class size:%d\n",sizeof(test_class));
	return 0;
}
````
下面是编译个输出
```
[root@localhost zltest]# g++ -DDEBUG mian.cpp  -lpthread
[root@localhost zltest]# ./a.out 
test_class size:8
[root@localhost zltest]# g++ mian.cpp  -lpthread
[root@localhost zltest]# ./a.out 
test_class size:4
[root@localhost zltest]# 
```
可以明显的看到 在使用DEBUG宏和不使用DEBUG和的时候，他们的程序中的大小是不一样的，所以我们在使用的情况下就不好把握。

然后我使用DevChannel的时候的问题就是
在我编译ZLMediaKit的时候不知道有定义了那些预编译宏，所以我在DevChannel使用的时候用的是DevChannel的头文件，就可能出现我程序中的DevChannel大小和库中的DevChannel大小不一样，导致程序创建的DevChannel不正确，导致程序崩溃。

**Comment by andrewli2** [comment]
我认为我们俩的根本的不一致还是：什么引起了你demo程序的crash？你说“ 我的代码还没有执行到创建线程的哪一行程序已经崩溃了”，我看到的是运行那一行之前程序完全正常。注释掉那一行之后程序根本不会crash。

**Comment by andrewli2** [comment]
刚刚看到你最后的发言，大概明白你的程序为啥crash了。我可以说是你编译方法不对造成的麻烦。
tests/目录下的例子就不会出这样的错。而且，如我上面所说，把你的demo放在tests/下面，编译出的程序也不会出错。
不用Cmake，我自己搞了个Makefile，编译我自己的程序和你的demo，也没有错。

**Comment by double7123456** [comment]
@andrewli2 
首先我们之间的问题有两个
1，你使用的开启线程函数之所以会崩溃是因为你没有调用线程分类函数。或者说释放了正常使用的线程

2，编译环境的问题，上面我有说到，你编译时应该使用的是ZLMediaKit的编译环境，或者你在编译ZLMediaKit的时候，关闭了关于DevChannel的所有编译时宏，所有你在使用DevChannel的时候，就不会出现 使用的DevChannel的大小和 ZLMediaKit库中的大小不一致的情况，所有是没有问题的。
但是我在编译我的demo的时候没有添加编译时宏，也没有使用ZLMediaKit的cmake，所有就出现了在我使用的DevChannel的大小和ZLMediaKit库中的大小不一样，这是一个非常不好的情况。
就向我上面的demo代码中，我将test_class封装成一个静态库，在头文件中定义DEBUG，编译这个库的时候我使用DEBUG宏，
然后我在代码中使用这个库，但是我编译代码时不使用DEBUG宏，
就会出现我使用的是4个字节的test_class，而库中的test_class大小确实8个字节，如果库中的test_class刚好有调用一个函数使用到了value1，（这个变量只用在定义了DEBUG宏的时候才会有），那么程序就会崩溃。

**Comment by andrewli2** [comment]
所以，我说是你编译方法不对。你使用和编译库时不一致的编译选项，当然会出错。

**Comment by andrewli2** [comment]
我同意你说的我们看到的crash起因不同。我看到的crash是使用std::thread而又没有调用thread.detatch().你的crash则是因为编译选项与库所使用的选项不一致造成的。
你的程序如果放在tests/目录下与其他test例子一起编译，应该能够正确运行。至少不会crash。

**Comment by andrewli2** [comment]
因为CMake会为库和测试程序生成完全相同的编译选项。
我想我们总算把这个问题搞清楚了。

**Comment by double7123456** [comment]
@andrewli2 嗯 确实是这样的，但是我并没有把ZLMediaKit的编译宏找全，所有没法正确的编译库，正如xia-chu所说的，如果使用工厂模式就不会出现这个问题了

**Comment by andrewli2** [comment]
谢谢double7123456。你的demo对我很有启发，虽然你在问有没有相关demo，其实你已经给出了一个相当完整的deviceChannel的例子。
我调试你这个demo的经验是：需要这样生成devchannel_：
devchannel_ = make_shared<DevChannel>(myarg._host, myarg._app, myarg._streamid, 0, true, true, true, false);
最后的四个参数分别对应bool enable_rtsp, bool enable_rtmp, bool enable_hls, bool enable_mp4，取决于你想使能那些服务器。
因为：
//DevChannel::DevChannel(const string &vhost, const string &app, const string &stream_id, float duration, bool enable_rtsp, bool enable_rtmp, bool enable_hls, bool enable_mp4) :

另外，在初始化完成以后，你的那个thread开始输出数据之前，应该：
 devchannel_->addTrackCompleted();
用来通知mediaSource regist。
加上以上两个，你的demo就可以基本跑起来了。
你的正式程序想来已经都有这些了。

**Comment by andrewli2** [comment]
既然说到了std::pthread,顺便分享一下我的一个与std::thread相关的编译ZLMedia静态程序经验。
如果你碰巧要编译一个静态链接的使用ZLmedia库的程序，即使用-static -lpthread选项编译生成最后程序，ZLMedia现有的编译方法生成的程序不能正常运行。原因在于g++编译器有bug， 参考：
 https://stackoverflow.com/questions/9002264/starting-a-stdthread-with-static-linking-causes-segmentation-fault
解决此问题的workaround：
要这样使用编译选项： -Wl,--whole-archive -lpthread -Wl,--no-whole-archive
而不是仅仅 -lpthread
直到现在的gcc9、gcc10还有这个问题。上面链接里有很简单的程序可以测试。
因为必须静态编译，我几乎放弃ZLMedia，直到偶然发现这个workaround。
