### ISSUE TITLE
大华网络摄像机  无有效负载的rtp包

### ISSUE THREAD

**Issue by Wizzercn** [xia-chu/ZLMediaKit#555]
mediakit::RtpReceiver::handleOneRtp 无有效负载的rtp包:542 <= 49380

**Comment by xia-chu** [comment]
忽略这个日志就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wizzer <notifications@github.com&gt;
发送时间: 2020年11月5日 10:19
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 大华网络摄像机  无有效负载的rtp包 (#555)





 
mediakit::RtpReceiver::handleOneRtp 无有效负载的rtp包:542 <= 49380

**Comment by Wizzercn** [comment]
@xia-chu 但是 /index/api/getMediaList 接口，获取不到内容

**Comment by xia-chu** [comment]
那说明是另外的异常



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wizzer <notifications@github.com&gt;
发送时间: 2020年11月5日 10:33
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 大华网络摄像机  无有效负载的rtp包 (#555)





 
@xia-chu 但是 /index/api/getMediaList 接口，获取不到内容

**Comment by Wizzercn** [comment]
![image](https://user-images.githubusercontent.com/2408114/98191006-39f47200-1f53-11eb-8e64-bf872e4f8f95.png)
帮看一下摄像机配置，注册密码不知道填啥，不知道是不是这个原因。谢谢哈~

**Comment by Wizzercn** [comment]
@xia-chu 打扰一下，上一条，麻烦了~

**Comment by xia-chu** [comment]
你应该吧ZLMediaKit的完整日志粘贴上来

**Comment by Wizzercn** [comment]
```
MediaServer.exe(5840) Z:\git\ZLMediaKit\src\Rtsp\RtpReceiver.cpp 121
2020-11-05 13:45:00.529 W | mediakit::RtpReceiver::handleOneRtp 无有效负载的rtp包:542 <= 49380
MediaServer.exe(5840) Z:\git\ZLMediaKit\src\Rtsp\RtpReceiver.cpp 121
2020-11-05 13:45:04.721 W | mediakit::RtpReceiver::handleOneRtp 无有效负载的rtp包:542 <= 49380
MediaServer.exe(5840) Z:\git\ZLMediaKit\src\Rtsp\RtpReceiver.cpp 121
2020-11-05 13:45:08.923 W | mediakit::RtpReceiver::handleOneRtp 无有效负载的rtp包:542 <= 49380
MediaServer.exe(5840) Z:\git\ZLMediaKit\src\Rtsp\RtpReceiver.cpp 121
2020-11-05 13:45:13.125 W | mediakit::RtpReceiver::handleOneRtp 无有效负载的rtp包:542 <= 49380
MediaServer.exe(5840) Z:\git\ZLMediaKit\src\Http\HttpSession.cpp 45
```

**Comment by xia-chu** [comment]
你可以更新下代码 你代码有点老
