### ISSUE TITLE
关于自适应码率

### ISSUE THREAD

**Issue by jim-king-2000** [xia-chu/ZLMediaKit#556]
亲，咱的服务器支持自适应码率么？

**Comment by xia-chu** [comment]
流媒体服务器没这个功能 因为流媒体服务器不编码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2020年11月6日 16:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 关于自适应码率 (#556)





 
亲，咱的服务器支持自适应码率么？

**Comment by jim-king-2000** [comment]
好的，了解了。谢谢亲。
