### ISSUE TITLE
流媒体服务器BUG

### ISSUE THREAD

**Issue by sunhui2013** [xia-chu/ZLMediaKit#557]
CentOS7上，使用最新版本，测试有一下问题：
1、播放RTSP时候，找不到流，提示是找不到RTMP的流；
2、在推流后不自动生成TS文件，需要拉HLS流才生成，这个时候播放时间比较长；

**Comment by xia-chu** [comment]
第二个问题是设计使然 本来就是这样设计的。
第一个问题 你以粘贴下你的日志 否则没法分析

**Comment by xia-chu** [comment]
????? 啥情况？

**Comment by xia-chu** [comment]
第二位优化了
配置文件选项general.hls_demand置0
