### ISSUE TITLE
.m3u8中的vhost=__defaultVhost__是否可以在enableVhost=0的时候，取消？

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#560]
.m3u8中ts的名称：
2020-11-05/18/57-05_0.ts?vhost=__defaultVhost__
配置文件 enableVhost=0的时候，是否可以不显示vhost

代码修改如下：
Recorder.cpp ::createRecorder()函数中
···
            GET_CONFIG(bool, enableVhost, General::kEnableVhost);
	    string params = enableVhost ? (string(VHOST_KEY) + "=" + vhost) : "";
            auto ret = std::make_shared<HlsRecorder>(path, params);
           //old  
           auto ret = std::make_shared<HlsRecorder>(path, string(VHOST_KEY) + "=" + vhost);
···

**Comment by xia-chu** [comment]
这个又不影响什么  你把vhost参数去掉了 后面如果开启了vhost，你就没法访问 了

**Comment by xia-chu** [comment]
其实你说的那样好像没问题

**Comment by xia-chu** [comment]
已实现
