### ISSUE TITLE
HlsPlayer在拉流时，未能根据返回的结果判断连接断开，同时无法正确调用onPlayResult

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#561]
HlsPlayer拉流时，如果服务端关闭，HlsPlayer没有调用onPlayResult返回失败并重试

### 1.HlsPlayer::onDisconnect()未回调onPlayResult
正常状态下Http超时也会调用HlsPlayer::onDisconnect函数，之后调用playDelay()重新下载m3u8。
ex.getErrCode()是Err_timeout，
ex.what()是 “http request time out".

HlsPlayer::onDisconnect()函数在服务端停止服务时，同样会被调用。
ex.getErrCode()是Err_timeout，
ex.what()) 是 string("connection timed out")
此时的处理还是重新下载m3u8，未调用onPlayResult进行出错处理。

### 2.PlayerBase.cpp中onPlayResult将 _playResultCB 置空，导致回调失败
```
void onPlayResult(const SockException &ex) override {
        if(_playResultCB) {
            _playResultCB(ex);
           //_playResultCB = nullptr; //_playResultCB 被置空
        }
    }
```

产生的结果就是：如果hls开始的时候播放是正常的， 播放过程中服务器关闭，播放失败，不会回调上层PlayerProxy的onPlayResult()，不能由上层进行重试、换URL等操作。PlayerProxy完全不知道下面连接不上。

**建议：**
### 1.在HlsPlayer::onDisconnect()函数添加对连接断开的处理
（暂时没有想到更好的区分方法）
```
if(string(ex.what()) == string("connection timed out"))
	onPlayResult(ex);
```

### 2.PlayerBase.cpp中
_playResultCB 不要置空

不知道这个修改是否会影响到别的逻辑。

**Comment by xia-chu** [comment]
hls播放器不太好做 短链接没长链接明确 你看ffplay ，播放hls时，服务器服务器返回404，ffplay会一直尝试访问。
可以交个重试次数，重试失败多少次了就回调错误上去
