### ISSUE TITLE
关于iOS移动端的咨询

### ISSUE THREAD

**Issue by zhuozhuo** [xia-chu/ZLMediaKit#562]
楼主非常感谢你的开源，找了很长时间才找到一个不错的开源库，再次感谢。我看了issue有人提问能否用于iOS 移动端进行开发，我看到你说可以，由于我是用于iOS的ReplayKit中，ReplayKit对内存限制非常严格，不能超过50M，我想咨询下，您或者其他人有没有成功的iOS案例Demo呢？

**Comment by xia-chu** [comment]
你在ios搞服务器还是推流客户端？还是录制文件？

**Comment by zhuozhuo** [comment]
推流客户端。

**Comment by xia-chu** [comment]
推流客户端相当多了 你没必要用zlm

**Comment by zhuozhuo** [comment]
嗯，RTMP的倒是挺多写了个也不错，不过支持RTSP的还真没找到..

**Comment by xia-chu** [comment]
你把c sdk编译成静态库 ，ios在链接时 只会用到里面用到的代码 所以其实没多大的
