### ISSUE TITLE
GB推流后显示时间过长问题

### ISSUE THREAD

**Issue by sunhui2013** [xia-chu/ZLMediaKit#563]
在国标推PS流时候，第一次开流时间过长，经过定位发现是checkTrackIfReady函数中，等待时间过长；
在ps流中有可能只有视频或者只有音频：

//如果添加Track，最多等待5秒
#define MAX_WAIT_MS_ADD_TRACK 1000     

 if(_track_map.size() == 1 && _ticker.elapsedTime() > MAX_WAIT_MS_ADD_TRACK){
            //如果只有一个Track，那么在该Track添加后，我们最多还等待若干时间(可能后面还会添加Track)
            emitAllTrackReady();
            return;
        }
修改后时间缩短，这块逻辑是否可以优化

**Comment by xia-chu** [comment]
你可以根据自己需求调整下 这个参数也算经验值 有些情况下 会调用addTrackComplete 所以也不会等这么久 28181推流 这个不好判断到底有多少个Track 只能超时法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunny <notifications@github.com&gt;
发送时间: 2020年11月10日 10:02
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] GB推流后显示时间过长问题 (#563)
