### ISSUE TITLE
推流无法生成对应hls

### ISSUE THREAD

**Issue by back0893** [xia-chu/ZLMediaKit#566]
![图片](https://user-images.githubusercontent.com/16218781/98681923-3f601b00-239e-11eb-8c42-8217d4a7af69.png)
![图片](https://user-images.githubusercontent.com/16218781/98681965-4b4bdd00-239e-11eb-967a-b8acd5288f3c.png)
![图片](https://user-images.githubusercontent.com/16218781/98682053-6880ab80-239e-11eb-9fec-f847714167f1.png)
默认的配置生成hls,但是在http服务器下的rtp没有对应的m3u8文件

使用的是最新的master分支

**Comment by xia-chu** [comment]
因为zlm现在支持的协议有点多了 我全部改成了按需生成 也就是有人访问时才生成或转协议

**Comment by xia-chu** [comment]
否则全部转协议浪费cpu 而单个配置又加大开发者负担

**Comment by xia-chu** [comment]
后面打算做个通用配置项 打开后 所有协议都无时无刻都转换
但是这样cpu有些浪费 但是体验却好很多 因为按需转协议第一次播放可能存在打开慢且花屏的问题

**Comment by back0893** [comment]
按需生成,但是我依据url规则拼写 ip/rtp/streamId
也没有触发hls的按需播放,rtmp和rtsp是看的.
是我的hls的url错误么.

**Comment by xia-chu** [comment]
请看wiki url规则篇



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: back0893 <notifications@github.com&gt;
发送时间: 2020年11月10日 23:40
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 推流无法生成对应hls (#566)





 
按需生成,但是我依据url规则拼写 ip/rtp/streamId
 也没有触发hls的按需播放,rtmp和rtsp是看的.
 是我的hls的url错误么.

**Comment by back0893** [comment]
好的.我去试试

**Comment by back0893** [comment]
哦,原来是这样的.
因为旧版本会自动生成,所以在http下可以看下到.
现在需要去访问完整的hls的地址才可以

**Comment by xia-chu** [comment]
现在加了配置项了，请置general.hls_demand为0就行
