### ISSUE TITLE
请教关于 C++ 接口多线程安全的问题

### ISSUE THREAD

**Issue by chuyue86** [xia-chu/ZLMediaKit#567]
最近在用 C++ 做二次开发，接口的线程安全问题比较困扰。
所以请教关于 MediaPusher/PlayerProxy/MediaSource 等几个比较关键的类，接口的多线程安全设计，是否有一致的标准（或者有相关的文档或注释可以说明）？
现在我主要是参考 C API 的实现，或者是直接阅读代码来确定线程的安全特性，有时比较繁琐

**Comment by xia-chu** [comment]
线程安全的核心要素就是，确保这个对象生命周期内，只有一条线程操作。

**Comment by xia-chu** [comment]
当然，构造和析构其实都是线程安全的，可以在其他线程调用。
析构的线程在使用shared_ptr时是线程安全的，但是你用裸指针，也要确保析构的线程安全

**Comment by xia-chu** [comment]
zlm里面 TCPSession类是绑定Poller线程的，它的生命周期内，只有一个线程操作它(其他线程操作时要切换到它的线程)。
比较棘手的是全局变量的线程安全问题，比如说单例，这个一般用锁保护。
其他情况下，例如MultiMediaSourceMuxer这种对象，它可能通过http api多线程操作它，但是你看见我也没用锁，我是通过拷贝智能智能确保线程安全。

**Comment by xia-chu** [comment]
有些情况下 不用锁 多线程下 也能做到线程安全 我一般借助智能指针拷贝时的原子性来确保

**Comment by xia-chu** [comment]
线程安全是门难题 要自己清醒的知道 哪些函数是单线程操作的 哪些是多线程的 针对不同的情况做不同的处理
