### ISSUE TITLE
index/api/startRecord 录像保存路径

### ISSUE THREAD

**Issue by qianyouqr** [xia-chu/ZLMediaKit#568]
您好，请教您一个问题：index/api/startRecord 这个API 的参数customized_path 可以是本地的路径吗？不是的话，怎么录制的视频保存到本地

**Comment by xia-chu** [comment]
customized_path是本地路径，相当于覆盖配置文件中的record.filePath和hls.filePath

**Comment by qianyouqr** [comment]
谢谢
