### ISSUE TITLE
gb28181多端口openRtpServer方法bug

### ISSUE THREAD

**Issue by qinqi** [xia-chu/ZLMediaKit#570]
当前方法貌似是未判断端口是否正在使用或已创建而导致会重复创建端口，如图：
![image](https://user-images.githubusercontent.com/5306217/99038607-bc6ada80-25c0-11eb-91df-a0a5eca736ee.png)

**Comment by xia-chu** [comment]
这个问题不存在啊，我的代码是会去重的：
<img width="748" alt="图片" src="https://user-images.githubusercontent.com/11495632/99151446-2b862300-26d6-11eb-8328-636a51aea370.png">

**Comment by qinqi** [comment]
但是出现我这种情况，是怎么造成的呀？可能是同时并发造成的？

**Comment by qinqi** [comment]
而且在现场环境很容易出现这样同端口的问题。。

**Comment by xia-chu** [comment]
端口重复的问题我测试过啊 应该是不会触发的。

**Comment by qinqi** [comment]
难道是我版本问题~？我更下最新版版本再试一下~

**Comment by zhang2349** [comment]
他这是流id不同  端口相同   端口是自己指定的吗？

**Comment by qinqi** [comment]
并不是 直接传0返回的端口

**Comment by xia-chu** [comment]
我猜是端口已经释放了 但是zlm却不知道而已

**Comment by qinqi** [comment]
没存储，我估计是我同时拉比如10路，并发了，然后可能有2~3个请求同时访问了openRtpServer接口，估计zlm没反应过来就给我返回了相同的接口。

**Comment by qinqi** [comment]
估计我得做个存储，来自己分配端口，解决并发这个问题

**Comment by xia-chu** [comment]
> 我估计是我同时拉比如10路，并发了，然后可能有2~3个请求同时访问了openRtpServer接口

应该不会的 分配端口是原子的 不会出现你说的 但是可能有个端口已经关闭了 zlm不知道而已

**Comment by qinqi** [comment]
这就不知道了。。应该没断过流端口应该也不会关闭。。我再查查是什么原因造成的

**Comment by xia-chu** [comment]
先关闭issue了 后面有新反馈 在这说就行了 谢谢
