### ISSUE TITLE
gb28181推流，播放器异常断开，报“rtp包长度异常，发送端可能缓存溢出并覆盖”

### ISSUE THREAD

**Issue by jianjunchang** [xia-chu/ZLMediaKit#571]
大神您好：
      最近想用您的媒体服务器接入gb28181设备推送的视频流，发现过一段时间（不一定多久，短则10几秒，长则半个小时）后，播放就断了，直接报错的地方是这里：
![image](https://user-images.githubusercontent.com/6183488/99161178-5e5a0680-272a-11eb-9c83-440146796f4e.png)
我在RtpSession.cpp的onRtpPacket函数里把数据保存了下来（每次进函数保存为一行），观察发现报错原因是从某一个行开始没有了正确的包头，这个包头出现在上一行的末尾。
类似于这样：
80 60 09 55 08 E7 2B 30 06 14 87 8C 00 00 01 BA ......
80 60 09 56 08 E7 2B 30 06 14 87 8C D1 78 4D B3 ......
80 60 09 57 08 E7 2B 30 06 14 87 8C E2 45 8E 97 ......
80 60 09 58 08 E7 2B 30 06 14 87 8C 7D B8 43 1F ......
80 60 09 59 08 E7 39 40 06 14 87 8C 00 00 01 C0 ......
80 60 09 5A 08 E7 39 40 06 14 87 8C 00 00 01 BA ...... 80 60 09 5B 08 E7 39 40 06 14 87 8C CC AF F8 4F ......
0B F8 49 73 D3 47 5C C7 E8 4F 8F D8 0B 31 6F E8 ...... 80 60 09 5C 08 E7 39 40 06 14 87 8C 57 37 5A ED ...... 80 60 ......
倒数第二行包含了一个完整的rtp包和后边一个残缺的rtp包，最后一行是上一行残缺包的后办部分，在最后一行后边有n个完整包所以长度远远大于程序里的阈值2 * 1024，程序在这里就异常了。
我发现issues中没有人提过这个问题，不知是不是我用的摄像机设置的问题，还是这个摄像机本身发出的包不符合标准协议导致的，希望大神指点一下，谢谢！！！

**Comment by xia-chu** [comment]
摄像头软件有bug 使用了非阻塞socket 但是却不管有没有写入socket成功 导致缓存区溢出



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianjunchang <notifications@github.com&gt;
发送时间: 2020年11月15日 10:29
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] gb28181推流，播放器异常断开，报“rtp包长度异常，发送端可能缓存溢出并覆盖” (#571)





 
大神您好：
 最近想用您的媒体服务器接入gb28181设备推送的视频流，发现过一段时间（不一定多久，短则10几秒，长则半个小时）后，播放就断了，直接报错的地方是这里：
 
 我在RtpSession.cpp的onRtpPacket函数里把数据保存了下来（每次进函数保存为一行），观察发现报错原因是从某一个行开始没有了正确的包头，这个包头出现在上一行的末尾。
 类似于这样：
 80 60 09 55 08 E7 2B 30 06 14 87 8C 00 00 01 BA ......
 80 60 09 56 08 E7 2B 30 06 14 87 8C D1 78 4D B3 ......
 80 60 09 57 08 E7 2B 30 06 14 87 8C E2 45 8E 97 ......
 80 60 09 58 08 E7 2B 30 06 14 87 8C 7D B8 43 1F ......
 80 60 09 59 08 E7 39 40 06 14 87 8C 00 00 01 C0 ......
 80 60 09 5A 08 E7 39 40 06 14 87 8C 00 00 01 BA ...... 80 60 09 5B 08 E7 39 40 06 14 87 8C CC AF F8 4F ......
 0B F8 49 73 D3 47 5C C7 E8 4F 8F D8 0B 31 6F E8 ...... 80 60 09 5C 08 E7 39 40 06 14 87 8C 57 37 5A ED ...... 80 60 ......
 倒数第二行包含了一个完整的rtp包和后边一个残缺的rtp包，最后一行是上一行残缺包的后办部分，在最后一行后边有n个完整包所以长度远远大于程序里的阈值2 * 1024，程序在这里就异常了。
 我发现issues中没有人提过这个问题，不知是不是我用的摄像机设置的问题，还是这个摄像机本身发出的包不符合标准协议导致的，希望大神指点一下，谢谢！！！

**Comment by jianjunchang** [comment]
这种情况我该如何应对呢？是不是可以在接收方做个特殊处理？给个建议吧

**Comment by xia-chu** [comment]
tcp上下文破坏了就很难恢复 这是基于长度的分包 不是基于分隔符 所以一般很难恢复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianjunchang <notifications@github.com&gt;
发送时间: 2020年11月15日 11:02
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] gb28181推流，播放器异常断开，报“rtp包长度异常，发送端可能缓存溢出并覆盖” (#571)





 
这种情况我该如何应对呢？是不是可以在接收方做个特殊处理？给个建议吧

**Comment by xia-chu** [comment]
可以换成udp推流 就不会有这个问题 但是udp有丢包问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianjunchang <notifications@github.com&gt;
发送时间: 2020年11月15日 11:02
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] gb28181推流，播放器异常断开，报“rtp包长度异常，发送端可能缓存溢出并覆盖” (#571)





 
这种情况我该如何应对呢？是不是可以在接收方做个特殊处理？给个建议吧

**Comment by jianjunchang** [comment]
👌，我先用udp试试
