### ISSUE TITLE
HLS优化建议

### ISSUE THREAD

**Issue by sunhui2013** [xia-chu/ZLMediaKit#572]
为了缩短HLS开流时间：
第一次生成3个文件使用2s或者更小，然后后面文件使用3s或者配置文件配置时间，有些公司这个做到9s左右显示出来；

**Comment by xia-chu** [comment]
还要看GOP大小 遇到关键帧才能切片的

**Comment by sunhui2013** [comment]
> 还要看GOP大小 遇到关键帧才能切片的

我测试发现2s保存一个TS文件在H5播放时候容易跳帧显得不流畅，正常播放建议使用3s及以上；我使用的是EasyPlayer.js，支持H265播放，使用wasm解码；
