### ISSUE TITLE
/index/api/stopSendRtp支持具体某一个端的推流停止

### ISSUE THREAD

**Issue by yangdon** [xia-chu/ZLMediaKit#573]
提一个小需求

1. 停止推流，支持对具体某一个端的停止推流，这样可以方便实现广播，对每个推流进行控制

2. 查询推流状态，支持查询所有的推流信息

**Comment by xia-chu** [comment]
你说的需求都已经实现了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangdon <notifications@github.com&gt;
发送时间: 2020年11月16日 11:43
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] /index/api/stopSendRtp支持具体某一个端的推流停止 (#573)





 
提一个小需求
  
 
停止推流，支持对具体某一个端的停止推流，这样可以方便实现广播，对每个推流进行控制
 

 
查询推流状态，支持查询所有的推流信息

**Comment by yangdon** [comment]
![image](https://user-images.githubusercontent.com/18587545/99247034-4923cb80-2841-11eb-8beb-cfae1355dd0b.png)
嗯。。。我的意思其实是这个，比如在实现广播发送rtp的时候，可以对每个发送进行管理

**Comment by xia-chu** [comment]
目前一个流只能推一路国标流的 不正常同时对给多个28181服务器
