### ISSUE TITLE
支持GB28181的前端设备录像回放

### ISSUE THREAD

**Issue by guxinyue** [xia-chu/ZLMediaKit#574]
是否考虑支持gb28181的前端设备录像回放

**Comment by zhang2349** [comment]
回放和实时 对流媒体服务 都是一样的
就是回放2倍速 4倍速的话 不知道会怎么样

**Comment by 648540858** [comment]
可以看下wvp,已经实现录象回放

**Comment by xia-chu** [comment]
zlm不关心28181推流是直播还是点播 它不知道

**Comment by tsingeye** [comment]
> 回放和实时 对流媒体服务 都是一样的
> 就是回放2倍速 4倍速的话 不知道会怎么样

2倍 4倍 务必要关闭rtmptimestampmodify

**Comment by xia-chu** [comment]
issue先关闭了 估计楼主也没其他问题了
