### ISSUE TITLE
请问下大家该如何实现按需拉流来实现摄像机的实时画面传输？

### ISSUE THREAD

**Issue by 782662671** [xia-chu/ZLMediaKit#577]
通过按需拉流的方式将我们自己的流转换成FLV/HLS/TS格式输出，摸索了一下午，没有弄明白

**Comment by xia-chu** [comment]
你看过wiki吗

**Comment by 782662671** [comment]
看过wiki了，您的wiki里按需推流有内容，但是按需拉流只有一张ZLMediaKit的logo，我摸索不出来该怎样通过服务器拉摄像机的流并且转换格式输出，请求指教！

**Comment by 782662671** [comment]
今天看按需拉流有那个工作流程图了，我想问一下您就是从播放器发送请求后，查询到该流存在，然后这个从ZLMediaKit至摄像头的开始拉流（支持rtsp/rtmp）要怎么开始？

**Comment by xia-chu** [comment]
播放器播放一个不存在的流时，zlm会触发web hook事件，你的业务服务器收到事件后再调用zlm的接口 让他开始拉流就行了

**Comment by 782662671** [comment]
该怎么调用这个zlm接口啊？我们的问题就处在这...

**Comment by xia-chu** [comment]
非要我把文档贴在你脸上才知道看吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 782662671 <notifications@github.com&gt;
发送时间: 2020年11月20日 15:49
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 请问下大家该如何实现按需拉流来实现摄像机的实时画面传输？ (#577)





 
该怎么调用这个zlm接口啊？我们的问题就处在这...

**Comment by 782662671** [comment]
您指的是wiki里那个restful接口的那个记录api的文档？

**Comment by 782662671** [comment]
我弄好了，谢谢您
