### ISSUE TITLE
test_wsClient 程序返回 bad http status code:400  问题

### ISSUE THREAD

**Issue by devfreq074** [xia-chu/ZLMediaKit#579]
利用nodejs  简易版的server 。

var WebSocketServer = require('ws').Server,
wss = new WebSocketServer({ port: 7272 });
wss.on('connection', function (ws) {
    console.log('client connected');
    ws.send('你是第' + wss.clients.length + '位');  
    ws.on('message', function (message) {
        console.log(message);
    });
    ws.on('close', function(close) {  
      	console.log('退出连接了');  
    });  
});
console.log('开始监听7272端口');

在 http://coolaf.com/tool/chattest  上进行测试，可正常的接收数据。

然后运行test_wsClient 测试程序，127.0.0.1:7272 ，报bad http status code:400 错误。

请问下作者，如何修复此问题呢？谢谢

**Comment by xia-chu** [comment]
你抓个包看看？看看为什么你的服务器返回400

**Comment by wusopp** [comment]
> 你抓个包看看？看看为什么你的服务器返回400

嗯，利用服务器本身的wsclient 和wsServer之间是没问题的。还有我测试websocketpp 连接Zlmediakit 的server 是没问题的。且websocketpp 连接这个nodejs 服务 也没问题。 主要问题是我对这个协议底层实现不熟，见谅见谅。
    我明玩抓个包再研究下，先别关issue。跟着学习zlmediakit，最近总算是入门了，感谢提供这么好的学习资料。

**Comment by devfreq074** [comment]
我今天下午抓个包发现普通的websocket client 和示例中的wsClient 在发送HTTP1.1时，只是普通的多个一个origin字段，不过百度查了下都说是客户端头信息缺失导致的，不过抓包看上去两者发送字段也没什么差别。

而且目前是zl中的wsclient 和zl中的wsServer之间互通没问题，普通的websocket客户端和zl中的wsServer也没问题。
websocketpp 与普通nodejs 互通也没问题。所以现在彻底懵逼了~希望大佬有时间时解救下，


抓包数据

[capture.zip](https://github.com/xia-chu/ZLMediaKit/files/5566984/capture.zip)

过滤条件：
ip.src==192.168.10.74 and  ip.dst == 192.168.10.46

**Comment by devfreq074** [comment]
普通的websocket 做客户端 ，nodejs 做服务端

![11](https://user-images.githubusercontent.com/74637573/99673653-01ef4200-2ab0-11eb-9068-cf030c4bbc3d.png)

![22](https://user-images.githubusercontent.com/74637573/99673657-03b90580-2ab0-11eb-9bec-7e3e79209123.png)


zlmediakit websocket ，nodejs 做服务端

![33](https://user-images.githubusercontent.com/74637573/99673659-04519c00-2ab0-11eb-9d84-73616a3cb504.png)

![44](https://user-images.githubusercontent.com/74637573/99673661-04ea3280-2ab0-11eb-9742-0c7aae7c4976.png)

**Comment by wasphin** [comment]
和 host 端口有没有关系？我看端口用的是 7272，而HOST 中没端口信息

**Comment by xia-chu** [comment]
![image](https://user-images.githubusercontent.com/11495632/99764395-eb8cc900-2b37-11eb-8dde-1363eca0e00c.png)
原因可能是zlm的Host字段没有端口号。
你把ws服务器端口设置80，zlm链接应该就没问题了，这个算是zlm的bug

**Comment by xia-chu** [comment]
应该修复了 试试

**Comment by devfreq074** [comment]
> 应该修复了 试试

多谢大佬，现在已经把所有demo 跑通了

**Comment by xia-chu** [comment]
你效率还是蛮高的！

**Comment by devfreq074** [comment]
> 你效率还是蛮高的！

前前后后，没事时就看这套源码，估计花了好几月时间了，多谢提供这么好的开源代码~

**Comment by xia-chu** [comment]
过奖了 希望能纠正代码注释错误、代码风格不统一、不完美、bug等，然后提交pr，谢谢！
