### ISSUE TITLE
没有推流日志

### ISSUE THREAD

**Issue by reachzxsframe** [xia-chu/ZLMediaKit#580]
调用SIP服务的播放接口后，成功返回ssrc：
{"ssrc":"0102006835"}

此时查看流媒体服务的日志：
2020-11-18 01:50:16.293 D MediaServer[71365] WebApi.cpp:186 operator() | 
# request:
GET /index/api/getMediaList?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&schema=rtmp
# content:

# args:
schema : rtmp
secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
# response:
{
   "code" : 0
}

**Comment by xia-chu** [comment]
嗯 这个时候收到推流了 但是还没解析出什么

**Comment by reachzxsframe** [comment]
感谢您的回复！
现状是这样：
流媒体服务部署在远程linux服务器，
SIP服务部署在本地计算机

进行以下操作：
postman查询设备列表，返回值如下：
[
    {
        "deviceId": "34020000002000000001",
        "name": "37010200492000000001",
        "manufacturer": null,
        "model": null,
        "firmware": null,
        "transport": "UDP",
        "host": {
            "ip": "192.168.1.197",
            "port": 44678,
            "address": "192.168.1.197:44678"
        },
        "online": 1,
        "channelMap": {
            "34020000001340000001": {
                "channelId": "34020000001340000001",
                "name": "Input1",
                "manufacture": "huawei",
                "model": "M2281-QL-MG",
                "owner": "34020000",
                "civilCode": "34020000001340000001",
                "block": null,
                "address": "34020000",
                "parental": 0,
                "parentId": null,
                "safetyWay": 0,
                "registerWay": 1,
                "certNum": null,
                "certifiable": 0,
                "errCode": 0,
                "endTime": null,
                "secrecy": "0",
                "ipAddress": null,
                "port": 0,
                "password": null,
                "status": 0,
                "longitude": 0.0,
                "latitude": 0.0
            },
            "34020000001340000002": {
                "channelId": "34020000001340000002",
                "name": "Input2",
                "manufacture": "huawei",
                "model": "M2281-QL-MG",
                "owner": "34020000",
                "civilCode": "34020000001340000002",
                "block": null,
                "address": "34020000",
                "parental": 0,
                "parentId": null,
                "safetyWay": 0,
                "registerWay": 1,
                "certNum": null,
                "certifiable": 0,
                "errCode": 0,
                "endTime": null,
                "secrecy": "0",
                "ipAddress": null,
                "port": 0,
                "password": null,
                "status": 0,
                "longitude": 0.0,
                "latitude": 0.0
            },
            "34020000001310000001": {
                "channelId": "34020000001310000001",
                "name": "34020000001320000001",
                "manufacture": "huawei",
                "model": "M2281-QL-MG",
                "owner": "34020000",
                "civilCode": "34020000001310000001",
                "block": null,
                "address": "34020000",
                "parental": 0,
                "parentId": null,
                "safetyWay": 0,
                "registerWay": 1,
                "certNum": null,
                "certifiable": 0,
                "errCode": 0,
                "endTime": null,
                "secrecy": "0",
                "ipAddress": null,
                "port": 0,
                "password": null,
                "status": 1,
                "longitude": 0.0,
                "latitude": 0.0
            }
        }
    }
]

调用播放接口，/api/play/34020000002000000001/34020000001340000001，返回值如下：
{"ssrc":"0102000428"}

此时SIP服务打印日志：
2020-11-18 18:32:09.910  INFO 33712 --- [nio-8080-exec-7] GB28181_SIP                              : <message
from="192.168.1.254:5060" 
to="192.168.1.197:41611" 
time="1605695529909"
isSender="true" 
transactionId="z9hg4bk-343135-3e8de8e29edcdcda1b6786c26d6fda1b" 
callId="f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254" 
firstLine="INVITE sip:34020000001340000001@192.168.1.197:41611 SIP/2.0" 
>
<![CDATA[INVITE sip:34020000001340000001@192.168.1.197:41611 SIP/2.0
Call-ID: f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254
CSeq: 1 INVITE
From: <sip:37010200492000000001@3701020049>;tag=live
To: <sip:34020000001340000001@3701020049>
Via: SIP/2.0/UDP 192.168.1.197:41611;rport;branch=z9hG4bK-343135-3e8de8e29edcdcda1b6786c26d6fda1b
Max-Forwards: 70
Contact: <sip:37010200492000000001@192.168.1.254:5060>
Content-Type: Application/SDP
Content-Length: 221

]]>
</message>

2020-11-18 18:32:09.912  INFO 33712 --- [     Thread-133] GB28181_SIP                              : Setting SIPMessage peerPacketSource to: /192.168.1.197:41611
2020-11-18 18:32:09.913  INFO 33712 --- [     Thread-133] GB28181_SIP                              : <message
from="192.168.1.197:41611" 
to="192.168.1.254:5060" 
time="1605695529912"
isSender="false" 
transactionId="z9hg4bk-343135-3e8de8e29edcdcda1b6786c26d6fda1b" 
callId="f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254" 
firstLine="SIP/2.0 100 Trying" 
>
<![CDATA[SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.1.197:41611;rport=5060;received=192.168.1.254;branch=z9hG4bK-343135-3e8de8e29edcdcda1b6786c26d6fda1b
From: <sip:37010200492000000001@3701020049>;tag=live
To: <sip:34020000001340000001@3701020049>;tag=34728591
CSeq: 1 INVITE
Call-ID: f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254
User-Agent: LiveGBS v201110
Contact: <sip:34020000002000000001@192.168.1.197:41611>
Content-Length: 0

]]>
</message>

2020-11-18 18:32:09.914  INFO 33712 --- [     Thread-133] GB28181_SIP                              : <message
from="192.168.1.197:41611" 
to="192.168.1.254:5060" 
time="1605695529914"
isSender="false" 
transactionId="z9hg4bk-343135-3e8de8e29edcdcda1b6786c26d6fda1b" 
callId="f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254" 
firstLine="SIP/2.0 100 Trying" 
>
<![CDATA[SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.1.197:41611;rport=5060;received=192.168.1.254;branch=z9hG4bK-343135-3e8de8e29edcdcda1b6786c26d6fda1b
From: <sip:37010200492000000001@3701020049>;tag=live
To: <sip:34020000001340000001@3701020049>;tag=34728591
CSeq: 1 INVITE
Call-ID: f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254
User-Agent: LiveGBS v201110
Contact: <sip:34020000002000000001@192.168.1.197:41611>
Content-Length: 0

]]>
</message>

2020-11-18 18:32:11.640  INFO 33712 --- [     Thread-134] GB28181_SIP                              : Setting SIPMessage peerPacketSource to: /192.168.1.197:41611
2020-11-18 18:32:11.640  INFO 33712 --- [     Thread-134] GB28181_SIP                              : <message
from="192.168.1.197:41611" 
to="192.168.1.254:5060" 
time="1605695531639"
isSender="false" 
transactionId="z9hg4bk-343135-3e8de8e29edcdcda1b6786c26d6fda1b" 
callId="f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254" 
firstLine="SIP/2.0 200 OK" 
>
<![CDATA[SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.1.197:41611;rport=5060;received=192.168.1.254;branch=z9hG4bK-343135-3e8de8e29edcdcda1b6786c26d6fda1b
From: <sip:37010200492000000001@3701020049>;tag=live
To: <sip:34020000001340000001@3701020049>;tag=34728591
CSeq: 1 INVITE
Call-ID: f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254
User-Agent: LiveGBS v201110
Contact: <sip:34020000002000000001@192.168.1.197:41611>
Content-Type: APPLICATION/SDP
Content-Length: 167

]]>
</message>

2020-11-18 18:32:11.640  INFO 33712 --- [     Thread-134] GB28181_SIP                              : <message
from="192.168.1.197:41611" 
to="192.168.1.254:5060" 
time="1605695531640"
isSender="false" 
transactionId="z9hg4bk-343135-3e8de8e29edcdcda1b6786c26d6fda1b" 
callId="f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254" 
firstLine="SIP/2.0 200 OK" 
>
<![CDATA[SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.1.197:41611;rport=5060;received=192.168.1.254;branch=z9hG4bK-343135-3e8de8e29edcdcda1b6786c26d6fda1b
From: <sip:37010200492000000001@3701020049>;tag=live
To: <sip:34020000001340000001@3701020049>;tag=34728591
CSeq: 1 INVITE
Call-ID: f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254
User-Agent: LiveGBS v201110
Contact: <sip:34020000002000000001@192.168.1.197:41611>
Content-Type: APPLICATION/SDP
Content-Length: 167

]]>
</message>

2020-11-18 18:32:11.643  INFO 33712 --- [ntScannerThread] GB28181_SIP                              : <message
from="192.168.1.254:5060" 
to="192.168.1.197:41611" 
time="1605695531642"
isSender="true" 
transactionId="z9hg4bk-343135-85260c342cf4431ece5aced1c9b27f7e" 
callId="f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254" 
firstLine="ACK sip:34020000002000000001@192.168.1.197:41611 SIP/2.0" 
>
<![CDATA[ACK sip:34020000002000000001@192.168.1.197:41611 SIP/2.0
Call-ID: f5f10ffbbbacb1a0b507635af8be6cfa@192.168.1.254
CSeq: 1 ACK
Via: SIP/2.0/UDP 192.168.1.197:41611;rport;branch=z9hG4bK-343135-85260c342cf4431ece5aced1c9b27f7e
From: <sip:37010200492000000001@3701020049>;tag=live
To: <sip:34020000001340000001@3701020049>;tag=34728591
Max-Forwards: 70
Content-Length: 0

]]>
</message>

再使用MediaServerUI查看视频列表，F12显示Request URL：
http://192.168.1.151:8037/index/api/getMediaList?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&schema=rtmp

Response显示：
{
   "code" : 0
}

视频列表仍未显示


SIP服务的.yml中media配置如下：
media:
#   ip: 10.200.64.88
#    ip: 192.168.0.102
    ip: 192.168.1.151
    port: 8037


请问大佬，media服务和SIP服务分开部署的情况下，配置文件还需要修改什么嘛？

**Comment by reachzxsframe** [comment]
流媒体服务config.ini，http服务器监听端口：
port=8037

MediaServerUI，global.js：
const serverip="192.168.1.151:8037"

SIP服务.yml配置：
media:
//   ip: 10.200.64.88
//   ip: 192.168.0.102
    ip: 192.168.1.151
    port: 8037

**Comment by xia-chu** [comment]
你要提供下zlm的日志 我对sip不熟悉的

**Comment by reachzxsframe** [comment]
非常感谢！问题已经解决了。
sip的配置问题：
media:
// ip: 10.200.64.88
// ip: 192.168.0.102
ip: 192.168.1.151
port: 8037

此处的port应该配置流媒体中udp、tcp代理服务器端口：
[rtp_proxy]
#udp类型的代理服务器是否检查rtp源地址，地址不配备将丢弃数据
checkSource=1
#导出调试数据(包括rtp/ps/h264)至该目录,置空则关闭数据导出
dumpDir=
#udp和tcp代理服务器，支持rtp(必须是ts或ps类型)代理
port=10000
#rtp超时时间，单位秒
timeoutSec=15

我给配成http服务器监听端口了，改成10000就好了

![image](https://user-images.githubusercontent.com/44544966/99766193-918e0280-2b3b-11eb-866a-c1a1790eee7f.png)
代码可以看到，sip服务会到这个端口拉流

**Comment by xia-chu** [comment]
那我关闭issue了
