### ISSUE TITLE
宇视摄像头GB28181,MediaServerUI视频广场的直播一直闪屏,ZLMediaKit报error

### ISSUE THREAD

**Issue by longqi0505** [xia-chu/ZLMediaKit#583]
![微信图片_20201119093719](https://user-images.githubusercontent.com/74653872/99609430-dab25980-2a4a-11eb-87b4-23a7a5f4e63e.png)

**Comment by xia-chu** [comment]
你的流不是264 aac，flv.js不支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: longqi0505 <notifications@github.com&gt;
发送时间: 2020年11月19日 09:38
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 宇视摄像头GB28181,MediaServerUI视频广场的直播一直闪屏,ZLMediaKit报error (#583)

**Comment by longqi0505** [comment]
> 你的流不是264 aac，flv.js不支持发自我的iPhone
> […](#)
> ------------------原始邮件------------------发件人：longqi0505 <notifications@github.com> 发送时间：2020年11月19日09:38收件人：xia-chu / ZLMediaKit <ZLMediaKit@noreply.github.com> 抄送：订阅<subscribed@noreply.github.com> 主题：回复：[xia-chu / ZLMediaKit]宇视摄像头GB28181，MediaServerUI视频广场的直播一直闪屏，ZLMediaKit报错误（[＃583](https://github.com/xia-chu/ZLMediaKit/issues/583)）—之所以收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

是因为宇视推得流不是ps-rtp的对吧,
![微信图片_20201119095337](https://user-images.githubusercontent.com/74653872/99610616-2239e500-2a4d-11eb-96de-b779f1215a25.png)

**Comment by longqi0505** [comment]
![微信图片_20201119181108](https://user-images.githubusercontent.com/74653872/99652501-de69ce80-2a92-11eb-9d15-9f9828693e20.png)
大神,只要带711音频就解码失败!

**Comment by xia-chu** [comment]
都说了flv.js不支持711
