### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by hh-kai** [xia-chu/ZLMediaKit#584]
把所有enable都置为false 编译失败 
option(ENABLE_HLS "Enable HLS" false)
option(ENABLE_OPENSSL "Enable OpenSSL" false)
option(ENABLE_MYSQL "Enable MySQL" false)
option(ENABLE_FAAC "Enable FAAC" false)
option(ENABLE_X264 "Enable x264" false)
option(ENABLE_MP4 "Enable MP4" false)
option(ENABLE_RTPPROXY "Enable RTPPROXY" false)
option(ENABLE_API "Enable C API SDK" false)
option(ENABLE_CXX_API "Enable C++ API SDK" false)
option(ENABLE_TESTS "Enable Tests" false)
option(ENABLE_SERVER "Enable Server" false)
编译结果
ZLMediaKit/src/Rtp/RtpCache.h:39:56: error: expected class-name before ‘{’ token
 class RtpCachePS : public RtpCache, public PSEncoderImp{

需打开option(ENABLE_HLS "Enable HLS" true)

**Comment by tsingeye** [comment]
ENABLE_RTPPROXY  打开也可以

**Comment by tsingeye** [comment]
> 把所有enable都置为false 编译失败
> option(ENABLE_HLS "Enable HLS" false)
> option(ENABLE_OPENSSL "Enable OpenSSL" false)
> option(ENABLE_MYSQL "Enable MySQL" false)
> option(ENABLE_FAAC "Enable FAAC" false)
> option(ENABLE_X264 "Enable x264" false)
> option(ENABLE_MP4 "Enable MP4" false)
> option(ENABLE_RTPPROXY "Enable RTPPROXY" false)
> option(ENABLE_API "Enable C API SDK" false)
> option(ENABLE_CXX_API "Enable C++ API SDK" false)
> option(ENABLE_TESTS "Enable Tests" false)
> option(ENABLE_SERVER "Enable Server" false)
> 编译结果
> ZLMediaKit/src/Rtp/RtpCache.h:39:56: error: expected class-name before ‘{’ token
> class RtpCachePS : public RtpCache, public PSEncoderImp{
> 
> 需打开option(ENABLE_HLS "Enable HLS" true)

PSEncoder.h 里面有个ENABLE_RTPPROXY 的宏， 你关闭了， 会导致PSEncoderImp 类未定义，所以错误哦

**Comment by wasphin** [comment]
我理解的 OP 的意思是既然选项可以开关, 那么就都应该支持在修改后可以正常编译, 如果某些选项不允许关闭那么就不该开放该选项.

**Comment by hh-kai** [comment]
这个我知道 就是有几个是不能置为false

**Comment by ph-nh-tech** [comment]
怎项目跑起来后，直接就报错了呢

**Comment by xia-chu** [comment]
修复了
