### ISSUE TITLE
Huge log because error at: H264Rtp.cpp:139 decodeRtp

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#585]
Hi,

I am trying your latest code and see there are many log events from H264Rtp.cpp:139 decodeRtp :
![ảnh](https://user-images.githubusercontent.com/59004953/99794294-87c8c700-2b5c-11eb-8b51-88f8ced75f79.png)

Size of log file ~ 10 GB after several hours. My video source is IP camera at resolution 5MP or 4K.
Tested with previous version (https://github.com/xia-chu/ZLMediaKit/tree/4132df89cdab9b068bb374c8e5781afb87960b75) dont have this problem.
this is log file:
[2020-11-20.zip](https://github.com/xia-chu/ZLMediaKit/files/5573161/2020-11-20.zip)

**Comment by xia-chu** [comment]
can you share me the rtsp url?

**Comment by pubpy2015** [comment]
Hi,

rtsp url: rtsp://Admin:1234@210.245.49.29:22454/h264

**Comment by xia-chu** [comment]
现在太晚了 明天再测试下 谢谢



发自我的iPhone


------------------ Original ------------------

**Comment by xia-chu** [comment]
<img width="712" alt="图片" src="https://user-images.githubusercontent.com/11495632/99878814-fbdd9a80-2c42-11eb-9f5f-025242963ad7.png">

**Comment by pubpy2015** [comment]
Hi,

Maybe internet connection (international) not good. You can try:
rtsp://Admin:1234@210.245.49.29:22454/h264_2 for 1920x1080 resolution, or
rtsp://Admin:1234@210.245.49.29:22454/h264_3 for 720x480 resolution

My internet connection still ok:
![image](https://user-images.githubusercontent.com/59004953/99879254-3d1f7b80-2c3e-11eb-8d91-253930cb85e1.png)

**Comment by xia-chu** [comment]
I'm sorry that none of the URLs you've provided can be played at this time
You can first provide a RTSP packet by wireshare, I will analysis it

**Comment by pubpy2015** [comment]
Hi,

this is wireshark log

[wireshark_log2.zip](https://github.com/xia-chu/ZLMediaKit/files/5577788/wireshark_log2.zip)

**Comment by xia-chu** [comment]
It's to late now. I'll get back to you tomorrow or next week

**Comment by xia-chu** [comment]
There is a bug in your camera，when rtp in fu-a mode, the start bit of your camera rtp stream is always 0

![图片](https://user-images.githubusercontent.com/11495632/99949539-2bf97a80-2db6-11eb-9e18-25777b226d7b.png)

**Comment by xia-chu** [comment]
Although there are ways to be compatible with this bug, I don't think it's very good to do so

**Comment by pubpy2015** [comment]
Thanks,

I have 2 camera models of mine has this problem and if yes, please make your media server compatible with it.
The proxy stream still play normarly so can i turn off log only for this bug?

**Comment by xia-chu** [comment]
You can turn off this log, but you can't play any other stream except RTSP stream

**Comment by pubpy2015** [comment]
Thanks,

Please fixed it if you have time.

**Comment by xia-chu** [comment]
This is a bug in your camera. Do't you think the camera manufacturer should fix this bug?

**Comment by pubpy2015** [comment]
No, because this is small camera manufacturer, May be they OEM/ODM camera from other manufacturers.

**Comment by rmokerone** [comment]
> No, because this is small camera manufacturer, May be they OEM/ODM camera from other manufacturers.

Maybe you should compile a special version of ZLMeidakit to fit your own camera.

**Comment by xia-chu** [comment]
Sorry for that,  this is bug of zlmediakit,  now i fixed it , please update your code.
