### ISSUE TITLE
用大华的摄像头，通过GB28181连接，一直报错非法的rtp，version!=2

### ISSUE THREAD

**Issue by smally84** [xia-chu/ZLMediaKit#586]

**Comment by xia-chu** [comment]
就这摄像头这样吗？
这个摄像头的rtp不规范

**Comment by smally84** [comment]
另外一个品牌也是一样

**Comment by tsingeye** [comment]
抓包看下 rtp包 起始标识

**Comment by smally84** [comment]
我是在docker上测试的，不太好操作。我之前用的是srs做国标接入，正常都是可以的，只是会有一些小问题。
偶然发现咱们这个，想试一下，但是说明太少，没有具体的从配置到使用的流程说明，对于很多像我一样的新手，无从下手。
貌似没有看到真正接入gb28181的真实案例，好像都是用软件模拟的。

**Comment by xia-chu** [comment]
??????????

**Comment by smally84** [comment]
我使用的比较初级，对rtp那类东西不怎么熟悉，一时无从下手，但又担心说错了误导大家，所以就关闭了。我之前是参考srs4.0，里面是有gb28181模块的，文档还算比较齐全，手里头几款摄像头都是可以接入使用的，不过我都是用的接口调用，底层就不懂了。咱们这个我搞不了，貌似我手里的摄像头都不能接入，反正都是提示rtp的version!=2，底层我不懂，我无法提供有效的建议。如果你们有时间可以看看srs 4.0，他们也是完全开源的，是可以驱动主流gb28181摄像头的，常规的海康，大华及一些小众的，我都试过。

**Comment by smally84** [comment]
> ??????????

是这样

**Comment by smally84** [comment]
@xia-chu  应该是我理解有问题，我以为咱们这个框架对gb28181的支持是一个完整的从sip信令到媒体转码及推拉流控制系统。现在看好像是没有实现bgb28181的sip信令部分
