### ISSUE TITLE
局域网可以使用https 吗？

### ISSUE THREAD

**Issue by chenxianjie** [xia-chu/ZLMediaKit#588]
你好，请问下在局域网环境下可以使用https吗？如果可以，证书怎么生成，能简单讲下大致流程吗。谢谢

**Comment by xia-chu** [comment]
可以 localhost都可以用https，只要你能正常解析域名到你局域网的ip就行
我是修改host文件 你应该怎么弄了？自己做dns解析服务器吗？
ssl证书都是绑定域名的

**Comment by chenxianjie** [comment]
这方面我也不太懂，但是像nginx ，tomcat 可以自己生成证书，在局域网使用https，并不需要域名，不知道能不能利用tomcat 这些生成一个流媒体也可以用的证书

**Comment by xia-chu** [comment]
如果用自签名证书 那就失去https的意义了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenxianjie <notifications@github.com&gt;
发送时间: 2020年11月24日 10:06
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 局域网可以使用https 吗？ (#588)

**Comment by chenxianjie** [comment]
我现在想在局域网做一下简单测试，也没有域名，能否用openssl 自己生成证书来做测试，具体要怎么操作呢

**Comment by xia-chu** [comment]
OpenSSL可以生成自签名证书 你百度下用法。
注意，zlm默认加载带公钥和私钥的pem证书，
你可以看看wiki，服务器启动与关闭编
