### ISSUE TITLE
华为摄像头，H264可以正常拉流播放，H265播放异常

### ISSUE THREAD

**Issue by reachzxsframe** [xia-chu/ZLMediaKit#589]
摄像头视频流参数配置：
![image](https://user-images.githubusercontent.com/44544966/100064968-26f80200-2e6e-11eb-9de2-10fb2724133d.png)
该配置下，播放正常

![image](https://user-images.githubusercontent.com/44544966/100065029-3e36ef80-2e6e-11eb-9bd9-f17835a712ee.png)
该配置下，无法播放，画面定格在开始这一帧
![image](https://user-images.githubusercontent.com/44544966/100065173-6fafbb00-2e6e-11eb-99fd-38bb866ffbf1.png)

**Comment by xia-chu** [comment]
flv不支持265、现在大家都是扩展了flv 并未受到世界的广泛认可 所以除非你用修改后的FFmpeg，否则都没法播放

**Comment by reachzxsframe** [comment]
好的，谢谢

**Comment by hengzhao** [comment]
夏总，修改后的FFmpeg怎么用啊？是直接编译安装你修改的版本？

**Comment by xia-chu** [comment]
> 
> 
> 夏总，修改后的FFmpeg怎么用啊？是直接编译安装你修改的版本后 再编译ZLMediaKit吗？

不用 zlm不依赖FFmpeg ，只是两个restful api用到FFmpeg的命令了而已
