### ISSUE TITLE
修改后UDP服务端口未关闭

### ISSUE THREAD

**Issue by sunhui2013** [xia-chu/ZLMediaKit#590]
RtpProcess::Ptr process;
    if (!stream_id.empty()) {
        //指定了流id，那么一个端口一个流(不管是否包含多个ssrc的多个流，绑定rtp源后，会筛选掉ip端口不匹配的流)
        process = RtpSelector::Instance().getProcess(stream_id, true);
        weak_ptr<Socket> weak_sock = udp_server;
        udp_server->setOnRead([weak_sock, process](const Buffer::Ptr &buf, struct sockaddr *addr, int) {
           process->inputRtp(true, weak_sock.lock(), buf->data(), buf->size(), addr);
         });
    } else {
        //未指定流id，一个端口多个流，通过ssrc来分流
        auto &ref = RtpSelector::Instance();
        weak_ptr<Socket> weak_sock = udp_server;
        udp_server->setOnRead([&ref, weak_sock](const Buffer::Ptr &buf, struct sockaddr *addr, int) {
           ref.inputRtp(weak_sock.lock(), buf->data(), buf->size(), addr);
         });
    }

    _on_clearup = [udp_server, process, stream_id]() {
        //去除循环引用
        //udp_server->setOnRead(nullptr);
        if (process) {
            //删除rtp处理器
            RtpSelector::Instance().delProcess(stream_id, process.get());
        }
    };
添加后服务器稳定，但是UDP服务端口发送指令后不能关闭端口，结果服务

[root@localhost]# netstat -anp|grep "MediaServer"|grep "udp"|wc -l
2466
[root@localhost]#

**Comment by xia-chu** [comment]
你会打补丁吗

**Comment by sunhui2013** [comment]
_on_clearup = [udp_server, process, stream_id]() {
        //去除循环引用
        //udp_server->setOnRead(nullptr);
        if (process) {
            //删除rtp处理器
            RtpSelector::Instance().delProcess(stream_id, process.get());
        }
        udp_server->closeSock();
    };
不是太熟悉，我把红色的去掉，绿色增加，添加一行  udp_server->closeSock()；目前在测试中

**Comment by sunhui2013** [comment]
有内存泄漏，没考虑清楚，修改为：
    _on_clearup = [udp_server, process, stream_id]() {
        //去除循环引用
        //udp_server->setOnRead(nullptr);
        if (process) {
            //删除rtp处理器
            RtpSelector::Instance().delProcess(stream_id, process.get());
        }
        //udp_server->closeSock();
         weak_ptr<Socket> weak_sock = udp_server;
         weak_sock.lock()->closeSock();
    };

**Comment by xia-chu** [comment]
udp_server->setOnRead(nullptr);不能注释掉

**Comment by xia-chu** [comment]
改成这样：
```patch
Index: src/Rtp/RtpServer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/RtpServer.cpp	(revision f7433b0f90f96851d028ded44c9fb53971120dad)
+++ src/Rtp/RtpServer.cpp	(date 1606214378000)
@@ -24,10 +24,10 @@
 
 void RtpServer::start(uint16_t local_port, const string &stream_id,  bool enable_tcp, const char *local_ip) {
     //创建udp服务器
-    Socket::Ptr udp_server = Socket::createSocket(nullptr, false);
+    Socket::Ptr udp_server = Socket::createSocket(nullptr, true);
     if (local_port == 0) {
         //随机端口，rtp端口采用偶数
-        Socket::Ptr rtcp_server = Socket::createSocket(nullptr, false);
+        Socket::Ptr rtcp_server = Socket::createSocket(nullptr, true);
         auto pair = std::make_pair(udp_server, rtcp_server);
         makeSockPair(pair, local_ip);
         //取偶数端口

```
