### ISSUE TITLE
本地录像是否也可以保存为 fragments-mp4 格式？

### ISSUE THREAD

**Issue by chuyue86** [xia-chu/ZLMediaKit#592]
如题。fmp4 文件方便连接合并多个视频文件。

**Comment by xia-chu** [comment]
可以 你可以稍微改一句代码就行

**Comment by chuyue86** [comment]
还望指教是在那个部分？

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/100199618-668b2080-2f38-11eb-939b-1f9400312e2a.png)

**Comment by xia-chu** [comment]
改成：
return _mp4_file->createWriter( 0, true);

**Comment by xia-chu** [comment]
改成：
 return _memory_file->createWriter(MOV_FLAG_SEGMENT, true);

**Comment by chuyue86** [comment]
OK，非常感谢！

**Comment by xia-chu** [comment]
写错了 我修正了 你刷新下我的回答

**Comment by chuyue86** [comment]
测试了一下 

此处若使用代码 createWriter(MOV_FLAG_SEGMENT, true)，会导致存储的录像文件无法正常解析播放

修改代码为 createWriter(MOV_FLAG_FASTSTART, true)，可以达到预期的效果

**Comment by xia-chu** [comment]
嗯 好像是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ethan <notifications@github.com&gt;
发送时间: 2020年11月25日 16:48
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 本地录像是否也可以保存为 fragments-mp4 格式？ (#592)

**Comment by lyzh04061135** [comment]
异常终止的推流也没有触发录制结束的回调
