### ISSUE TITLE
[Strange RTSP source] VLC can not play rtsp proxy, rtmp is normal

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#594]
Hi,

I am using AddStreamProxy to add a rtsp source to MediaServer.
All process is normal but VLC can not play RTSP stream from MediaServer while still play rtmp stream well.
Other rtsp source are normal.

Here is log from MediaServer and wireshark
[2020-11-26.zip](https://github.com/xia-chu/ZLMediaKit/files/5600427/2020-11-26.zip)
[wiresharklog.zip](https://github.com/xia-chu/ZLMediaKit/files/5600428/wiresharklog.zip)

**Comment by xia-chu** [comment]
Please change this option to 0:
![图片](https://user-images.githubusercontent.com/11495632/100316496-99471e80-2ff5-11eb-8408-b9d66039806d.png)

**Comment by pubpy2015** [comment]
Thanks,

But seem this a bug from camera. After change audio codec of camera from G711 to Opus it's work fine with both audio codecs.
![ảnh](https://user-images.githubusercontent.com/59004953/100328350-00b59c00-2fff-11eb-9c48-9873adff8f55.png)
