### ISSUE TITLE
rtsp转hls，没有声音

### ISSUE THREAD

**Issue by yuezhongxin** [xia-chu/ZLMediaKit#596]
通过调用接口addStreamProxy，rtsp转hls，hls播放没有声音，但是rtsp我用vlc播放是有声音的。

摄像头音频配置：
![image](https://user-images.githubusercontent.com/6800671/100335031-76c1ff00-300f-11eb-9b59-13f5d579c1be.png)

大神，啥原因呀？

**Comment by xia-chu** [comment]
ffplay播放下 看看有没有声音 没声音看看ffplay日志

**Comment by yuezhongxin** [comment]
好的，我试试看

**Comment by yuezhongxin** [comment]
ffplay日志：

```
[http @ 0x7fdd3a8b2200] Opening 'http://xxxx/online/278/2020-11-27/11/32-32_13.ts?vhost=__defaultVhost__' for reading
[hls @ 0x7fdd3c884400] Opening 'http://xxxx/online/278/2020-11-27/11/32-32_13.ts?vhost=__defaultVhost__' for reading
[mp3float @ 0x7fdd3b80f600] Header missing    0KB sq=    0B f=0/0
    Last message repeated 5 times
[hls @ 0x7fdd3c884400] decoding for stream 0 failed
[hls @ 0x7fdd3c884400] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float) ([144][0][0][0] / 0x0090), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls, from 'http://xxxx/hls.m3u8?vhost=__defaultVhost__':
  Duration: N/A, start: 4.040000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: mp3 ([144][0][0][0] / 0x0090), 0 channels, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 640x352, 12.50 fps, 12.50 tbr, 90k tbn, 25 tbc
    Metadata:
      variant_bitrate : 0
[http @ 0x7fdd3a8c3400] Opening 'http://xxxx/hls.m3u8?vhost=__defaultVhost__' for reading
[hls @ 0x7fdd3c884400] Skip ('#EXT-X-VERSION:3')B sq=    0B f=0/0
[hls @ 0x7fdd3c884400] Skip ('#EXT-X-ALLOW-CACHE:NO')
```

**Comment by yuezhongxin** [comment]
@xia-chu 大神，求救

**Comment by xia-chu** [comment]
被识别成mp3了，你能提供下hls的链接吗？我测试下

**Comment by yuezhongxin** [comment]
@xia-chu http://net-forward-01.simboss.com:49997/online/278/hls.m3u8?vhost=__defaultVhost__

**Comment by yuezhongxin** [comment]
@xia-chu 大神地址收到了吧，我先删了

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/100495922-f0322c80-318a-11eb-9805-8eb59132d53e.png)
![图片](https://user-images.githubusercontent.com/11495632/100495925-f7f1d100-318a-11eb-9ea6-e455c6087af4.png)

**Comment by xia-chu** [comment]
g711 可能不被FFmpeg支持

**Comment by xia-chu** [comment]
问过大佬了 FFmpeg确实不支持G711的hls

**Comment by yuezhongxin** [comment]
@xia-chu  大神，addStreamProxy接口实现，也是用FFmpeg转的吗？这个问题有其他的方式解决吗？

**Comment by xia-chu** [comment]
只能转码才能播放 用ffmpeg拉流吧

**Comment by yuezhongxin** [comment]
好的，我用addFFmpegSource试试看

**Comment by yuezhongxin** [comment]
@xia-chu 我试了这个命令：

`/usr/local/ffmpeg/bin/ffmpeg -re -f rtsp -rtsp_transport tcp -i rtsp://admin:admin@127.0.0.1:11024/12 -force_key_frames "expr:gte(t,n_forced*1)" -strict -2 -c:v libx264 -vsync 2 -c:a aac -f hls -hls_list_size 10 -hls_wrap 10 -hls_time 1 ./www/test/hx_replay/280-hls.m3u8`

是有声音的，但现在addFFmpegSource好像不支持rtsp转hls，我改代码的话可以直接支持，但是没办法用到on_stream_not_found事件了，就不能按需拉流了，怎么解决呢？

**Comment by yuezhongxin** [comment]
试了调用addFFmpegSource，要很久才能播放出来，而且关闭播放，等一段时间并没有调用on_stream_none_reader，这样ffmpeg一直在拉流，无法关闭了。

**Comment by yuezhongxin** [comment]
@xia-chu 大神，我看代码里面有on_stream_not_found_ffmpeg，能让调用addFFmpegSource，hls无人播放之后，调用webhook吗？

**Comment by yuezhongxin** [comment]
![image](https://user-images.githubusercontent.com/6800671/100864560-1d574580-34d1-11eb-95ae-122df9027435.png)

@xia-chu 我找到一个可以支持G711的播放器，但测试下来并没有效果，是不是通过addStreamProxy转的hls，音频格式并不是G711了，而是上面日志中的mp3？通过addStreamProxy能保证音频格式还是G711吗？这样就可以用QPlayer播放了

**Comment by yuezhongxin** [comment]
@xia-chu 大神，求救~
