### ISSUE TITLE
/index/api/addStreamProxy 填了secret报缺少其他必填参数

### ISSUE THREAD

**Issue by 472630126** [xia-chu/ZLMediaKit#597]
![image](https://user-images.githubusercontent.com/18320573/100417026-daedcd00-30ba-11eb-8a46-612d6e76e2d4.png)

由于我不是127.0.0.1访问。所以要填写secret ，但是填写了secret报缺少其他的几个必填参数。 如上图我的参数都已传到后台
不填就报缺少 secret 参数

我拉的master代码

**Comment by 472630126** [comment]
不好意思 少了个app参数  打扰啦

**Comment by Jesse3692** [comment]
有一些特殊的api是需要secret的，访问地址如下：

http://192.168.1.58:8180/index/api/restartServer?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
