### ISSUE TITLE
播放延迟

### ISSUE THREAD

**Issue by farawaychen** [xia-chu/ZLMediaKit#598]
网络环境：内网-A机器, 公网-B机器，内网-C机器
软件部署：A机器使用FFMPEG拉rtsp流推到在B机器部署的ZL，C机器使用VLC播放推流到ZL的rtsp地址。
问题描述：C机器通过VLC播放ZL的rtsp流，需要11S左右才能拉到视频流。
推流命令：ffmpeg -i rtsp://192.168.1.111:554/h264/ch1/main/av_stream -codec copy -rtsp_transport tcp -f rtsp -g 5 rtsp://xx.xx.xx.xx:554/live/proxyStream
ZL配置：官方config.ini

**Comment by xia-chu** [comment]
你确定vlc是用tcp方式播放的rtsp?

**Comment by farawaychen** [comment]
谢谢，VLC配置为tcp方式后，快了很多。
