### ISSUE TITLE
感觉invoker("200 OK")这样的可以把OK这些状态描述放在函数中实现

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#602]
在WebApi.cpp中http返回的时候，invoker第一个参数是状态码，目前用的是纯字符串，200 + OK，
```
invoker("200 OK", headerOut, val.toStyledString());
```
总感觉目前的实现对调用方来讲有一点麻烦，用到某个状态，还需要查具体的描述,。
如果能实现只输入200， 字符串或 int 就会方便一点。 
建议在invoker中对状态码进行解析，拼出后面的状态描述。
```
invoker("200", headerOut, val.toStyledString());
invoker(200, headerOut, val.toStyledString());
```

参考 代码
https://github.com/yhirose/cpp-httplib/blob/615867322d5088bbcae9756249c1395796bbd562/httplib.h#L2179
```
inline const char *status_message(int status) {
  switch (status) {
  case 100: return "Continue";
  case 101: return "Switching Protocol";
  case 102: return "Processing";
  case 103: return "Early Hints";
  case 200: return "OK";
  case 201: return "Created";
  case 202: return "Accepted";
  case 203: return "Non-Authoritative Information";
  case 204: return "No Content";
  case 205: return "Reset Content";
  case 206: return "Partial Content";
  case 207: return "Multi-Status";
  case 208: return "Already Reported";
  case 226: return "IM Used";
  case 300: return "Multiple Choice";
  case 301: return "Moved Permanently";
  case 302: return "Found";
  case 303: return "See Other";
  case 304: return "Not Modified";
  case 305: return "Use Proxy";
  case 306: return "unused";
  case 307: return "Temporary Redirect";
  case 308: return "Permanent Redirect";
  case 400: return "Bad Request";
  case 401: return "Unauthorized";
  case 402: return "Payment Required";
  case 403: return "Forbidden";
  case 404: return "Not Found";
  case 405: return "Method Not Allowed";
  case 406: return "Not Acceptable";
  case 407: return "Proxy Authentication Required";
  case 408: return "Request Timeout";
  case 409: return "Conflict";
  case 410: return "Gone";
  case 411: return "Length Required";
  case 412: return "Precondition Failed";
  case 413: return "Payload Too Large";
  case 414: return "URI Too Long";
  case 415: return "Unsupported Media Type";
  case 416: return "Range Not Satisfiable";
  case 417: return "Expectation Failed";
  case 418: return "I'm a teapot";
  case 421: return "Misdirected Request";
  case 422: return "Unprocessable Entity";
  case 423: return "Locked";
  case 424: return "Failed Dependency";
  case 425: return "Too Early";
  case 426: return "Upgrade Required";
  case 428: return "Precondition Required";
  case 429: return "Too Many Requests";
  case 431: return "Request Header Fields Too Large";
  case 451: return "Unavailable For Legal Reasons";
  case 501: return "Not Implemented";
  case 502: return "Bad Gateway";
  case 503: return "Service Unavailable";
  case 504: return "Gateway Timeout";
  case 505: return "HTTP Version Not Supported";
  case 506: return "Variant Also Negotiates";
  case 507: return "Insufficient Storage";
  case 508: return "Loop Detected";
  case 510: return "Not Extended";
  case 511: return "Network Authentication Required";

  default:
  case 500: return "Internal Server Error";
  }
}
```

**Comment by xia-chu** [comment]
你这个确实可以这么做啊 后面尝试集成下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: along <notifications@github.com&gt;
发送时间: 2020年11月30日 15:58
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 感觉invoker("200 OK")这样的可以把OK这些状态描述放在函数中实现 (#602)





 
在WebApi.cpp中http返回的时候，invoker第一个参数是状态码，目前用的是纯字符串，200 + OK，
 invoker("200 OK", headerOut, val.toStyledString());  
总感觉目前的实现对调用方来讲有一点麻烦，用到某个状态，还需要查具体的描述,。
 如果能实现只输入200， 字符串或 int 就会方便一点。
 建议在invoker中对状态码进行解析，拼出后面的状态描述。
 invoker("200", headerOut, val.toStyledString()); invoker(200, headerOut, val.toStyledString());  
参考 代码
 https://github.com/yhirose/cpp-httplib/blob/615867322d5088bbcae9756249c1395796bbd562/httplib.h#L2179
 inline const char *status_message(int status) {   switch (status) {   case 100: return "Continue";   case 101: return "Switching Protocol";   case 102: return "Processing";   case 103: return "Early Hints";   case 200: return "OK";   case 201: return "Created";   case 202: return "Accepted";   case 203: return "Non-Authoritative Information";   case 204: return "No Content";   case 205: return "Reset Content";   case 206: return "Partial Content";   case 207: return "Multi-Status";   case 208: return "Already Reported";   case 226: return "IM Used";   case 300: return "Multiple Choice";   case 301: return "Moved Permanently";   case 302: return "Found";   case 303: return "See Other";   case 304: return "Not Modified";   case 305: return "Use Proxy";   case 306: return "unused";   case 307: return "Temporary Redirect";   case 308: return "Permanent Redirect";   case 400: return "Bad Request";   case 401: return "Unauthorized";   case 402: return "Payment Required";   case 403: return "Forbidden";   case 404: return "Not Found";   case 405: return "Method Not Allowed";   case 406: return "Not Acceptable";   case 407: return "Proxy Authentication Required";   case 408: return "Request Timeout";   case 409: return "Conflict";   case 410: return "Gone";   case 411: return "Length Required";   case 412: return "Precondition Failed";   case 413: return "Payload Too Large";   case 414: return "URI Too Long";   case 415: return "Unsupported Media Type";   case 416: return "Range Not Satisfiable";   case 417: return "Expectation Failed";   case 418: return "I'm a teapot";   case 421: return "Misdirected Request";   case 422: return "Unprocessable Entity";   case 423: return "Locked";   case 424: return "Failed Dependency";   case 425: return "Too Early";   case 426: return "Upgrade Required";   case 428: return "Precondition Required";   case 429: return "Too Many Requests";   case 431: return "Request Header Fields Too Large";   case 451: return "Unavailable For Legal Reasons";   case 501: return "Not Implemented";   case 502: return "Bad Gateway";   case 503: return "Service Unavailable";   case 504: return "Gateway Timeout";   case 505: return "HTTP Version Not Supported";   case 506: return "Variant Also Negotiates";   case 507: return "Insufficient Storage";   case 508: return "Loop Detected";   case 510: return "Not Extended";   case 511: return "Network Authentication Required";   default:   case 500: return "Internal Server Error";   } }

**Comment by alongL** [comment]
看418错误码。
```
case 418: return "I'm a teapot";
```

**Comment by xia-chu** [comment]
> teapot

有意思

**Comment by xia-chu** [comment]
已实现
