### ISSUE TITLE
28181推流（RTP Over TCP）播放一段时间自动断开

### ISSUE THREAD

**Issue by Allenisme** [xia-chu/ZLMediaKit#605]
![image](https://user-images.githubusercontent.com/17775578/100856133-fd6e5480-34c5-11eb-8c4d-879889af733c.png)
每次出现Out-Of-Order的时候就会断开，请问有什么解决方法吗？

**Comment by xia-chu** [comment]
没有 这个是tcp协议栈上的问题 跟应用程序无关&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Allenisme <notifications@github.com&gt;
发送时间: 2020年12月2日 17:45
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 28181推流（RTP Over TCP）播放一段时间自动断开 (#605)





 

 每次出现Out-Of-Order的时候就会断开，请问有什么解决方法吗？

**Comment by Allenisme** [comment]
> 没有 这个是tcp协议栈上的问题 跟应用程序无关&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Allenisme <notifications@github.com&gt; 发送时间: 2020年12月2日 17:45 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] 28181推流（RTP Over TCP）播放一段时间自动断开 (#605) 每次出现Out-Of-Order的时候就会断开，请问有什么解决方法吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好吧，谢谢
