### ISSUE TITLE
建议HttpTSPlayer.cpp 中onResponseBody()函数加入对status的判断

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#606]
src/Http/HttpTSPlayer.cpp
```
void HttpTSPlayer::onResponseBody(const char *buf, int64_t size, int64_t recvedSize, int64_t totalSize) {
    if (recvedSize == size) {
        //开始接收数据
        if (buf[0] == TS_SYNC_BYTE) {
            //这是ts头
            _is_first_packet_ts = true;
        } else {
            WarnL << "可能不是http-ts流";
        }
    }

    if (_split_ts) {
        _segment.input(buf, size);
    } else {
        onPacket(buf, size);
    }
}
```
当前不判断返回的status，虽然在onResponseHeader中判断状态码，并且关闭socket，但是比如在404的情况下，http服务器仍然可以返回一些数据，比如 “<html>  你好像来到了知识的荒原 </html>”，并且这些数据与header一块返回的，所以还是会调用onResponseBody，此时warn "可能不是http-ts流" 没有必要。

建议在onResponseHeader中保存status， 在onResponseBody中判断status，如果不是“200”或“206” 返回，不再进行后续处理。

int64_t HttpTSPlayer::onResponseHeader(const string &status, const HttpClient::HttpHeader &headers) {
   _status = status;
  .....
}

void HttpTSPlayer::onResponseBody(const char *buf, int64_t size, int64_t recvedSize, int64_t totalSize) {
    if (status != "200" && status != "206") {
          return 0;
    }
  .....
}

**Comment by xia-chu** [comment]
大佬👍🏻！ 麻烦提交个pr吧😃



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: along <notifications@github.com&gt;
发送时间: 2020年12月2日 17:47
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 建议HttpTSPlayer.cpp 中onResponseBody()函数加入对status的判断 (#606)





 
src/Http/HttpTSPlayer.cpp
 void HttpTSPlayer::onResponseBody(const char *buf, int64_t size, int64_t recvedSize, int64_t totalSize) {     if (recvedSize == size) {         //开始接收数据         if (buf[0] == TS_SYNC_BYTE) {             //这是ts头             _is_first_packet_ts = true;         } else {             WarnL << "可能不是http-ts流";         }     }     if (_split_ts) {         _segment.input(buf, size);     } else {         onPacket(buf, size);     } }  
当前不判断返回的status，虽然在onResponseHeader中判断状态码，并且关闭socket，但是比如在404的情况下，http服务器仍然可以返回一些数据，比如 “  你好像来到了知识的荒原 ”，并且这些数据与header一块返回的，所以还是会调用onResponseBody，此时warn "可能不是http-ts流" 没有必要。
 
建议在onResponseHeader中保存status， 在onResponseBody中判断status，如果不是“200”或“206” 返回，不再进行后续处理。
 
int64_t HttpTSPlayer::onResponseHeader(const string &amp;status, const HttpClient::HttpHeader &amp;headers) {
 _status = status;
 .....
 }
 
void HttpTSPlayer::onResponseBody(const char *buf, int64_t size, int64_t recvedSize, int64_t totalSize) {
 if (status != "200" &amp;&amp; status != "206") {
 return 0;
 }
 .....
 }

**Comment by alongL** [comment]
提交了。
 HttpTSPlayer.h中的变量 string   _status 在提交中好像没加上。
辛苦夏总啦~~

**Comment by xia-chu** [comment]
合并了 谢谢大佬！
