### ISSUE TITLE
请问低帧率推流如何调试

### ISSUE THREAD

**Issue by zhuangdx** [xia-chu/ZLMediaKit#608]
开发者，你好：
这边接入低帧率海康监控摄像头时遇到个问题，
- 帧率在8帧/s以上时可以通过播放地址播放，延迟在2s以内。
- 帧率调低后，如1/2帧或者1/s帧，会导致播放地址无法获取画面。通过浏览器ws地址也是只能获取第一帧，之后画面一直卡在第一张。

这边尝试了调高maxStreamWaitMS、streamNoneReaderDelayMS，但没有改善，
请问有什么配置建议或者调试方法吗
谢谢

**Comment by xia-chu** [comment]
估计播放器不支持

**Comment by xia-chu** [comment]
你这个帧率还不至于接受超时

**Comment by zhuangdx** [comment]
帧率低于1帧时，容易导致播放器停止播放，并且推流不稳定，zlmediakit日志提示丢包

**Comment by TRYOKETHEPEN** [comment]
> 帧率低于1帧时，容易导致播放器停止播放，并且推流不稳定，zlmediakit日志提示丢包

请问这个问题后面有什么优化方式吗？
我现在也有使用RK3588视觉识别处理后1FPS推流的需求，播放也是只显示第一帧，拉流开启录制后，record视频每帧画面都正常但是帧间隔时间不正常（本应为1s，视频实际为1ms）。
