### ISSUE TITLE
录制下来的视频是否能通过接口删除

### ISSUE THREAD

**Issue by hhhuaang** [xia-chu/ZLMediaKit#609]
好像没看到有接口能删除录制的视频

**Comment by hhhuaang** [comment]
有考虑会添加一下功能吗？包括主机 cpu 内存 当前使用带宽的查询，对磁盘文件的基础管理，类似删除文件，下载文件的操作

**Comment by xia-chu** [comment]
> 好像没看到有接口能删除录制的视频

并没有 这个最好结合数据库来实现

**Comment by xia-chu** [comment]
> 有考虑会添加一下功能吗？包括主机 cpu 内存 当前使用带宽的查询，对磁盘文件的基础管理，类似删除文件，下载文件的操作

 这个很难做到跨平台的 这个事情应该由其他专业的软件实现

**Comment by hhhuaang** [comment]
/index/api/getSnap 接口好像有问题，调用返回404

**Comment by xia-chu** [comment]
需要安装ffmpeg 并且在配置文件中配置下ffmpeg的路径



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 黄晓旭 <notifications@github.com&gt;
发送时间: 2020年12月5日 14:54
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 录制下来的视频是否能通过接口删除 (#609)





 
/index/api/getSnap 接口好像有问题，调用返回404

**Comment by hhhuaang** [comment]
tks
