### ISSUE TITLE
[咨询]RtmpPush dns阻塞问题

### ISSUE THREAD

**Issue by Luosh** [xia-chu/ZLMediaKit#612]
二次开发拉流转rtmp推流功能, 测试发现, 当ZLM向外并发多个推流.url中域名地址填写出错(比如:push.error.com 这种无法解析的域名), zlm 整体功能受到影响, 拉流无法正常播放. 考虑可能是ZLM 线程池受到dns解析阻塞影响. 比如开了12个线程, 并发 12个dns异常解析. 这种情况下每个线程是不是都会被阻塞到dns超时?  导致正常代码无法执行.
不确定分析的对不对, 有没有好的解决方案, 望大神指导一二, 谢谢~

自己想的解决方案是, 阻塞dns解析时,不使用线程池线程, 另外创建独立线程做解析, 返回结果或超时后在切换回原本线程继续工作.这种是否可行, 会不会造成二次bug?

**Comment by xia-chu** [comment]
是的 你说的对， 要是dns全是这种无法解析 且阻塞很久的域名 会导致dns解析全部无法使用
