### ISSUE TITLE
请问下我想推送pcm，如何支持？

### ISSUE THREAD

**Issue by Dw9** [xia-chu/ZLMediaKit#613]

**Comment by xia-chu** [comment]
其实已经支持了 只是不能转协议而已

**Comment by Dw9** [comment]
我用的是ffmpeg推送的，但无法再用ffmpeg播放rtsp链接

**Comment by xia-chu** [comment]
FFmpeg能推pcm的rtsp 却不能播放？

**Comment by Dw9** [comment]
我的操作如下：
1、启动MediaServer

**Comment by Dw9** [comment]
我的操作如下：
1、 linux上启动MediaServer
2、 mac上命令行 ffmpeg -re -i 16k.wav -codec pcm_s16le -f rtsp -rtsp_transport tcp rtsp://192.168.3.9:554/live/test
现象：ffmpeg 播放不了该链接rtsp://192.168.3.9:554/live/test

**Comment by Dw9** [comment]
[16k.wav.zip](https://github.com/xia-chu/ZLMediaKit/files/5656585/16k.wav.zip)
实验音频样本

**Comment by xia-chu** [comment]
这是FFmpeg推流的sdp，所以FFmpeg推流就不支持pcm
```sdp
v=0
o=- 0 0 IN IP4 127.0.0.1
s=ç©ºç½æ ¼
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 58.64.100
m=audio 0 RTP/AVP 96
b=AS:256
a=control:streamid=0
```

**Comment by xia-chu** [comment]
从这个sdp中根本没法知道audio是什么编码格式

**Comment by Dw9** [comment]
是这样的。 通过wirshark抓包，sdp中抓不到编码信息。 但pcm本来就是无编码的，所以程序会提示无法支持此sdp.

**Comment by Dw9** [comment]
所以想请教一下作者大大，能否指点下怎样支持此类型的

**Comment by xia-chu** [comment]
你只要确保sdp能被播放器识别就行 zlm只是转发的 见不兼容不看zlm
程序提示无法支持此sdp是说这个track无法转换到其他协议 但是本协议还是ok的
