### ISSUE TITLE
如何配置最大连接数和日志

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#617]
如题，在wiki中没有看到如何对ZLMediaKit的最大连接数和日志进行配置，请教有人知道吗？

**Comment by xia-chu** [comment]
zlm在MediaServer主程序里面会自行设置最大连接数 一般不用单独设置

**Comment by mayomeng** [comment]
@xia-chu 大神，我这边有个需求，需要对流媒体服务器的大连接数和日志位置级别进行手动设置，请问是否有手动设置的方法呀？

**Comment by xia-chu** [comment]
日志级别在 启动时可以设置， 譬如：./MediaServer -l 2

**Comment by xia-chu** [comment]
最多连接数不能设置，默认已经是最大

**Comment by xia-chu** [comment]
程序本身不会限制最大连接数

**Comment by mayomeng** [comment]
多谢多谢
