### ISSUE TITLE
on_stream_changed 回调问题

### ISSUE THREAD

**Issue by Alec-DSheng** [xia-chu/ZLMediaKit#621]
on_stream_changed 这个流注册或注销的回调。在服务器监听这个回调每次都会发过来5个请求过来。想问一下这个是就是这样考虑的呢还是个bug

**Comment by wasphin** [comment]
schema 不一样

**Comment by xia-chu** [comment]
这个确实可以优化下  ，加个配置文件比较好，让用户决定监听哪种协议的注册事件

**Comment by Alec-DSheng** [comment]
明白了，感谢感谢
