### ISSUE TITLE
 PlayerProxy中导致rtmp拉流失败的一个推测

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#622]
### 场景：
使用test_pusher.cpp， 拉某个rtmp流，再转推rtmp://127.0.0.1/live/tv用来生成hls

### 遇到的问题是：
这个程序会在某些神秘时刻停止工作，经过排查，rtmppush还在工作（因为有失败后的定时重试）,rtmpplayer也在正常工作。

### 日志显示的是：
2020-12-09 01:03:37.392 W [12244] test_pusher.cpp:34 | Server connection is closed:1 end of file
2020-12-09 01:03:39.394 I [12244] test_pusher.cpp:54 | Re-Publishing...
大概是rtmp push 的源没有数据，在15秒后关闭了推流。

----------------------------------------------------------------------------------------------
### 故障可能出现的原因分析
在PlayerProxy.cpp中
void PlayerProxy::play(const string &strUrlTmp)的时候，setOnShutdown把媒体源置nullptr，
一旦在播放过程中遇到中断，_pMediaSrc就成了nullptr，在replay()， 以及播放成功后并未将媒体源加上，也就是还是nullptr。

```
setOnShutdown([weakSelf,strUrlTmp,piFailedCnt](const SockException &err) {
        auto strongSelf = weakSelf.lock();
        if(!strongSelf) {
            return;
        }
        //注销直接拉流代理产生的流：#532
        strongSelf->setMediaSource(nullptr);
        ....
}
```

产生的结果就是：
RtmpPlayerImp.h中，正常情况下，_rtmp_src和_delegate都不为空，chunkData会被分别写入_rtmp_src，和_delegate。
断开一次后，_rtmp_src为空，不写入数据了。
此时后续任务暂时不受影响，推流还是正常的。

```
    void onMediaData(const RtmpPacket::Ptr &chunkData) override {
        if (_rtmp_src) {
            if (!_set_meta_data && !chunkData->isCfgFrame()) {
                _set_meta_data = true;
                _rtmp_src->setMetaData(TitleMeta().getMetadata());
            }
            _rtmp_src->onWrite(chunkData);
        }
        if (!_delegate) {
            //这个流没有metadata
            _delegate.reset(new RtmpDemuxer());
        }
        _delegate->inputRtmp(chunkData);
    }
```
但是如果此时执行onCheckMeta()，_delegate重置，_delegate原先与mediasource的某种绑定就失效，推流就没数据了。
（此处是推断的，因为我不太清楚_rtmp_src在此处的作用， 不太清楚为什么 _rtmp_src->onWrite不执行，也不影响后续业务）
```
    bool onCheckMeta(const AMFValue &val) override {
        _rtmp_src = dynamic_pointer_cast<RtmpMediaSource>(_pMediaSrc);
        if (_rtmp_src) {
            _rtmp_src->setMetaData(val);
            _set_meta_data = true;
        }
	_delegate.reset(new RtmpDemuxer);
	_delegate->loadMetaData(val);
	
        return true;
    }
```

-------------------------------------------------------------------------------
### 解决办法：
replay()后，或onPlaySuccess()后像下面这样把媒体源加上？

```
    MediaSource::Ptr mediaSource;
    if(dynamic_pointer_cast<RtspPlayer>(_delegate)){
        //rtsp拉流
        GET_CONFIG(bool,directProxy,Rtsp::kDirectProxy);
        if(directProxy){
            mediaSource = std::make_shared<RtspMediaSource>(_vhost, _app, _stream_id);
        }
    } else if(dynamic_pointer_cast<RtmpPlayer>(_delegate)){
        //rtmp拉流,rtmp强制直接代理
        mediaSource = std::make_shared<RtmpMediaSource>(_vhost, _app, _stream_id);
    }
    if(mediaSource){
        setMediaSource(mediaSource);
        mediaSource->setListener(shared_from_this());
    }
```

**Comment by alongL** [comment]
停止rtmp源后，程序会回调 setOnShutdown中的内容 
strongSelf->setMediaSource(nullptr);


之后再用  https://github.com/xia-chu/ZLMediaKit/issues/455 中的ffmpeg脚本进行测试，可以完美复现此问题。
（此处的流是rtmp源处的脚本，ffmpeg停止1秒后重推，rtmp拉流这里会调用RtmpPlayerImp::onCheckMeta把_delegate.reset()
导致出现跟#455一样的问题。
```
#!/bin/bash
for((;;)); do \
        ./bin/ffmpeg -re -i jqr.mkv \
        -vcodec copy -acodec copy \
        -f flv -y rtmp://mediasource.com/live/my; \
        sleep 1; \
done
```

### 第2种可能的解决办法
是跟 https://github.com/xia-chu/ZLMediaKit/issues/455 一样

```
    bool onCheckMeta(const AMFValue &val) override {
        _rtmp_src = dynamic_pointer_cast<RtmpMediaSource>(_pMediaSrc);
        if (_rtmp_src) {
            _rtmp_src->setMetaData(val);
            _set_meta_data = true;
        }
		
	if (!_delegate) {//add this line
		_delegate.reset(new RtmpDemuxer);
		_delegate->loadMetaData(val);
	}
        return true;
    }
```

**Comment by xia-chu** [comment]
这个问题是修复了一个问题导致了另外一个问题，这个issue(#532)说，拉流失败时，MediaSource没注销，所以在OnShutdown事件中，我把MediaSource设置为空了，这样推流器绑定的MediaSource就失效了。
解决这个问题的办法就是，每次Rtmp MediaSource注册时，就重现创建推流器并绑定该Rtmp MediaSource。

**Comment by xia-chu** [comment]
前几天测试了这个的相关功能 很遗憾没能重现啊

**Comment by pzhu10** [comment]
@xia-chu 大神，请问最新的代码这个问题修复了吧，我用proxy_player代理rtsp流最近最近也发现了在某个神秘时刻会拉流失败，但是流并没有被删掉，因为vlc播放客户端再次拉流时，zlmedia没有进入on_mk_media_not_found回调，而是不断地尝试播放但是获取不到rtp 数据

**Comment by alongL** [comment]
@pzhu10  很遗憾。我认为并没有修复。你可以看一下PlayerProxy.cpp这个文件 

bool onCheckMeta(const AMFValue &val) override {   

并没有改变。
