### ISSUE TITLE
请问在这个框架上如何实现实时音频流转码的？比如g711a 到 aac 或 opus?

### ISSUE THREAD

**Issue by rmokerone** [xia-chu/ZLMediaKit#623]
我们基于这个框架实现了私有数据的rtp_mpegts格式rtp传输，现在**需要在服务端对音频流进行实时转码。**

主要目的如下：

- [x] 加密数据服务端解密；

- [x] 将g711数据转为aac/opus，方便通用客户端播放；

这个需求应该算比较通用，类似#407。

对这个框架理解不够，求指点下思路，在哪一块实现比较好，毕竟转码对计算资源的消耗还是比较大的。

非常感谢~

**Comment by xia-chu** [comment]
在MultiMediaSource.cpp里面实现就行，拦截Track和Frame，转码后输入新的Track和新的Frame

**Comment by xia-chu** [comment]
addFFmpegSource这个接口也能实现转码，你可以看看这个接口的实现代码，就大概知道怎么转码了

**Comment by ChnPhantom** [comment]
用easyaacencoder转码成aac

**Comment by a327958099** [comment]
> addFFmpegSource这个接口也能实现转码，你可以看看这个接口的实现代码，就大概知道怎么转码了
addFFmpegSource代理后延迟达到了16秒左右
