### ISSUE TITLE
异步写MP4

### ISSUE THREAD

**Issue by dengchaowen-cx** [xia-chu/ZLMediaKit#624]

**Comment by dengchaowen-cx** [comment]
您好：我想异步写mp4文件 先获取一个 _poller = WorkThreadPool::Instance().getPoller(); 然后调用_poller->async(）写数据到mp4文件 结果vlc播放器可以正常播放，但是http-flv播放不了 不知道什么原因。

**Comment by xia-chu** [comment]
写mp4不会影响http-flv的播放的 你vlc播放下rtmp试试

**Comment by dengchaowen-cx** [comment]
应该是我没有表达清楚，我在MP4Recorder类 构造函数 _poller = WorkThreadPool::Instance().getPoller(); 写数据的时候在MP4Recorder::inputFrame函数中调用_poller->async([muxer, frame]() {muxer->inputFrame(frame);},false); 录制的mp4文件在本地用vlc可以正常播放，但是用flv.js 播放器  websock-flv点播此mp4文件却播放不出来。不知道什么原因。

**Comment by xia-chu** [comment]
哦哦 ？ 那说明mp4文件没问题啊. ws-flv点播地址url粘贴上来，我看看是不是正确的。
另外把你ws-flv点播mp4录像时的zlm的日志粘贴上来

**Comment by dengchaowen-cx** [comment]
地址是正确的 我测试了多次 有的情况是完全点播不了 有的情况是播放十几秒就播不动了 我用的b站的那播放器flv.js 不不重新开线程录制就没有上述问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年12月17日 10:03
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 异步写MP4 (#624)





 
哦哦 ？ 那说明mp4文件没问题啊. ws-flv点播地址url粘贴上来，我看看是不是正确的。
 另外把你ws-flv点播mp4录像时的zlm的日志粘贴上来

**Comment by xia-chu** [comment]
日志啊老哥 没日志怎么分析

**Comment by dengchaowen-cx** [comment]
我重新测试了一下，没有log打印，我发现如果不写音频帧的话就没有问题，我同时两种情况一起录制录制，用比较工具二进制比较录制的两个mp4文件发现视频数据一样但是音频数据不一样，用vlc播放发现声音有问题，我之前没有注意，只关注了视频正常。没有去确认声音是否正常。

**Comment by dengchaowen-cx** [comment]
没有任何日志打印 只打印开启成功 啥都没有 播放器的日志我看不到



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年12月17日 18:03
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 异步写MP4 (#624)





 
日志啊老哥 没日志怎么分析

**Comment by dengchaowen-cx** [comment]
如果有日志看 我也不会来麻烦你了

**Comment by xia-chu** [comment]
我看看你怎么修改的代码

**Comment by dengchaowen-cx** [comment]
MultiMuxerPrivate构造函数添加_
poller = WorkThreadPool::Instance().getPoller();
在void MultiMuxerPrivate::onTrackFrame(const Frame::Ptr &frame)接口中修改
auto mp4 = _mp4;
if (mp4)
{
	mp41->inputFrame(frame);
});
为
auto mp4 = _mp4;
if (mp4)
{
	_poller->async([mp4, frame]() {
		mp4->inputFrame(frame);
});
就修改这两个地方，
同样的我poller放到MP4Recorder类中
在MP4Recorder构造函数中执行poller = WorkThreadPool::Instance().getPoller();
然后在void MP4Recorder::inputFrame(const Frame::Ptr &frame)函数中调用
_poller->async([muxer, frame]() {
			muxer->inputFrame(frame);
		});
也是同样的问题

通过比较Beyond Compare对比我发现有些音频帧的数据变了 但并不是每次音频数据会变，播放的时候声音也就有异常

**Comment by xia-chu** [comment]
有些frame不是cacheable的，也就是只有本次函数调用栈周期是有效的，传递到其他线程就失效了，所以你要转换成cacheAble的帧，
用Frame::getCacheAbleFrame转换就行

**Comment by dengchaowen-cx** [comment]
确实是这个问题导致的 问题已解决。可以解释一下这这两者的区别吗？

**Comment by xia-chu** [comment]
不可缓存的帧只是包含了内存的指针，并没有拷贝和持有它，所以你如果在本次函数栈生命周期结束后还访问它，那么它可能已经失效，或者被覆盖

**Comment by xia-chu** [comment]
设计不可缓存的帧的目的是为了提高性能 不用拷贝数据嘛 因为有些数据不是从zlm的代码出来的 它们只给zlm一个指针而已

**Comment by dengchaowen-cx** [comment]
非常感谢您的解答 我刚刚看了这几个封装的类 也搞清楚了里面的原理 非常感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年12月18日 15:34
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: dengchaowen-cx <1020443551@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 异步写MP4 (#624)





 
设计不可缓存的帧的目的是为了提高性能 不用拷贝数据嘛 因为有些数据不是从zlm的代码出来的 它们只给zlm一个指针而已
