### ISSUE TITLE
是否有服务器资源统计，流量统计等API接口？

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#627]
请问，是否有服务器资源统计，流量统计等信息统计类的API接口？如果没有的话，是否有推荐的统计方案？

**Comment by xia-chu** [comment]
现在有一定的统计功能，getMediaList接口能返回流的速度、流量等信息。
getThreadLoad接口能统计zlm的负载，不过这些接口都是应用内的信息，操作系统的，目前没有，这个绑定操作系统的，做跨平台不好做，而且这个不应该是zlm的工作
