### ISSUE TITLE
调用ffmpeg拉流时，是否可以填写ffmpeg参数

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#628]
调用API：addFFmpegSource可以通过ffmpeg拉流，请问是否可以在该AIP的参数中设置ffmpeg的各种参数，如改变分辨率，格式等，多谢！！！

**Comment by xia-chu** [comment]
其实这个很好实现 不过就怕别人瞎搞攻击你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mayomeng <notifications@github.com&gt;
发送时间: 2020年12月16日 14:24
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 调用ffmpeg拉流时，是否可以填写ffmpeg参数 (#628)





 
调用API：addFFmpegSource可以通过ffmpeg拉流，请问是否可以在该AIP的参数中设置ffmpeg的各种参数，如改变分辨率，格式等，多谢！！！

**Comment by xia-chu** [comment]
限制随意设定FFmpeg参数 不是做不到 而是不想太自由 太自由意味着无序、不安全、以及复杂。
很多人连FFmpeg都不知道是什么，你让他设置FFmpeg的参数 不是为难他么 现在addFFmpegSource接口比较简单，如果要支持设置FFmpeg参数，建议新增一个接口
