### ISSUE TITLE
rtsp player teardown时没有url

### ISSUE THREAD

**Issue by hh-kai** [xia-chu/ZLMediaKit#631]
rtsp player在打开没有数据的流的时候 重试的时候 在teardown时  request里面url为空 
能不能加上这个url
因为有些rtsp server在关闭地址时 会校验这个url  因为这个url在服务端是存在的
![无标题2](https://user-images.githubusercontent.com/19390025/102442178-bf913480-405e-11eb-8265-8821608d0c14.png)

**Comment by xia-chu** [comment]
其实teardown这个命令没啥用 直接close socket都行的

**Comment by hh-kai** [comment]
因为服务器端有个url的断言 所以次次都把服务器搞退出 目前就用_player_url 来代替参数url为空时的参数

**Comment by xia-chu** [comment]
> 
> 
> 因为服务器端有个url的断言 所以次次都把服务器搞退出 目前就用_player_url 来代替参数url为空时的值

你这个图我终于加载出来了 ，这个算是zlm的bug 我下次修复下。

**Comment by xia-chu** [comment]
已经修复
