### ISSUE TITLE
收到推流，但是播放404

### ISSUE THREAD

**Issue by sharcv** [xia-chu/ZLMediaKit#632]
作者你好，目前的情况，前端点播后通过tcpdump抓包发现有推流，并且此时 getMediaList 接口也有流信息，但是前端请求的 ws flv 为 404 ，zlm 日志如下，望回复：
MediaSource.cpp:391 emitEvent | 媒体注册:hls __defaultVhost__ rtp 138CF27A
RtpProcess.cpp:207 operator() | 138CF27A(192.168.53.27:26404) 允许RTP推流
GB28181Process.cpp:119 onRtpDecode | 138CF27A judged to be PS
CommonRtp.cpp:52 inputRtp | rtp丢包:35076 -> 35145
RtpSelector.cpp:109 onManager | RtpProcess timeout:138CF27A
TcpServer.h:143 ~TcpServer | close tcp server 0.0.0.0:30006
RtpProcess.cpp:54 ~RtpProcess | 138CF27A(192.168.53.27:26404) RTP推流器(__defaultVhost__/rtp/138CF27A)断开,耗时(s):0
MediaSource.cpp:391 emitEvent | 媒体注销:hls __defaultVhost__ rtp 138CF27A
HttpSession.cpp:24 HttpSession | 139924270117424(192.168.93.87:16460) 
HttpSession.cpp:112 onError | 139924288028352(192.168.13.55:60322) session timeouted

**Comment by xia-chu** [comment]
zlm rtp接受超时就关闭了

**Comment by xia-chu** [comment]
也有可能rtp接受到了 但是无法解析出数据

**Comment by sharcv** [comment]
有什么解决办法吗

**Comment by xia-chu** [comment]
你可以把rtp dump出文件给我调试下 请查看wiki了解怎么dump

**Comment by sharcv** [comment]
好的，我在群里，发你qq了~

**Comment by sharcv** [comment]
rtp dump 发你了~~

**Comment by xia-chu** [comment]
这个rtp不规范 时间戳一直为0，所以数据一直缓存在rtp解码器中，修改这里可以解决这个问题：
<img width="1151" alt="图片" src="https://user-images.githubusercontent.com/11495632/102612062-09ffd780-416b-11eb-9a44-da08ec5e6967.png">
默认是256K，改小点就行 。

**Comment by xia-chu** [comment]
老哥 给个star吧

**Comment by sharcv** [comment]
哈哈哈，原来一直没给，给了给了，感谢

**Comment by qiziwang** [comment]
播放成功了，但是不出向画面是什么情况，现在是在webrtc页面
![图片](https://github.com/user-attachments/assets/7f9b1210-9df5-4ebb-90dc-3cb3b859a986)

**Comment by qiziwang** [comment]
![Uploading 图片.png…]()
显示播放成功了，但是不出向画面是什么情况，现在是在webrtc页面

**Comment by qiziwang** [comment]
![Uploading 120yfy5r837xsh2syfunc40ye_0.jpg…]()

显示播放成功了，但是不出向画面是什么情况，现在是在webrtc页面
