### ISSUE TITLE
Optimize for HLS

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#634]
Hi,

I am trying your latest source code and add a RTSP stream to MediaServer by AddStreamProxy with enable HLS.
In www folder, i can see that *.ts file automatic created athough dont have any player connect to that HLS stream.
This  will comsuming more disk resource.
But with previous version: https://github.com/xia-chu/ZLMediaKit/tree/4132df89cdab9b068bb374c8e5781afb87960b75 
*.ts only created when there is a player connect to that stream.

Which is better ?

![ảnh](https://user-images.githubusercontent.com/59004953/102576170-778a1480-4127-11eb-83d6-0a83bc06f047.png)

**Comment by xia-chu** [comment]
Please change `hls_demand` to `1` to create ts file when demand:
![图片](https://user-images.githubusercontent.com/11495632/102578926-4d8c1e80-4136-11eb-985d-f2f8bb8c0dc0.png)

**Comment by xia-chu** [comment]
Stream generation on demand, good performance, but slightly less experience.
Now the default is to generate streams all the time, because I find that most people need good experience, not performance

**Comment by pubpy2015** [comment]
Thank you very much.

But seem performance of latest version is slower than previous version. CPU, RAM usage higher, ...
(on my laptop CPU usage of MediaServer increase 1.5 times)
this is my config with enable on demand:
[general]
addMuteAudio=1
enableVhost=0
flowThreshold=1024
fmp4_demand=1
hls_demand=1
maxStreamWaitMS=15000
mediaServerId=behkoruxBEHKORUX
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=1
rtsp_demand=0
streamNoneReaderDelayMS=20000
ts_demand=1

**Comment by xia-chu** [comment]
how many stream  do you pulled?

**Comment by pubpy2015** [comment]
Hi,
I have 36 IP cameras, each camera have 2 streams (high and low resolution)  => total 72 streams

**Comment by xia-chu** [comment]
Can you use `perf top`? I'd like to see how the CPU usage of the old and new versions of the code is

**Comment by pubpy2015** [comment]
I am using MediaServer.exe on Window PC.

**Comment by xia-chu** [comment]
Then I may have to check it out later.
You can tell me the GIT hash of your old code and the GIT hash of your new code

**Comment by pubpy2015** [comment]
Yes,

I will test more and report to you.

**Comment by xia-chu** [comment]
> Then I may have to check it out later.
> 
> You can tell me the GIT hash of your old code and the GIT hash of your new code


i mean git commit hash.

**Comment by pubpy2015** [comment]
old code here: https://github.com/xia-chu/ZLMediaKit/tree/4132df89cdab9b068bb374c8e5781afb87960b75
and new code is latest.
