### ISSUE TITLE
ZLM有集群方案吗

### ISSUE THREAD

**Issue by wanglimeng** [xia-chu/ZLMediaKit#636]
现在项目有大量的摄像头，8万左右，想问一下ZML有大集群的方案吗 
我在网上搜索搜不到 @

**Comment by xia-chu** [comment]
集群一般大公司的大项目才会用到，一家大公司没几个开发者吗？也想躺着让开源作者给他干活，然后就把钱赚了？
况且本项目成立以来，从未收到大公司的任何支持(特别是代码提交)，相反，支持更多的是个人开发者和中小型公司，
集群这种针对大公司大项目的特性，zlm目前是不会去支持的，除非大公司也能参与贡献代码。

**Comment by wanglimeng** [comment]
好吧 那我先自己试试 ，我的还有点特殊，gb28181的。感谢作者提供的流媒体服务，尤其是多核支持，特别棒。
