### ISSUE TITLE
RTP丢包 花屏

### ISSUE THREAD

**Issue by CHENGKUNHOU** [xia-chu/ZLMediaKit#637]
非常感谢作者优秀的开源工作！使用时发现rtp丢包，使用ffmplay播放会出现花屏现象，特来请教。
使用场景如下：利用ffmpeg拉取海康的IPC的RTSP流，4k分辨率，码流8Mbps,然后通过rtp转发，再推流至rtsp
即使用如下两行代码：
`ffmpeg -rtsp_transport tcp -i rtsp://admin:**@**/steam  -vcodec copy -f rtp rtp://127.0.0.1:6001 > vid.sdp`
`ffmpeg -protocol_whitelist "file,rtp,udp" -i vid.sdp -vcodec copy -f rtsp://127.0.0.1/live/stream`

![拉流](https://user-images.githubusercontent.com/26861188/102785111-6451a000-43d8-11eb-82d1-292bcc6b083d.jpg)
图1 拉流

![sdp丢包](https://user-images.githubusercontent.com/26861188/102785211-8a774000-43d8-11eb-9446-49f03512d8b3.jpg)
图2 rtp推流至rtsp丢包情况

![zlm服务器](https://user-images.githubusercontent.com/26861188/102785302-bb577500-43d8-11eb-9009-b26a53945eac.jpg)
图3 为zlm的提示信息，提示rtp丢包、丢帧

![播放丢包](https://user-images.githubusercontent.com/26861188/102785409-e6da5f80-43d8-11eb-96f5-125f2f3f0768.jpg)
图4 为使用ffplay播放丢包情况

请问以上有何办法能够保证尽量不丢包呢？因业务要求，拉流后需要向某端口通过udp发送数据。
已尝试如下方法均为奏效，

- 修改系统udp读写buffer大小，还是会明显丢包
- 修改zlm中的udp 读写缓存也未奏效
- 修改zlm配置文件中的videoMtuSize 为1500也还是丢包
- 尝试直接拉取rtsp流进行rtsp推流也发现丢包，会有一定花屏,（虽然不符合业务要求）

请问下，出现该情况的问题根源在哪呢？有解决的办法吗？或者是解决的方向？烦请大佬指教，新手已经看完全部wiki和历史issue好像都没找到解决办法，求指教！！

**Comment by xia-chu** [comment]
推流命令改成这个试试：
ffmpeg -protocol_whitelist "file,rtp,udp" -i vid.sdp -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/stream

**Comment by CHENGKUNHOU** [comment]
感谢您的回复。试了下，还是会出现花屏，丢包情况还是很严重

**Comment by xia-chu** [comment]
这样呢：
ffmpeg -rtsp_transport tcp -i rtsp://admin:**@**/steam -vcodec copy -f rtsp://127.0.0.1/live/stream

**Comment by CHENGKUNHOU** [comment]
这也会丢包，也有花屏，但是比之前情况好点，之前尝试过，一直没有出现不丢包的情况。

**Comment by xia-chu** [comment]
ffplay -rtsp_transport tcp -i rtsp://admin:@/steam 能播放不花屏吗

**Comment by CHENGKUNHOU** [comment]
对的，直接播放不花屏的，目前尝试还有直接保存到本地没问题，或者保存本地再读取本地推流没问题，是不是这种转发的8Mbps的太大了会出问题呢

**Comment by xia-chu** [comment]
ffmpeg -rtsp_transport tcp -i rtsp://admin:**@**/steam -vcodec copy -f rtp rtp://127.0.0.1:6001 > vid.sdp
ffmpeg -protocol_whitelist "file,rtp,udp" -i vid.sdp -vcodec copy -f flv ./test.flv

**Comment by xia-chu** [comment]
保存为flv文件 看看是否花屏

**Comment by CHENGKUNHOU** [comment]
终端打印丢包信息，会花屏

**Comment by xia-chu** [comment]
你在中转成rtp（udp）时就丢包了

**Comment by xia-chu** [comment]
按道理，这样不会丢包的：
```bash
ffmpeg -rtsp_transport tcp -i rtsp://admin:@/steam -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/stream
```

**Comment by CHENGKUNHOU** [comment]
对啊，我之前估计应该直接推rtsp应该不丢包，结果还是丢包，这个是摄像头本身的问题吗？有没可能是发生的流有什么标志位之类的，然后接收端这边没解析到默认直接丢弃了？

**Comment by xia-chu** [comment]
> 
> 
> 按道理，这样不会丢包的：
> 
> ```shell
> ffmpeg -rtsp_transport tcp -i rtsp://admin:@/steam -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/stream
> ```


你这样推流给zlm 然后这样播放：

ffplay rtsp://127.0.0.1/live/stream -rtsp_transport tcp

如果还花屏 说明你摄像头有问题

**Comment by CHENGKUNHOU** [comment]
这种不花屏的，有什么办法可以udp中转尽量减少丢包吗

**Comment by xia-chu** [comment]
没办法 这个是操作系统和FFmpeg的缺陷导致的

**Comment by xia-chu** [comment]
操作系统可以增加udp的读buffer上限值 但是不同操作系统不一样
FFmpeg应该也可以修改udp读缓存上限值
你用rtp udp中转流 在大码率情况下丢包很正常

**Comment by xia-chu** [comment]
你这样推流：
ffmpeg -rtsp_transport tcp -i rtsp://admin:@/steam -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/stream
然后这样播放:
ffplay rtsp://127.0.0.1/live/stream -rtsp_transport tcp

也花屏？

**Comment by CHENGKUNHOU** [comment]
这种情况不花屏，很稳定。

**Comment by xia-chu** [comment]
> 
> 
> 这种不花屏的，有什么办法可以udp中转尽量减少丢包吗

这样不花屏 说明原始的rtsp没问题 zlm也没问题

**Comment by CHENGKUNHOU** [comment]
这种rtp udp中转可以手动写个大的buffer缓存然后再发送吗？还是说就算写了由于udp在linux下本身上限问题还是没办法改善呢？

**Comment by xia-chu** [comment]
可以改下内核参数试试  就是udp的读缓存上限，自己百度下。
另外FFmpeg的udp端口读缓存大小不知道能不能参数设置，不能的话 那就要改FFmpeg的代码。

**Comment by xia-chu** [comment]
反正你选择这种技术方案就意味着很麻烦

**Comment by CHENGKUNHOU** [comment]
对的，因为业务需要只能udp单向传输无法追踪那种，这种单向性只能采用udp的方式了吧？

**Comment by xia-chu** [comment]
搞iptv直播啊？

**Comment by CHENGKUNHOU** [comment]
也不算吧，就是需要保证最高画面质量拉流，延迟高点都没关系，重在无法发送到指定端口然后在该端口接收即可

**Comment by CHENGKUNHOU** [comment]
您有建议吗？除了udp传输之外？还有其他方式可以满足这种要求吗

**Comment by xia-chu** [comment]
试试文件中转

**Comment by xia-chu** [comment]
你的业务我不清楚 没法建议

**Comment by CHENGKUNHOU** [comment]
好的，我多尝试尝试，非常感谢大佬抽空解答，小白学习中，如有能力定来pr！！

**Comment by CHENGKUNHOU** [comment]
来反馈更新下，目前通过设置ffmpeg源码udp.c中的UDP_MAX_PKT_SIZE 65536增大10倍解决该问题，基本在8Mbps码流不丢包，注意对应的系统udp读buffer也要对应更改，具体数值可以根据需求来改。问题基本解决，感谢大佬提供的思路，感谢开源工作，特来还愿。

**Comment by xia-chu** [comment]
谢谢反馈！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wesley <notifications@github.com&gt;
发送时间: 2020年12月23日 09:44
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] RTP丢包 花屏 (#637)





 
来反馈更新下，目前通过设置ffmpeg源码udp.c中的UDP_MAX_PKT_SIZE 65536增大10倍解决该问题，基本在8Mbps码流不丢包，注意对应的系统udp读buffer也要对应更改，具体数值可以根据需求来改。问题基本解决，感谢大佬提供的思路，感谢开源工作，特来还愿。
