### ISSUE TITLE
gb28181推流画面模糊

### ISSUE THREAD

**Issue by sunyong518** [xia-chu/ZLMediaKit#638]

**Comment by xia-chu** [comment]
预览摄像头应该是rtsp协议，GB28181推流，应该可以控制主码流和子码流 你确定是主码流吗

**Comment by sunyong518** [comment]
是用的子码流，设置的h264，但是我用另一个三方平台的连接上去，画面是清晰的，没变动摄像头的其他配置

**Comment by xia-chu** [comment]
那说明别的平台可能是主码流？

**Comment by sunyong518** [comment]
![image](https://user-images.githubusercontent.com/37390509/102967118-37160680-452c-11eb-9b87-b3ba866fee37.png)
第三方平台我是用的liveqing的LiveGBS演示平台，更改sip配置，连接上去看效果是清晰的，可能是流媒体转码的问题，大神ZLMediaKit有没有配置属性是提高转码清晰度的。

**Comment by xia-chu** [comment]
zlm不转码的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunyong518 <notifications@github.com&gt;
发送时间: 2020年12月23日 14:40
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] gb28181推流画面模糊 (#638)





 

 第三方平台我是用的liveqing的LiveGBS演示平台，更改sip配置，连接上去看效果是清晰的，可能是流媒体转码的问题，大神ZLMediaKit有没有配置属性是提高转码清晰度的。

**Comment by sunyong518** [comment]
那有没有调整流服务清晰度的地方

**Comment by xia-chu** [comment]
这个是sip服务器选择分辨率的问题 zlm不会转码 所以清不清晰跟zlm一点关系都没有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunyong518 <notifications@github.com&gt;
发送时间: 2020年12月24日 11:33
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] gb28181推流画面模糊 (#638)





 
那有没有调整流服务清晰度的地方
