### ISSUE TITLE
请问最新master中 mp4.cpp 85行fmp4_writer_write_l和87行 mov_writer_write_l 这两个方法实现在哪里呢

### ISSUE THREAD

**Issue by ziyuyouxia** [xia-chu/ZLMediaKit#646]
请问最新master中 mp4.cpp 85行fmp4_writer_write_l和87行 mov_writer_write_l 这两个方法实现在哪里呢

**Comment by xia-chu** [comment]
在我fork的分支里面https://github.com/xia-chu/media-server
