### ISSUE TITLE
win10  vs2019编译失败

### ISSUE THREAD

**Issue by zhuqiyun** [xia-chu/ZLMediaKit#647]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“libssl64MDd.lib”	E:\dev\gxy\video\ZLMediaKit\out\build\x64-Debug (默认值)\ZLMediaKit	E:\dev\gxy\video\ZLMediaKit\out\build\x64-Debug (默认值)\LINK	1

**Comment by xia-chu** [comment]
你卸载你电脑上32位的OpenSSL 再按照64位的OpenSSL不就行了？zlm qq群里面有分享OpenSSL按照包
