### ISSUE TITLE
一级二级缓存问题

### ISSUE THREAD

**Issue by dengchaowen-cx** [xia-chu/ZLMediaKit#649]
你好，我想请教一下bool Socket::flushData(const SockFD::Ptr &sock, bool poller_thread) 里面使用一级和二级缓存有什么优势吗？谢谢！

**Comment by xia-chu** [comment]
发送缓存有两级别，分包存放在_send_buf_sending和_send_buf_waiting链表中，
其中，_send_buf_sending链表直接用于写socket，_send_buf_waiting链表会转换成BufferList对象再移入到_send_buf_sending链表中。

其实就是把发送缓存切段，因为sendmsg这样的接口是批量发送数据的，所以数据要分段发送，设计两级缓存，目的是更好的适配sendmsg这个批量发送接口，从而减少系统调用。
