### ISSUE TITLE
提个小建议，HTTP API流ID参数建议保持一致

### ISSUE THREAD

**Issue by yarafa** [xia-chu/ZLMediaKit#653]
如题，流ID有的地方是stream，有的地方是stream_id，建议保持一致。
如提法不正确，请忽略。

**Comment by xia-chu** [comment]
抱歉啊 确实有不严谨不统一的地方
http接口现在不太好改 因为会导致其他用户不兼容

**Comment by xia-chu** [comment]
这个issue先关闭了 api不兼容 很多用户会骂人的 抱歉
