### ISSUE TITLE
配置ssl证书遇到问题,使用https访问时,浏览器报错 “使用了不受支持的协议”

### ISSUE THREAD

**Issue by gao0205** [xia-chu/ZLMediaKit#657]
阿里云官网申请的pem证书，启动命令nohup ./MediaServer -d -s ./ssl.pem，但是浏览器访问时报错

ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

谷歌和火狐均无法访问

**Comment by xia-chu** [comment]
里面有公钥和私钥吗

**Comment by xia-chu** [comment]
这个问题一般是你的pem证书里面只有公钥
你把公钥私钥复制粘贴在一起就行了

**Comment by gao0205** [comment]
把.key里边的信息粘贴到.pem文件里边是吗



---原始邮件---
发件人: "夏楚"<notifications@github.com&gt;
发送时间: 2020年12月26日(周六) 下午5:44
收件人: "xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送: "gao0205"<673596700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xia-chu/ZLMediaKit] 配置ssl证书遇到问题,使用https访问时,浏览器报错 “使用了不受支持的协议” (#657)




 
这个问题一般是你的pem证书里面只有公钥
 你把公钥私钥复制粘贴在一起就行了

**Comment by xia-chu** [comment]
是啊

**Comment by gao0205** [comment]
好的，我已经解决了这个问题，感谢大佬支持



---原始邮件---
发件人: "夏楚"<notifications@github.com&gt;
发送时间: 2020年12月28日(周一) 上午9:32
收件人: "xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送: "gao0205"<673596700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xia-chu/ZLMediaKit] 配置ssl证书遇到问题,使用https访问时,浏览器报错 “使用了不受支持的协议” (#657)




 
是啊
