### ISSUE TITLE
录制时的MP4文件是否可以做到一边录制一边播放

### ISSUE THREAD

**Issue by LGxxxxxx** [xia-chu/ZLMediaKit#658]
目前录制生成的MP4文件只能录制结束后进行播放，是否可以做到录制过程中通过HTTP进行播放？

**Comment by xia-chu** [comment]
改成fmp4录制就行

**Comment by xia-chu** [comment]
请参考这个issue：#592
里面说了怎么把mp4录制改成fmp4录制

**Comment by LGxxxxxx** [comment]
尝试参考这种方式改为fmp4后，播放录像首帧时间变得非常长，请问是什么原因。

> 请参考这个issue：#592
> 里面说了怎么把mp4录制改成fmp4录制

**Comment by xia-chu** [comment]
> 放录像首帧时间变得非常长，请问是什么原因。

你是什么协议什么播放器播放？
网速给力不？fmp4文件直接播放呢？

**Comment by n45284** [comment]
我也遇到相同的问题， 修改录制方式为fmp4后， 播放首帧时间变得非常长。
播放是通过Chrome通过mp4文件的url播放的。
同样的方式播放MP4录制的文件没有问题， 但fmp4录制的文件首帧需要13秒以上。
fmp4文件用vlc播放没有类似的问题。
ps： 从浏览器来看， 播放时需要下载40+MB的数据后才能播放出首帧

**Comment by xia-chu** [comment]
> 
> 
> @xia-chu 我也遇到相同的问题， 修改录制方式为fmp4后， 播放首帧时间变得非常长。
> 播放是通过Chrome通过mp4文件的url播放的。
> 同样的方式播放MP4录制的文件没有问题， 但fmp4录制的文件首帧需要13秒以上。
> fmp4文件用vlc播放没有类似的问题。
> ps： 从浏览器来看， 播放时需要下载40+MB的数据后才能播放出首帧

你怎么修改代码的？

**Comment by n45284** [comment]
> > @xia-chu 我也遇到相同的问题， 修改录制方式为fmp4后， 播放首帧时间变得非常长。
> > 播放是通过Chrome通过mp4文件的url播放的。
> > 同样的方式播放MP4录制的文件没有问题， 但fmp4录制的文件首帧需要13秒以上。
> > fmp4文件用vlc播放没有类似的问题。
> > ps： 从浏览器来看， 播放时需要下载40+MB的数据后才能播放出首帧
> 
> 你怎么修改代码的？

参考#592， 我只修改了这些：
![image](https://user-images.githubusercontent.com/37611452/114518003-7bf7b180-9c71-11eb-9f1a-ee68916d0b5b.png)
代码是基于8d50d3c39732852e9dd08c240c40f18536b62c0a

**Comment by xia-chu** [comment]
> 
> 
> > > @xia-chu 我也遇到相同的问题， 修改录制方式为fmp4后， 播放首帧时间变得非常长。
> > > 播放是通过Chrome通过mp4文件的url播放的。
> > > 同样的方式播放MP4录制的文件没有问题， 但fmp4录制的文件首帧需要13秒以上。
> > > fmp4文件用vlc播放没有类似的问题。
> > > ps： 从浏览器来看， 播放时需要下载40+MB的数据后才能播放出首帧
> > 
> > 
> > 你怎么修改代码的？
> 
> 参考#592， 我只修改了这些：
> ![image](https://user-images.githubusercontent.com/37611452/114518003-7bf7b180-9c71-11eb-9f1a-ee68916d0b5b.png)
> 代码是基于8d50d3c39732852e9dd08c240c40f18536b62c0a

应该这样的：createWriter(MOV_FLAG_SEGMENT, true);

**Comment by xia-chu** [comment]
你可以参考MP4MuxerMemory对象的代码

**Comment by n45284** [comment]
> > > > @xia-chu 我也遇到相同的问题， 修改录制方式为fmp4后， 播放首帧时间变得非常长。
> > > > 播放是通过Chrome通过mp4文件的url播放的。
> > > > 同样的方式播放MP4录制的文件没有问题， 但fmp4录制的文件首帧需要13秒以上。
> > > > fmp4文件用vlc播放没有类似的问题。
> > > > ps： 从浏览器来看， 播放时需要下载40+MB的数据后才能播放出首帧
> > > 
> > > 
> > > 你怎么修改代码的？
> > 
> > 
> > 参考#592， 我只修改了这些：
> > ![image](https://user-images.githubusercontent.com/37611452/114518003-7bf7b180-9c71-11eb-9f1a-ee68916d0b5b.png)
> > 代码是基于8d50d3c39732852e9dd08c240c40f18536b62c0a
> 
> 应该这样的：createWriter(MOV_FLAG_SEGMENT, true);

我有尝试过使用MOV_FLAG_SEGMENT， 但是这样录制出来的视频浏览器直接无法播放了， 也看不出什么报错。

**Comment by xia-chu** [comment]
先调用initSegment 然后调用 saveSegment

**Comment by xia-chu** [comment]
fmp4也有个头 在添加所有Track后应该生成这个头

**Comment by xia-chu** [comment]
```patch
Index: src/Record/MP4Muxer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Record/MP4Muxer.cpp b/src/Record/MP4Muxer.cpp
--- a/src/Record/MP4Muxer.cpp	(revision a4ba0c2b60c682e823cc0900fb42b422d75ecb0e)
+++ b/src/Record/MP4Muxer.cpp	(date 1618381598000)
@@ -29,7 +29,7 @@
 
 MP4FileIO::Writer MP4Muxer::createWriter(){
     GET_CONFIG(bool, mp4FastStart, Record::kFastStart);
-    return _mp4_file->createWriter(mp4FastStart ? MOV_FLAG_FASTSTART : 0, false);
+    return _mp4_file->createWriter(MOV_FLAG_SEGMENT, true);
 }
 
 void MP4Muxer::closeMP4(){
@@ -79,6 +79,8 @@
         }
         //开始写文件
         _started = true;
+        initSegment();
+        saveSegment();
     }
 
     //mp4文件时间戳需要从0开始
```

**Comment by n45284** [comment]
> ```diff
> Index: src/Record/MP4Muxer.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/Record/MP4Muxer.cpp b/src/Record/MP4Muxer.cpp
> --- a/src/Record/MP4Muxer.cpp	(revision a4ba0c2b60c682e823cc0900fb42b422d75ecb0e)
> +++ b/src/Record/MP4Muxer.cpp	(date 1618381598000)
> @@ -29,7 +29,7 @@
>  
>  MP4FileIO::Writer MP4Muxer::createWriter(){
>      GET_CONFIG(bool, mp4FastStart, Record::kFastStart);
> -    return _mp4_file->createWriter(mp4FastStart ? MOV_FLAG_FASTSTART : 0, false);
> +    return _mp4_file->createWriter(MOV_FLAG_SEGMENT, true);
>  }
>  
>  void MP4Muxer::closeMP4(){
> @@ -79,6 +79,8 @@
>          }
>          //开始写文件
>          _started = true;
> +        initSegment();
> +        saveSegment();
>      }
>  
>      //mp4文件时间戳需要从0开始
> ```

多谢大佬指点， 我尝试一下。
另外按这个原理看， 只是在写完mp4的识货调用的话， 如果是播放正在录制的那个录像， 大概还是会有首帧慢的问题？
盲猜如果要解决这个问题就得每一个track都更新mp4头？

**Comment by xia-chu** [comment]
不会的 照你那样说 那fmp4直播没法做了

**Comment by n45284** [comment]
> ```diff
> Index: src/Record/MP4Muxer.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/Record/MP4Muxer.cpp b/src/Record/MP4Muxer.cpp
> --- a/src/Record/MP4Muxer.cpp	(revision a4ba0c2b60c682e823cc0900fb42b422d75ecb0e)
> +++ b/src/Record/MP4Muxer.cpp	(date 1618381598000)
> @@ -29,7 +29,7 @@
>  
>  MP4FileIO::Writer MP4Muxer::createWriter(){
>      GET_CONFIG(bool, mp4FastStart, Record::kFastStart);
> -    return _mp4_file->createWriter(mp4FastStart ? MOV_FLAG_FASTSTART : 0, false);
> +    return _mp4_file->createWriter(MOV_FLAG_SEGMENT, true);
>  }
>  
>  void MP4Muxer::closeMP4(){
> @@ -79,6 +79,8 @@
>          }
>          //开始写文件
>          _started = true;
> +        initSegment();
> +        saveSegment();
>      }
>  
>      //mp4文件时间戳需要从0开始
> ```

大佬，我按照这个代码修改了并尝试了一下， 发现MOV_FLAG_SEGMENT方式录制的视频确实可以播放出来了， 但是首帧慢的问题还是存在， 我尝试录了一段20分钟的视频， 首帧仍然需要10s左右的加载时间。

**Comment by xia-chu** [comment]
initSegment();
saveSegment();
这两句代码加了吗

**Comment by xia-chu** [comment]
ffplay直接播放文件速度快吗

**Comment by n45284** [comment]
更新一些信息：
尝试用vlc通过http播放这个fmp4文件。 
可以秒播， 但是不能做seek操作，进行seek操作时vlc出现该提示：
![image](https://user-images.githubusercontent.com/37611452/114668693-998d4f80-9d33-11eb-9276-720ab74bf8fb.png)
根据提示选择建立索引后， 需要等待10s左右， 就可以自由seek， 也知道视频长度了， 怀疑浏览器做了类似的事情。

**Comment by n45284** [comment]
> initSegment();
> saveSegment();
> 这两句代码加了吗

代码都加了~，否则放都放不了~

**Comment by xia-chu** [comment]
嗯 fmp4确实一般不能seek的 这是真的 如果FFmpeg和vlc都能秒开文件 说明文件问题不大 你可以把文件放上来

**Comment by n45284** [comment]
> 嗯 fmp4确实一般不能seek的 这是真的 如果FFmpeg和vlc都能秒开文件 说明文件问题不大 你可以把文件放上来

原视频不方便放上来， 重新录了一段， 问题是一样的：链接: https://pan.baidu.com/s/1ogSfsL5PBChShT0lMLtqKg 提取码: frvx 

这个6分钟的视频大约需要6s左右时间出首帧。
ps: 文件vlc本地播放时建立建立索引的速度非常快，但也有这个过程

**Comment by xia-chu** [comment]
fmp4可能确实不适合http点播

**Comment by xia-chu** [comment]
但是如果本地能快速加载fmp4文件 那说明http协议或浏览器对fmp4兼容性不好

**Comment by n45284** [comment]
看上去是的， 那只能走别的办法了。。。

**Comment by Luosh** [comment]
我试了写fmp4的录制文件， chrome浏览器似乎需要将整个文件下载下来才去播， 所以当文件比较大下载比较慢的时候， 就会有类似等待首帧的感觉， 再flag 加上faststart效果一样， firefox倒是不会一下下载全部。

不知道是否算有改善空间？

**Comment by crolin-zhang** [comment]
> 但是如果本地能快速加载fmp4文件 那说明http协议或浏览器对fmp4兼容性不好

可以做什么设置能支持fmp4的seek 呢？  而不是让播放器建立索引？
