### ISSUE TITLE
流媒体服务器不支持SIP通信吗

### ISSUE THREAD

**Issue by huolianchiyun** [xia-chu/ZLMediaKit#660]
![Uploading image.png…]()

**Comment by xia-chu** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: huolianchiyun <notifications@github.com&gt;
发送时间: 2020年12月28日 17:55
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 流媒体服务器不支持SIP通信吗 (#660)

**Comment by huolianchiyun** [comment]
谢谢，那怎么按28181中点播 流程走呢，因为28181流程上是sip服务与设备流媒体服务要建立sip会话，交互的



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------

**Comment by xia-chu** [comment]
readme中有推荐的相关工程 你可以了解下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: huolianchiyun <notifications@github.com&gt;
发送时间: 2020年12月28日 18:07
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 流媒体服务器不支持SIP通信吗 (#660)





 谢谢，那怎么按28181中点播 流程走呢，因为28181流程上是sip服务与设备流媒体服务要建立sip会话，交互的 
 
 
 
 Sent&amp;nbsp;from&amp;nbsp;my&amp;nbsp;iPhone 
 
 
 ------------------ 原始邮件 ------------------

**Comment by huolianchiyun** [comment]
关键我们要按28181来的



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------

**Comment by mayomeng** [comment]
SIP服务自己实现，用ZLMediaKit做流媒体服务器，发送播放命令的时候，流媒体IP和端口填ZLMediaKit的就行

**Comment by huolianchiyun** [comment]
sip服务我们自己搞的 但28181要求流媒体服务要和sip服务之间通过sip协议交互 所以流媒体服务要支持sip通信



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------

**Comment by xia-chu** [comment]
> sip服务我们自己搞的 但28181要求流媒体服务要和sip服务之间通过sip协议交互 所以流媒体服务要支持sip通信

没这个要求啊  现在GB28281第三方sip服务器跟zlm配合工作的不是挺好吗

**Comment by huolianchiyun** [comment]
我们项目 这么要求的 呵呵



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------

**Comment by mayomeng** [comment]
GB28181里面并没有要求SIP信令服务器和流媒体服务器必须是一台服务器，首先SIP是信令，可以理解为控制摄像头的命令，是文本协议，流媒体服务器是用来承载摄像头推送的RTP码流的。根本不是一回事。
