### ISSUE TITLE
RESTful接口`/index/api/addStreamProxy`在动态添加rtsp拉流代理时，一直提示msg:"DESCRIBE: 401 Unauthorized"

### ISSUE THREAD

**Issue by 17Sdubin** [xia-chu/ZLMediaKit#663]
我用是Hik IPC测试的，其中一台设备直接可以添加成功，另外两台一直提示msg:"DESCRIBE: 401 Unauthorized"，请问楼主大神呢，这个是那方便的问题呢，三台相机的配置和认证方式是一样的，我想在正在从源码层面跟，因为对c不熟，时间又比较紧迫，想请教下经验

**Comment by xia-chu** [comment]
你的rtsp url带参数 需要转义后才能作为http的参数 &nbsp;


发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 17Sdubin <notifications@github.com&gt;
发送时间: 2020年12月29日 14:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] RESTful接口`/index/api/addStreamProxy`在动态添加rtsp拉流代理时，一直提示msg:"DESCRIBE: 401 Unauthorized" (#663)





 
我用是Hik IPC测试的，其中一台设备直接可以添加成功，另外两台一直提示msg:"DESCRIBE: 401 Unauthorized"，请问楼主大神呢，这个是那方便的问题呢，三台相机的配置和认证方式是一样的，我想在正在从源码层面跟，因为对c不熟，时间又比较紧迫，想请教下经验

**Comment by 17Sdubin** [comment]
感谢大神，已成功解决，顶一个！^-^

**Comment by Jason5592** [comment]
> 感谢大神，已成功解决，顶一个！^-^

怎么解决的，我也遇到这个问题，两款摄像头，一个正常播放，一个报401

**Comment by zhengang-Hou** [comment]
RESTful接口/index/api/addStreamProxy在动态添加rtsp拉流代理时，一直提示msg:"DESCRIBE: 404 Not Found "
