### ISSUE TITLE
websocket-fmp4 使用是否有哪位写了文档，可否贡献到wiki

### ISSUE THREAD

**Issue by caojunwei1988** [xia-chu/ZLMediaKit#664]
没有看到测试的文档，有哪位大神方便共享下吗？

再次感谢作者提供这么强大的开源项目。

**Comment by xia-chu** [comment]
你看wiki url规则篇就行 
http-fmp4直播 zlm默认生成 你不用特殊配置

**Comment by caojunwei1988** [comment]
搞定了，我把我遇到的几个问题记录下，希望帮到其他人
（1）ws端口是80
（2）ws的url有格式校验 （.live.mp4 后缀）
我的推流命令：ffmpeg -re -i "./localvideos/testh265.mp4" -vcodec copy -acodec copy -f flv rtmp://127.0.0.1/live/test
wsurl是：ws://10.72.55.67:80/live/test.live.mp4
（3）支持H265，已验证，强大！！感谢作者！@xia-chu

**Comment by xia-chu** [comment]
ws-fmp4你用的什么播放器？推荐一个

**Comment by caojunwei1988** [comment]
> ws-fmp4你用的什么播放器？推荐一个

现在是保存的（.mp4）文件，用vlc播放可以播放。
正在开发基于MSE的无插件播放器，开发完了可以吧.js分享出来.

**Comment by xia-chu** [comment]
厉害了👍🏻



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: caojunwei1988 <notifications@github.com&gt;
发送时间: 2020年12月31日 09:53
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] websocket-fmp4 使用是否有哪位写了文档，可否贡献到wiki (#664)





  
ws-fmp4你用的什么播放器？推荐一个
  
现在是保存的（.mp4）文件，用vlc播放可以播放。
 正在开发基于MSE的无插件播放器，开发完了可以吧.js分享出来.

**Comment by xia-chu** [comment]
等你好消息 issue先关闭了

**Comment by xia-chu** [comment]
@caojunwei1988 你的ws-fmp4播放器播放ws-fmp4成功了没？

**Comment by caojunwei1988** [comment]
> @caojunwei1988 你的ws-fmp4播放器播放ws-fmp4成功了没？

目前还在调优【我这主要是针对H265】
（1）需要支持Hevc解码的浏览器（自己编译chromium、或者使用edge安装hecv插件）
（2）ZLMediaKit需要修改fmp4支持ISO5

> static int fmp4_writer_init(struct mov_t* mov)
> {
> 	if (mov->flags & MOV_FLAG_SEGMENT)
> 	{
> 		mov->ftyp.major_brand = MOV_BRAND_MSDH;
> 		mov->ftyp.minor_version = 0;
> 		mov->ftyp.brands_count = 5;
> 		mov->ftyp.compatible_brands[0] = MOV_BRAND_ISOM;
> 		mov->ftyp.compatible_brands[1] = MOV_BRAND_MP42;
> 		mov->ftyp.compatible_brands[2] = MOV_BRAND_MSDH;
> 		mov->ftyp.compatible_brands[3] = MOV_BRAND_MSIX;
> 		mov->ftyp.compatible_brands[4] = MOV_BRAND_ISO5;
> 		mov->header = 0;
> 	}
> 	else
> 	{
> 		mov->ftyp.major_brand = MOV_BRAND_ISOM;
> 		mov->ftyp.minor_version = 1;
> 		mov->ftyp.brands_count = 4;
> 		mov->ftyp.compatible_brands[0] = MOV_BRAND_ISOM;
> 		mov->ftyp.compatible_brands[1] = MOV_BRAND_MP42;
> 		mov->ftyp.compatible_brands[2] = MOV_BRAND_AVC1;
> 		mov->ftyp.compatible_brands[3] = MOV_BRAND_DASH;
> 		mov->header = 0;
> 	}
> 	return 0;
> }

（3）msedemo源码参考，目前还在调优（目前需要拖动进度条到最后面可以显示出来）

> <!DOCTYPE html>
> <html>
>     <head>
>         <title>WebSocket and MSE demo</title>
>     </head>
> 
>     <body>
>         <video controls autoplay width="100%" height="100%">
>             
>             Your browser does not support the video tag.
>         </video>
>     <script src="FileSaver.js"></script> 
>     <script>
>         var video = document.querySelector('video');
>         var byte = new ArrayBuffer();
>         var wsURL = "ws://10.72.55.25:80/liveh265/test.live.mp4";
>         //var mimeCodec = 'video/mp4; codecs="avc1.4d0020, mp4a.40.2"';
>         //var mimeCodec = 'video/mp4; codecs="avc1.4D001F, mp4a.40.2"';
>         var mimeCodec = 'video/mp4; codecs="hvc1.1.6.L123.b0, mp4a.40.2"'; 
>         var updatesToCleanup = 0
>         if ('MediaSource' in window && MediaSource.isTypeSupported(mimeCodec)){
>             var mediaSource = new MediaSource();
>             console.log(mediaSource.readyState);
>             video.src = URL.createObjectURL(mediaSource);
>             mediaSource.addEventListener('sourceopen', sourceOpen);
>         } else {
>             console.error("unsupported type");
>         }
> 
>         function sourceOpen() {
>             console.log(this.readyState);
> 
>             var mediaSource = this;
>             var sourceBuffer = mediaSource.addSourceBuffer(mimeCodec);
>             fetchMedia(wsURL, function (buf) {
>                 var buff = new Uint8Array(buf)
>                 sourceBuffer.addEventListener('updateend', function () {
> 
>                     let len = sourceBuffer.buffered.length - 1;
>                     // //if(len>0){
>                     // //debugger;
>                     // //}
>                     let currentPlayTime = mediaSource.currentTime;
>                     let start = sourceBuffer.buffered.start(len);
>                     let end = sourceBuffer.buffered.end(len);
>                     //
>                     console.log("start:",start);
>                     console.log("end:",end);
>                     console.log("video0.currentTime:",currentPlayTime);
>                     if (currentPlayTime< start){
>                         currentPlayTime = end
>                     } else if (currentPlayTime> end){
>                         sourceBuffer.remove(start, end);
>                         currentPlayTime = end
>                     }
> 
>                     updatesToCleanup++;
>                     if (updatesToCleanup > 50) {
> 
>                         let bufferedDuration = end - start;
>                         let removeEnd = end - 50;
>                         if ((removeEnd > 0) && (bufferedDuration > 50) && (currentPlayTime > start) &&
>                             (currentPlayTime > removeEnd)) {
>                             try {
>                                 this.sourceBuffer.remove(start, removeEnd);
>                             } catch (e) {
>                                 //Log$1.warn("Failed to cleanup buffer");
>                             }
>                         }
>                         updatesToCleanup = 0;
>                     }
>                     mediaSource.endOfStream();
>                     video.play();
>                     console.log(mediaSource.readyState);
>                 });
>                 sourceBuffer.appendBuffer(buff);
>             });
>         };
> 
>         function fetchMedia(url, cb) {
>             console.log(url);
>             ws = new WebSocket(url);
>             ws.binaryType = "arraybuffer";
>             ws.onopen = function () {
>                 console.log("connected")
>             };
>             ws.onmessage = function (e) {
>                 // var byte1 = new Uint8Array(e.data)
>                 // byte = appendByteArray(byte, byte1)
>                 // console.log("byte.length",byte.length)
>                 // if (byte.length > 10000000){
>                 //     var file = new File([byte], "test2020-12-17.mp4", { type: "text/plain;charset=utf-8" });
>                 //     saveAs(file);
>                 //     return;
>                 // }
>                 cb(e.data);
>             }
>             ws.onclose = function () {
>                 console.log("closed")
>             }
>             ws.onerror = function (e) {
>                 console.log(e.msg);
>             }
>         }
> 
>         function appendByteArray(buffer1, buffer2) {
>             let tmp = new Uint8Array((buffer1.byteLength|0) + (buffer2.byteLength|0));
>             tmp.set(buffer1, 0);
>             tmp.set(buffer2, buffer1.byteLength|0);
>             return tmp;
>         }
> 
>     </script>
>     </body>
> </html>

打算弄好才贡献的，先粘出来大家一起看看。希望能有所帮助。

**Comment by xia-chu** [comment]
谢谢 @caojunwei1988 的反馈！

**Comment by tianmaogen** [comment]
@caojunwei1988 

大佬，msedemo弄好了吗？
可以贡献下不？
