### ISSUE TITLE
虚拟主机配置

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#666]
Restful API不支持对虚拟主机的配置吗（添加删除）？如果不支持的话，在配置文件中该如何配置多个虚拟主机呀？

**Comment by xia-chu** [comment]
虚拟主机不需要提前添加的 你用不同的域名访问 就是不同的虚拟主机

**Comment by xia-chu** [comment]
zlm代码本身没限制任何虚拟主机 所以不需要提交添加或配置虚拟主机
