### ISSUE TITLE
关于 getMediaList 的建议

### ISSUE THREAD

**Issue by mis-czx** [xia-chu/ZLMediaKit#669]
getMediaList是获取刘列表,
getMediaInfo,isMediaOnline 均已过期
我只是想得知一个流是否存在 
可否在getMediaList加上一个可选筛选参数 用于判断流ID是否存在

**Comment by xia-chu** [comment]
你先用isMediaOnline 接口吧 这个接口性能好点 getMediaList接口是遍历，如果流比较多，那么筛选的代价就比较高了

**Comment by xia-chu** [comment]
getMediaList接口后续我添加下stream参数用于筛选流吧

**Comment by mis-czx** [comment]
感谢

**Comment by xia-chu** [comment]
已实现
