### ISSUE TITLE
大华获取设备信息时返回403

### ISSUE THREAD

**Issue by zhou-hao** [xia-chu/ZLMediaKit#677]
使用大华摄像头注册后，获取设备信息时返回403错误怎么处理
```
SIP/2.0 403 Forbidden
Call-ID: d862ea2ff051341ded3c55f5ef1f4cc5@0.0.0.0
CSeq: 1 MESSAGE
From: <sip:34020000002000000002@3402000000>;tag=FromDeviceInfoTag
To: <sip:34020000001320000001@3402000000>;tag=ToDeviceInfoTag
User-Agent: SIP UAS V.2016.xxxx
Via: SIP/2.0/UDP 192.168.3.230:5060;rport=12345;received=192.168.3.113;branch=z9hG4bK-3832-4a8570138479923485a4753bc9d88e47
Warning: 399 devnull "<102>[Component]Not registered"
Content-Length: 0
```

**Comment by xia-chu** [comment]
这个我就不知道了 建议在wvp项目下提issue



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 老周 <notifications@github.com&gt;
发送时间: 2021年1月6日 20:10
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 大华获取设备信息时返回403 (#677)





 
使用大华摄像头注册后，获取设备信息时返回403错误怎么处理
 SIP/2.0 403 Forbidden Call-ID: d862ea2ff051341ded3c55f5ef1f4cc5@0.0.0.0 CSeq: 1 MESSAGE From: <sip:34020000002000000002@3402000000&gt;;tag=FromDeviceInfoTag To: <sip:34020000001320000001@3402000000&gt;;tag=ToDeviceInfoTag User-Agent: SIP UAS V.2016.xxxx Via: SIP/2.0/UDP 192.168.3.230:5060;rport=12345;received=192.168.3.113;branch=z9hG4bK-3832-4a8570138479923485a4753bc9d88e47 Warning: 399 devnull "<102&gt;[Component]Not registered" Content-Length: 0

**Comment by xia-chu** [comment]
或者咨询下大华的人 sip这块 我真不熟

**Comment by zhou-hao** [comment]
不好意思，发错地方了。。。。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2021年1月6日 20:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 老周 <zh.sqy@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 大华获取设备信息时返回403 (#677)





 
或者咨询下大华的人 sip这块 我真不熟

**Comment by xia-chu** [comment]
没事 认识大佬很开心

**Comment by xia-chu** [comment]
加个群聊聊天？

**Comment by zhou-hao** [comment]
ok
