### ISSUE TITLE
hook API相关疑问

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#680]
请问是否有停止推流和停止播放的hook，如果没有的话，后续是否有添加的计划？

**Comment by xia-chu** [comment]
停止推流可以使用
on_stream_changed接口，这个接口可以汇报流注销事件，也就是停止推流事件。

zlm有个hook叫on_flow_report，只要播放器和推流器断开，并且使用流量超过一定阈值时，就会触发该事件，
如果你把阈值设置为0，相当于推流介绍或播放结束事件

**Comment by mayomeng** [comment]
我试了一下，停止RTP推流的时候，on_stream_changed方法没有被调用，是不是只有rtsp/rtmp推流端口这个接口才会被调用呀？

**Comment by xia-chu** [comment]
跳转下阈值，默认使用流量超过1MB才会触发该事件。
播放/推流都会触发该事件的，rtp推流也会
