### ISSUE TITLE
调用getSnap接口截图一直返回默认的logo.png

### ISSUE THREAD

**Issue by 18285160741** [xia-chu/ZLMediaKit#681]
求指教：
调用getSnap接口截图一直返回默认的logo.png、snap目录下也没有生成图片。

测试地址：
http://39.99.188.174:8282/index/api/getSnap?timeout_sec=100&expire_sec=36000&url=ws://39.99.188.174:8282/rtp/gb_play_34020000001320000001_34020000001320000001.flv&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc

**Comment by reachzxsframe** [comment]
你看下ffmpeg你安装了么

**Comment by 18285160741** [comment]
> 你看下ffmpeg你安装了么

安装了ffmpeg，修改了config.ini中的ffmpeg的bin路径，重启了zlm服务。

**Comment by 18285160741** [comment]
版本： ffmpeg version 3.4.8-0ubuntu0.2

**Comment by 18285160741** [comment]
版本： ffmpeg version 3.4.8-0ubuntu0.2
config.ini 配置
[ffmpeg]
bin=/usr/bin/ffmpeg

**Comment by reachzxsframe** [comment]
ffmpeg的日志你看下

**Comment by 18285160741** [comment]
> ffmpeg的日志你看下

#### pid=18187,cmd=/usr/bin/ffmpeg -i ws://39.99.188.174:8282/rtp/gb_play_34020000001320000001_34020000001320000001.flv -y -f mjpeg -t 0.001 /home/webdev/liumeiti/release/linux/Debug/www/snap/60776305c4deedd483781ee5c409c085/1610009945.jpeg.tmp #####

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
ws://39.99.188.174:8282/rtp/gb_play_34020000001320000001_34020000001320000001.flv: Protocol not found
Did you mean file:ws://39.99.188.174:8282/rtp/gb_play_34020000001320000001_34020000001320000001.flv?

**Comment by 18285160741** [comment]
> ffmpeg的日志你看下

直播画面都能看的，在播放页面发起的截图请求

**Comment by xia-chu** [comment]
ffmpeg不支持ws-flv拉流截图，你可以改成http-flv拉流截图，或者rtsp。

**Comment by xia-chu** [comment]
如果是H265,ffmpeg也不支持http-flv拉流截图，算了 建议还是用http-ts或http-fmp4截图

**Comment by 18285160741** [comment]
> 如果是H265,ffmpeg也不支持http-flv拉流截图，算了 建议还是用http-ts或http-fmp4截图

摄像头是海康的，h265
我再尝试下，谢谢

**Comment by 18285160741** [comment]
> ffmpeg的日志你看下

摄像头是海康的，h265
我再尝试下其它方式，谢谢指点

**Comment by 18285160741** [comment]
换成http-fmp4可以截图了，谢谢各位大佬的指点。
