### ISSUE TITLE
RTP收流相关问题

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#682]
使用ZLMediaKit作为GB28181的流媒体服务器时遇到了两个问题
1.关于不能使用相同的ssrc推流，wiki中写可以通过配置rtp_proxy.checkSource=0来关闭这个限制，但是我修改这个配置后，发现一段时间内还是不能使用相同的ssrc进行推流，这个配置没有生效。
2.openRtpServer接口动态开启国标收流端口，开放的收流端口是动态随机的，如果使用docker运行ZLMediaKit的话，每次都动态为容器绑定端口太麻烦了，请问有没有更好的解决方法？
多谢多谢！

**Comment by xia-chu** [comment]
openRtpServer接口可以指定端口的 你自己管理端口不就行了？
另外，如果你要用随机端口的话，也可以配置Linux系统下随机端口的范围的，你可以查询下资料

**Comment by xia-chu** [comment]
rtp_proxy.checkSource这个配置打算去掉了，以后将强制打开，因为关闭有线程安全的问题 会崩溃的

**Comment by xia-chu** [comment]
如果你打算多个流同时推流到10000端口 那么建议用不同的ssrc 否则会互相干扰

**Comment by mayomeng** [comment]
大神，是这样的，因为需要用到RTP的录像功能，如果每次都使用不同的ssrc会导致一个摄像头的录像被存储在不同的文件夹中，所以才会想使用相同的ssrc推流
