### ISSUE TITLE
请问怎么设置gop呢？现在有一个视频流播放不了，可能是gop太大导致直播播放器等不到I帧 没法渲染

### ISSUE THREAD

**Issue by BzHuang** [xia-chu/ZLMediaKit#686]

**Comment by xia-chu** [comment]
这个是视频源的问题 视频源如果一直不产生关键帧 那么zlm最多缓存512帧
你的视频源是什么格式？

**Comment by BzHuang** [comment]
h264 格式。
情况是这样：
有多个摄像头监控，App端基本都能正常播放，然后发现某一个摄像头在App端的播放器不能播放，但在别端的播放器能正常播放。
APP端播发器SDK 的技术支持 调试后说可能是 gop 设置太大的问题，让我们修改gop试试。

**Comment by xia-chu** [comment]
你应该去设置摄像头的gop大小 服务器没法设置



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BzHuang <notifications@github.com&gt;
发送时间: 2021年1月13日 10:26
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 请问怎么设置gop呢？现在有一个视频流播放不了，可能是gop太大导致直播播放器等不到I帧 没法渲染 (#686)





 
h264 格式。
 情况是这样：
 有多个摄像头监控，App端基本都能正常播放，然后发现某一个摄像头在App端的播放器不能播放，但在别端的播放器能正常播放。
 APP端播发器SDK 的技术支持 调试后说可能是 gop 设置太大的问题，让我们修改gop试试。

**Comment by BzHuang** [comment]
好的！谢谢！
