### ISSUE TITLE
websocket flv 多个同时播放阻塞问题？

### ISSUE THREAD

**Issue by xlsky0713** [xia-chu/ZLMediaKit#687]
你好，web端我采用websocket方式请求flv视频流，同时请求4个
for(var i =0;i<4;i++){
new WebSocket(‘ws://ip:port/live/xxx.flv’)
}
由于是按需拉流，建立连接需要一段时间，通过浏览器监听websocekt请求发现，4次请求
在建立连接过程中会阻塞（串行在执行，也就是第一个请求响应后在发起第二个），如果第一个flv注册响应很慢或者注册失败，直接导致后面的请求需要等待很久才能发起连接，如果使用http-flv去请求不会出现这个问题，但是http-flv有播放路数限制。

本地搭建websocket服务，是可以同时发起的，ZLMedia是否有什么机制限制了多个websocket的连接？

**Comment by xlsky0713** [comment]
![QQ截图20210112193911](https://user-images.githubusercontent.com/17897913/104310000-fa777280-550d-11eb-98b5-c48a23857504.jpg)
这是请求的时间线

**Comment by xia-chu** [comment]
这个是浏览器的限制 有人已经反馈这个问题了

**Comment by xlsky0713** [comment]
好的，谢谢

**Comment by hxgqh** [comment]
解决了吗？如何解决？
