### ISSUE TITLE
服务器播放rtsp断开问题

### ISSUE THREAD

**Issue by 17Sdubin** [xia-chu/ZLMediaKit#689]
大神你好，我这边用服务器添加流代理拉的hik ipc h264的视频流，然后用VLC从服务器拉rtsp流播放，几秒钟就会自动断开。
log：rtsp播放器断开，rtp over udp session timeouted,耗时(s):15
请问这个是什么原因

**Comment by xia-chu** [comment]
zlm对rtsp超时时间限制比较严 默认15秒超时 你可以修改下配置文件 或者把vlc设置成rtsp over tcp





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 17Sdubin <notifications@github.com&gt;
发送时间: 2021年1月14日 09:35
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 服务器播放rtsp断开问题 (#689)





 
大神你好，我这边用服务器添加流代理拉的hik ipc h264的视频流，然后用VLC从服务器拉rtsp流播放，几秒钟就会自动断开。
 log：rtsp播放器断开，rtp over udp session timeouted,耗时(s):15
 请问这个是什么原因

**Comment by 17Sdubin** [comment]
> zlm对rtsp超时时间限制比较严 默认15秒超时 你可以修改下配置文件 或者把vlc设置成rtsp over tcp 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 17Sdubin <notifications@github.com&gt; 发送时间: 2021年1月14日 09:35 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] 服务器播放rtsp断开问题 (#689) 大神你好，我这边用服务器添加流代理拉的hik ipc h264的视频流，然后用VLC从服务器拉rtsp流播放，几秒钟就会自动断开。 log：rtsp播放器断开，rtp over udp session timeouted,耗时(s):15 请问这个是什么原因 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

多谢大神，问题已经解决！
