### ISSUE TITLE
GB28181 推流到ZLMediaKit  快进命令下达成功后 flv播放没有快进

### ISSUE THREAD

**Issue by yxw13141618** [xia-chu/ZLMediaKit#691]
通过28181推rtp ps流到ZLMediaKit  下达快进命令后  观测到码流变大  但是flv地址还是照25帧速度播放，求救。

**Comment by xia-chu** [comment]
快不快进 其实跟转发服务器无关 这个主要是发送端和播放端的问题。
假如你快进2倍，无非是两倍速度的发送数据，如果你的播放器能两倍速度播放，那么就一切OK。
但是你的播放器虽然收到的数据是之前的两倍了，但是它就会两倍速度播放吗？显然不会，因为一般的播放器，
是根据时间戳来播放的，数据速度的快慢不太会影响播放速度，播放器只会认为它可能是一时的网络抖动。

那么你在发送端，以两倍的速度发送数据，时间戳也两倍的速度递增可不可以呢？
一般来说，你如果没有音频，确实可以让播放器两倍速度播放，因为视频确实是完全根据时间戳来控制播放速度的。

但是假如你又音频了，那么对不起，音频还是那个播放速度，音频声卡播放器音频的速度跟时间戳无关，声卡只会匀速的播放音频，没法加快速度。

但是假如你的播放器是定制的，那么你可以加快音频播放速度，方法是用soundtouch变速，当然你也可以在倍数播放音频时直接关闭音频。
