### ISSUE TITLE
对ARM不支持

### ISSUE THREAD

**Issue by xwz823** [xia-chu/ZLMediaKit#693]
什么时候能提供对ARM支持的版本镜像？

**Comment by xia-chu** [comment]
docker镜像吗？其实zlm在arm下编译很简单的，交叉编译也简单，你是什么arm，什么系统？

**Comment by chenhanwen2019** [comment]
@xia-chu  交叉编译需要改哪里呢，有文档说明吗

**Comment by xia-chu** [comment]
其实你可以搜索下issue: #326

**Comment by ixingqiao** [comment]
docker hub上有个arm镜像的，可以拿去下载直接使用的，为了支持h265-flv，arm下我这边编译成功了，并且做了个人的arm下的镜像
