### ISSUE TITLE
onError | 32A16B01 rtp包长度异常(49449)，发送端可能缓存溢出并覆盖

### ISSUE THREAD

**Issue by ts0203** [xia-chu/ZLMediaKit#694]
您好，我在mediaserver的日志中看到如下错误打印：

onError | 32A16B01 rtp包长度异常(49449)，发送端可能缓存溢出并覆盖

我能把这里的限制调大吗？调到50K可以吗？
 if (len > 1024 * 10) {
        throw SockException(Err_shutdown, StrPrinter << "rtp包长度异常(" << len << ")，发送端可能缓存溢出并覆盖");
    }

**Comment by xia-chu** [comment]
你可以改成50K试试 不过 这个问题一般是发送端的bug
