### ISSUE TITLE
用VLC选fmp4直播流拉流播放h265编码的1080p的视频流，延时会随着播放时间的推移越来越大

### ISSUE THREAD

**Issue by tplusy** [xia-chu/ZLMediaKit#696]
VLC对比rtsp和fmp4两种方式拉流。rtsp拉流默认延迟稳定在2s左右。但是使用fmp4直播流拉流的话，一开始延迟2秒，但是随着播放时间的推移，延迟会不断增大。测试fmp4方式拉流3分钟左右，延迟就到了6秒。 然而VLC统计显示并没有丢帧。
 
![image](https://user-images.githubusercontent.com/1529224/104908780-ea560c00-59c1-11eb-8c70-570b6d2ae70c.png)

**Comment by xia-chu** [comment]
rtsp的时间戳是原始时间戳，zlm不会做任何修改，fmp4是zlm生成的相对时间戳。
你是rtsp拉流代理产生的流吗

**Comment by tplusy** [comment]
请问延迟跟时间戳有关系？
http-fmp4流是rtsp推流后，zml转换来的

**Comment by xia-chu** [comment]
有关系的，rtsp推流，你rtsp播放时原汁原味的，zlm未对rtp做任何处理，没有修改时间戳。
但是fmp4不同，首先，zlm要根据pts生成dts(假如你又B帧的话)，然后要根据绝对时间戳取相对时间戳。
在取相对时间戳时，可能由于rtsp时间戳抖动，会有一点误差，特别是rtp时间戳回环时，如果播放时间久了，这种累计误差可能会比较大。你说延时从2秒增加到6秒，我感觉比较轻微了，感觉不像是程序bug，更像是网络抖动时缓冲中导致的。
你是公网播放http-fmp4吗
