### ISSUE TITLE
general.rtsp_demand和general.ts_demand参数配置无效

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#697]
如题将general.rtsp_demand和general.ts_demand配置为1，但是当推流到ZLMediaKit时，还是会产生rtsp和ts的直播流

**Comment by xia-chu** [comment]
不会的 注册后就停止生成了 有访问才会继续生成的

**Comment by mayomeng** [comment]
您的意思是这两个参数配置为1后，不会自动产生RTSP和TS的直播流，但是如果有RTSP和TS请求的话，就会产生对应协议的直播流？这样的话，我想屏蔽RTSP和TS协议，该如何配置？

**Comment by xia-chu** [comment]
你把rtsp和http端口关闭 不就行了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mayomeng <notifications@github.com&gt;
发送时间: 2021年1月20日 09:27
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] general.rtsp_demand和general.ts_demand参数配置无效 (#697)

**Comment by xia-chu** [comment]
其实 如果播放器想播放http-ts你就让它播放呗 真不影响什么，况且，你不说，谁知道可以播放http-ts?
还有，播放鉴权，你也可以过滤http-ts的播放请求啊

**Comment by mayomeng** [comment]
了解，多谢啦！
