### ISSUE TITLE
【需求】可在配置文件中预定义推流拉流代理

### ISSUE THREAD

**Issue by ptma** [xia-chu/ZLMediaKit#698]
【需求】可在配置文件中预定义推流拉流代理
有时候我们有一些固定的流地址，希望能将这些地址直接写到配置文件中， 在 MediaServer 启动后能自动把这些地址注册为推流拉流代理，而不是在启动后通过调用 RESTful API 来添加。

谢谢。

**Comment by xia-chu** [comment]
首先 添加拉流代理需要很多参数的，写在配置文件中太复杂了，而且现在zlm的配置文件系统，不支持非常复杂的内容，
其次是，这样做真的很low，已经不是一个正经服务器应该干的事了

**Comment by xia-chu** [comment]
其实，你可以基于zlm二次开发，通过数据库的方式加载拉流代理

**Comment by solomonyx** [comment]
我把流地址写在yml文件里面,然后拉流代理

**Comment by xia-chu** [comment]
配置文件添加拉流代理的方式 一般是客户端 或者很固定的业务 zlm作为一个通用的服务器 加这个太特殊的需求不合适的
