### ISSUE TITLE
HTTP Hook的on_publish有问题

### ISSUE THREAD

**Issue by Allenisme** [xia-chu/ZLMediaKit#699]
![image](https://user-images.githubusercontent.com/17775578/105028198-b21b0000-5a8b-11eb-9a46-fcf19448efa4.png)
其他hook都正常，唯独on_publish的hook貌似没有发请求
![image](https://user-images.githubusercontent.com/17775578/105028062-83048e80-5a8b-11eb-8eb0-e550beb48532.png)
自己用postman是可以请求到的

**Comment by xia-chu** [comment]
如果推流端是127的地址 就不会触发hook



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Allenisme <notifications@github.com&gt;
发送时间: 2021年1月19日 19:25
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] HTTP Hook的on_publish有问题 (#699)





 

 其他hook都正常，唯独on_publish的hook貌似没有发请求
 
 自己用postman是可以请求到的

**Comment by Allenisme** [comment]
> 如果推流端是127的地址 就不会触发hook 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Allenisme <notifications@github.com&gt; 发送时间: 2021年1月19日 19:25 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] HTTP Hook的on_publish有问题 (#699) 其他hook都正常，唯独on_publish的hook貌似没有发请求 自己用postman是可以请求到的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢大佬
