### ISSUE TITLE
Pushing RTSP stream with ANNOUNCE returns "406 Not Acceptable" 

### ISSUE THREAD

**Issue by TheAnswer3** [xia-chu/ZLMediaKit#700]
I'm using the ZLMediaKit as a library. I have an **ffmpeg** instance that pushes a video file via RTSP in this way:

_ffmpeg -re -i video.mp4 -c:v copy -f rtsp rtsp://127.0.0.1:8554/live/video1_

Connecting **ffplay** to this URL works, but if I kill the ffmpeg pushing process and I restart it, the player remains stuck. The only way to make the player works is to restart it.

I've analyzed using _Wireshark_ the RTSP session flow between the MediaServer, the ffmpeg process (Feed) and the ffplay process (Player):

![rtsp](https://user-images.githubusercontent.com/7317228/105057736-cf44d400-5a75-11eb-9809-d6415a50a165.png)

It seems that the ZLMediaKit refuses new _ANNOUNCE_, with code _406 - Not Acceptable_, if there is a player connected to the stream. I need to close and restart the _Player_ and the stream works.

Is this a know behaviour? How can I make it works? Thank you for you work!!

**Comment by xia-chu** [comment]
The error code 406 is because zlmediakit didn't receive the disconnection of your pusher.
Generally speaking, if you disconnect the pusher, zlmediakit can receive EOF's message. In this way, zlmediakit can immediately accept the re pushing,
However, it's strange that when you close ffmpeg, zlmediakit doesn't receive EOF

**Comment by xia-chu** [comment]
In this case, it will take about 15 seconds for zlmediakit to receive data

**Comment by TheAnswer3** [comment]
As you can see in the diagram, the pusher sends the TEARDOWN message that is accepted by the MediaKit. 
I've waited more than 15 seconds, but there isn't a timeout. 
The issue happens still if I try to push a live stream from an IPC camera, so I don't think that the end of file Is the problem.
It seems that the MediaKit refuses updates to the stream if a player Is connected to this stream, Is It possible?

**Comment by nokiovo79** [comment]
Hi friend,
do you think adding these options (-reconnect_at_eof 1 
-reconnect_streamed 1) to ffmpeg can work?

**Comment by xia-chu** [comment]
Can you tell me your version(git commit hash) of zlmediakit,

**Comment by TheAnswer3** [comment]
This is the **_git show_** in _ZLMediaKit_ directory:

```
commit 416d21df36bd2487ac6174943542f9489759ca0c ( HEAD -> master)
Author: xiongziliang <771730766@qq.com> Date: Mon Sep 21 14:32:56 2020 +0800
```

**Comment by xia-chu** [comment]
I checkout to the version of `416d21df36bd2487ac6174943542f9489759ca0c` and found that the phenomenon is the same as the latest code.

start push a stream by ffmpeg to zlmediakit -->  play this stream with ffplay --> Ctrl + C to kill ffmpeg to stop push --> zlmediakit disconnect from ffplay and release the stream -->  ffplay is frozen --> repush same stream  by ffmpeg to zlmediakit --> ffplay is still frozen

**Comment by xia-chu** [comment]
If you stop push, the player that is playing the pushing stream will be disconnect by zlmediakit

**Comment by TheAnswer3** [comment]
I've updated the ZLMediaKit to the latest commit but I haven't your same behaviour. The mediakit refuses any push to the stream if there is a player connected to this stream. 
I've the same behaviour of your first reply, but not of the second, the player will not disconnect still if I stop the pusher.

**Comment by TheAnswer3** [comment]
You didn't get the "406 Not Acceptable" error code?
Can you send me the configuration file to check if I've a wrong configuration in the RTSP section, please?
This is mine:
```
[rtsp]
authBasic=1
directProxy=1
handshakeSecond=10
keepAliveSecond=10
port=8554
sslport=322
```

**Comment by xia-chu** [comment]
Only when ffmpeg stop push stream, and zlmediakit does not receive EOF,  then it will return `406 Not Acceptable`.
Generally speaking, EOF is triggered when you kill the ffmpeg process，
but `windows` seems to be an exception.

If zlmediakit does not receive the EOF, and you restart ffmpeg to push the stream to the same URL, then it is possible to return  `406 Not Acceptable`。

However, this state will only last about 15 seconds. zlmediakit will automatically release resources after 15 seconds without receiving data.

Whether you play the video or not will not affect the `pushing stream` at all.
You can try, in the case of not playing video, repeat ffmpeg push stream whether also return `406 Not Acceptable`?

**Comment by xia-chu** [comment]
My config file is default，Modifying the configuration file will not lead to the situation you said。

**Comment by xia-chu** [comment]
You can provide the log of zlmediakit when the phenomenon you said happened

**Comment by TheAnswer3** [comment]
How can I enable the MediaKit log from the C++ code?

**Comment by xia-chu** [comment]
The log is opened by default，it will be generated named `log` in the same directory as MediaServer.

**Comment by rmokerone** [comment]
I also ran into this problem when pushing rtsp streaming  on IoT devices. When the Internet of Things device is powered off and restarted, it also trigger an error issued by Already publishing. So I think the best solution is to add an option to allow repeated same name push in config.ini, and set this option to false by default.
