### ISSUE TITLE
视频存储有计划支持对象存储吗？

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#701]
目前ZLMediaKit的视频存储都是存在服务器的本地磁盘中（或者通过挂载目录的方式存储到NFS之类的网络文件存储中），以后有计划支持类似ceph，fastdfs之类的对象存储吗？

**Comment by xia-chu** [comment]
zlm把mp4录制事件以hook的方式暴露出来，目的就是为了方便你们对接云存储之类的业务
