### ISSUE TITLE
使用zlm http服务器分发hls来播放ts文件时，调用 获取流信息(getMediaInfo) 接口没有查询到hls流信息

### ISSUE THREAD

**Issue by paipergo** [xia-chu/ZLMediaKit#702]
> 感谢作者开源提供如此一流媒体服务器

使用ZLMediaKi的MediaServer的HTTP服务器分发已有的HLS切片文件，已经成功了

但是，播放的时候，调用`获取流信息(getMediaInfo)` 接口却没有查询到媒体流信息。

目标：ZLMediaKit分发HLS文件，通过HTTP接口或者HOOK能够获取到播放状态

**Comment by xia-chu** [comment]
hls文件是zlm生成的还是其他代码？如果是其他代码，那么zlm只是当做http服务器使用，当然用getMediaInfo接口获取不到信息

**Comment by paipergo** [comment]
hls文件是zlm生成的，但是m3u8是自己的外挂独立小脚本生成的。如果zlm只是当做http服务器使用，那么就得使用`on_http_access`回掉来确认播放器的播放状态了。

对于ts切片来说这样会增加很多负载。有没有更好的办法呢？

**Comment by xia-chu** [comment]
没有 如果m3u8不是zlm生成的 那么http文件服务器之外的功能就无法使用

**Comment by xia-chu** [comment]
zlm的http文件服务器对zlm生成的hls做了单独的优化和处理，所以才能支持丰富的hls业务逻辑

**Comment by paipergo** [comment]
好的  多谢 多谢
