### ISSUE TITLE
拉rtsp流，推ps流出去，vlc播放无声音

### ISSUE THREAD

**Issue by hh-kai** [xia-chu/ZLMediaKit#703]
vlc播放的sdp文件时这样写的
s=MPEG Program Stream, streamed by XXXX  
m=video 6666 RTP/AVP 96
a=rtpmap:96 MP2P/90000
c=IN IP4 127.0.0.1

有视频没画面

这里加了测试 保存音频
![image](https://user-images.githubusercontent.com/19390025/105135434-fad5c600-5b2a-11eb-806d-24fcdb8bc855.png)
同时这里也加了测试代码 保存打包后的ps流
![image](https://user-images.githubusercontent.com/19390025/105135481-117c1d00-5b2b-11eb-8974-584456dd1ca2.png)
保存出来的ps播放没有声音
[ps_aac.zip](https://github.com/xia-chu/ZLMediaKit/files/5840503/ps_aac.zip)
是这个ps_muxer_input没有把音频打包进去 还是我使用错了

**Comment by xia-chu** [comment]
你好 你这个问题解决没？ 我看你在老陈的qq群提问了.
你保持的文件，aac有声音，ps不知道， 我电脑没声卡。

**Comment by zg9uagfv** [comment]
ps流不是国际标准，VLC不支持，音频播放不出来正常。找其他的播放器来播放就可以。

**Comment by hh-kai** [comment]
PS流AAC的音频ffplay可以播放
PS流G711的音频播放器都播放不了 
但是PS的G711流推流到国标设备是可以播放的
有些国标设备只支持G711的推流
