### ISSUE TITLE
rtp创建随机端口这个端口范围是否可以配置指定？

### ISSUE THREAD

**Issue by qinxukai** [xia-chu/ZLMediaKit#704]
看代码看不太明白，因为服务器一般只会按需求开放端口范围。
自己维护这个范围有点麻烦

**Comment by qinxukai** [comment]
我找见别人提过这个问题了  我自己关了……

**Comment by xia-chu** [comment]
老哥 zlm去管理端口范围也挺麻烦的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qinxukai <notifications@github.com&gt;
发送时间: 2021年1月20日 22:33
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] rtp创建随机端口这个端口范围是否可以配置指定？ (#704)





 
看代码看不太明白，因为服务器一般只会按需求开放端口范围。
 自己维护这个范围有点麻烦

**Comment by qinxukai** [comment]
嗯，我后来想了个办法  摄像头在数据库有id
我分配给摄像头的ip就是 id + 端口范围的开始
