### ISSUE TITLE
能否优化websocket播放协议？

### ISSUE THREAD

**Issue by xlsky0713** [xia-chu/ZLMediaKit#705]
如题，使用websocket播放的时候，能否尽早返回101响应，避免多个视频播放的时候造成请求阻塞。

**Comment by xia-chu** [comment]
如果这个视频已经存在 那么zlm会立即返回101的，如果播放一个不存在的视频，zlm会让播放器等待十几秒，目的是为了实现按需拉流等逻辑，如果超时后流还未上线，zlm会返回404告知播放器，流不存在

**Comment by xia-chu** [comment]
所以你说的尽早返回101响应是指流不存在时吗？

**Comment by xlsky0713** [comment]
对的，流不存在时等待101响应太长时间，在多视频播放时体验不是很好，如果能尽早返回101，这样多个websocket基本可以同时执行，先返回101，后续如果没流可以直接断开websocket，但是不知这样是否可行？

**Comment by xia-chu** [comment]
太粗暴了这样 直接断开socket 用户根本不知道为什么

**Comment by xia-chu** [comment]
而且 没流也返回101 但是又没数据 对播放器来说有何意义呢？跟没返回101体验一样啊

**Comment by xlsky0713** [comment]
确实有这个问题，我的想法是如果尽早返回101，这样是不是可以就并行请求数据了，相当于多个播放器可以同时开画面，即使第一个没流，但不影响后面的播放器打开画面的速度？

**Comment by xia-chu** [comment]
你的意思 一个挂起的播放器会影响其他流在线的播放器的打开速度？

**Comment by xia-chu** [comment]
同主机下的websocket客户端 链接时时串行阻塞的吗？

**Comment by xlsky0713** [comment]
是的，我在firefox 浏览器测试结果是这样的，非得等101响应后，才会继续走下一个

**Comment by xia-chu** [comment]
http-flv不存在这个问题吧？

**Comment by xlsky0713** [comment]
http是正常的

**Comment by xia-chu** [comment]
如果不要求同时播放6个视频以上 还是用http-flv吧

**Comment by xlsky0713** [comment]
现在也用的HTTP-FLV的方案，因为有大屏展示的需要，刚好是6路视频，如果ws-flv能跟http一样能同时开画面就完美了 ：）

**Comment by xia-chu** [comment]
那你可以修改点代码 没有流 直接返回404吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xlsky0713 <notifications@github.com&gt;
发送时间: 2021年1月21日 12:00
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 能否优化websocket播放协议？ (#705)





 
现在也用的HTTP-FLV的方案，因为有大屏展示的需要，刚好是6路视频，如果ws-flv能跟http一样能同时开画面就完美了 ：）

**Comment by xlsky0713** [comment]
了解，谢谢大佬的答疑
