### ISSUE TITLE
添加rtsp拉流代理返回open udp sock err

### ISSUE THREAD

**Issue by colaicode** [xia-chu/ZLMediaKit#708]
rtsp地址可以通过ffplay正常播放。
![image](https://user-images.githubusercontent.com/25426335/105787235-8a5ef700-5fb9-11eb-8340-5538047856ca.png)
但是通过接口拉流时报错
![image](https://user-images.githubusercontent.com/25426335/105787283-a498d500-5fb9-11eb-880f-2e9d8384996f.png)

**Comment by xia-chu** [comment]
组播拉流？ 组播端口打开失败，你看下zlm的日志？

**Comment by xia-chu** [comment]
你测试zlm的组播拉流时 请把ffplay关闭

**Comment by colaicode** [comment]
![image](https://user-images.githubusercontent.com/25426335/105788422-73b99f80-5fbb-11eb-9912-004def656bc8.png)
已经将ffplay关闭，还是返回这个错误

**Comment by xia-chu** [comment]
可能系统差异的原因 在Linux下是可以的。
zlm在创建组播端口时，绑定的是组播地址，而不是本地ip地址或0.0.0.0，在Windows下，可能需要绑定0.0.0.0地址。
你打下补丁试试：
```patch
Index: src/Rtsp/RtspPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtsp/RtspPlayer.cpp	(revision 66baaf8e21314a563ec5e919aaaa432eb5785a17)
+++ src/Rtsp/RtspPlayer.cpp	(date 1611043390000)
@@ -292,7 +292,7 @@
             //udp组播
             auto multiAddr =  transport_map["destination"];
             pRtpSockRef = createSocket();
-            if (!pRtpSockRef->bindUdpSock(rtp_port, multiAddr.data())) {
+            if (!pRtpSockRef->bindUdpSock(rtp_port, "0.0.0.0")) {
                 pRtpSockRef.reset();
                 throw std::runtime_error("open udp sock err");
             }

```

**Comment by colaicode** [comment]
通过接口拉流返回成功。
![image](https://user-images.githubusercontent.com/25426335/105937469-8f42aa00-6090-11eb-9b04-5c41e30b1422.png)
但是通过flv.js/ffplay/VLC无法播放rtmp。其他流正常

**Comment by xia-chu** [comment]
265吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: colaicode <notifications@github.com&gt;
发送时间: 2021年1月27日 11:13
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 添加rtsp拉流代理返回open udp sock err (#708)





 
通过接口拉流返回成功。
 
 但是通过flv.js/ffplay/VLC无法播放rtmp。其他流正常

**Comment by colaicode** [comment]
不是

**Comment by colaicode** [comment]
用FFmpeg cmd模板可以正常播放

**Comment by xia-chu** [comment]
你的rtmp url能暴露公网吗，我测试下

**Comment by xia-chu** [comment]
> 
> 
> 用FFmpeg cmd模板可以正常播放

这个默认转码的

**Comment by colaicode** [comment]
这个可以正常播放，采用OSD： http://f75dc78e.nat.nsloop.com/live/sub3.flv
这个不能正常播放，采用udp组播： http://f75dc78e.nat.nsloop.com/live/test.flv，
不能正常播放的ffplay截图：
![image](https://user-images.githubusercontent.com/25426335/105940218-c36c9980-6095-11eb-969c-8909c10c37cd.png)

不能正常播放采用的FFmpeg指令：%s -re -rtsp_transport udp_multicast -i %s  -c:v libx264 -preset superfast -tune zerolatency -c:a aac -ar 44100 -f flv %s，使用这个指令后可以正常播放

**Comment by colaicode** [comment]
发现日志输出：
![image](https://user-images.githubusercontent.com/25426335/105982229-fa60a080-60d1-11eb-8cca-476210d5cf19.png)

**Comment by xia-chu** [comment]
返回404了 是不是已经停掉了？

**Comment by colaicode** [comment]
开起来了，今天都会开着

**Comment by colaicode** [comment]
这个可以正常播放，采用OBS： http://f75dc78e.nat.nsloop.com/live/sub3.flv


这个不能正常播放，采用udp组播，使用addStreamProxy接口： http://f75dc78e.nat.nsloop.com/live/test.flv，不能正常播放
同一个地址，采用UDP组播，使用的是addFFmpegSource接口，http://f75dc78e.nat.nsloop.com/live/cad6c0e97983d7c4f4ba4eb3505c556e.flv，可以正常播放。FFmpeg命令为：%s -fflags nobuffer -rtsp_transport udp_multicast -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s

**Comment by xia-chu** [comment]
addStreamProxy 换udp或tcp拉流也是不行吗

**Comment by colaicode** [comment]
这个流很特殊，他只支持udp 组播

**Comment by xia-chu** [comment]
那真的不好测试了 有个能这个流的时间戳有点问题 可能有些帧的时间戳相同导致这样

**Comment by colaicode** [comment]
很感谢你的回复，用FFmpeg来解决先

**Comment by xia-chu** [comment]
大概知道原因了，可能是这个流的时间戳不规范，P帧时间戳跟其他帧一样导致的，打上这个patch rtmp就应该能播放：
```patch
Index: src/Extension/H264Rtmp.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Extension/H264Rtmp.cpp	(revision 3a670acd8a20a3b310cc767ae78acc5d63249948)
+++ src/Extension/H264Rtmp.cpp	(revision 72d031d35c9d91bd1c1eeadbfd5607b5357e8c43)
@@ -185,7 +185,7 @@
         }
     }
 
-    if(_lastPacket && _lastPacket->time_stamp != frame->dts()) {
+    if(_lastPacket && (_lastPacket->time_stamp != frame->dts() || type == H264Frame::NAL_B_P)) {
         RtmpCodec::inputRtmp(_lastPacket);
         _lastPacket = nullptr;
     }
@@ -217,6 +217,10 @@
     _lastPacket->buffer.append((char *) &size, 4);
     _lastPacket->buffer.append(pcData, iLen);
     _lastPacket->body_size = _lastPacket->buffer.size();
+    if (type == H264Frame::NAL_B_P) {
+        RtmpCodec::inputRtmp(_lastPacket);
+        _lastPacket = nullptr;
+    }
 }
 
 void H264RtmpEncoder::makeVideoConfigPkt() {

```

**Comment by xia-chu** [comment]
赶紧试试

**Comment by colaicode** [comment]
添加这个补丁后，结果是这样
![image](https://user-images.githubusercontent.com/25426335/106696716-405cbd80-6618-11eb-959d-e57d71670c5a.png)
![image](https://user-images.githubusercontent.com/25426335/106696771-59656e80-6618-11eb-96ab-4a4923d3b60a.png)

**Comment by xia-chu** [comment]
你这个流不能暴露公网 我没法调试 很难办

**Comment by colaicode** [comment]
http://f75dc78e.nat.nsloop.com/live/test.flv
用这个地址，一直开着
