### ISSUE TITLE
websocket+fmp4方案浏览器的mse接口播放失败

### ISSUE THREAD

**Issue by jiubao** [xia-chu/ZLMediaKit#709]
尝试用WebSocket+fmp4方案在浏览器内用mse+video播放失败．

环境:
  Ubuntu 16.04.7 LTS
  chrome: Version 83.0.4103.106 (Official Build) (64-bit)

ZLMediaKit:
  hash: fb1e35a39ac86ebefa3fafbc30b80b59acaf8046

代码示例:
  https://codepen.io/jiubao/pen/LYRwGEr

现象:
1. video标签直接播放http-fmp4地址成功.
2. vlc播放http-fmp4成功.
3. ws-fmp4用mse+video播放失败: ws正常连接，浏览器console未报错，视频白屏．
4. chrome://media-internals/日志
render_id: 11
player_id: 58
origin_url: http://localhost:8080/
frame_url: http://localhost:8080/
frame_title: rtsp -> fmp4 -> web socket -> mse -> video
surface_layer_mode: kAlways
url: blob:http://localhost:8080/4870b3b2-3bbb-45d1-a865-6394a294c656
info: Selected FFmpegVideoDecoder for video decoding, config: codec: h264, profile: h264 main, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}
pipeline_state: kPlaying
found_video_stream: true
video_codec_name: h264
found_audio_stream: true
audio_codec_name: aac
debug: (Log limit reached. Further similar entries may be suppressed): Media segment did not contain any coded frames for track 2, mismatching initialization segment. Therefore, MSE coded frame processing may not interoperably detect discontinuities in appended media.
audio_dds: false
audio_decoder: FFmpegAudioDecoder
is_platform_audio_decoder: false
video_dds: false
video_decoder: FFmpegVideoDecoder
is_platform_video_decoder: false
duration: unknown

![chrome_media_log](https://user-images.githubusercontent.com/8424102/105831923-48a66e80-6002-11eb-9659-7646cb499d30.png)

5. 同样的前端代码，稍加改动连接rtsp-ws-proxy (https://github.com/Garefield/RTSP-WS-Proxy) 播放成功

猜测：
尝试将ws接到的fmp4片段连起来保存成文件，用mp4工具分析，怀疑是分片中时间设置问题，有可能是每片的时间没有归零导致video标签定位不到播放时间．

**Comment by xia-chu** [comment]
火狐浏览器应该可以直接播放，Chrome好像确实不能直接播放。
这个问题有人反馈过，好像是chrome需要fmp4的起始时间戳为0才行。
但是在直播转发场景下，要确保每个播放器的起始时间戳为0，那么意味着，每播放一次，都要创建一个fmp4复用器，这个开销太大了，不符合直播的场景，所以我暂时没去做修改。

**Comment by xia-chu** [comment]
不对啊 ，http-fmp4你都能播放，怎么ws-fmp4就不行啊？ 难道是video标签直接播放http-fmp4跟mse播放内存fmp4片段有点区别吗？

**Comment by jiubao** [comment]
> 不对啊 ，http-fmp4你都能播放，怎么ws-fmp4就不行啊？ 难道是video标签直接播放http-fmp4跟mse播放内存fmp4片段有点区别吗？

是的，有区别：
video+http-fmp4代码：
`<video autoPlay muted>
  <source src="http://localhost:8080/live/test.live.mp4?vhost=__defaultVhost__" />
</video>`

ws-fmp4+mse+video代码：
(以下mse代码类似伪代码，无法运行，仅说明调用方式。另外，mime需要从视频分片中解析。)
`var video = documemt.getElementById('video1');
var mediaSource = new MediaSource();
// var mime = 'video/mp4; codecs="avc1.4d002a,mp4a.40.2"';
video.src = URL.createObjectURL(mediaSource);
var sourceBuffer = mediaSource.addSourceBuffer(mime);
websocket.addEventListener('message', evt => {
  var buf = new Unit8Array(evt.data);
  sourceBuffer.appendBuffer(buf);
});`

video标签的方式是直接给video设置src
mse方式需要把fmp4一片一片'append'到sourceBuffer

**Comment by xia-chu** [comment]
是不是你fmp4分片没分对？ fmp4 有个segment头，播放依赖这个，但是这个东西只有开始才会发送，后面没这个的

**Comment by jiubao** [comment]
> 火狐浏览器应该可以直接播放，Chrome好像确实不能直接播放。
> 这个问题有人反馈过，好像是chrome需要fmp4的起始时间戳为0才行。
> 但是在直播转发场景下，要确保每个播放器的起始时间戳为0，那么意味着，每播放一次，都要创建一个fmp4复用器，这个开销太大了，不符合直播的场景，所以我暂时没去做修改。

firefox跟chrome表现一致，video+http-fmp4可以播放, mse+ws-fmp4无法播放。
不确定是否每个片段的时间都要从0开始，但同样的前端代码用https://github.com/Garefield/RTSP-WS-Proxy是可以播出来的。
RTSP-WS-Proxy用的也是ws-fmp4 + mse的方案。它的rtsp转fmp4是调的ffmpeg api。

**Comment by jiubao** [comment]
> 是不是你fmp4分片没分对？ fmp4 有个segment头，播放依赖这个，但是这个东西只有开始才会发送，后面没这个的

![ws-fmp4](https://user-images.githubusercontent.com/8424102/105942149-a3d77000-6099-11eb-9dcd-7d1c244a469e.png)

截图里面第一条红色下行ws包，盒子长度(0000 0020)，盒子类型(ftyp)，这个就是我第一段append到sourceBuffer的分片。segment头指的是这一片么？

**Comment by xia-chu** [comment]
你看下这个issue 已经有人播放ws-fmp4成功了：#664

**Comment by jiubao** [comment]
> 你看下这个issue 已经有人播放ws-fmp4成功了：#664

“拖动进度条到最后面” 确实可以播放，这貌似也证实了我的猜测--fmp4分片的时间设置的有问题。这里前端也许有办法通过设置video的播放时间绕过这个问题，但更好的解法还是要后端能正确的解出让浏览器mse接口满意的fragment mp4啊。

**Comment by xia-chu** [comment]
更新下代码试试

**Comment by jiubao** [comment]
更新了代码和三方依赖，问题依然存在。

**Comment by xia-chu** [comment]
陈大佬(ireader/media-server作者)给我说过怎么改：
![图片](https://user-images.githubusercontent.com/11495632/106686909-2ade9800-6606-11eb-860c-79d3658c51d7.png)

他的库最新的提交，我看是有这个修改的
