### ISSUE TITLE
请问x264依赖怎么添加，ZLMediaKit如何识别x264已经安装

### ISSUE THREAD

**Issue by lzb206** [xia-chu/ZLMediaKit#710]
x264.h文件放在src/codec下，.lib，.dll文件放在vc对接文件夹下，ENABLE_X264已经设置为true， 编译时还是没找到x264，请问如何配置，ZLMediaKit会自动识别x264已经安装

**Comment by xia-chu** [comment]
Windows下比较麻烦 可能要单独指定路径  你可以用cmake-gui单独指定下x264的路径 或者直接修改cmakelist.txt文件
对了 x264默认是关闭的
