### ISSUE TITLE
支持webrtc吗？

### ISSUE THREAD

**Issue by dearthatom** [xia-chu/ZLMediaKit#712]

**Comment by xia-chu** [comment]
不支持

**Comment by EchoChan1985** [comment]
有支持计划吗？

**Comment by HammerZhao** [comment]
> 有支持计划吗？

请问有实践过sdp 扩展中的 nack nackpli 这种rtcp对抗丢失数据包的么？ 
我想实践一下不知道去哪参考开源库 webrtc又太庞大

**Comment by xia-chu** [comment]
我正在做rtcp相关代码 后面要实现  nack nackpli 这些rtcp比较简单了。
你也可以参考下 https://github.com/ireader/media-server 这个库，里面rtcp实现比较完善
