### ISSUE TITLE
RTP推流没有marker标志

### ISSUE THREAD

**Issue by wujianGit123** [xia-chu/ZLMediaKit#713]
RTP推流没有marker标志，可以如下解决：
void CommonRtpEncoder::inputFrame(const Frame::Ptr &frame){
    GET_CONFIG(uint32_t, cycleMS, Rtp::kCycleMS);
    auto stamp = frame->dts() % cycleMS;
    auto ptr = frame->data() + frame->prefixSize();
    auto len = frame->size() - frame->prefixSize();
    auto remain_size = len;
    const auto max_rtp_size = _ui32MtuSize - 20;

    bool marker = false;
    while (remain_size > 0) {
        auto rtp_size = remain_size;
        if (remain_size > max_rtp_size)
            rtp_size = max_rtp_size;
        else
            marker = true;
        RtpCodec::inputRtp(makeRtp(getTrackType(), ptr, rtp_size, marker, stamp), false);
        ptr += rtp_size;
        remain_size -= rtp_size;
    }
}

**Comment by xia-chu** [comment]
是的 确实没设置marker标记 这个貌似不怎么重要 好像都能支持 G711 PS 这样打包 都能被播放

**Comment by wujianGit123** [comment]
有些厂商的GB28181平台不能正确解包


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 上午9:27
收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;"Hello World"<393817707@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] RTP推流没有marker标志 (#713)





 
是的 确实没设置marker标记 这个貌似不怎么重要 好像都能支持 G711 PS 这样打包 都能被播放

**Comment by xia-chu** [comment]
这个问题 我后面会修复下 谢谢您的反馈！

**Comment by xia-chu** [comment]
已修复
