### ISSUE TITLE
海思芯片上,运行报错pure virtual method called terminate called without an active exception Aborted

### ISSUE THREAD

**Issue by lixinhan2019** [xia-chu/ZLMediaKit#715]
在ubuntu上用海思提供的编译器交叉编译,现在编译没有问题,运行最简单的日志打印test都会报pure virtual method called terminate called without an active exception Aborted这个错,芯片是海思3531DV100.
请问哪位大神知道怎么解决???

**Comment by xia-chu** [comment]
需要添加编译参数
g++ -mcpu=generic-armv7-a  -mfloat-abi=softfp  -mfpu=neon-vfpv4

**Comment by lixinhan2019** [comment]
谢谢,问题已经解决了,主要还是编译选项少了 -pthread,
https://blog.sharpbai.com/2021/01/%e8%a7%a3%e5%86%b3%e6%b5%b7%e6%80%9d%e5%b9%b3%e5%8f%b0%e4%b8%8bc%e5%90%af%e5%8a%a8%e7%ba%bf%e7%a8%8b%e6%8a%a5pure-virtual-method-called-terminate-called-without-an-active-exception%e9%97%ae/

**Comment by xia-chu** [comment]
嗯 跟pthread 关系不大 主要还是指定 mcpu mfloat-abi mfpu这些东西 
我很早之前也在海思上编译过

**Comment by lixinhan2019** [comment]
我这边实际开发的时候就是少了-pthread,加这个就正常运行了,不加这个就报错

**Comment by chenhanwen2019** [comment]
@lixinhan2019 您好，请问您使用的海思交叉编译器是哪一个呢，是hisiv500吗？我现在用hisiv500编译报错，如若您有空，帮忙看看，谢谢！！！
