### ISSUE TITLE
httpApi访问内存泄露？

### ISSUE THREAD

**Issue by chenxihai** [xia-chu/ZLMediaKit#717]
centos7系统，4G内存，运行项目自带程序test_httpApi
使用http_load进行web服务器的吞吐量与负载测试
http_load -p 5 -s 120 urllist.txt  (访问链接http://127.0.0.1/api/my_api?key=0)
发现test_httpApi占用内存从1%慢慢涨到63.5%，之后top查看一直不释放，系统也出现反应迟缓情况。
请问这是内存泄露导致的吗？

**Comment by xia-chu** [comment]
你测试下MediaServer的http接口试试？ test_httpApi的api做了一次线程切换 如果处理不过来 确实会内存积压
