### ISSUE TITLE
关于getMediaList接口问题：

### ISSUE THREAD

**Issue by 17Sdubin** [xia-chu/ZLMediaKit#721]
大神你好，getmedialist接口可以获取到hls、rtsp、rtmp、ts、fmp4这五种转协议的播放情况，比如每种协议的播放数量等。我想请教下是否这个属性可以进一步细化呢？比如配置文件中rtmp[s]、http[s]-flv、ws[s]-flv都是基于rtmp流传输播放的，现在调用getmedialist接口只能获取到rtmp流的观看人数,如何进一步获取rtmp[s]、http[s]-flv、ws[s]-flv这三种协议具体每一种协议的播放情况呢？请大神指点下！

**Comment by 17Sdubin** [comment]
或者调用getAllSession接口是否可以获取到每个客户端是基于哪种协议播放的哪种媒体流呢？

**Comment by xia-chu** [comment]
rtmp[s] http[s]-flv ws[s]-flv这些协议访问的数据源都是同一个 他们本质上是一样的 只是传输协议不同 播放个数统计都是在数据源内统计的，所以没法区分是什么协议访问的。
其实一般来说，用户根本不关系播放用什么协议，他们只关心同事观看人数，所以我觉得没必要分的那么清楚
