### ISSUE TITLE
请问是否计划更低延迟的LHLS或者说hls+?

### ISSUE THREAD

**Issue by amhoho** [xia-chu/ZLMediaKit#726]
使用ZLMediaKit一年多,hls延迟基本维持在9-10s左右,而LHLS至少能缩减到5-6s,请问未来是否有更新计划?毕竟使用hls可能在web端而言是使用最广泛的了.

**Comment by xia-chu** [comment]
暂时没这个打算 因为我觉得hls不是种好协议 就算5~6秒  还是延时太高了
