### ISSUE TITLE
[需求] 流地址已经创建, 但是track尚未ready, 此时客户端访问的话, 会失败, 能否等待一段时间?

### ISSUE THREAD

**Issue by netjune** [xia-chu/ZLMediaKit#727]
比如可以跟打开不存在的流一样, 先hold住连接, 稍微等待一段时间, 比如等到所有track都ready之后, 才给客户端返回数据.

**Comment by xia-chu** [comment]
嗯 这个是流创建了 zlm等待太久 还解析不出sps pps, 那么zlm会忽略掉这个track，这个跟你说的挂起播放器不具备可比性啊，

**Comment by netjune** [comment]
此时数据一点都还没过来, 大概几百毫秒到1两秒左右, 数据才过来.

**Comment by netjune** [comment]
有些摄像头打开的时候, 数据有延迟

**Comment by xia-chu** [comment]
现在zlm会等10秒呢 10秒还不够长吗

**Comment by netjune** [comment]
> 
> 
> 现在zlm会等10秒呢 10秒还不够长吗

你说这个是码流id不存在(未创建)的情况下等待吗? 我说的是码流id已经提前创建, 但是码流数据还没过来, 此时客户端访问的话, 会马上返回错误.

**Comment by netjune** [comment]
还有一种情况就是, 视频可能ready了, 但是音频还未ready, 此时客户端访问的话, 可能也会有问题, 比如RTSP的sdp信息里就只有视频, 没有音频.

**Comment by xia-chu** [comment]
> 
> 
> 还有一种情况就是, 视频可能ready了, 但是音频还未ready, 此时客户端访问的话, 可能也会有问题, 比如RTSP的sdp信息里就只有视频, 没有音频.

这个情况不会存在的 zlm在忽略track后 sdp里面不会有被忽略的track

**Comment by xia-chu** [comment]
> 
> 
> > 现在zlm会等10秒呢 10秒还不够长吗
> 
> 你说这个是码流id不存在(未创建)的情况下等待吗? 我说的是码流id已经提前创建, 但是码流数据还没过来, 此时还没有track信息, 此时客户端访问的话, 会马上返回错误. 这种情况下, 如果能等待几百毫秒到几秒, 码流数据就过来了.

是说的是28181推流场景吗

**Comment by netjune** [comment]
> 
> 
> > 还有一种情况就是, 视频可能ready了, 但是音频还未ready, 此时客户端访问的话, 可能也会有问题, 比如RTSP的sdp信息里就只有视频, 没有音频.
> 
> 这个情况不会存在的 zlm在忽略track后 sdp里面不会有被忽略的track

实际上是有音频的, 只是晚了一点, 不希望忽略音频.

**Comment by netjune** [comment]
> 
> 
> > > 现在zlm会等10秒呢 10秒还不够长吗
> > 
> > 
> > 你说这个是码流id不存在(未创建)的情况下等待吗? 我说的是码流id已经提前创建, 但是码流数据还没过来, 此时还没有track信息, 此时客户端访问的话, 会马上返回错误. 这种情况下, 如果能等待几百毫秒到几秒, 码流数据就过来了.
> 
> 是说的是28181推流场景吗

不是28181, 通用的, 比如RTSP, RTMP等.

我想到其他方法了. 这个需求不是必须, 可以关了.
