### ISSUE TITLE
语音对讲建议用webrtc,有什么推荐的demo嘛

### ISSUE THREAD

**Issue by Huanghetaotao** [xia-chu/ZLMediaKit#729]
webrtc我目前仅知道，比如我的电脑端和另一个电脑端，这我理解应该可以开发出语音对讲，因为他们每个都可以当作一个点可以互相连的上。但是PC和摄像头一起的话，怎么样可以把一个摄像头端当作一个点，这我就不知道怎么搞

**Comment by Huanghetaotao** [comment]
根据上面2个文章，搞定了基于wvp-gb28181
GB28181协议——摄像机语音对讲
https://blog.csdn.net/qq_38795209/article/details/110953058?utm_medium=distribute.pc_relevant_bbs_down.none-task--2~all~first_rank_v2~rank_v29-12.nonecase&depth_1-utm_source=distribute.pc_relevant_bbs_down.none-task--2~all~first_rank_v2~rank_v29-12.nonecase

RTP打包音频g711
https://blog.csdn.net/qq_38795209/article/details/113942389

**Comment by ly616187030** [comment]
GB28181协议——摄像机语音对讲，请问你解决了吗？我也遇到这个问题了

**Comment by xia-chu** [comment]
可以用webrtc推流到zlm zlm在通过sendRtp的方式发给设备？不过好像zlm也不太可能直接能跨越nat访问摄像头
