### ISSUE TITLE
PS收流导致程序异常退出

### ISSUE THREAD

**Issue by ChuLiqiang** [xia-chu/ZLMediaKit#731]
#0  0x00007f6b1bd8764b in malloc_consolidate () from /lib64/libc.so.6
#1  0x00007f6b1bd89295 in _int_malloc () from /lib64/libc.so.6
#2  0x00007f6b1bd8c1ac in malloc () from /lib64/libc.so.6
#3  0x00007f6b1be1b1be in backtrace_symbols () from /lib64/libc.so.6
#4  0x0000000000b2c8c4 in sig_crash(int) ()
#5  <signal handler called>
#6  0x00007f6b1be5c76a in __memcpy_ssse3_back () from /lib64/libc.so.6
#7  0x0000000000eb63a1 in mpeg_packet_append ()
#8  0x0000000000eb67e4 in pes_packet ()
#9  0x0000000000eaeeaa in pes_packet_read ()
#10 0x0000000000eaf0f6 in ps_demuxer_input ()
#11 0x0000000000e5c993 in mediakit::PSDecoder::input(unsigned char const*, unsigned long) ()
#12 0x0000000000e501e5 in mediakit::DecoderImp::input(unsigned char const*, unsigned long) ()
#13 0x0000000000e59d75 in mediakit::GB28181Process::onSearchPacketTail(char const*, unsigned long) ()
#14 0x0000000000c70593 in mediakit::HttpRequestSplitter::input(char const*, unsigned long) ()
#15 0x0000000000e5a1a3 in mediakit::GB28181Process::onRtpDecode(std::shared_ptr<mediakit::Frame> const&) ()
#16 0x0000000000e59774 in mediakit::GB28181Process::onRtpSorted(std::shared_ptr<mediakit::RtpPacket> const&, int)::{lambda(std::shared_ptr<mediakit::Frame> const&)#3}::operator()(std::shared_ptr<mediakit::Frame> const&) const ()
#17 0x0000000000e5b85d in std::_Function_handler<void (std::shared_ptr<mediakit::Frame> const&), mediakit::GB28181Process::onRtpSorted(std::shared_ptr<mediakit::RtpPacket> const&, int)::{lambda(std::shared_ptr<mediakit::Frame> const&)#3}>::_M_invoke(std::_Any_data const&, std::shared_ptr<mediakit::Frame> const&) ()
#18 0x0000000000d98087 in std::function<void (std::shared_ptr<mediakit::Frame> const&)>::operator()(std::shared_ptr<mediakit::Frame> const&) const ()
#19 0x0000000000d97ebf in mediakit::FrameWriterInterfaceHelper::inputFrame(std::shared_ptr<mediakit::Frame> const&) ()
#20 0x0000000000cac2d9 in mediakit::FrameDispatcher::inputFrame(std::shared_ptr<mediakit::Frame> const&) ()
#21 0x0000000000e43478 in mediakit::CommonRtpDecoder::inputRtp(std::shared_ptr<mediakit::RtpPacket> const&, bool) ()
#22 0x0000000000e59c2a in mediakit::GB28181Process::onRtpSorted(std::shared_ptr<mediakit::RtpPacket> const&, int) ()
#23 0x0000000000e3a132 in mediakit::RtpReceiver::RtpReceiver()::{lambda(unsigned short, std::shared_ptr<mediakit::RtpPacket>&)#1}::operator()(unsigned short, std::shared_ptr<mediakit::RtpPacket>&) const ()
#24 0x0000000000e3b03e in std::_Function_handler<void (unsigned short, std::shared_ptr<mediakit::RtpPacket>&), mediakit::RtpReceiver::RtpReceiver()::{lambda(unsigned short, std::shared_ptr<mediakit::RtpPacket>&)#1}>::_M_invoke(std::_Any_data const&, unsigned short, std::shared_ptr<mediakit::RtpPacket>&) ()
#25 0x0000000000e3c561 in std::function<void (unsigned short, std::shared_ptr<mediakit::RtpPacket>&)>::operator()(unsigned short, std::shared_ptr<mediakit::RtpPacket>&) const ()
#26 0x0000000000e3c46b in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 256ul, 10ul>::popIterator(std::_Rb_tree_iterator<std::pair<unsigned short const, std::shared_ptr<mediakit::RtpPacket> > >) ()
#27 0x0000000000e3bd2c in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 256ul, 10ul>::popPacket() ()
#28 0x0000000000e3b80a in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 256ul, 10ul>::tryPopPacket() ()
#29 0x0000000000e3b5e8 in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 256ul, 10ul>::sortPacket(unsigned short, std::shared_ptr<mediakit::RtpPacket>) ()
#30 0x0000000000e3ac5f in mediakit::RtpReceiver::handleOneRtp(int, mediakit::TrackType, int, unsigned char*, unsigned long) ()
#31 0x0000000000e595ce in mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long) ()
#32 0x0000000000e236df in mediakit::RtpProcess::inputRtp(bool, std::shared_ptr<toolkit::Socket> const&, char const*, unsigned long, sockaddr const*, unsigned int*) ()
---Type <return> to continue, or q <return> to quit---
#33 0x0000000000d3856d in mediakit::RtpServer::start(unsigned short, std::string const&, bool, char const*)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const ()
#34 0x0000000000d394ff in std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), mediakit::RtpServer::start(unsigned short, std::string const&, bool, char const*)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) ()
#35 0x0000000000e6c5d5 in std::function<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)>::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const ()
#36 0x0000000000e63326 in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#37 0x0000000000e62d50 in toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}::operator()(int) const ()
#38 0x0000000000e67c09 in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int) ()
#39 0x0000000000c8e470 in std::function<void (int)>::operator()(int) const ()
#40 0x0000000000e7c852 in toolkit::EventPoller::runLoop(bool, bool) ()
#41 0x0000000000e8bfbc in void std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)>::operator()<bool, bool, void>(toolkit::EventPoller*, bool&&, bool&&) const ()
#42 0x0000000000e8bdd3 in void std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) ()
#43 0x0000000000e8bb13 in std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::operator()() ()
#44 0x0000000000e8b85c in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)> >::_M_run() ()
#45 0x00007f6b1c6a1070 in ?? () from /lib64/libstdc++.so.6
#46 0x00007f6b1c8fadd5 in start_thread () from /lib64/libpthread.so.0
#47 0x00007f6b1be04ead in clone () from /lib64/libc.so.6

**Comment by xia-chu** [comment]
你的代码什么版本？

**Comment by ChuLiqiang** [comment]
> 你的代码什么版本？

最新的代码

**Comment by xia-chu** [comment]
给下Git hash

**Comment by ChuLiqiang** [comment]
> 给下Git hash

[root@localhost ZLMediaKit]# git log
commit bad9553ec46ab2e88a595eb8bc09e91ce41f0f82 (HEAD -> master)
Author: xiongziliang <771730766@qq.com>
Date:   Sun Jan 24 21:59:55 2021 +0800

我发现咱们最近这个RTP收流好像更新了一下东西,RTP收流这块有内存问题吗?
![image](https://user-images.githubusercontent.com/2747722/107172403-3532d480-6a00-11eb-98bc-de1e1483927d.png)

**Comment by xia-chu** [comment]
更新代码试试 可能是线程安全的问题

**Comment by ChuLiqiang** [comment]
> 更新代码试试 可能是线程安全的问题

恩,晚上跑上试试.

**Comment by xia-chu** [comment]
```patch
Index: src/Rtp/Decoder.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/Decoder.h	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
+++ src/Rtp/Decoder.h	(date 1612849676000)
@@ -25,7 +25,7 @@
     typedef std::function<void(int stream, int codecid, int flags, int64_t pts, int64_t dts, const void *data, size_t bytes)> onDecode;
     typedef std::function<void(int stream, int codecid, const void *extra, size_t bytes, int finish)> onStream;
 
-    virtual size_t input(const uint8_t *data, size_t bytes) = 0;
+    virtual ssize_t input(const uint8_t *data, size_t bytes) = 0;
     virtual void setOnDecode(onDecode cb) = 0;
     virtual void setOnStream(onStream cb) = 0;
 
@@ -57,7 +57,7 @@
     ~DecoderImp() = default;
 
     static Ptr createDecoder(Type type, MediaSinkInterface *sink);
-    size_t input(const uint8_t *data, size_t bytes);
+    ssize_t input(const uint8_t *data, size_t bytes);
 
 protected:
     void onTrack(const Track::Ptr &track);
Index: src/Rtp/TSDecoder.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/TSDecoder.cpp	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
+++ src/Rtp/TSDecoder.cpp	(date 1612849736000)
@@ -77,7 +77,7 @@
     ts_demuxer_destroy(_demuxer_ctx);
 }
 
-size_t TSDecoder::input(const uint8_t *data, size_t bytes) {
+ssize_t TSDecoder::input(const uint8_t *data, size_t bytes) {
     if (TSSegment::isTSPacket((char *)data, bytes)) {
         return ts_demuxer_input(_demuxer_ctx, (uint8_t *) data, bytes);
     }
Index: src/Rtp/PSDecoder.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/PSDecoder.cpp	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
+++ src/Rtp/PSDecoder.cpp	(date 1612849736000)
@@ -44,7 +44,7 @@
     ps_demuxer_destroy((struct ps_demuxer_t*)_ps_demuxer);
 }
 
-size_t PSDecoder::input(const uint8_t *data, size_t bytes) {
+ssize_t PSDecoder::input(const uint8_t *data, size_t bytes) {
     return ps_demuxer_input((struct ps_demuxer_t*)_ps_demuxer,data,bytes);
 }
 
Index: src/Rtp/PSDecoder.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/PSDecoder.h	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
+++ src/Rtp/PSDecoder.h	(date 1612849676000)
@@ -21,7 +21,7 @@
 public:
     PSDecoder();
     ~PSDecoder();
-    size_t input(const uint8_t* data, size_t bytes) override;
+    ssize_t input(const uint8_t* data, size_t bytes) override;
     void setOnDecode(onDecode cb) override;
     void setOnStream(onStream cb) override;
 
Index: src/Rtp/Decoder.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/Decoder.cpp	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
+++ src/Rtp/Decoder.cpp	(date 1612849676000)
@@ -54,7 +54,7 @@
     return DecoderImp::Ptr(new DecoderImp(decoder, sink));
 }
 
-size_t DecoderImp::input(const uint8_t *data, size_t bytes){
+ssize_t DecoderImp::input(const uint8_t *data, size_t bytes){
     return _decoder->input(data, bytes);
 }
 
Index: src/Rtp/TSDecoder.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Rtp/TSDecoder.h	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
+++ src/Rtp/TSDecoder.h	(date 1612849736000)
@@ -45,7 +45,7 @@
 public:
     TSDecoder();
     ~TSDecoder();
-    size_t input(const uint8_t* data, size_t bytes) override ;
+    ssize_t input(const uint8_t* data, size_t bytes) override ;
     void setOnDecode(onDecode cb) override;
     void setOnStream(onStream cb) override;
 

```

**Comment by ChuLiqiang** [comment]
> 试试这个patch
> 
> ```diff
> Index: src/Rtp/Decoder.h
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- src/Rtp/Decoder.h	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
> +++ src/Rtp/Decoder.h	(date 1612849676000)
> @@ -25,7 +25,7 @@
>      typedef std::function<void(int stream, int codecid, int flags, int64_t pts, int64_t dts, const void *data, size_t bytes)> onDecode;
>      typedef std::function<void(int stream, int codecid, const void *extra, size_t bytes, int finish)> onStream;
>  
> -    virtual size_t input(const uint8_t *data, size_t bytes) = 0;
> +    virtual ssize_t input(const uint8_t *data, size_t bytes) = 0;
>      virtual void setOnDecode(onDecode cb) = 0;
>      virtual void setOnStream(onStream cb) = 0;
>  
> @@ -57,7 +57,7 @@
>      ~DecoderImp() = default;
>  
>      static Ptr createDecoder(Type type, MediaSinkInterface *sink);
> -    size_t input(const uint8_t *data, size_t bytes);
> +    ssize_t input(const uint8_t *data, size_t bytes);
>  
>  protected:
>      void onTrack(const Track::Ptr &track);
> Index: src/Rtp/TSDecoder.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- src/Rtp/TSDecoder.cpp	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
> +++ src/Rtp/TSDecoder.cpp	(date 1612849736000)
> @@ -77,7 +77,7 @@
>      ts_demuxer_destroy(_demuxer_ctx);
>  }
>  
> -size_t TSDecoder::input(const uint8_t *data, size_t bytes) {
> +ssize_t TSDecoder::input(const uint8_t *data, size_t bytes) {
>      if (TSSegment::isTSPacket((char *)data, bytes)) {
>          return ts_demuxer_input(_demuxer_ctx, (uint8_t *) data, bytes);
>      }
> Index: src/Rtp/PSDecoder.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- src/Rtp/PSDecoder.cpp	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
> +++ src/Rtp/PSDecoder.cpp	(date 1612849736000)
> @@ -44,7 +44,7 @@
>      ps_demuxer_destroy((struct ps_demuxer_t*)_ps_demuxer);
>  }
>  
> -size_t PSDecoder::input(const uint8_t *data, size_t bytes) {
> +ssize_t PSDecoder::input(const uint8_t *data, size_t bytes) {
>      return ps_demuxer_input((struct ps_demuxer_t*)_ps_demuxer,data,bytes);
>  }
>  
> Index: src/Rtp/PSDecoder.h
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- src/Rtp/PSDecoder.h	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
> +++ src/Rtp/PSDecoder.h	(date 1612849676000)
> @@ -21,7 +21,7 @@
>  public:
>      PSDecoder();
>      ~PSDecoder();
> -    size_t input(const uint8_t* data, size_t bytes) override;
> +    ssize_t input(const uint8_t* data, size_t bytes) override;
>      void setOnDecode(onDecode cb) override;
>      void setOnStream(onStream cb) override;
>  
> Index: src/Rtp/Decoder.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- src/Rtp/Decoder.cpp	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
> +++ src/Rtp/Decoder.cpp	(date 1612849676000)
> @@ -54,7 +54,7 @@
>      return DecoderImp::Ptr(new DecoderImp(decoder, sink));
>  }
>  
> -size_t DecoderImp::input(const uint8_t *data, size_t bytes){
> +ssize_t DecoderImp::input(const uint8_t *data, size_t bytes){
>      return _decoder->input(data, bytes);
>  }
>  
> Index: src/Rtp/TSDecoder.h
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- src/Rtp/TSDecoder.h	(revision e4904623a77b7f812125409893677c6f6bd1ab99)
> +++ src/Rtp/TSDecoder.h	(date 1612849736000)
> @@ -45,7 +45,7 @@
>  public:
>      TSDecoder();
>      ~TSDecoder();
> -    size_t input(const uint8_t* data, size_t bytes) override ;
> +    ssize_t input(const uint8_t* data, size_t bytes) override ;
>      void setOnDecode(onDecode cb) override;
>      void setOnStream(onStream cb) override;
>  
> ```

已经确认是老层底层库这块的长度越界问题,咱们上层暂时不用改。
