### ISSUE TITLE
【求助】国标28181保活问题

### ISSUE THREAD

**Issue by Allenisme** [xia-chu/ZLMediaKit#732]
![image](https://user-images.githubusercontent.com/17775578/107172945-9909cd00-6a01-11eb-868a-2b935d2a2495.png)
大佬，请问下RTP over TCP不需要发rtcp包保活吗？试了下TCP推流隔一段时间还是会断开。

**Comment by xia-chu** [comment]
目前28181 zlm在tcp模式下是不会发rtcp保活包的 理论上 这个不是必要的
