### ISSUE TITLE
PSEncoder::inputFrame在做PS封包时有问题

### ISSUE THREAD

**Issue by wujianGit123** [xia-chu/ZLMediaKit#733]
接收端在收到PS封包后的流之后，解包出流rtsp可以正常播放，而flv、mp4等流则无法正常播放。测试是PS封包的问题，因为同样是ps流，海康等厂家摄像头的流在接收端解包出流后rtsp、flv、mp4等均可正常播放。该问题仅在h265编码流出现，h264流一切正常。

**Comment by xia-chu** [comment]
可能是这个摄像头的p帧时间戳有点问题 这个问题应该修复了 你可以pull下新代码试试

**Comment by wujianGit123** [comment]
不是时间戳问题，此问题我已解决，是libmpeg库中强制插入AUD导致，可通过设置ps_muxer_input的flags参数 |= 0x8000标志位，避免libmpeg库插入AUD，如此输出的ps流就可以解析并正常播放

**Comment by wujianGit123** [comment]
另外fmp4流还是存在跳帧的问题，应该是libmov库的bug，希望第三方库作者能及时解决

**Comment by xia-chu** [comment]
哦哦 应该在生产flv mp4 rtsp时忽略掉AUD

**Comment by xia-chu** [comment]
> 另外fmp4流还

你是http-fmp4直播 还是生产fmp4文件？

**Comment by wujianGit123** [comment]
> > 另外fmp4流还
> 
> 你是http-fmp4直播 还是生产fmp4文件？

http-fmp4

**Comment by xia-chu** [comment]
这个不是第三方库的问题 是浏览器问题 firefox就不卡

**Comment by xia-chu** [comment]
也可以改zlm代码让Chrome流畅 但是会增大延时

**Comment by wujianGit123** [comment]
不是，用vlc播放也存在这种情况。这种情况出现在PSEncoder::inputFrame输出的ps流，接收端解析ps流之后生产的http-fmp4流有卡帧跳帧的现象，但是用RtspPlayer拉流所产生的http-fmp4流播放是正常的。说到底应该还是PSEncoder::inputFrame的问题。

**Comment by wujianGit123** [comment]
PSEncoder::inputFrame输出的ps流，接收端解析ps流之后生产flv、rtsp等都是正常的

**Comment by xia-chu** [comment]
哦哦 你发送端和接收端都是zlm对吧

**Comment by wujianGit123** [comment]
> 哦哦 你发送端和接收端都是zlm对吧

是的
