### ISSUE TITLE
Stream goes out of sync after some time

### ISSUE THREAD

**Issue by xoraingroup** [xia-chu/ZLMediaKit#736]
I have following scenario

**OBS -> Origin <--- Edge**

So I am sending api call to **Edge** using addStreamProxy with enable_hls: 1. Everything works fine. The hls fragments are generated and I can pull stream using **ffplay "rtmp://edge-ip/live/mystream"** and everything works well. But after like 2 or 4 hours I can see that the stream audio / video on **Edge** is out of sync.

**ffplay threw some error related to "co located POCs unavailable"**

If i try to play the same stream from **Origin** at the same moment using **ffplay "rtmp://origin-ip/live/mystream"** its perfectly synced.

Any input would be highly appreciated.

**Comment by xia-chu** [comment]
Is  `rtmp://edge-ip/live/mystream` or `http://edge-ip/live/mystream/hls.m3u8`  out of sync？

**Comment by xoraingroup** [comment]
Actually both are out of sync hls and rtmp on edge.

**Comment by xoraingroup** [comment]
Any idea on this? Are there any parameters that can be tuned?

**Comment by xoraingroup** [comment]
Anything?

**Comment by xia-chu** [comment]
Sorry, we just had the Chinese New Year，We're now starting working

**Comment by xia-chu** [comment]
When HLS and RTMP are generated, ZLM will convert absolute time stamp into relative time stamp。
However, there may be errors when the timestamp is looped. If the number of looping times is more, the cumulative error will be larger, resulting in audio and video out of sync

**Comment by xia-chu** [comment]
Here's the key code：
![图片](https://user-images.githubusercontent.com/11495632/108291349-1cc77480-71cd-11eb-8634-fad782b55e6a.png)

**Comment by xia-chu** [comment]
However, the RTSP timestamp loops once every 21 hours. In fact, the error is not big

**Comment by xia-chu** [comment]
What stream do you add with the addstreamproxy interface?

**Comment by xoraingroup** [comment]
Its an RTMP Stream.

**Comment by xoraingroup** [comment]
Is there any possibility to disconnect current flow and reconnect if it sees there is a delay without invoking deletestreamproxy and invoking again addstreamproxy.? If it can be done internally thats also good.

**Comment by xia-chu** [comment]
Is the origin RTMP server ZLMediaKit?

**Comment by xoraingroup** [comment]
Yes, they both are ZLMediaKit.

**Comment by xia-chu** [comment]
Now  i will test it

**Comment by xia-chu** [comment]
I used obs push rtmp to `origin sever(zlmediakit)`, and then use `addStreamProxy` api pull it by rtmp on the `edge server(zlmediakit)`,
Then i use vlc to play this stream by rtmp from `edge server`, now i played it for 3 hours, and video is synced to audio.

**Comment by xia-chu** [comment]
I haven't reproduced what you said at present

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/108811132-a4efb480-75e7-11eb-9f8d-d862ae1b3f2f.png)

**Comment by xia-chu** [comment]
Now i played 5 hours, and video is synced to audio too
![图片](https://user-images.githubusercontent.com/11495632/108822126-9a3e1b00-75f9-11eb-8477-273e34ec2fc6.png)

**Comment by xia-chu** [comment]
Can you provide the GIT hash of ZLM code

**Comment by xoraingroup** [comment]
I think you tried it on localhost. When a user is streaming to a remote server and then a pull is made, thats where it causes issue. For localhost i think you might never find such issue or very rarely.

**Comment by xoraingroup** [comment]
git log shows bba18156ea1ab93744a0e226ccca8e9e0154be2e as latest commit.

**Comment by xia-chu** [comment]
Now i played for 21 hours, and video is synced to audio too
![图片](https://user-images.githubusercontent.com/11495632/108929845-bab0b880-767f-11eb-889e-972b24b0be2c.png)

**Comment by xia-chu** [comment]
> 
> 
> I think you tried it on localhost. When a user is streaming to a remote server and then a pull is made, thats where it causes issue. For localhost i think you might never find such issue or very rarely.

I don't think so. In terms of code, there is no difference between localhost and remote

**Comment by xoraingroup** [comment]
What happens when there are packet loss from server pulling stream from another server with addStreamProxy. ?

**Comment by xia-chu** [comment]
> 
> 
> What happens when there are packet loss from server pulling stream from another server with addStreamProxy. ?

No ， tcp will not happen packet loss

**Comment by xoraingroup** [comment]
The full setup is like

addStreamProxy on Server1 -----pull from ----> Server2

Server1 also generates hls ts fragments. Then we play stream from Server1 using rtmp pull. Any bells ringing if it has to do with hls ts fragments. 

We are so confused that with tcp packet loss will not happen, then why audio video sync issue happening on Server1 and not Server2.

I will try to reproduce it and then try to give you rtmp urls to check urself. Is that ok with you?
