### ISSUE TITLE
GBS28281推流时会出现RTP丢包及close connection after send http body completed情况

### ISSUE THREAD

**Issue by perryDavid** [xia-chu/ZLMediaKit#738]
新年好，摄像头通过GBS28281推流时会出现卡顿、花屏现象，观察ZLMediaServer日志出现RTP丢包及close connection after send http body completed情况，请问该如何处理？

![image](https://user-images.githubusercontent.com/28890694/108445372-3b923d80-7297-11eb-8b4c-19225abf22c7.png)

**Comment by xia-chu** [comment]
你按照这个设置下：
https://sharechain.qq.com/8ad7ce0e08fe44a35ddf89d92be7b077

**Comment by xia-chu** [comment]
先关闭issue了 有问题继续在此讨论

**Comment by perryDavid** [comment]
你好，我按照文档上设置后，没有解决RTP丢包的问题，采用内网地址推送，操作如下：
1.设置socket默认缓存区为4M
![image](https://user-images.githubusercontent.com/28890694/108953979-09be1400-76a7-11eb-9212-0de1108ad4f7.png)
2.执行cat /proc/net/snmp | grep -w Udp
![image](https://user-images.githubusercontent.com/28890694/108954047-235f5b80-76a7-11eb-84f0-2a19d7a06622.png)
3.设置RtpReceiver.h kmin=1
![image](https://user-images.githubusercontent.com/28890694/108954183-63bed980-76a7-11eb-9212-4d73c1513010.png)

烦请指教，谢谢。

**Comment by xia-chu** [comment]
多次执行cat /proc/net/snmp | grep -w Udp如果发现RcvbufErrors   不变，那说明丢包在网络传输或发送端就丢包了

**Comment by xia-chu** [comment]
RcvbufErrors 增大 则代表udp接收端消费不及时导致丢包，你应该关注zlm的日志 如果有显示丢包 请及时查看RcvbufErrors 是否增大

**Comment by perryDavid** [comment]
好的，多谢指教。
