### ISSUE TITLE
/index/api/addFFmpegSource 推流给自己超时

### ISSUE THREAD

**Issue by ZhouMin216** [xia-chu/ZLMediaKit#739]
调用/index/api/addFFmpegSource接口拉取h265的流，当dst_url参数设置为另一个MediaServer服务器时能推流成功，当dst_url设置为自己时，提示超时。（dst_url设置为rtmp://127.0.0.1/live/stream_form_ffmpeg或者是自身ip都不行）
以下是MediaServer的日志：
{
   "code" : -1,
   "msg" : "等待超时"
}

以下是ffmpeg.log的错误日志：
[rtmp @ 0x26ba8a0] Cannot open connection tcp://192.168.104.19:1935
rtmp://192.168.104.19/live/streamFF: Immediate exit requested

**Comment by xia-chu** [comment]
你手动执行下FFmpeg命令 看看行不行

**Comment by ZhouMin216** [comment]
> 你手动执行下FFmpeg命令 看看行不行

试过了 ，是可以的。而且敲的指令跟参数和MediaServer里执行的都是一样的。

**Comment by xia-chu** [comment]
你看 FFmpeg的日志不会骗人 所以zlm在启动FFmpeg时 确实推流失败

**Comment by xia-chu** [comment]
你确实你的推流地址  rtmp://192.168.104.19:1935/xx/xxxx  是ok的?

**Comment by ZhouMin216** [comment]
> 你确实你的推流地址 rtmp://192.168.104.19:1935/xx/xxxx 是ok的?

我确定推流地址是可用的，因为我手动执行FFmpeg指令时用到的也是这个推流地址。
<img width="1035" alt="pushSuccess" src="https://user-images.githubusercontent.com/47287700/108650257-1ea97480-74fa-11eb-8692-d655389b318c.png">
<img width="974" alt="ffmpegCmd" src="https://user-images.githubusercontent.com/47287700/108650274-2701af80-74fa-11eb-9c4d-9ec8246f0550.png">

**Comment by xia-chu** [comment]
addFFmpegSource拉流的rtsp吗

**Comment by xia-chu** [comment]
完整api参数提供下

**Comment by ZhouMin216** [comment]
测试环境：
centOS7虚拟机(192.168.104.19)运行MediaServer, 在win10环境下使用Postman调用addFFmpegSource接口拉取另一台服务器上的流rtsp://192.168.1.237:554/wangzhe，当我把拉到的流转成h264在推给另一台服务器（192.168.1.136）上的MediaServer时，是可以正常执行的，使用VLC播放也是没问题的，但是当我把推流地址改成虚拟机自身（192.168.104.19）时就提示超时了。

**Comment by xia-chu** [comment]
这种问题一般是网络问题的 跟代码关系不大

**Comment by ZhouMin216** [comment]
Postman使用以下参数能够正常执行：
http://192.168.104.19/index/api/addFFmpegSource?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&src_url=rtsp://192.168.1.237:554/wangzhe&dst_url=rtmp://192.168.1.136/live/streamFF&timeout_ms=1000&enable_hl=0&enable_mp4=0
dst_url改成自身rtmp://127.0.0.1/live/streamFF或者rtmp://192.168.104.19/live/streamFF，都会失败。
但是在命令行执行时，不论是
/usr/bin/ffmpeg -re -i rtsp://192.168.1.237:554/wangzhe -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://192.168.1.136/live/streamFF
还是
/usr/bin/ffmpeg -re -i rtsp://192.168.1.237:554/wangzhe -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://192.168.104.19/live/streamFF
都能推流成功。

**Comment by ZhouMin216** [comment]
<img width="644" alt="ok" src="https://user-images.githubusercontent.com/47287700/108676326-06018480-7523-11eb-8e3c-a53d95d4ef79.png">

**Comment by ZhouMin216** [comment]
> 这种问题一般是网络问题的 跟代码关系不大

有可能，但是不应该是推给其他服务器出现问题的可能性更大一点吗？

**Comment by xia-chu** [comment]
你让ffmpeg 1秒内就成功 不是难为它吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZhouMin216 <notifications@github.com&gt;
发送时间: 2021年2月22日 15:32
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] /index/api/addFFmpegSource 推流给自己超时 (#739)





  
这种问题一般是网络问题的 跟代码关系不大
  
有可能，但是不应该是推给其他服务器出现问题的可能性更大一点吗？

**Comment by ZhouMin216** [comment]
这个值我改过，之前设置的是10秒，刚才设置到15秒时推流给自己就成功了。感谢大佬！！！
（从log来看，其实设置到13秒时，就已经接收到流了，并且已经开始媒体注册，但紧接又媒体注销了。）

**Comment by chatop2020** [comment]
确实，有些流用ffmpeg拉过来会很慢，所以我当时建议把zlm内部的ffmpeg超时设置到20秒

**Comment by xia-chu** [comment]
> 
> 
> 这个值我改过，之前设置的是10秒，刚才设置到15秒时推流给自己就成功了。感谢大佬！！！
> （从log来看，其实设置到13秒时，就已经接收到流了，并且已经开始媒体注册，但紧接又媒体注销了。）

这个问题已结贴 那就关闭吧
