### ISSUE TITLE
期望添加两个hook，一个是定期发送机器的负载情况和流媒体的数量， 一个定期发送所有的流媒体信息。

### ISSUE THREAD

**Issue by yangdon** [xia-chu/ZLMediaKit#741]
期望添加两个hook：
一个是定期发送机器的负载情况和流媒体的数量；
一个定期发送所有的流媒体信息。

这两个hook的信息在http api中有提供对应的查询接口，一个是getStatistic接口，一个是getMediaList的全量查询，但是在流媒体集群环境下，不太适合由业务服务去请求媒体服务，获取这些信息，由流媒体集群发送到业务服务更合理一些。

一个hook可以配置多个链接就更好了。😁😁😁😁😁

**Comment by xia-chu** [comment]
你这个需求太特殊了 也不是必须的 而且别人未必需要 放在master分支是不妥的
建议你自己实现相关功能 其实也不难

**Comment by xia-chu** [comment]
而且这个功能现在restful api已经提供 再搞个hook 功能重复了 我不想让zlm有太多重复和臃肿的功能

**Comment by xia-chu** [comment]
zlm在设计hook时，并不支持多个hook url，这样做的目的其实是让你自己的hook业务服务器 再去派发hook事件。
有些情况下，每个流的hook 地址都可能不一样的 ，这种太业务的东西 没必要在zlm实现

**Comment by yangdon** [comment]
嗯嗯好的吧，我只是觉得用hook来传这些数据更好一些，hook的代码看了个七七八八，我试一下吧
