### ISSUE TITLE
windows编译生成可执行文件在其他主机运行问题

### ISSUE THREAD

**Issue by 17Sdubin** [xia-chu/ZLMediaKit#744]
大神们好，我用win7 + vs2019 编译生成可执行文件，拷贝给其他人运行时一致提示：应用程序无法正常启动(0x000007b)，请单击”确定“关闭应用程序。关于0x000007b错误错误码，我把网上的解决方案试了一个遍也没有解决，请问大家遇到过这个问题吗？请问楼主大大有什么高见？

**Comment by xia-chu** [comment]
首先 你要编译Release版本的exe，然后你要在目标主机安装vc运行时

**Comment by w523827698** [comment]
我也遇到这种情况了，用DX修复工具把所有dll和c++2005-2015 的Redistributable都安装了问题也没有解决

**Comment by 17Sdubin** [comment]
大神，用release版本的exe还是不行，同样的错误(0x000007),请问vc版本有具体的版本要求吗？

**Comment by xia-chu** [comment]
安装下这个 https://www.microsoft.com/zh-CN/download/details.aspx?id=48145
