### ISSUE TITLE
使用/index/api/addStreamProxy接口拉流，如果拉流地址是带用户名和密码校验的rtsp流地址，则拉流报错

### ISSUE THREAD

**Issue by fishminer** [xia-chu/ZLMediaKit#745]
各位大神们，如题，比方说拉流地址是rtsp://<username>:<password>@<设备IP>:554/<path>，该rtsp地址在VLC播放器可以正常播放，在调用该拉流接口会报如下错误：
{
    "code": -1,
    "msg": "DESCRIBE:404 Not Found"
}
如果是不带用户名密码校验的rtsp流地址，在调用该拉流接口是返回成功的。
这是怎么回事呢？求教大神

**Comment by fishminer** [comment]
上面拉流地址没写全，带用户名和密码的拉流地址格式类似这样：rtsp://<用户名>:<密码>@<设备IP>:554/<path>

**Comment by fishminer** [comment]
还是没写全，带用户名和密码的拉流地址格式类似这样：rtsp://<用户名>:<密码>@<设备IP>:554/<路径>

**Comment by xia-chu** [comment]
这个rtsp流不在线呢

**Comment by xia-chu** [comment]
提issue别不给star啊老哥

**Comment by fishminer** [comment]
> 提issue别不给star啊老哥

抱歉哈，忘了star，rtsp流应该是在线的，不然vlc也不能正常播放吧。我想问一下，对于这种带用户名和密码校验的rtsp流地址，是否可以使用/index/api/addStreamProxy接口去拉流？如果不可以，是不是要在/index/api/addStreamProxy拉流接口的源码中去进行rtsp流的digest安全认证，然后才能把流拉过来？

**Comment by xia-chu** [comment]
当然支持这种带用户名和密码校验的rtsp流地址
