### ISSUE TITLE
Mp4 Recording  - Use case for limiting recording length

### ISSUE THREAD

**Issue by xoraingroup** [xia-chu/ZLMediaKit#747]
I have a use case, as there is an api and webhook to start recording certain stream. 

I have tested it and it works great however I couldn't find a way to limit the recording length.

For example I want to limit a stream recording to 2 hours or 4 hours only after that specified amount of time of video recording it should stop recording.

With current configuration where you specify fileSecond in config file, it creates files related to fileSecond limit continuously.

It would be great if you we could specify certain parameters in config file, api or webhook response to set this limit.

**Comment by xoraingroup** [comment]
I think its very much possible using API using startRecord. What do you think?

**Comment by xia-chu** [comment]
Yes, this can be realized ，by the way, i would be cheerful if you can star this project.

**Comment by xoraingroup** [comment]
Awesome. Oh I didn't star this project .... very sorry. This is one of the top project for me in github. Starred already. :)))

I will happily test this feature if you can implement this. 👍

**Comment by xoraingroup** [comment]
So any updates on this? :)

**Comment by xia-chu** [comment]
It has been realized

**Comment by xia-chu** [comment]
It has been realized

**Comment by xia-chu** [comment]
It has been realized
