### ISSUE TITLE
关于支持GB28181 TCP主动模式问题

### ISSUE THREAD

**Issue by zlluye** [xia-chu/ZLMediaKit#749]
你好，我这边发现一个问题，关于使用GB28181支持问题 ，TCP主动模式流程为： 下级平台开放RTP端口 -->上级平台使用ZLMediaKit主动向下级流媒体服务器发起建链请求 --> 链路建立成功后下级平台往该链路推流。当下级平台使用TCP 主动模式时，ZLMediaKit 好像没有一个这样的接口可以主动去连接下级流媒体服务器的端口。只有被动开启端口等待下级连接(TCP 被动模式)。是否能增加支持 GB28181 TCP主动的接口呢。

**Comment by xia-chu** [comment]
是的 目前没这功能 UDP用主动模式吗

**Comment by xia-chu** [comment]
zlm目前没有GB28181拉流功能

**Comment by zlluye** [comment]
后面还会更新么。下个版本是否能新增支持GB28181 tcp active 功能呢。

**Comment by xia-chu** [comment]
你是要支持主动拉流客户端 还是被动推流服务器

**Comment by xia-chu** [comment]
现在zlm支持主动推流客户端和被动推流服务器
