### ISSUE TITLE
截图不成功

### ISSUE THREAD

**Issue by kevin-onepiece** [xia-chu/ZLMediaKit#750]
问题描述：通过WVP推海康的视频流，ZLM的ffmpeg日志出现如下，尝试用/usr/bin/ffmpeg -i http://192.168.0.72/rtp/0BEBC69E/hls.m3u8 -y -f mjpeg -t 0.001 xxx命令在终端可以截图成功，想请问怎么可以改成http呢？

#### pid=47185,cmd=/usr/bin/ffmpeg -i rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv -y -f mjpeg -t 0.001 /home/kingyea/video_project/ZLMediaKit/release/linux/Debug/www/snap/0b08761bd7b5da9d9fec7dcf2bcaad3f/1614651493.jpeg.tmp #####

ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
-- 省略ffmpeg 配置信息--
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
**rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv: Input/output error**
Exiting normally, received signal 15.

**Comment by kevin-onepiece** [comment]
在MediaServerUI的global.js修改baseMediaUrl，在前端可以看到截图了，以下为修改后的global.js
```const serverip="192.168.0.72"
const host = 'http://' + serverip + '/index/api';
const secret = '035c73f7-bb6b-4889-a715-d9eb2d1925cc';
const baseMediaUrl='http://' + serverip + '/rtp/';
function genApiUrl(method){
	return host+method+"?secret="+secret;
}
export default{
	serverip,
        host,
        secret,
	genApiUrl,
	baseMediaUrl
}

**Comment by skywsp** [comment]
我也截图失败
![image](https://user-images.githubusercontent.com/25943305/109607658-877c9680-7b63-11eb-9c9e-f1208831dc27.png)


目录生成了，但没有图片，应该是url没有拿到流数据导致没有截图成功
![image](https://user-images.githubusercontent.com/25943305/109607680-8f3c3b00-7b63-11eb-93a3-2b399d1fba51.png)

**Comment by xia-chu** [comment]
很明显 你的截图地址` rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv ` 不正确

**Comment by skywsp** [comment]
@xia-chu 我的呢，我通过postman调用的zml的api，rtmp视频都播放出来了，但截图失败~

**Comment by xia-chu** [comment]
你确定你能播放rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv？

**Comment by skywsp** [comment]
我题主不是同一个人啊……我的播流地址不是那个，是rtmp://127.0.0.1:1935/rtp/gb_play_33010000991187002300_33010000991327002301

这个地址在我本地已经播放成功了，见上面截图

**Comment by xia-chu** [comment]
> 
> 
> 我题主不是同一个人啊……我的播流地址不是那个，是rtmp://127.0.0.1:1935/rtp/gb_play_33010000991187002300_33010000991327002301
> 
> 这个地址在我本地已经播放成功了，见上面截图

嗯 你的原因是你没安装FFmpeg吧？安装FFmpeg后记得设置zlm的配置文件

**Comment by skywsp** [comment]
@xia-chu 什么时候可以出一个wvp+zml教程 :smile: 
在wiki可以写一篇技术栈么，小白入门好难~~

**Comment by kevin-onepiece** [comment]
> 很明显 你的截图地址`rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv` 不正确

是的，url填错了，然后我就用VLC试了下所有的播放规则url，测试结果如下：

`rtsp://192.168.0.72/rtp/0BEBC69E    yes 2秒延迟`

`rtmp://192.168.0.72/rtp/0BEBC69E    no`

`http://192.168.0.72/rtp/0BEBC69E.flv   no`

`ws://192.168.0.72/rtp/0BEBC69E.flv  no`

`http://192.168.0.72/rtp/0BEBC69E/hls.m3u8   yes  13秒延迟`

`http://192.168.0.72/rtp/0BEBC69E.live.ts  yes 2秒延迟`

`ws://192.168.0.72/rtp/0BEBC69E.live.ts  no`

`http://192.168.0.72/rtp/0BEBC69E.live.mp4  yes 2秒延迟`

`ws://192.168.0.72/rtp/0BEBC69E.live.mp4   no`

其实挺多url是不能播放的，可以在播放规则url那里备注下吗，或许会对新手友好点？因为你在wiki>播放规则url里写着：
> 一般而言，上述url在ZLMediaKit都有效，因为ZLMediaKit默认转换流媒体源。

因为我之前一直在用rtmp的url去播放，一直看不了，纠结了很久

**Comment by xia-chu** [comment]
视频是不是265啊？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevinfu2048 <notifications@github.com&gt;
发送时间: 2021年3月2日 16:56
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 截图不成功 (#750)

**Comment by kevin-onepiece** [comment]
> 视频是不是265啊？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: kevinfu2048 <notifications@github.com&gt; 发送时间: 2021年3月2日 16:56 收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt; 主题: 回复：[xia-chu/ZLMediaKit] 截图不成功 (#750)

是的，海康摄像头

**Comment by xia-chu** [comment]
rtmp不支持265

**Comment by kevin-onepiece** [comment]
> vlc也不支持ws-flv ws-fmp4

哦，这样啊，感谢感谢

**Comment by skywsp** [comment]
> > 很明显 你的截图地址`rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv` 不正确
> 
> 是的，url填错了，然后我就用VLC试了下所有的播放规则url，测试结果如下：
> 
> `rtsp://192.168.0.72/rtp/0BEBC69E yes 2秒延迟`
> 
> `rtmp://192.168.0.72/rtp/0BEBC69E no`
> 
> `http://192.168.0.72/rtp/0BEBC69E.flv no`
> 
> `ws://192.168.0.72/rtp/0BEBC69E.flv no`
> 
> `http://192.168.0.72/rtp/0BEBC69E/hls.m3u8 yes 13秒延迟`
> 
> `http://192.168.0.72/rtp/0BEBC69E.live.ts yes 2秒延迟`
> 
> `ws://192.168.0.72/rtp/0BEBC69E.live.ts no`
> 
> `http://192.168.0.72/rtp/0BEBC69E.live.mp4 yes 2秒延迟`
> 
> `ws://192.168.0.72/rtp/0BEBC69E.live.mp4 no`
> 
> 其实挺多url是不能播放的，可以在播放规则url那里备注下吗，或许会对新手友好点？因为你在wiki>播放规则url里写着：
> 
> > 一般而言，上述url在ZLMediaKit都有效，因为ZLMediaKit默认转换流媒体源。
> 
> 因为我之前一直在用rtmp的url去播放，一直看不了，纠结了很久

@kevin-onepiece 请问怎么获取播流的短地址呢？比如你的是：
```
http://192.168.0.72/rtp/0BEBC69E.flv
```
而我的是：
```
http:/ip/rtp/gb_play_43062100501187000103_43062100501327000141.flv
```

**Comment by kevin-onepiece** [comment]
> > > 很明显 你的截图地址`rtmp://192.168.0.72/rtp/rtp/0BEBC69E.flv` 不正确
> > 
> > 
> > 是的，url填错了，然后我就用VLC试了下所有的播放规则url，测试结果如下：
> > `rtsp://192.168.0.72/rtp/0BEBC69E yes 2秒延迟`
> > `rtmp://192.168.0.72/rtp/0BEBC69E no`
> > `http://192.168.0.72/rtp/0BEBC69E.flv no`
> > `ws://192.168.0.72/rtp/0BEBC69E.flv no`
> > `http://192.168.0.72/rtp/0BEBC69E/hls.m3u8 yes 13秒延迟`
> > `http://192.168.0.72/rtp/0BEBC69E.live.ts yes 2秒延迟`
> > `ws://192.168.0.72/rtp/0BEBC69E.live.ts no`
> > `http://192.168.0.72/rtp/0BEBC69E.live.mp4 yes 2秒延迟`
> > `ws://192.168.0.72/rtp/0BEBC69E.live.mp4 no`
> > 其实挺多url是不能播放的，可以在播放规则url那里备注下吗，或许会对新手友好点？因为你在wiki>播放规则url里写着：
> > > 一般而言，上述url在ZLMediaKit都有效，因为ZLMediaKit默认转换流媒体源。
> > 
> > 
> > 因为我之前一直在用rtmp的url去播放，一直看不了，纠结了很久
> 
> @kevin-onepiece 请问怎么获取播流的短地址呢？比如你的是：
> 
> ```
> http://192.168.0.72/rtp/0BEBC69E.flv
> ```
> 
> 而我的是：
> 
> ```
> http:/ip/rtp/gb_play_43062100501187000103_43062100501327000141.flv
> ```

wiki里的播放规则里有啊，eg
rtsp://ip/rtp/gb_play_43062100501187000103_43062100501327000141

**Comment by skywsp** [comment]
我是按照wiki文档的规则生成的，请问你的短地址是怎么生成的呢？
![image](https://user-images.githubusercontent.com/25943305/109632000-878b8f00-7b81-11eb-9a10-5ee080a7c201.png)

**Comment by kevin-onepiece** [comment]
> 我是按照wiki文档的规则生成的，请问你的短地址是怎么生成的呢？
> ![image](https://user-images.githubusercontent.com/25943305/109632000-878b8f00-7b81-11eb-9a10-5ee080a7c201.png)

ZLM自动生成的就是短地址啊，推流后，可以调ZLM的/index/api/getMediaList接口查看你的视频流ID
