### ISSUE TITLE
rtsp推流有使用ssl加密吗

### ISSUE THREAD

**Issue by pai-da-xin** [xia-chu/ZLMediaKit#752]
你好，
我使用测试程序test_pusherMp4进行rtsp推流，我修改了推流地址和MP4文件路径。请问一下，当我运行测试程序test_pusherMp4的时候，我的推流地址会使用ssl加密吗？如果没有，怎么实现ssl加密呢？我看看cmake里面是包含了openssl的

**Comment by xia-chu** [comment]
使用rtsps 或 rtmps就行 不过要看你服务器支不支持 并且记得端口要正确



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pai-da-xin <notifications@github.com&gt;
发送时间: 2021年3月3日 09:47
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] rtsp推流有使用ssl加密吗 (#752)





 
你好，
 我使用测试程序test_pusherMp4进行rtsp推流，我修改了推流地址和MP4文件路径。请问一下，当我运行测试程序test_pusherMp4的时候，我的推流地址会使用ssl加密吗？如果没有，怎么实现ssl加密呢？我看看cmake里面是包含了openssl的

**Comment by pai-da-xin** [comment]
rtsps就是rtsp使用ssl加密过后的吗？

**Comment by xia-chu** [comment]
对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pai-da-xin <notifications@github.com&gt;
发送时间: 2021年3月3日 10:05
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] rtsp推流有使用ssl加密吗 (#752)

**Comment by pai-da-xin** [comment]
ZLMediaKit是实现了rtsps的吗？我现在是想提供一个推流地址把ZLMediaKit当作客户端用来推流，怎么使用rtsps呢？

**Comment by pai-da-xin** [comment]
怎么来设置证书哦？我使用的流媒体服务器，推流需要做ssl加密才行，那应该就是支持rtsps的

**Comment by xia-chu** [comment]
看wiki



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pai-da-xin <notifications@github.com&gt;
发送时间: 2021年3月3日 10:15
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] rtsp推流有使用ssl加密吗 (#752)

**Comment by xia-chu** [comment]
MediaServer -s /path/to/pem

**Comment by xia-chu** [comment]
https://github.com/xia-chu/ZLMediaKit/wiki/%E7%94%9F%E6%88%90SSL%E8%87%AA%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6%E5%B9%B6%E6%B5%8B%E8%AF%95
https://github.com/xia-chu/ZLMediaKit/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%90%AF%E5%8A%A8%E4%B8%8E%E5%85%B3%E9%97%AD
