### ISSUE TITLE
linux下编译提示undefined reference to `Json::Value::~Value()

### ISSUE THREAD

**Issue by 17Sdubin** [xia-chu/ZLMediaKit#753]
大神你好，我在HttpFileManager.cpp responseFile()函数中加入Json::Value respon;对json的引用，编译的时候一直提示：
../../release/linux/Debug/libzlmediakit.a(HttpFileManager.cpp.o): In function `mediakit::HttpResponseInvokerImp::responseText(mediakit::StrCaseMap const&, mediakit::StrCaseMap const&, std::string const&) const':
HttpFileManager.cpp:(.text+0x6415): undefined reference to `Json::Value::Value(Json::ValueType)'
HttpFileManager.cpp:(.text+0x6441): undefined reference to `Json::Value::~Value()'
HttpFileManager.cpp:(.text+0x66ee): undefined reference to `Json::Value::~Value()'
collect2: error: ld returned 1 exit status
make[2]: *** [../release/linux/Debug/test_server] Error 1
make[1]: *** [tests/CMakeFiles/test_server.dir/all] Error 2
../../release/linux/Debug/libzlmediakit.a(HttpFileManager.cpp.o): In function `mediakit::HttpResponseInvokerImp::responseText(mediakit::StrCaseMap const&, mediakit::StrCaseMap const&, std::string const&) const':
HttpFileManager.cpp:(.text+0x6415): undefined reference to `Json::Value::Value(Json::ValueType)'
HttpFileManager.cpp:(.text+0x6441): undefined reference to `Json::Value::~Value()'
HttpFileManager.cpp:(.text+0x66ee): undefined reference to `Json::Value::~Value()'
collect2: error: ld returned 1 exit status
make[2]: *** [../release/linux/Debug/test_rtp] Error 1
make[1]: *** [tests/CMakeFiles/test_rtp.dir/all] Error 2

我在网上查询，提示缺少json库，需要在cmakelist.txt文件中加，但是src目录下没有 cmakelist.txt文件，我自己创建，将server下的cmakelist.txt文件json库设置语句复制了过来，还是编译不通过，请问大神具体应该怎么设置呢？

**Comment by 17Sdubin** [comment]
另外请问大神，cmakelist.txt文件中
option(ENABLE_HLS "Enable HLS" true)
option(ENABLE_OPENSSL "Enable OpenSSL" true)
option(ENABLE_MYSQL "Enable MySQL" false)
option(ENABLE_FAAC "Enable FAAC" false)
option(ENABLE_X264 "Enable x264" false)
option(ENABLE_MP4 "Enable MP4" true)
option(ENABLE_RTPPROXY "Enable RTPPROXY" true)
option(ENABLE_API "Enable C API SDK" true)
option(ENABLE_CXX_API "Enable C++ API SDK" false)
option(ENABLE_TESTS "Enable Tests" true)
option(ENABLE_SERVER "Enable Server" true)
option(ENABLE_MEM_DEBUG "Enable Memory Debug" false)
option(ENABLE_ASAN "Enable Address Sanitize" false)
open设置为true的宏，问什么编译的时候都没编译进来，代码中查看宏定义，查看不到请问这是什么问题

**Comment by xia-chu** [comment]
你是不是在HttpFileManager中修改了代码 添加了JSON相关的代码？

**Comment by xia-chu** [comment]
zlmediakit主体工程部以来jsoncpp的 所以没链接它 只有 server目录下的MediaServer进程链接jsoncpp了

**Comment by 17Sdubin** [comment]
> zlmediakit主体工程部以来jsoncpp的 所以没链接它 只有 server目录下的MediaServer进程链接jsoncpp了

是的，请问要如何链接呢？大神方便加你各qq或者微信吗？想向您多请教下

**Comment by xia-chu** [comment]
实现没明白你为什么要在HttpFileManager中添加json相关代码啊，你不能把代码写在server目录下的源码中吗？
zlmediakit的主体工程可以通过NoticeCenter把时间广播出来，你在server目录下的源码中监听并处理就行了

**Comment by 17Sdubin** [comment]
> 大神你好，我在HttpFileManager.cpp responseFile()函数中加入Json::Value respon;对json的引用，编译的时候一直提示：
> ../../release/linux/Debug/libzlmediakit.a(HttpFileManager.cpp.o): In function `mediakit::HttpResponseInvokerImp::responseText(mediakit::StrCaseMap const&, mediakit::StrCaseMap const&, std::string const&) const': HttpFileManager.cpp:(.text+0x6415): undefined reference to `Json::Value::Value(Json::ValueType)'
> HttpFileManager.cpp:(.text+0x6441): undefined reference to `Json::Value::~Value()' HttpFileManager.cpp:(.text+0x66ee): undefined reference to `Json::Value::~Value()'
> collect2: error: ld returned 1 exit status
> make[2]: *** [../release/linux/Debug/test_server] Error 1
> make[1]: *** [tests/CMakeFiles/test_server.dir/all] Error 2
> ../../release/linux/Debug/libzlmediakit.a(HttpFileManager.cpp.o): In function `mediakit::HttpResponseInvokerImp::responseText(mediakit::StrCaseMap const&, mediakit::StrCaseMap const&, std::string const&) const': HttpFileManager.cpp:(.text+0x6415): undefined reference to `Json::Value::Value(Json::ValueType)'
> HttpFileManager.cpp:(.text+0x6441): undefined reference to `Json::Value::~Value()' HttpFileManager.cpp:(.text+0x66ee): undefined reference to `Json::Value::~Value()'
> collect2: error: ld returned 1 exit status
> make[2]: *** [../release/linux/Debug/test_rtp] Error 1
> make[1]: *** [tests/CMakeFiles/test_rtp.dir/all] Error 2
> 
> 我在网上查询，提示缺少json库，需要在cmakelist.txt文件中加，但是src目录下没有 cmakelist.txt文件，我自己创建，将server下的cmakelist.txt文件json库设置语句复制了过来，还是编译不通过，请问大神具体应该怎么设置呢？
