### ISSUE TITLE
拉流代理时是否有链接长度限制或者其他限制

### ISSUE THREAD

**Issue by yxw002** [xia-chu/ZLMediaKit#754]
您好，这个系统做的真好，我用其作为一个拉流转换协议的用途，但是使用过程中发现某些链接转换就会失败，失败时我用VLC本地播放没有问题，同时测试了转换其他流也没有问题。API拉流显示的错误信息是：play失败：error NetStream.Play.StreamNotFound。我又将其转换为短链接尝试，这次错误提示换成了play rtsp timeout。

这个流我拉的时候是有的，但是可能不会一直有流。

**Comment by xia-chu** [comment]
你的拉流url如果有特殊字符 那么需要转义的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yxw002 <notifications@github.com&gt;
发送时间: 2021年3月3日 11:16
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 拉流代理时是否有链接长度限制或者其他限制 (#754)





 
您好，这个系统做的真好，我用其作为一个拉流转换协议的用途，但是使用过程中发现某些链接转换就会失败，失败时我用VLC本地播放没有问题，同时测试了转换其他流也没有问题。API拉流显示的错误信息是：play失败：error NetStream.Play.StreamNotFound。我又将其转换为短链接尝试，这次错误提示换成了play rtsp timeout。
 
拉的这个流：rtmp://play-pc.ourwill.cn/live/tw-903590-7spmfep9_hd?txSecret=9ce0df49c53bc4876dd0ad6f8012ba05&amp;txTime=6041C919
 
这个流我拉的时候是有的，但是可能不会一直有流。

**Comment by yxw002** [comment]
感谢解答，转义后成功了。
