### ISSUE TITLE
有漏洞

### ISSUE THREAD

**Issue by hhhuaang** [xia-chu/ZLMediaKit#755]
![image](https://user-images.githubusercontent.com/10963105/109748466-e4378a00-7c13-11eb-97ee-a774749fb85d.png)

**Comment by xia-chu** [comment]
谢谢您的反馈 请问您是怎么用工具测试出这个漏洞的？

**Comment by hhhuaang** [comment]
是我们负责安全的同时测出来的，我也不清楚

**Comment by xia-chu** [comment]
该漏洞已修复
