### ISSUE TITLE
请问：测试test_rtp的loadFile,传入的是什么格式文件？

### ISSUE THREAD

**Issue by Travis990** [xia-chu/ZLMediaKit#756]
![image](https://user-images.githubusercontent.com/6883210/109901156-810d2c80-7cd3-11eb-983b-f68aaccddadd.png)

**Comment by xia-chu** [comment]
前面另个字节是大端的int16,表明后面rtp数据长度，后面是rtp数据。
这个rtp文件一般是zlm dump 28181出的rtp

**Comment by Travis990** [comment]
了解，非常感谢
