### ISSUE TITLE
windos下使用/index/api/getSnap接口进行截图返回“<h1>您访问的资源不存在！</h1>“”

### ISSUE THREAD

**Issue by BigPotato1** [xia-chu/ZLMediaKit#757]
![Uploading 企业微信截图_16149243623453.png…]()
配置文件里ffmpeg也是配置的绝对路径

**Comment by BigPotato1** [comment]
![配置](https://user-images.githubusercontent.com/45842244/110075514-dfaed500-7dbd-11eb-9ddd-312ec8116a0f.png)

**Comment by xia-chu** [comment]
有空格 应该用 \转义下

**Comment by xia-chu** [comment]
如果不转义 那么会被当做几个参数 原理跟shell启动程序一样

**Comment by BigPotato1** [comment]
> 有空格 应该用 \转义下

**Comment by BigPotato1** [comment]
> 有空格 应该用 \转义下

尝试添加转义不行后直接重新安装了ffmpeg到路径“D:\ffmpeg\bin\”，结果还是一样返回“访问资源不存在”
![企业微信截图_16149305045228](https://user-images.githubusercontent.com/45842244/110084671-31aa2780-7dcb-11eb-9d24-f377c7489e58.png)
![企业微信截图_1614930781325](https://user-images.githubusercontent.com/45842244/110084694-37a00880-7dcb-11eb-8be1-6c86bf9fc5bb.png)

**Comment by xia-chu** [comment]
那你应该看看ffmpeg的日志 我猜你截图地址不对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈青文 <notifications@github.com&gt;
发送时间: 2021年3月5日 15:55
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] windos下使用/index/api/getSnap接口进行截图返回“<h1&gt;您访问的资源不存在！</h1&gt;“” (#757)





  
有空格 应该用 \转义下
  
尝试添加转义不行后直接重新安装了ffmpeg到路径“D:\ffmpeg\bin\”，结果还是一样返回“访问资源不存在”

**Comment by BigPotato1** [comment]
postman中请求地址：127.0.0.1:80/index/api/getSnap?url=rtsp://admin:root@193.169.60.220:554/h264/ch1/sub/av_stream&timeout_sec=10&expire_sec=30&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
ffmpeg日志都是 0 k 的空白文件
![企业微信截图_16149328622886](https://user-images.githubusercontent.com/45842244/110089008-8f8d3e00-7dd0-11eb-89eb-10b83add8964.png)

**Comment by xia-chu** [comment]
嗯 看看zlm的日志



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈青文 <notifications@github.com&gt;
发送时间: 2021年3月5日 16:34
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] windos下使用/index/api/getSnap接口进行截图返回“<h1&gt;您访问的资源不存在！</h1&gt;“” (#757)





 
postman中请求地址：127.0.0.1:80/index/api/getSnap?url=rtsp://admin:root@193.169.60.220:554/h264/ch1/sub/av_stream&amp;timeout_sec=10&amp;expire_sec=30&amp;secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
 ffmpeg日志都是 0 k 的空白文件

**Comment by BigPotato1** [comment]
zlm的日志如下：
![企业微信截图_16149338075085](https://user-images.githubusercontent.com/45842244/110090180-f3fccd00-7dd1-11eb-8647-9630c1e9eabe.png)

**Comment by xia-chu** [comment]
启动ffmpeg进程失败 估计ffmpeg依赖的dll不存在 无法启动





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈青文 <notifications@github.com&gt;
发送时间: 2021年3月5日 16:44
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] windos下使用/index/api/getSnap接口进行截图返回“<h1&gt;您访问的资源不存在！</h1&gt;“” (#757)





 
zlm的日志如下：

**Comment by BigPotato1** [comment]
缺少哪个依赖库，要如何解决呢？重新下载安装了不同版本ffmpeg，还是一样的，单独启动ffmpeg进程好像也没有报啥错，能问下具体解决方法吗？
![企业微信截图_16149398895408](https://user-images.githubusercontent.com/45842244/110103011-6674a980-7de0-11eb-9125-ba46bb5e15ab.png)

**Comment by BigPotato1** [comment]
您好，我最后尝试ffmpeg直接命令行执行本地存储的视频截图，发现是可以正常截图的，说明ffmpeg本身应该是不存在问题的，执行的命令及结果如下：
![企业微信截图_1614995550543](https://user-images.githubusercontent.com/45842244/110191263-661cf280-7e62-11eb-852e-118479cd35dc.png)
![企业微信截图_16149956132019](https://user-images.githubusercontent.com/45842244/110191272-703ef100-7e62-11eb-819e-9444eb9c3054.png)

**Comment by xia-chu** [comment]
看zlm日志是启动子进程失败 会不会是权限不足？这个要调试代码才知道了

**Comment by BigPotato1** [comment]
我下载这个您分享的编译好的可执行程序
![企业微信截图_1615163711701](https://user-images.githubusercontent.com/45842244/110260956-449a4300-7fe9-11eb-8b0f-80708a0255bf.png)
运行后也还是返回访问的资源不存在，但是ffmpwg的日志不再是空白了，而且snap文件夹下也有了截的图片文件，但是打不开，看日志好像是说“找不到适合输出该截图的输出格式”，情况如下:
![企业微信截图_1615163461842](https://user-images.githubusercontent.com/45842244/110261136-efaafc80-7fe9-11eb-998e-86174e66faf6.png)

**Comment by xia-chu** [comment]
你用写字板打开就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈青文 <notifications@github.com&gt;
发送时间: 2021年3月8日 08:40
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] windos下使用/index/api/getSnap接口进行截图返回“<h1&gt;您访问的资源不存在！</h1&gt;“” (#757)





 
我下载这个您分享的编译好的可执行程序
 
 运行后也还是返回访问的资源不存在，但是ffmpwg的日志不再是空白了，而且snap文件夹下也有了截的图片文件，但是打不开，看日志好像是说“找不到适合输出该截图的输出格式”，情况如下:

**Comment by BigPotato1** [comment]
您是什么意思，没太理解，用写字板打开图片文件吗？这有什么用吗？看了一下那个截到的图片，大小是0kB

**Comment by xia-chu** [comment]
我说打开ffmpeg日志看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈青文 <notifications@github.com&gt;
发送时间: 2021年3月8日 10:07
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] windos下使用/index/api/getSnap接口进行截图返回“<h1&gt;您访问的资源不存在！</h1&gt;“” (#757)





 
您是什么意思，没太理解，用写字板打开图片文件吗？这有什么用吗？看了一下那个截到的图片，大小是0kB

**Comment by BigPotato1** [comment]
ffmpeg日志上面已经发了，就是这样的
![企业微信截图_16151698494242](https://user-images.githubusercontent.com/45842244/110265869-8500bd80-7ff7-11eb-8125-d674e39d6119.png)

**Comment by xia-chu** [comment]
保存路径有空格&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈青文 <notifications@github.com&gt;
发送时间: 2021年3月8日 10:18
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] windos下使用/index/api/getSnap接口进行截图返回“<h1&gt;您访问的资源不存在！</h1&gt;“” (#757)





 
ffmpeg日志上面已经发了，就是这样的

**Comment by BigPotato1** [comment]
看日志好像是说“找不到适合输出该截图的输出格式”

**Comment by BigPotato1** [comment]
换了一个没有空格的路径放置ZLM，结果确实没问题了，postman顺利返回了截图快照，多谢大佬。最后总结就是：ffmpeg多媒体处理工具安装路径和ZML本身放置路径都不能包含空格，否则会出现我上述问题。话说回来，我自己编译的ZML可执行文件为啥ffmpeg连日志返回都是空白的0KB文件呢？如果有日志应该早发现是路径中带空格的原因导致的了。总之，问题解决，再次感谢大佬！
![企业微信截图_16151713598073](https://user-images.githubusercontent.com/45842244/110268251-546f5280-7ffc-11eb-8150-c103c8a49468.png)
