### ISSUE TITLE
[Feature] MP4 Recording - Set Max number of slices

### ISSUE THREAD

**Issue by xoraingroup** [xia-chu/ZLMediaKit#759]
There should be an option via API and config to set max number of slices. 

For example I want max_slices 1 i.e. only 1 recording file after max time has elapased. No further recording for that stream.

**Comment by xoraingroup** [comment]
Any update on this?

**Comment by xia-chu** [comment]
Pure business function, I hope the development can be realized by themself. ZLM has exposed the http API that start or stop MP4 recording. After recording, ZLM will also push http hook event of MP4 generation. Developers should complete the recording management function through these existing functions

**Comment by xoraingroup** [comment]
Ok, i can do that as well, but it will still create one extra recording with few second video when i will try to stop recording on webhook. But thank you I will close this now.
