### ISSUE TITLE
使用C Api时，mk_media_create/init_video/init_complete后，on_media_changed回调收到多次

### ISSUE THREAD

**Issue by flowerlove** [xia-chu/ZLMediaKit#761]
server部分代码参考server.c
    mk_config config;
    config.ini = NULL;
    config.ini_is_path = 0;
    config.log_level = LOG_LEV;
    config.log_file_path = NULL;
    config.log_file_days = 0;
    config.ssl = NULL;
    config.ssl_is_path = 0;
    config.ssl_pwd = NULL;
    config.thread_num = 0;
    mk_env_init(&config);
    rtsp_port_ = port;
    bool ret = create_rtsp_server(rtsp_port_);
    mk_events events;
    events.on_mk_media_changed = on_mk_media_changed;
    events.on_mk_media_publish = on_mk_media_publish;
    events.on_mk_rtsp_get_realm = on_mk_rtsp_get_realm;
    events.on_mk_rtsp_auth = on_mk_rtsp_auth;
    mk_events_listen(&events);

注册mk_media：
	auto mk_media = mk_media_create("__defaultVhost__", "live", std::to_string(rtsp_channel).c_str(), 0, false, false);
	mk_media_init_video(mk_media, 0, width, height, 30);
	mk_media_init_complete(mk_media);
随后在on_mk_media_changed回调中收到多次（register == 1）注册事件

**Comment by xia-chu** [comment]
是会回调多次 因为支持多种协议



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: flowerlove <notifications@github.com&gt;
发送时间: 2021年3月9日 15:10
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 使用C Api时，mk_media_creat/init_video/init_complete后，on_media_changed回调收到多次 (#761)
