### ISSUE TITLE
C API:  输入H264 编码帧输入，生成rtsp直播流后，VLC播放花屏

### ISSUE THREAD

**Issue by flowerlove** [xia-chu/ZLMediaKit#762]
夏楚大神，你好，目前我在项目上测试ZLMediaKit的C API接口。项目需要实现Nvidia硬编码纹理，生成H264帧数据，并通过Rtsp Server推流。由于之前的Rtsp Server是前同事写的，目前维护困难，所以我在考虑换成ZLMediaKit.

mk_media 相关代码:
```
auto mk_media = mk_media_create("__defaultVhost__", "live", std::to_string(rtsp_channel).c_str(), 0, false, false);
mk_media_init_video(mk_media, 0, width, height, 0);
mk_media_init_complete(mk_media);
```
pusher相关代码：
在on_mk_media_changed回调中处理schema == rtsp的情况。
```
auto mk_pusher = mk_pusher_create(schema,vhost, app, stream);
auto url = "rtsp://127.0.0.1:" + std::to_string(RtspServer::rtsp_port_) + "/live/" + stream;
mk_pusher_publish(mk_pusher, url.c_str());
```
VLC 播放器截图和原视频画面：

![微信图片_20210309165033](https://user-images.githubusercontent.com/10022404/110444268-c7112880-80f7-11eb-9e1d-2d51d7f301f0.png)
![微信图片_20210309165026](https://user-images.githubusercontent.com/10022404/110444288-ced0cd00-80f7-11eb-8e6d-94abe5368d1b.png)

**Comment by flowerlove** [comment]
这是因为时间戳导致的丢帧吗？
目前传入H264帧时，我传入了我定义的时间戳（单位为毫秒数），我之前使用Rtsp Server时也是传入此参数。
```
auto timestamp = clock() - base;
mk_media_input_h264(window_encode_info->mk_media_, (unsigned char*)frame->buffer, frame->len, timestamp, timestamp);
```
为了查找问题，我查看了源码处理后，将时间戳传入值改为0，仍然会出现上图中的现象

**Comment by flowerlove** [comment]
这是因为时间戳导致的丢帧吗？
目前传入H264帧时，我传入了我定义的时间戳（单位为毫秒数），我之前使用Rtsp Server时也是传入此参数。
```
auto timestamp = clock() - base;
mk_media_input_h264(window_encode_info->mk_media_, (unsigned char*)frame->buffer, frame->len, timestamp, timestamp);
```
为了查找问题，我查看了源码处理后，将时间戳传入值改为0，仍然会出现上图中的现象

**Comment by flowerlove** [comment]
VLC 中设置 RTP over RTSP(tcp)即可。

**Comment by xia-chu** [comment]
连休了9天假 今天才回工作地
