### ISSUE TITLE
是否支持一路流进，两路流出？

### ISSUE THREAD

**Issue by jim-king-2000** [xia-chu/ZLMediaKit#763]
一路1080p的rtsp流，推入媒体服务器。现在需要在两个url可以同时访问一路1080p的拉流和一路720p的拉流。请问zlmediakit是否支持？

**Comment by xia-chu** [comment]
不能 目前zlmediakit不能转码 你可以用srs



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2021年3月9日 17:42
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持一路流进，两路流出？ (#763)





 
一路1080p的rtsp流，推入媒体服务器。现在需要在两个url可以同时访问一路1080p的拉流和一路720p的拉流。请问zlmediakit是否支持？

**Comment by jim-king-2000** [comment]
#283 可否参照这篇帖子里的方法，实现我的目标？

**Comment by xia-chu** [comment]
addFFmpegSource确实能满足你的需求 不过由于比较复杂 所以 我一般干脆说不支持转码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin <notifications@github.com&gt;
发送时间: 2021年3月10日 09:46
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 是否支持一路流进，两路流出？ (#763)





 
#283 可否参照这篇帖子里的方法，实现我的目标？

**Comment by jim-king-2000** [comment]
赞。能支持就行。谢谢。
