### ISSUE TITLE
[BUG] Switcher Studio does not work with ZLMediaKit

### ISSUE THREAD

**Issue by xoraingroup** [xia-chu/ZLMediaKit#764]
So the apps are located at https://dashboard.switcherstudio.com/downloads.

Try to use Switch Studio IOS App and set the output source to custom RTMP. Try to stream and you get 

 RTMP播放器(__defaultVhost__/live/live_131208_akar19yme)断开:not a publisher,耗时(s):8#033[0m

In which cases it throws this issue?

Here is the app that you can install on iphone or ipad.

https://itunes.apple.com/us/app/switcher-studio-pro/id908386221

**Comment by xoraingroup** [comment]
Tried Nginx rtmp and it works fine.

**Comment by xoraingroup** [comment]
Any idea if could be fixed?

**Comment by xoraingroup** [comment]
Any updates on this?

**Comment by xoraingroup** [comment]
Kindly waiting for your reply on this. Thank you

**Comment by xia-chu** [comment]
I need to find a MAC device to test this

**Comment by xoraingroup** [comment]
You don't have iphone or ipad?

**Comment by xoraingroup** [comment]
I wish if i could help you with this.

**Comment by xoraingroup** [comment]
But from switcher studio it works on  all platforms except ZLMediaKit. That is very very strange.

**Comment by xoraingroup** [comment]
Did you find the ios device to test?

**Comment by xoraingroup** [comment]
Or you can tell me the instructions that i can follow to give you full log.

**Comment by xia-chu** [comment]
We can't visit GitHub in China recently. I can't reply to issue or view it. Now I reply to you by email



发自我的iPhone


------------------ Original ------------------
From: xoraingroup ***@***.***&gt;
Date: Thu,Mar 18,2021 8:16 PM
To: xia-chu/ZLMediaKit ***@***.***&gt;
Cc: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xia-chu/ZLMediaKit] [BUG] Switcher Studio does not work with ZLMediaKit (#764)





 
Or you can tell me the instructions that i can follow to give you full log.

**Comment by xoraingroup** [comment]
Ok, how you can do this? Do you have my email? Or can you send me your email?

**Comment by xia-chu** [comment]
<img width="1671" alt="图片" src="https://user-images.githubusercontent.com/11495632/112156021-d5dffb00-8c20-11eb-846b-99541425098d.png">

**Comment by xia-chu** [comment]
![IMG_8057](https://user-images.githubusercontent.com/11495632/112156368-27888580-8c21-11eb-93c3-9b755ccbe117.PNG)
![IMG_8056](https://user-images.githubusercontent.com/11495632/112156388-29eadf80-8c21-11eb-81c4-c7eedddbeb90.PNG)

**Comment by xoraingroup** [comment]
Try to set **on_publish** **webhook** in **config.ini** file and then from your server respond with

return res.status(200).json({
                "code": 0,
                "enableHls": false,
                "enableMP4": false,
                "msg": "success"
            });

for **on_publish** **webhook**. You will see that it does not work and throws error which i paste on the first time i created this issue. 

**So with on_publish webhook it does not work.**

**Comment by xia-chu** [comment]
Sorry, I'm very busy recently. I know the cause of the problem. This should be a bug in the streaming client.
After the authentication is turned on, the client starts to push the stream without waiting for the server to reply. Hmm

**Comment by xia-chu** [comment]
I'm sorry I've been very busy recently, so I've been delayed for so long
