### ISSUE TITLE
[提问] Web Hook 的文档中提到鉴权勾子在访问HLS时不会触发

### ISSUE THREAD

**Issue by Dustone-JavaWeb** [xia-chu/ZLMediaKit#765]
![微信截图_20210309173932](https://user-images.githubusercontent.com/35624201/110451169-e3fd2a00-80fe-11eb-96b6-e1bdaceb328e.png)
那应该如何做鉴权呢，或者有什么其他的替代方案，

**Comment by xia-chu** [comment]
hls播放鉴权会触发on_play hook



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dustone-JavaWeb <notifications@github.com&gt;
发送时间: 2021年3月10日 09:07
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] [提问] Web Hook 的文档中提到鉴权勾子在访问HLS时不会触发 (#765)

**Comment by Dustone-JavaWeb** [comment]
@xia-chu 多谢
