### ISSUE TITLE
去除ultraLowDelay后如何能让直播延迟降低到400ms左右?

### ISSUE THREAD

**Issue by qdmxy** [xia-chu/ZLMediaKit#769]
ultraLowDelay在某一次更新时去掉了, 直播延迟无法降低到1s以内

**Comment by xia-chu** [comment]
应该不会吧？ 你是什么协议播放的？

**Comment by qdmxy** [comment]
rtmp协议
[![6B7aB4.jpg](https://s3.ax1x.com/2021/03/15/6B7aB4.jpg)]

**Comment by xia-chu** [comment]
播放器是什么播放器？

**Comment by xia-chu** [comment]
MediaServer -t 1启动 应该延时能低点

**Comment by qdmxy** [comment]
> 播放器是什么播放器？

ffmpeg

**Comment by xia-chu** [comment]
你用test_player播放试试 test_player目前不支持windows ,你可以在mac、Linux下测试。
FFmpeg nobuffer还是有点缓存的
