### ISSUE TITLE
在线图片粘贴专用

### ISSUE THREAD

**Issue by xia-chu** [xia-chu/ZLMediaKit#77]

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/64310961-e3994580-cfd4-11e9-945b-7abcc7fe643f.png)
![image](https://user-images.githubusercontent.com/11495632/64311009-0af01280-cfd5-11e9-9117-2f520db0b70f.png)
![image](https://user-images.githubusercontent.com/11495632/64311040-2b1fd180-cfd5-11e9-8526-675d5d40d746.png)
![image](https://user-images.githubusercontent.com/11495632/64311126-76d27b00-cfd5-11e9-89e4-59e9cb15b8bc.png)
![image](https://user-images.githubusercontent.com/11495632/64311161-9b2e5780-cfd5-11e9-96dd-5ab7eecc83ca.png)
![image](https://user-images.githubusercontent.com/11495632/64311179-b600cc00-cfd5-11e9-953f-07e73c377df1.png)

![image](https://user-images.githubusercontent.com/11495632/64311187-c022ca80-cfd5-11e9-89b4-a015d614706e.png)

![image](https://user-images.githubusercontent.com/11495632/64311220-daf53f00-cfd5-11e9-8d1f-c39d95c335c4.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/67911733-8da2e180-fbc2-11e9-9c9e-e7af01ab149c.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/67912185-1bcb9780-fbc4-11e9-9f99-02dbc7053ca1.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/67912898-5a625180-fbc6-11e9-9ea0-89bc48b08c9e.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/67912942-854ca580-fbc6-11e9-8b2c-b49b6e3e865f.png)

**Comment by xiongziliang** [comment]
[windows下编译mp4v2加入项目.doc.zip](https://github.com/xiongziliang/ZLMediaKit/files/4347347/windows.mp4v2.doc.zip)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/76932566-2d6ccc00-6926-11ea-8e75-f3c0690e7fb9.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/78686734-f6d31180-7925-11ea-9ba3-864865a910b9.png)
![image](https://user-images.githubusercontent.com/11495632/78686849-1b2eee00-7926-11ea-9434-a4f943021be5.png)
![image](https://user-images.githubusercontent.com/11495632/78687097-621ce380-7926-11ea-9adb-80ccbbfca1f3.png)
![image](https://user-images.githubusercontent.com/11495632/78687391-b031e700-7926-11ea-9b81-0339d8d9dafd.png)
![image](https://user-images.githubusercontent.com/11495632/78687480-c8096b00-7926-11ea-9d72-f21fffa8fd7d.png)

![image](https://user-images.githubusercontent.com/11495632/78687796-22a2c700-7927-11ea-8158-0324f8f8b83e.png)

![image](https://user-images.githubusercontent.com/11495632/78687893-3b12e180-7927-11ea-9e41-653b771405de.png)


![image](https://user-images.githubusercontent.com/11495632/78688104-7a413280-7927-11ea-953b-d3b9a4c5ed0c.png)



![image](https://user-images.githubusercontent.com/11495632/78688226-9e9d0f00-7927-11ea-8d31-49d487f339b4.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/78741558-39c7d000-798c-11ea-9860-6dc18db1ef0c.png)
![image](https://user-images.githubusercontent.com/11495632/78741649-78f62100-798c-11ea-85a9-1810bf1deaf1.png)
![image](https://user-images.githubusercontent.com/11495632/78741678-8d3a1e00-798c-11ea-9aec-dff834620781.png)

![image](https://user-images.githubusercontent.com/11495632/78741720-ad69dd00-798c-11ea-83c6-1b0b57d79ba2.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/78963526-5568dd00-7b2a-11ea-850b-0af7d022aa2e.png)

**Comment by xiongziliang** [comment]
[ZLMediaKit.postman_collection.json.zip](https://github.com/xiongziliang/ZLMediaKit/files/4682924/ZLMediaKit.postman_collection.json.zip)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/86908534-3d185680-c149-11ea-816b-a90e64dd89ea.png)
![image](https://user-images.githubusercontent.com/11495632/86908544-41447400-c149-11ea-86d5-96844d095fad.png)
![image](https://user-images.githubusercontent.com/11495632/86908523-3ab5fc80-c149-11ea-92da-c90dc88a298a.png)
![image](https://user-images.githubusercontent.com/11495632/86908550-443f6480-c149-11ea-9924-b3743119031a.png)
![image](https://user-images.githubusercontent.com/11495632/86908559-47d2eb80-c149-11ea-8173-4b2dfb4238d3.png)
![image](https://user-images.githubusercontent.com/11495632/86908653-7650c680-c149-11ea-8783-2be617fdab42.png)

**Comment by xia-chu** [comment]
<img width="1062" alt="图片" src="https://user-images.githubusercontent.com/11495632/93857284-f15b5f00-fcec-11ea-894d-83eb656dc235.png">

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/93867941-51a5cd00-fcfc-11ea-8ab7-be5914929c90.png)
![图片](https://user-images.githubusercontent.com/11495632/93867961-579bae00-fcfc-11ea-843a-dcb473957fb7.png)

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/93870262-823b3600-fcff-11ea-8656-3d5ce081be87.png)

**Comment by xia-chu** [comment]
<img width="1631" alt="图片" src="https://user-images.githubusercontent.com/11495632/93871851-e232dc00-fd01-11ea-8802-b8e91e5f6de1.png">
<img width="1631" alt="图片" src="https://user-images.githubusercontent.com/11495632/93871913-f8d93300-fd01-11ea-8aec-c35f1dab90e9.png">
![图片](https://user-images.githubusercontent.com/11495632/93871941-01ca0480-fd02-11ea-8dc8-1a5a2cfd4a08.png)

**Comment by xia-chu** [comment]
<img width="611" alt="图片" src="https://user-images.githubusercontent.com/11495632/93872911-6c2f7480-fd03-11ea-85d4-911d6d998c83.png">

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/93873207-e7912600-fd03-11ea-83f7-00132f917540.png)

**Comment by xia-chu** [comment]
<img width="1551" alt="图片" src="https://user-images.githubusercontent.com/11495632/93873636-a0576500-fd04-11ea-8b0f-98fb3f60c778.png">

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/93874009-44411080-fd05-11ea-9444-0b86cf266252.png)

**Comment by xia-chu** [comment]
<img width="961" alt="图片" src="https://user-images.githubusercontent.com/11495632/97776151-ccd28c80-1ba0-11eb-977b-31892e913e60.png">

**Comment by xia-chu** [comment]
<img width="921" alt="图片" src="https://user-images.githubusercontent.com/11495632/102689561-09824200-423a-11eb-9cf9-b39d1378ef68.png">

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/204230234-04da9d84-ffc7-4d32-bda3-04c72474205f.png)
![图片](https://user-images.githubusercontent.com/11495632/204230272-13448d78-b6da-40f2-94b9-da517fa5cc0b.png)
![图片](https://user-images.githubusercontent.com/11495632/204230325-1b395c6f-c094-414d-9d4e-8ea04120eed6.png)

**Comment by xia-chu** [comment]
<img width="1060" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/481ea769-5b27-495e-bf7d-31191e6af9d2">

**Comment by xia-chu** [comment]
Index: src/Rtsp/RtspPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Rtsp/RtspPlayer.cpp b/src/Rtsp/RtspPlayer.cpp
--- a/src/Rtsp/RtspPlayer.cpp	(revision 6b9889a883a91d7ba906f44f3c5288311dc883a4)
+++ b/src/Rtsp/RtspPlayer.cpp	(date 1688614578481)
@@ -451,7 +451,7 @@
             case type_pause: WarnL << "Pause failed:" << parser.status() << " " << parser.statusStr(); break;
             case type_play:
                 WarnL << "Play failed:" << parser.status() << " " << parser.statusStr();
-                onPlayResult_l(SockException(Err_shutdown, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
+                onPlayResult_l(SockException(Err_other, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
                 break;
             case type_seek: WarnL << "Seek failed:" << parser.status() << " " << parser.statusStr(); break;
         }
@@ -502,9 +502,8 @@
         if (trackIdx == -1) {
             return;
         }
-        handleOneRtp(
-            trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate, (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize,
-            len - RtpPacket::kRtpTcpHeaderSize);
+        handleOneRtp(trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate,
+                     (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize, len - RtpPacket::kRtpTcpHeaderSize);
     } else {
         trackIdx = getTrackIndexByInterleaved(interleaved - 1);
         if (trackIdx == -1) {
@@ -615,11 +614,7 @@
     }
 
     _StrPrinter printer;
-    if (cmd == "PLAY") {
-        printer << cmd << " " << _play_url << " RTSP/1.0\r\n";
-    } else {
-        printer << cmd << " " << url << " RTSP/1.0\r\n";
-    }
+    printer << cmd << " " << url << " RTSP/1.0\r\n";
 
     for (auto &pr : header) {
         printer << pr.first << ": " << pr.second << "\r\n";
@@ -743,7 +738,7 @@
     if (_sdp_track.size() == 1) {
         return 0;
     }
-    throw SockException(Err_shutdown, StrPrinter << "no such track with type:" << getTrackString(track_type));
+    throw SockException(Err_other, StrPrinter << "no such track with type:" << getTrackString(track_type));
 }
 
 ///////////////////////////////////////////////////

**Comment by xia-chu** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/a8dea3ac-2445-4e17-8e1b-d92ef31e8f35)

**Comment by xia-chu** [comment]
<img width="858" height="820" alt="Image" src="https://github.com/user-attachments/assets/38ceef40-3a9c-4e54-8b4a-dd9a4aa89d53" />

**Comment by xia-chu** [comment]
<img width="852" height="817" alt="Image" src="https://github.com/user-attachments/assets/7072fe1c-e2b3-47e9-bd50-e5266523edf1" />

**Comment by xia-chu** [comment]
![Image](https://github.com/user-attachments/assets/fe9b7be5-ab99-4873-a2a3-ad436bc525ce)
![Image](https://github.com/user-attachments/assets/fd666589-b7da-4a0e-9759-247e308cc898)
![Image](https://github.com/user-attachments/assets/f619438f-ba95-4120-ba92-5991745d476d)
![Image](https://github.com/user-attachments/assets/33de1598-709b-47ba-b5b9-a1059abb3f0f)
![Image](https://github.com/user-attachments/assets/2817e7c9-215c-4c1f-b406-baaa7078110c)
![Image](https://github.com/user-attachments/assets/58d36e90-ff78-42a1-89b3-9f1f789e9b2e)
![Image](https://github.com/user-attachments/assets/a04165c7-14d5-4068-8f4a-1767efe99b39)
![Image](https://github.com/user-attachments/assets/c633f10b-98c3-4d2e-8259-1eb88098a3b8)
![Image](https://github.com/user-attachments/assets/556c0b58-799b-4693-b417-847b2ab39d44)
![Image](https://github.com/user-attachments/assets/c7efc5f7-49ee-4711-b6c1-a95e9498fdae)
![Image](https://github.com/user-attachments/assets/b16c3068-f603-4d5a-b41d-ffd0920df5c9)
