### ISSUE TITLE
Logo加上眼睛更好看？

### ISSUE THREAD

**Issue by alongL** [xia-chu/ZLMediaKit#770]
大佬，你看这些知名的产品 logo都加上眼睛，是不是有感情多了？可爱多了？
![image](https://user-images.githubusercontent.com/5533883/111096267-1cc35600-857a-11eb-8be1-3936e1bc1b1c.png)

![image](https://user-images.githubusercontent.com/5533883/111096316-34024380-857a-11eb-9504-41bed0c9a995.png)
![image](https://user-images.githubusercontent.com/5533883/111096328-39f82480-857a-11eb-98df-60e90d8e0153.png)
![image](https://user-images.githubusercontent.com/5533883/111096339-3fee0580-857a-11eb-9373-6bc02d0b0f6b.png)

我们的Logo也可以尝试加上眼睛，类似于这样的？或者别的更能体现某种情感的？ 
![image](https://user-images.githubusercontent.com/5533883/111096217-f998a680-8579-11eb-8d57-9bc1c59232e4.png)

**Comment by xia-chu** [comment]
是的 这个logo我其实也不是很满意 当时花钱请别人做的  虽然不是很满意 但是总比没有好

**Comment by woodlyer** [comment]
我用google的 gemini画了2张，供大师参考。


<img width="1024" height="490" alt="Image" src="https://github.com/user-attachments/assets/4519c187-25b8-442b-8fa3-c0705766130d" />



<img width="1024" height="490" alt="Image" src="https://github.com/user-attachments/assets/626f393e-8f9e-44b5-b164-f0a9b7cf0cc0" />


提示词
```
这是一个流媒体开源项目的logo，但是图片上的这条旗鱼没有眼睛，
能不能在这张图片上画一张眼睛，让它看起来更加的生动，活沷，有趣。 
图片本身比较简单，颜色比较纯，这个眼睛也要颜色单纯一点，只有1-2种颜色就行了。
```

**Comment by xia-chu** [comment]
是的 没眼镜一直是个败笔 另外我觉得鱼背鳍也太生硬了
