### ISSUE TITLE
使用index/api/addFFmpegSource拉二路流遇到的问题

### ISSUE THREAD

**Issue by sp-cache-hit** [xia-chu/ZLMediaKit#771]
1.使用拉流代理，第二路流可以正常观看，但是第一路流无法观看
2.使用index/api/delFFmpegSource关闭拉流代理，返回false，再度打开拉流代理，返回值为true，但是状态本身没有变化
使用url:
拉流代理：
本地（get）:
http://localhost:8080/index/api/addFFmpegSource?src_url=rtsp://172.16.2.184:8554/abc/live&dst_url=rtsp://172.16.2.184:8554/abc/live2&timeout_ms=60000
返回：
    {
       "code" : 0,
       "data" : {
          "key" : "cf9b1fbbb48e7e24fcdb31cf5bcf1b97"
       }
    }
        
关闭拉流代理：
本地（get）:
http://localhost:8080/index/api/delFFmpegSource?key=cf9b1fbbb48e7e24fcdb31cf5bcf1b97
返回：
    {
       "code" : 0,
       "data" : {
          "flag" : false
       }
    }

**Comment by xia-chu** [comment]
addFFmepgSource接口默认的FFmpeg命令模板只支持推流rtmp的 ，如果你要推流rtsp，那么需要修改配置文件的：
![图片](https://user-images.githubusercontent.com/11495632/111726879-ba819280-88a4-11eb-827d-c355818e116e.png)

**Comment by xia-chu** [comment]
而且你推流到第三方服务器，zlm其实不支持有没有推流成功，zlm只能通过FFmpeg进程时候存活判断成功与否
