### ISSUE TITLE
测试url网址路径写错了

### ISSUE THREAD

**Issue by qdmxy** [xia-chu/ZLMediaKit#772]
ZLMediaKit/server/WebApi.cpp中的723行, 应该是delFFmpegSource而不是delFFmepgSource

**Comment by xia-chu** [comment]
新代码已经修正了 你代码比较老吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qdmxy ***@***.***&gt;
发送时间: 2021年3月16日 08:38
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 测试url网址路径写错了 (#772)





 
ZLMediaKit/server/WebApi.cpp中的723行, 应该是delFFmpegSource而不是delFFmepgSource

**Comment by qdmxy** [comment]
我看那个master分支还是那样, 不知道是不是最新的
![](https://www.hualigs.cn/image/60500a368c7a6.jpg)

**Comment by xia-chu** [comment]
哦哦 注释是错误的 代码是正确的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qdmxy ***@***.***&gt;
发送时间: 2021年3月16日 09:33
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 测试url网址路径写错了 (#772)





 
我看那个master分支还是那样, 不知道是不是最新的

**Comment by xia-chu** [comment]
谢谢你的反馈！
