### ISSUE TITLE
建议增加转码功能

### ISSUE THREAD

**Issue by wlz19930129** [xia-chu/ZLMediaKit#775]
ZLM接受/转发流时，视频与音频编码格式与原流保持相同，并不支持任意播放器播放，建议增加转码功能，支持更多的播放器。

**Comment by xia-chu** [comment]
addFFmpegSource接口可以满足你的需求的，只是转码开销和代价太高了，我一般不推荐如此

**Comment by wlz19930129** [comment]
试了一下确实可以，但是延迟明显变高了，CPU占用也变高，有没有其他的方式，或者增加扩展接口

**Comment by xia-chu** [comment]
任何转码都这样 如果能选择硬件编解码器 能稍微好点



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wlz19930129 ***@***.***&gt;
发送时间: 2021年3月22日 10:29
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 建议增加转码功能 (#775)

**Comment by wlz19930129** [comment]
那能不能只增加音频转码功能呢，使用addFFmpegSource这个接口无论是启播速度还是并发情况都有点不太好，我们遇到了一些具有双向通话功能的设备，取流只支持g711和g722的音频编码，web端也没找到可以支持的播放器

**Comment by xia-chu** [comment]
ffmpeg命令模板改成-vcodec copy就不转码视频



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wlz19930129 ***@***.***&gt;
发送时间: 2021年3月22日 14:05
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 建议增加转码功能 (#775)

**Comment by mayomeng** [comment]
addFFmpegSource接口能否添加一个直接传递命令参数的入参，用ffmpeg_cmd_key每次都要修改配置文件，用起来不太方便

**Comment by xia-chu** [comment]
你可以自己修改代码那样做 但是我不建议 那样做可能不是很安全

**Comment by taojishou** [comment]
是否可以配置多个ffmpeg模板配置 然后指定调用哪个

**Comment by xia-chu** [comment]
> 是否可以配置多个ffmpeg模板配置 然后指定调用哪个

你不看wiki么？
![图片](https://user-images.githubusercontent.com/11495632/131278310-f4481603-5052-45d5-9dfd-97f33f43ccd5.png)

**Comment by taojishou** [comment]
是因为这样调用了 然后发现多个的话 不起作用 所以才问的 最新的master代码~~

**Comment by taojishou** [comment]
好了知道啦 cmd_key=ffmpeg.cmdaac  我直接传的是cmd_key=cmdaac 哈哈 不好意思了老哥
