### ISSUE TITLE
海康RTSP通过addStreamProxy接口推流，报错，大华的RTSP却正常，请指点

### ISSUE THREAD

**Issue by chenxihai** [xia-chu/ZLMediaKit#778]
使用addStreamProxy接口推海康RTSP流，url:rtsp://admin:admin123@192.168.1.100/Streaming/Channels?101(此流VLC播放正常)，流媒体报如下错误：
![20210321231049](https://user-images.githubusercontent.com/68054900/111910290-be2b3a00-8a9b-11eb-9e30-d2bfde4d5294.png)
用大华摄像头RTSP流一切正常

**Comment by xia-chu** [comment]
这个url能否暴露公网给我调试下？

**Comment by chenxihai** [comment]
不好意思，没办法暴露，就是普通海康摄像头，我这里有好几个海康的都是这样，大华的没事，海康的推流报这个错误，转出来的流可以打开，但是丢帧严重，花屏现象比较多

**Comment by xia-chu** [comment]
安装frp后 应该可以暴露的 你先更新下zlm试试

**Comment by chenxihai** [comment]
我印象中去年11月份之前的版本，没有这个问题，我也记不清是从什么时候更新版本才出现的。

**Comment by xia-chu** [comment]
你更新下 可能又没这个问题了

**Comment by xia-chu** [comment]
改动大 会引入点bug 后面又会修复

**Comment by chenxihai** [comment]
是的，更新之后没有报错了，谢谢！另外我想咨询一下，我这有一个红外摄像头，不是海康大华的设备，提供的rtsp流用vlc可以正常播放，但是用addstreamproxy却取不到流，可能是啥原因？

**Comment by xia-chu** [comment]
rtsp抓包分析下

**Comment by CallMeReznov** [comment]
> 是的，更新之后没有报错了，谢谢！另外我想咨询一下，我这有一个红外摄像头，不是海康大华的设备，提供的rtsp流用vlc可以正常播放，但是用addstreamproxy却取不到流，可能是啥原因？

你看一下接口地址是不是有&之类的字符被强制转义后丢弃了.
