### ISSUE TITLE
sip与摄像头建立的是UDP连接，向摄像头发起预览请求后能返回ssrc，但ZLMediaKit没有获取到对应的推流消息

### ISSUE THREAD

**Issue by mmy-wly** [xia-chu/ZLMediaKit#779]
是用wvp+ZLMediakit实现的，这两个工程都放在同一台服务器上跑，wvp与摄像头是UDP的方式连接，在wvp能成功获取到设备信息，并且预览视频流时能返回ssrc值，但ZLMediakit这边没有任何反应，是不是因为ZLMediakit这边监听的是TCP的连接呀。？这个会有影响吗。？

之前放在本地测试时用TCP连接，是能正常取到流播放的，放到服务器上就不行了

**Comment by xia-chu** [comment]
这个应该是安全组和防火墙设置有问题 或者是你在配置wvp的公网ip时有误 请仔细阅读wvp的wiki和配置文件注释再尝试。

**Comment by mmy-wly** [comment]
@xia-chu   你好，我参照着教程来配置，WVP中的配置文件里是media项的ip属性值 和sip项的ip属性值是一样的，都是当前服务器的私网ip，设置media的port是10000，在服务器的防火墙里添加了port为10000的入站规则。

ZLMediaKit进行推流测试是正常的，wvp那边运行相关的api也是正常的，也能收到摄像头的心跳包。但wvp预览摄像头数据时ZLMediaKit这边就没收到消息

**Comment by xia-chu** [comment]
这个问题 我真的不好回答你 wvp我其实也不熟悉的

**Comment by mmy-wly** [comment]
@xia-chu   嗯嗯 感谢 我抓包分析了下，发送请求的流程都跑通了，但摄像头那边没有推流过来。。 跟流媒体这边没关系  应该还是有什么配置没弄好  我再看看~
