### ISSUE TITLE
cmake build失败

### ISSUE THREAD

**Issue by ZhangJiaLei123** [xia-chu/ZLMediaKit#781]
Centos7源码构建报错,请问怎么解决. 百度没有收到方案:
```
[root@localhost build]# cmake ..
-- Debug版本
-- found library:"/usr/local/lib/libjemalloc.so"
-- found library:/usr/lib64/libssl.so;/usr/lib64/libcrypto.so,ENABLE_OPENSSL defined
-- MySQL not found.
-- ENABLE_HLS defined
-- ENABLE_MP4 defined
-- ENABLE_RTPPROXY defined
-- add c api tester:pusher
-- add c api tester:server
-- add c api tester:websocket
-- test_player ingored, please install sdl2 ffmpeg/libavcodec ffmpeg/libavutil
-- add test:bom
-- add test:tab
-- add test:test_bench_proxy
-- add test:test_bench_pull
-- add test:test_bench_push
-- add test:test_httpApi
-- add test:test_httpClient
-- add test:test_pusher
-- add test:test_pusherMp4
-- add test:test_rtcp
-- add test:test_rtp
-- add test:test_server
-- add test:test_sortor
-- add test:test_wsClient
-- add test:test_wsServer
-- Git version is master:f2edf354de355fd12dfba598fbb4081f09e405eb:2021/03/22-16:25:54
-- Configuring done
CMake Error at CMakeLists.txt:157 (add_library):
  No SOURCES given to target: flv


CMake Error at CMakeLists.txt:133 (add_library):
  No SOURCES given to target: mpeg


CMake Error at CMakeLists.txt:156 (add_library):
  No SOURCES given to target: mov


CMake Error at CMakeLists.txt:189 (add_library):
  No SOURCES given to target: zltoolkit


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by xia-chu** [comment]
wiki快速开始都不看吗

**Comment by xia-chu** [comment]
git submodule update --init

**Comment by hylyLLL** [comment]
你好，我其他的依赖都装了但是提示：
root@guardianbox:~/ZLMediaKit/build# cmake ..
-- Debug版本
-- found library:/usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so,ENABLE_OPENSSL defined
-- MySQL not found.
-- ENABLE_HLS defined
-- ENABLE_MP4 defined
-- ENABLE_RTPPROXY defined
-- add c api tester:pusher
-- add c api tester:server
-- add c api tester:websocket
-- found library:avutil
-- found library:avcodec
-- test_player ingored, please install sdl2 ffmpeg/libavcodec ffmpeg/libavutil
-- add test:bom
-- add test:tab
-- add test:test_bench_proxy
-- add test:test_bench_pull
-- add test:test_bench_push
-- add test:test_httpApi
-- add test:test_httpClient
-- add test:test_pusher
-- add test:test_pusherMp4
-- add test:test_rtcp
-- add test:test_rtp
-- add test:test_server
-- add test:test_sortor
-- add test:test_wsClient
-- add test:test_wsServer
-- Git version is master:86afa379c48600e8b92e575b678023fa9491aac0:2021/04/27-13:48:53
-- Configuring done
-- Generating done
-- Build files have been written to: /root/ZLMediaKit/build

**Comment by hylyLLL** [comment]
原先是可以编译的，拉取了最新代码后就这样了
