### ISSUE TITLE
运行正常,但是一直在刷这个警告

### ISSUE THREAD

**Issue by tonyonce2017** [xia-chu/ZLMediaKit#782]
![image](https://user-images.githubusercontent.com/34465929/111984738-b96f9000-8b46-11eb-8d90-25f82405c676.png)

**Comment by xia-chu** [comment]
没事 只是一直收到了http请求了而已



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tonyonce ***@***.***&gt;
发送时间: 2021年3月22日 19:42
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 运行正常,但是一直在刷这个警告 (#782)
