### ISSUE TITLE
录制hls的相关疑问

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#784]
调用startRecord stopRecord 进行录像录制时，发现下述问题，请教一下大神

1.调用/index/api/startRecord方法进行录像保存时， 设置了customized_path参数，但是在自定义的路径下生成了app/stream的文件夹，是否可以不生成app/stream的文件夹？

2. 调用/index/api/startRecord方法进行录像保存时，当type为0(HLS)时，保存的文件个数始终是9个，当超过9个时，旧的文件就会被删除。(配置文件中的hls.segRetain=5)

3. 调用/index/api/stopRecord停止录像保存时，当type为0(HLS)时，所有的ts文件都被删除了

**Comment by xia-chu** [comment]
<img width="761" alt="图片" src="https://user-images.githubusercontent.com/11495632/112158350-09bc2000-8c23-11eb-9d58-ac09a3d26d7c.png">
HLS录制其实就是HLS直播文件生成，两种不能同时并存的。

**Comment by mayomeng** [comment]
但是如果设置hls.segNum=0，那么不调用startRecord，正常推流产生的ts文件也不会被删除。
即如果想按照自定义时间保存ts文件，就不能开启hls直播，如果开启hls直播，那么推流期间所有的ts文件都会被保存。

**Comment by xia-chu** [comment]
是的 hls只能用于直播或录制，不能同时存在。zlm的hls本来是用于直播的，后面别人提交了pr，就假装支持了hls录制。其实支持力度很小，zlm的录制本来就只有mp4
