### ISSUE TITLE
hoop接口无人观看事件

### ISSUE THREAD

**Issue by tonyonce2017** [xia-chu/ZLMediaKit#785]
![image](https://user-images.githubusercontent.com/34465929/112115707-74099c00-8bf4-11eb-802b-610bec057543.png)
请问这个地方, 我测试, 如果hls格式的流无人观看, flv格式的流有人在观看, 我收到hls无人观看事件, 返回close, 推流就关闭了, 导致flv也无法观看了, 我实际想要的是, 没有任何格式的有人在看就关闭这个推流, 现在的好像做不到吧, 我收到无人观看事件时, 不好判断是不是有其格式的正在被人观看

**Comment by xia-chu** [comment]
现在这个hook就是所有协议都没人看才会触发，你红框中的schema字段是指，这个协议是最后一个播放器关闭时触发这个无人观看事件的，其他协议早就没人看了

**Comment by tonyonce2017** [comment]
> 现在这个hook就是所有协议都没人看才会触发，你红框中的schema字段是指，这个协议是最后一个播放器关闭时触发这个无人观看事件的，其他协议早就没人看了
嗯, 再测试了一下, 确实不是每个流无人看都发通知, 不过我会偶尔遇到才刚开始推流, 就收到fmp4的无人观看通知, 请问这个跟配置有关系吗?
