### ISSUE TITLE
ZLMediaKit是否有推流多路的性能测试报告

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#786]
https://github.com/xia-chu/ZLMediaKit/issues/406 中提供了推流1路播放1000路的测试数据，请问是否有推多路的测试数据可供参考一下？单机能够接受的推流大概在多少路？（目前测试环境接入路数有限，没法测试，希望问问有没有相关的测试数据）

**Comment by xia-chu** [comment]
单线程性能跟srs差不多 但是zlm是多线程的 可以发挥cpu多线程性能
