### ISSUE TITLE
客户端收看HLS情况下，API发送Kick_Session后，无法断开TCP链接

### ISSUE THREAD

**Issue by NangenX** [xia-chu/ZLMediaKit#787]
【现象】客户端收看HLS情况下，API发送Kick_Session后，无法断开TCP链接，用FLV播放，发送Kick_Session就可以正常关闭链接。
【使用版本】：Docker最新版本
【启动命令】：docker run -id --name zlm --network host panjjo/zlmediakit
![image](https://user-images.githubusercontent.com/18715023/112276184-6c60fa80-8cbb-11eb-8ff9-12de5d94b507.png)

**Comment by xia-chu** [comment]
hls如果你不开启播放鉴权 那么踢除后客户端会再次连接并成功的

**Comment by xia-chu** [comment]
hls是短连接 播放器会一直重试
