### ISSUE TITLE
有个流一直断不掉 用getMediaList查询到他的local_ip是0.0.0.0

### ISSUE THREAD

**Issue by mmy-wly** [xia-chu/ZLMediaKit#788]
同一个摄像头连推了几次流后，其他的自动断开了，就剩最后一个流，但特别卡还总是花屏，就想断开重新推，结果用断不掉，通过http://127.0.0.1:8082/index/api/getMediaList获取信息发现他的local_ip一直是0.0.0.0  其他的值是正常的

关掉服务器重新运行他又会自动注册上，请问 可能是什么原因呀。？

**Comment by xia-chu** [comment]
你的zlm版本是多少？
http://127.0.0.1:8082/index/api/getMediaList 的json粘贴上来看看
