### ISSUE TITLE
ZLMediaKit and Microsoft Media Foundation

### ISSUE THREAD

**Issue by klukule** [xia-chu/ZLMediaKit#789]
Hello,

during my testing, I've found that there are few bugs that prevent ZLMediaKit from being used with RTSP client and hardware AAC/H264 decoders provided my MMF.

First problem is that AAC SDP must have MPEG4-GENERIC in lowercase (mpeg4-generic):
Doesn't work:
```
a=rtpmap:98 MPEG4-GENERIC/48000/2
```
Works:
```
a=rtpmap:98 mpeg4-generic/48000/2
```
---
Second problem is that because MMF has small or no buffers, any audio bitrate above 160kbit/s results in random popping sounds. (We were testing using 320kbit/s AAC 48000hz stereo audio stream using RTMP -> RTSP)

---
Tested with custom MMF based client and can be also replicated in unity using AVPro library (you need to use rtspt:// instead of rtsp://)

Thank you very much for your feedback.

**Comment by xia-chu** [comment]
When you push a 320kbit / s RTMP stream to zlmediakit, zlmediakit will extract the bit rate related information from the RTMP protocol and generate the bit rate field in the SDP of RTSP.

**Comment by klukule** [comment]
I checked the SDP and bitrates get passed through (2500 for video and 320 for audio) but even with them in the SDP I still get popping like you can hear in the video:
https://user-images.githubusercontent.com/3607341/112493769-bf51b500-8d82-11eb-93d3-ce6d4135056a.mp4

Audio plays without a problem when using 160kbit/s audio

**Comment by xia-chu** [comment]
So you should choose 160 audio instead of 320 when streaming RTMP

**Comment by klukule** [comment]
I will be closing this issue now because main issue of MF not being able to play RTSP stream is resolved. And I also found that I needed to make rtp audio mtu size larger which avoids poping.

Thank you for your work.
