### ISSUE TITLE
delay occurs

### ISSUE THREAD

**Issue by feelwa17** [xia-chu/ZLMediaKit#790]
I created 100 rtsp pushers.
There is a serious delay in transmission.
There is a lot of delay between frames.
(bitrate : 10mbps)

**Comment by xia-chu** [comment]
please change ini config file like this:
![图片](https://user-images.githubusercontent.com/11495632/112414523-265c7300-8d5d-11eb-8159-c8282c7105a7.png)

**Comment by feelwa17** [comment]
It's still the same.
I think delay occurs in the rtp packet send part when transferring to a large number of rtsp pushers.

**Comment by xia-chu** [comment]
is the cpu usage heigh?



发自我的iPhone


------------------ Original ------------------
From: feelwa17 ***@***.***&gt;
Date: Fri,Mar 26,2021 2:02 PM
To: xia-chu/ZLMediaKit ***@***.***&gt;
Cc: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xia-chu/ZLMediaKit] delay occurs (#790)





 
It's still the same.
 I think delay occurs in the rtp packet send part when transferring to a large number of rtsp pushers.

**Comment by feelwa17** [comment]
Cpu usage is not high.

**Comment by feelwa17** [comment]
For example,
Can all rtsp pushers transmit the same frame at the same time?

When I test, the input time is the same, but the transmission is very different.

**Comment by xia-chu** [comment]
Of course, I've tested several thousand RTSP streams pushed at the same time, and everything is normal. Are you TCP pushing
