### ISSUE TITLE
hls播放总是时间回退

### ISSUE THREAD

**Issue by Glorysun** [xia-chu/ZLMediaKit#791]
通过zlm拉海康H265的rtsp流转hls使用easyPlayer播放，有的视频可以正常播放但是偶尔花屏，有的视频播放的时候时间总是会回退几秒也经常花屏，
![image](https://user-images.githubusercontent.com/56619202/112416543-d8496e80-8d60-11eb-9021-3b667267a483.png)
配置文件默认没有修改，日志总是打印H265Rtp.cpp:90 unpackAp | 数据不够

![image](https://user-images.githubusercontent.com/56619202/112416597-f31be300-8d60-11eb-8d22-daa7f2b68642.png)
这是我配置的问题吗..

**Comment by xia-chu** [comment]
这个流的rtp应该有问题 你试试vlc ffplay播放



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: glorysun ***@***.***&gt;
发送时间: 2021年3月25日 11:56
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] hls播放总是时间回退 (#791)

**Comment by Glorysun** [comment]
> 这个流的rtp应该有问题 你试试vlc ffplay播放 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: glorysun ***@***.***&gt; 发送时间: 2021年3月25日 11:56 收件人: xia-chu/ZLMediaKit ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[xia-chu/ZLMediaKit] hls播放总是时间回退 (#791)

用vlc播放有时时间也会回退，但是没有用web播放器验证，vlc回退频率很慢，而且就回退大概一秒；我用web播放器的话，经常回退，而且会回退3、4秒
![image](https://user-images.githubusercontent.com/56619202/112417458-a76a3900-8d62-11eb-8d97-077ad81fc306.png)
用web播放器播放的时候，日志打印的特别快还

**Comment by xia-chu** [comment]
播放原始rtsp试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: glorysun ***@***.***&gt;
发送时间: 2021年3月25日 12:08
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] hls播放总是时间回退 (#791)

**Comment by Glorysun** [comment]
试了很多rtsp的流在vlc播放没有问题，通过zlm转成hls之后在vlc播放也都没有问题；但是在浏览器通过播放器播放，有的hls流就会出现这种时间回退的现象，而且是固定的那些流，尝试换了不同的播放器也是固定的流出现这种现象，查看摄像头的配置也是一样的
![image](https://user-images.githubusercontent.com/56619202/112463303-09e02b00-8d9d-11eb-88dc-58635dc8a6f9.png)

这是播放异常的拉流频率
![image](https://user-images.githubusercontent.com/56619202/112463782-a276ab00-8d9d-11eb-81e0-371d29820e80.png)

这是播放正常的拉流频率
![image](https://user-images.githubusercontent.com/56619202/112463960-d81b9400-8d9d-11eb-9997-b3b284fcf2fe.png)

想不出来到底是那个部分的问题..

**Comment by xia-chu** [comment]
是不是有些摄像头有b帧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: glorysun ***@***.***&gt;
发送时间: 2021年3月25日 19:12
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] hls播放总是时间回退 (#791)





 
试了很多rtsp的流在vlc播放没有问题，通过zlm转成hls之后在vlc播放也都没有问题；但是在浏览器通过播放器播放，有的hls流就会出现这种时间回退的现象，而且是固定的那些流，尝试换了不同的播放器也是固定的流出现这种现象，查看摄像头的配置也是一样的
 
 
这是播放异常的拉流频率
 
 
这是播放正常的拉流频率
 
 
想不出来到底是那个部分的问题..

**Comment by xia-chu** [comment]
这个问题可能是摄像头又B帧，有些浏览器对这个支持不好。
