### ISSUE TITLE
http api 获取截图或生成实时截图接口 不支持 h265格式流地址截图吗

### ISSUE THREAD

**Issue by rsxieliang** [xia-chu/ZLMediaKit#792]
23、/index/api/getSnap
功能：获取截图或生成实时截图并返回

**Comment by xia-chu** [comment]
FFmpeg支持265的协议包括：
- rtsp
- http-ts
- http-fm4
由于rtmp、flv协议不支持265，
所以建议你截图时，用rtsp、http-ts、http-fm4的url
