### ISSUE TITLE
mac vlc只能播放3秒画面

### ISSUE THREAD

**Issue by GiantClam** [xia-chu/ZLMediaKit#794]
使用master分支最新的代码，编译后，从海康设备ehome协议拉流，在mac上仅能播放3秒画面暂停，并且提示内部线程过载

![image](https://user-images.githubusercontent.com/1756007/112835876-6fe5ee80-90cc-11eb-9cfd-e6371f4f2275.png)

**Comment by GiantClam** [comment]
尝试了rtsp是正常的，难道是ffmpeg转换rtmp协议的参数有问题？试试再说

**Comment by xia-chu** [comment]
有测试或ffplay播放rtmp正常么

**Comment by xia-chu** [comment]
> 使用master分支最新的代码，编译后，从海康设备ehome协议拉流，在mac上仅能播放3秒画面暂停，并且提示内部线程过载
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1756007/112835876-6fe5ee80-90cc-11eb-9cfd-e6371f4f2275.png)
> 
> 

偶尔提示线程负载比较高没问题的
