### ISSUE TITLE
关于gb28181级联转发ps流问题

### ISSUE THREAD

**Issue by qinqi** [xia-chu/ZLMediaKit#799]
当调用startSend方法时，当前有人观看视频转发是可以正常转发的，但当当前视频无人观看后，一定时间会关闭端口（即按需拉取），同时转发的PS流的也会断，请问大佬能否做一个机制，当检测到无人观看并且无转发的时候，再自动关闭端口。录制会不会有这个毛病目前还没有测，等我有时间测一下告诉您一下结果。

**Comment by xia-chu** [comment]
录制和向上级推流都不算播放个数统计的 所以没人看都会停止 建议你的业务服务器在响应hook时判断下这个流有没有启动录制或推流 如果没有才返回关断

**Comment by qinqi** [comment]
好的 多谢大佬 刚开始没想明白 思考了一下想明白了 多谢指点

**Comment by xia-chu** [comment]
没做这个接口呢 不过控制主动推流 不是你触发的功能吗 你应该也知道啊

**Comment by qinqi** [comment]
好的，大概理解这个流程了，多谢大佬

**Comment by xia-chu** [comment]
可以适当二次开发zlm啊 毕竟业务是千差万别的

**Comment by qinqi** [comment]
嗯嗯。感觉zlm确实已经很完善了，哈哈哈

**Comment by zhang2349** [comment]
> 录制和向上级推流都不算播放个数统计的 所以没人看都会停止 建议你的业务服务器在响应hook时判断下这个流有没有启动录制或推流 如果没有才返回关断

看了下代码 在观看人数变化成0时才触发无人观看的定时器  如果这时我判断有向上级推流 不关， 当之后再停止向上级推流  再之后一直没人观看过 这无人观看也就不会触发了

**Comment by mrjackwang** [comment]
> > 录制和向上级推流都不算播放个数统计的 所以没人看都会停止 建议你的业务服务器在响应hook时判断下这个流有没有启动录制或推流 如果没有才返回关断
> 
> 看了下代码 在观看人数变化成0时才触发无人观看的定时器 如果这时我判断有向上级推流 不关， 当之后再停止向上级推流 再之后一直没人观看过 这无人观看也就不会触发了 这逻辑在外面不太好做呀

可以手动请求关流

**Comment by zhang2349** [comment]
或者 在停止向上级推流的时候 再去查询下 有没有人观看？ 没人观看 就关闭？
这就做的有点不上不下了  无人观看的作用就没什么用了

**Comment by qinqi** [comment]
> 或者 在停止向上级推流的时候 再去查询下 有没有人观看？ 没人观看 就关闭？
> 这就做的有点不上不下了 无人观看的作用就没什么用了

你可以做一个定时器，当你级联的时候你记住端口，定时查看一下listRtpServer，跟你对应记录的端口对比，当count为0且记录的端口无的时候调用closeRtpServer就可以了

**Comment by zhang2349** [comment]
> > 或者 在停止向上级推流的时候 再去查询下 有没有人观看？ 没人观看 就关闭？
> > 这就做的有点不上不下了 无人观看的作用就没什么用了
> 
> 你可以做一个定时器，当你级联的时候你记住端口，定时查看一下listRtpServer，跟你对应记录的端口对比，当count为0且记录的端口无的时候调用closeRtpServer就可以了

是可以这么做  这样做了 那个无人观看就失去了意义  而且这样是轮询式的   路数多了 也会有性能问题把

**Comment by xia-chu** [comment]
假设有种需求，用户观看摄像头的时候，平台希望能同时静默监管，同时通过startSendRtp接口发送流到其他平台，但是用户不看摄像头时，又触发无人观看事件，同时把推流关闭，你说跟你的业务场景是不是冲突了？

**Comment by xia-chu** [comment]
目前zlm的 rtsp rtmp推流计算进观看人数， 但是ps-rtp推流不计算进人数

**Comment by zhang2349** [comment]
那可以通过参数有区别对待呀

**Comment by zhang2349** [comment]
我觉得ps-rtp推流更应该是流的一种播放方式 跟rtsp rtmp http 一样，而不能说是为了静默监管做的一种业务功能

**Comment by bravecat** [comment]
如果我从摄像头取流，然后开始ps-rtp推流，假如对方媒体服务器异常或关闭了，我如何查询推流状态，从而停止从摄像头取流呢？

**Comment by qinqi** [comment]
> 如果我从摄像头取流，然后开始ps-rtp推流，假如对方媒体服务器异常或关闭了，我如何查询推流状态，从而停止从摄像头取流呢？

有keepalive保活机制或rctp保活机制

**Comment by xia-chu** [comment]
如果说udp推流 现在没做接收rtcp保活的 需要开发者通过其他途径获取这个信息并手动stopSendRtp接口

**Comment by xia-chu** [comment]
@qinqi @zhang2349 改了下代码 你们的这个特性支持了

**Comment by qinqi** [comment]
> @qinqi @zhang2349 改了下代码 你们的这个特性支持了

好的 多谢大佬

**Comment by zhang2349** [comment]
额 两句就搞定了 我尝试改了下 加了好多代码。。。。还好没拿出来。。。

下一步要加rtcp保活了 测试发现 直接发目标 端口关闭会触发onErr
如果经过转发的 无法通过连接去确定 目标有没有在接收

**Comment by xia-chu** [comment]
这样udp又要新增一个端口了

**Comment by xia-chu** [comment]
而且现在接收端停止收流， zlm会一直尝试重连的

**Comment by zhang2349** [comment]
重试没什么用，一般接收端停止了 就不需要发了

接收端会重新走信令流程 给一个新的端口

**Comment by xia-chu** [comment]
那怎么通知你停止了 ？ 通过hook吗

**Comment by zhang2349** [comment]
大概想了下
通不通知可以没什么关系，感觉可以跟 播放一样 发失败了就是 停止播放了

**Comment by zhang2349** [comment]
其实跟openRtpServer的逻辑差不多， 保活失败了，就自动删除了
在流信息里加上当前在转发的信息

**Comment by bravecat** [comment]
赞同 RtpSender::onErr 加hook，这样就可以自己决定是否停止推流了

**Comment by bravecat** [comment]
赞同 RtpSender::onErr 加hook，这样就可以自己决定是否停止推流了
