### ISSUE TITLE
win10  64   vs2019编译报错

### ISSUE THREAD

**Issue by zhuqiyun** [xia-chu/ZLMediaKit#802]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 HMAC_CTX_init，函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl openssl_HMACsha256(void const *,unsigned __int64,void const *,unsigned __int64)" (?openssl_HMACsha256@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBX_K01@Z) 中引用了该符号	E:\media\ZLMediaKit\out\build\x64-Debug\ZLMediaKit	E:\media\ZLMediaKit\out\build\x64-Debug\zlmediakit.lib(RtmpProtocol.cpp.obj)	1

**Comment by xia-chu** [comment]
openssl链接失败 你应该没安装对正确的openssl版本

**Comment by zhuqiyun** [comment]
> openssl链接失败 你应该没安装对正确的openssl版本

最新的代码对应的openssl版本是多少现在？

**Comment by xia-chu** [comment]
基本都支持的

**Comment by zhuqiyun** [comment]
> 基本都支持的

安装完之后按照说明也配置了环境变量，就是不行，搞不定。

**Comment by zhuqiyun** [comment]
> > 基本都支持的
> 
> 安装完之后按照说明也配置了环境变量，就是不行，搞不定。

能提供一个配置案例嘛，win10 openssl的

**Comment by zhuqiyun** [comment]
> 基本都支持的

编译通过了  可以结案了  不用配置  就是openssl路径设置好

> 基本都支持的

编译通过了   可以结案了   就是配置好openssl的环境变量
