### ISSUE TITLE
使用按需拉流方式时的疑问

### ISSUE THREAD

**Issue by CallMeReznov** [xia-chu/ZLMediaKit#803]
windows,下载连接内的release测试:    
https://github.com/xia-chu/ZLMediaKit/issues/483#issuecomment-758372740  

我按照"按需拉流"内流流程方式写了个demo,测试顺利通过,从not_found hook到addStreamProxy请求发出后视频1秒就出来了
,效率之高令人惊讶.   
但不知为何,无论我如何修改配置文件内[ffmpeg]的cmd都无法设置流的音频编码为ACC.导致网页内使用播放器播放http://127.0.0.1/live/1.flv时游览器疯狂报错(easyplayer.js)

我是使用addStreamProxy接口添加的视频
使用getMediaList获取流发现默认4路流内的音频全是CodecG711A.    

麻烦抽空解答一下我这个到底是什么情况?在此感谢.

**Comment by xia-chu** [comment]
用addFFmegSource接口就行
