### ISSUE TITLE
对新创建的rtp服务器推流，花屏

### ISSUE THREAD

**Issue by kingecg** [xia-chu/ZLMediaKit#805]
场景：

自己搭建了个GB28181的sip服务器，并提供webhook.

交互流程：

- 播放器向ZLK请求视频流
- ZLK通过on_stream_not_found hook告诉sip服务器需要新流
- sip服务器调用ZLK的api /index/api/openRtpServer 创建一个新的rtp server. 
- sip服务器向摄像头发指令向上一步创建的rtp服务器推流

这样得到的流底部花屏

但是，如果直接向ZLK推流，则不会花屏

**Comment by xia-chu** [comment]
不可能一直花屏吧
