### ISSUE TITLE
请问如何修改缓存时间

### ISSUE THREAD

**Issue by alexliyu7352** [xia-chu/ZLMediaKit#806]
比如因为zlmediakit与推流端或者拉流端之间的网络质量不好, 比如丢包厉害而导致速度比较慢.
是否可以做到可以设置缓存流的时间长度.
比如设置zlmediakit可以缓存5分钟的直播流, 那么一旦开始拉流或者接收到推流后就开始进行缓存.
之后客户端从zlmediakit拉流的时候, zlmediakit始终是从缓冲的5分钟开始发送流.

这样虽然客户端看到的流延时5分钟,但是至少能保证流畅.

请教下, 如果想要这样改动, 应该修改哪里?

之前看issues,你有说了修改_max_send_buffer_ms, 我觉得应该做不到我说的需求吧.

**Comment by xia-chu** [comment]
你这个叫GOP缓存功能 你可以在编码端提供GOP大小 但是不建议这样做 主要是延时太高了

**Comment by xia-chu** [comment]
#809
