### ISSUE TITLE
关于jemalloc的疑问

### ISSUE THREAD

**Issue by alexliyu7352** [xia-chu/ZLMediaKit#807]
由于方便部署, 所以我采用静态编译jemalloc到mediaServer.而不是默认的动态库链接.

但是代码里面, 我找不到使用jemalloc来作为内存分配器的相关逻辑.比如redis就是有一系列专门的逻辑来判断使用哪个内存分配器,
并且定义相关的宏.但是在您的代码中我找不到这个逻辑.

所以如何判断启用了jemalloc?或者是具体使用的哪个第三方库在使用jemalloc?如何判断已经启用了.

**Comment by xia-chu** [comment]
ldd一下进程文件 运行时perf top看下都可以证明



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: alexliyu7352 ***@***.***&gt;
发送时间: 2021年4月3日 22:51
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 关于jemalloc的疑问 (#807)

**Comment by alexliyu7352** [comment]
我已经静态编译进去了, 所以用ldd肯定看不到阿.
使用perf top -g -p 来看, 其中使用的__memcmp仍旧是libc提供的阿, 找不到使用jemalloc的地方

**Comment by xia-chu** [comment]
> 
> 
> 我已经静态编译进去了, 所以用ldd肯定看不到阿.
> 使用perf top -g -p 来看, 其中使用的__memcmp仍旧是libc提供的阿, 找不到使用jemalloc的地方

jemalloc会替换malloc和free的函数 但是memcpy不会替换的

**Comment by lystormenvoy** [comment]
> 由于方便部署, 所以我采用静态编译jemalloc到mediaServer.而不是默认的动态库链接.
> 
> 但是代码里面, 我找不到使用jemalloc来作为内存分配器的相关逻辑.比如redis就是有一系列专门的逻辑来判断使用哪个内存分配器, 并且定义相关的宏.但是在您的代码中我找不到这个逻辑.
> 
> 所以如何判断启用了jemalloc?或者是具体使用的哪个第三方库在使用jemalloc?如何判断已经启用了.

你好，请教一下。我对编译不大懂，像jemalloc如何进行静态编译呀。还有openssl是不是也可以静态编译？到时候就不用放so库到目标服务器的lib文件夹里了吧？

**Comment by alexliyu7352** [comment]
修改cmake文件就可以了.

其实你搜索下就明白了.

静态编译ssl
#查找openssl是否安装
set(OPENSSL_USE_STATIC_LIBS TRUE)
find_package(OpenSSL REQUIRED)
if (OPENSSL_FOUND AND ENABLE_OPENSSL)
    message(STATUS "found library:${OPENSSL_LIBRARIES},ENABLE_OPENSSL defined")
    include_directories(${OPENSSL_INCLUDE_DIR})
    add_definitions(-DENABLE_OPENSSL)
    list(APPEND LINK_LIB_LIST OpenSSL::Crypto OpenSSL::SSL)
    if (CMAKE_SYSTEM_NAME MATCHES "Linux" AND OPENSSL_USE_STATIC_LIBS)
        list(APPEND LINK_LIB_LIST dl)
    endif ()
else ()
    message(WARNING "openssl未找到，rtmp将不支持flash播放器，https/wss/rtsps/rtmps也将失效")
endif ()

jemalloc



find_path(JEMALLOC_INCLUDE_DIR
		NAMES jemalloc/jemalloc.h
		)

find_library(JEMALLOC_LIBRARY
		NAMES ${CMAKE_FIND_LIBRARY_PREFIXES}jemalloc_pic${CMAKE_STATIC_LIBRARY_SUFFIX}
		${CMAKE_FIND_LIBRARY_PREFIXES}jemalloc${CMAKE_FIND_LIBRARY_SUFFIXES}
		HINTS ${PC_JEMALLOC_LIBRARY_DIRS}
		)
set(JEMALLOC_INCLUDE_DIRS ${JEMALLOC_INCLUDE_DIR})
set(JEMALLOC_LIBRARIES ${JEMALLOC_LIBRARY})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(JEMALLOC DEFAULT_MSG JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR)

**Comment by lystormenvoy** [comment]
> 修改cmake文件就可以了.
> 
> 其实你搜索下就明白了.
> 
> 静态编译ssl #查找openssl是否安装 set(OPENSSL_USE_STATIC_LIBS TRUE) find_package(OpenSSL REQUIRED) if (OPENSSL_FOUND AND ENABLE_OPENSSL) message(STATUS "found library:${OPENSSL_LIBRARIES},ENABLE_OPENSSL defined") include_directories(${OPENSSL_INCLUDE_DIR}) add_definitions(-DENABLE_OPENSSL) list(APPEND LINK_LIB_LIST OpenSSL::Crypto OpenSSL::SSL) if (CMAKE_SYSTEM_NAME MATCHES "Linux" AND OPENSSL_USE_STATIC_LIBS) list(APPEND LINK_LIB_LIST dl) endif () else () message(WARNING "openssl未找到，rtmp将不支持flash播放器，https/wss/rtsps/rtmps也将失效") endif ()
> 
> jemalloc
> 
> find_path(JEMALLOC_INCLUDE_DIR NAMES jemalloc/jemalloc.h )
> 
> find_library(JEMALLOC_LIBRARY NAMES ${CMAKE_FIND_LIBRARY_PREFIXES}jemalloc_pic${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_FIND_LIBRARY_PREFIXES}jemalloc${CMAKE_FIND_LIBRARY_SUFFIXES} HINTS ${PC_JEMALLOC_LIBRARY_DIRS} ) set(JEMALLOC_INCLUDE_DIRS ${JEMALLOC_INCLUDE_DIR}) set(JEMALLOC_LIBRARIES ${JEMALLOC_LIBRARY})
> 
> include(FindPackageHandleStandardArgs)
> 
> find_package_handle_standard_args(JEMALLOC DEFAULT_MSG JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR)

谢谢，不过我试了一下，还是需要ssl的so文件才能运行
