### ISSUE TITLE
HlsPlayer的BUG

### ISSUE THREAD

**Issue by alexliyu7352** [xia-chu/ZLMediaKit#808]
在拉流hls的时候, 如果拉流速度过慢有时候会造成_ts_list为空, 而_ts_url_cache不为空的情况.
导致会重复的获取m3u8文件,而并不会拉取实际的ts文件.

`
 for (auto &pr : ts_map) {
            auto &ts = pr.second;
            if (_ts_url_cache.emplace(ts.url).second) {
                //该ts未重复
                _ts_list.emplace_back(ts);
                //按时间排序
                _ts_url_sort.emplace_back(ts.url);
            }
        }
`
这里所有的Url都会在cache里面, 因此_ts_list一直为空

**Comment by xia-chu** [comment]
这个会导致什么问题呢？会做无谓的拉取m3u8文件吗？

**Comment by xia-chu** [comment]
这个会导致什么问题呢？会做无谓的拉取m3u8文件吗？

**Comment by alexliyu7352** [comment]
是的, 一直拉m3u8文件, 因为m3u8文件中的url已经在_ts_url_cache中了, 所以不会继续播放.只是会反复拉m3u8文件.

**Comment by xia-chu** [comment]
那m3u8不会更新吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: alexliyu7352 ***@***.***&gt;
发送时间: 2021年4月6日 17:23
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] HlsPlayer的BUG (#808)

**Comment by alexliyu7352** [comment]
的确更新很慢, 这个m3u8每个切片很大.是我调试的时候网络上随便搜索的m3u8的直播, 正好出现了这个问题.

**Comment by alexliyu7352** [comment]
这个情况应该很少, 我现在是做了一个判断.如果不同步就强制同步一次.

主要是不清楚为何_ts_url_cache中有Url, 但是_ts_list却是为空.

理论上应该是同步的才对.

**Comment by xia-chu** [comment]
_ts_list是ts文件地址列表，下载m3u8文件后，会解析出ts文件地址并比对在_ts_url_cache中有没有重复，没有重复才会放入到_ts_list去下载ts文件。

**Comment by xia-chu** [comment]
如果m3u8一直不更新 那么_ts_list会很快就被消费完毕，这个时候zlm就要等待刷新_ts_list列表了，这个时候会去触发下载m3u8文件，如果m3u8文件未更新，那么_ts_list会一直未空，那么zlm会不断重新下载m3u8文件
