### ISSUE TITLE
跨域传输的问题

### ISSUE THREAD

**Issue by alexliyu7352** [xia-chu/ZLMediaKit#809]
其实这个和我之前的一个issues类似的问题, 就是如果跨域拉流或者推流如何保证播放流畅.
因为有需求需要跨国家进行推流和拉流, 但是这样如果服务器网络不好, 比如中美之间, 不走CN2 GIA, 那么推流或者拉流都是卡顿的.
所以我之前提出了那个issues, 想要增加一个跨域所需要的缓存. 

比方说设置跨域延时180秒.
那么也就是要缓存180秒的帧数据, 任何终端播放的时候都是从180秒前进行播放, 这样就至少保证不会出现卡顿.

这两天研究了下您的代码, 做了一些测试, 但是仍旧没办法实现. 

我一开始是顺着PlayerProxy走, 发现拉流的具体逻辑在分别每个player实现里面, 然后根据每隔协议的不一样分别实现拉流并解析成帧.因此我一开始是修改缓存帧的数量, 但是发现这其实没有任何的用途.

后来我继续跟踪, 发现不管哪个协议实现, 最终都是把帧押入到RingBuffer, 并且存储到RingStorage中.

因此, 我尝试修改_RingStorage的write方法, 但是总是有莫名奇妙的问题.请问如何实现这个逻辑呢?

根据您这里的逻辑是遇到关键帧那么就进行缓存, 并且清除掉以前的缓存, 如果缓存的帧数超过最大缓存帧数则也清除掉旧缓存.

这样的目的应该是保证客户端第一帧尽快出画面是否?因为其实只是在环形缓存中缓存了一个GOP而以.

如果要实现我的需求, 这里请问怎么修改比较好呢?

**Comment by alexliyu7352** [comment]
我简单的写了一个测试代码, 这里缓存1个gop改成了10个GOP, 以此来实现跨区域传输的平滑.
因为是简单测试代码,所以随便写了下, 代码比较low不要介意, 大神帮忙看看, 是否这样修改的思路是正确的?
可以达到我说的需求, 跨区域或者跨网络平滑播放的目的?会不会带来其他问题?

`

    void write(T in, bool is_key = true) {
            if (is_key) {
                //遇到I帧，那么移除老数据
    //            _size = 0;
                _f_size = 0;
                _have_idr = true;
    //            _data_cache.clear();
                _size++;
                // 缓存10个GOP
                if (_size > 10) {
                    // 删除掉第一个GOP
                    for (auto i = _data_cache.begin()+1; i != _data_cache.end();) {
                        if(i->first){
                            _data_cache.erase(_data_cache.begin(), i);
                            _size--;
                            break;
                        }
                        i++;
                    }
                }
            }
            int i_size =0;
            for (auto i = _data_cache.begin(); i != _data_cache.end();i++) {
                if(i->first){
                    i_size++;
                }
            }
            WarnL << "缓存帧数[" << _data_cache.size() << "],GOP数量[" << _size <<"], 关键帧数量"<<i_size;
            if (!_have_idr) {
                //缓存中没有关键帧，那么gop缓存无效
                return;
            }
            _data_cache.emplace_back(std::make_pair(is_key, std::move(in)));
            if (++_f_size > _max_size) {
                //GOP缓存溢出，清空关老数据
    //            _data_cache.clear();
                _f_size--;
                if(_f_size<(int)_data_cache.size()){
                    _data_cache.erase(_data_cache.begin()+_f_size, _data_cache.end());
                }
                _f_size = 0;
                _have_idr = false;
            }
        }

`

**Comment by xia-chu** [comment]
如果是超远距离传输 主要是延时高 如果带宽不够 再怎么优化也没用
另外 如果网络不稳定 ，抖动厉害，也不好优化。
你说的这种增加GOP缓存的操作，只能减缓开播时由于网络抖动导致卡顿的问题，
而且这样的副作用明显，会显著提高服务器内存占用和一刀切增加延时，
我的建议是增加超时时间限制，现在zlm的超时时间一般是15秒 你可以调大点，
这样用户网络抖动时，不容易断开链接，并且不影响网络好的用户

**Comment by alexliyu7352** [comment]
感谢大神在繁忙中的回复.是的, 您说的很对, 这样开播时候至少是稳定的, 不会卡顿.
至于延时和内存占用, 如果只是改成2-3个GOP, 应该不会很大的.
我的想法并不是一刀切, 而是增加一个参数, 通过addstreamproxy或者推流的时候可以通过api参数控制Gop缓存数量.
不知道这样是否可以?

您是否需要这个功能?如果需要我可以测试好后提交pr给您. 如果不需要我就自己用.

另外您说的参数是否是Client::kTimeoutMS这个参数?

**Comment by xia-chu** [comment]
你用什么协议播放直播的？我觉得你这种修改进入了歧途

**Comment by alexliyu7352** [comment]
Rtmp, 主要是有些情况下, 拉流或者推流网络会不稳定, 但是播放端至少应该是能尽快出画面并且一开时应该不卡顿.

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/113980163-bbd92600-9878-11eb-81fd-13b0469dcb75.png)
这两个参数调大 能满足你的需求
