### ISSUE TITLE
笔记本电脑推送摄像头视频延迟严重

### ISSUE THREAD

**Issue by zhuqiyun** [xia-chu/ZLMediaKit#811]
推送命令:  ffmpeg -f dshow -i video="Integrated Camera" -vcodec libx264 -f flv rtmp://127.0.0.1/live/test

播放器VLC:    http://127.0.0.1/live/test/hls.m3u8

**Comment by wasphin** [comment]
[怎么测试ZLMediaKit的延时?](https://github.com/xia-chu/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E6%B5%8B%E8%AF%95ZLMediaKit%E7%9A%84%E5%BB%B6%E6%97%B6%EF%BC%9F)
