### ISSUE TITLE
新增HTTP-ts拉流的问题

### ISSUE THREAD

**Issue by alexliyu7352** [xia-chu/ZLMediaKit#812]
我想要新增一个http ts拉流和推流的功能并且完成后提交pr, 目前拉流的功能已经写好了, 也可以正常拉流并且输出给客户端了.
但是有一个问题需要大神帮忙看看.

具体问题就是设备输出的HTTP TS流是一段一段的, 就是可能会输出流7-8秒中, 然后会停几秒, 然后继续再次输出7-8秒流这样的, 我记得有一个朋友之前提交的issues也说类似的这种阶段性输出流的问题, 只是他是推流我这里是拉取设备输出的http ts流.
因此在拉流的时候, 就会触发以下的代码

`

         if (_aliveTicker.elapsedTime() > 3 * 1000 && _totalBodySize < 0 && !_chunkedSplitter) {
                //如果Content-Length未指定 但接收数据超时
                //则认为本次http请求完成
                onResponseCompleted_l();
            }

`

最后回调到void TsPlayer::onResponseCompleted()里.

另外还有一种情况是, 直接触发了EOF错误导致认为流已经拉弯了, 

实际上流并没有拉完, 而我不太想改动您本身的http协议的逻辑, 所以我这里直接触发重新拉流操作.
但是如果重新拉流的时候, 拉到的流会有延时.

举个例子
当前本身拉流到1分30秒, 然后中断了, 重新拉流时候拉到的流却是1分15秒开始的. 这样就导致终端会观看到重复的一段画面.

因此, 我的想法就是判断当前帧缓存最顶部的帧的DTS时间, 然后用来比对, 如果新拉到的流中的帧小于这个时间的那么就直接抛弃掉.

大概代码如下,

重新拉流的时候缓存最后一个帧的DTS

`

       void TsPlayerImp::reConnect() {
              if(!_frame_cache.empty()){
                  last_dts = _frame_cache.rbegin()->first;
              }
          }

`

然后在inputFrame中进行处理如下

`

        //计算相对时间戳
        int64_t dts, pts;
        _stamp[frame->getTrackType()].revise(frame->dts(), frame->pts(), dts, pts);
        // 放弃掉小于缓存中最后一个帧dts的其他帧
        if(last_dts > dts){
            return;
        }
        last_dts = 0;
        //根据时间戳缓存frame
        _frame_cache.emplace(dts, Frame::getCacheAbleFrame(frame));

`

这样处理我发现就算服务器超时断开重联后, 播放并不受到影响, 不会重复播放, 但是新的问题出现了, 
当我用ffplay直接拉流几分钟后会出现错误
ffplay        http://127.0.0.1:8081/proxy/test.live.ts

`

    [http @ 0x7fa960001680] Stream ends prematurely at 28739642, should be 18446744073709551615
    [mpegts @ 0x7fa960000b80] PES packet size mismatch
    [http @ 0x7fa960001680] Stream ends prematurely at 28739642, should be 18446744073709551615
    [h264 @ 0x7fa9604933c0] error while decoding MB 36 37, bytestream -6
    [h264 @ 0x7fa9604933c0] concealing 653 DC, 653 AC, 653 MV errors in B frame
     427.63 A-V:  0.003 fd=   4 aq=    0KB vq=    0KB sq=    0B f=1/1   

`
请问如何解决呢?我希望能完善他并提交给您, 因为还是有部分家用设备是输出Ts流的.

**Comment by alexliyu7352** [comment]
不, 还是会重复播放一段时间画面, 每次重连后.
  if(last_dts > dts)
感觉没什么用阿, 这里需要使用原始时间戳来判断么?不能使用您计算出来的相对时间戳??

另外断开的, 我发现是if (_aliveTicker.elapsedTime() > 3 * 1000 && _totalBodySize < 0 && !_chunkedSplitter) 
这里的3秒等待太少了, 改成15秒就差不多了..

但是我不希望在这里改动, 因为很难判断设备究竟会有多少的断流时间.最好还是自动重联后再次播放.

**Comment by alexliyu7352** [comment]
奇怪,使用原始的dts来判断, 就稳定了许多了..

**Comment by xia-chu** [comment]
http-ts直播拉流应该是稳定的 应该不会持续7~8秒没输出吧？
由于http-ts直播拉流时没有content-length的，所以如果接受超时确实会触发onResponseCompleted_l事件的。
我的建议是http客户端参数在http-ts拉流时做调整，确保http-ts拉流能稳定，
你根据dts丢弃重连时重复的帧我觉得没太大必要，我认为重连时应该注销MediaSource，这样让播放器也重连

**Comment by alexliyu7352** [comment]
播放器重连会看到重复的画面, 而且会音视频不同步.
目前就是卡在这里了, 这个问题其实有些类似ffmpeg的自动重连的参数.
-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1
我这监控流没有在公网, 所以您那没办法测试,
我网上找了一个播放链接, 就是明显的这个问题, 虽然不是监控输出的ts流, 但是问题类似.
http://goodtv.xyz:2052/mthomas/mthomas/2599201?name=.ts
这个也是直接输出ts流的走的CDN.

现在问题就是每隔一段时间, 就会触发onResponseCompleted_l事件, 因此我把参数都调整大了.
但是仍旧会每隔几十秒有底层的socket eof报错,然后触发onDisconnect事件.
我看了socket的代码, 一旦eof报错, 就直接关闭了socket, 然后触发上层err, 最终走到onDisconnect事件中.
然后我在player层开始重新发起http请求链接再次获取数据.结果就非常容易出现画面重复以及音视频不同步问题了.

但是如果我使用ffmpeg拉流, 加了参数-reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1后这类的情况下, 会提示重连, 但是画面不会重复也不会音视频不同步.

`


            read_ret = http_buf_read(h, buf, size);
            if (   (read_ret  < 0 && s->reconnect        && (!h->is_streamed || s->reconnect_streamed) && s->filesize > 0 && s->off < s->filesize)
                || (read_ret == 0 && s->reconnect_at_eof && (!h->is_streamed || s->reconnect_streamed))) {
                int64_t target = h->is_streamed ? 0 : s->off;
  
          if (s->reconnect_delay > s->reconnect_delay_max)
              return AVERROR(EIO);
  
          av_log(h, AV_LOG_INFO, "Will reconnect at %"PRId64" error=%s.\n", s->off, av_err2str(read_ret));
          av_usleep(1000U*1000*s->reconnect_delay);
          s->reconnect_delay = 1 + 2*s->reconnect_delay;
          seek_ret = http_seek_internal(h, target, SEEK_SET, 1);
          if (seek_ret != target) {
              av_log(h, AV_LOG_ERROR, "Failed to reconnect at %"PRId64".\n", target);
              return read_ret;
          }
  
          read_ret = http_buf_read(h, buf, size);
      } else
          s->reconnect_delay = 0;
  
      return read_ret;


`

他这块的代码逻辑如上, 当eof的时候, 判断是否有那些参数, 如果有那么就延时一段时间后再次重新读取.
所以我这里是不是应该在socket底层进行改动?不关闭socket,而是再次延时一段时间尝试继续读取?

**Comment by xia-chu** [comment]
你过段时间重连最好 因为gop缓存都更新了 所以不会有重复的画面的
