### ISSUE TITLE
在跨网域并且同时播放多个hls串流时Cookie变动问题

### ISSUE THREAD

**Issue by EGK-ZongYan** [xia-chu/ZLMediaKit#813]
目前我们这边有一个使用情境是需要让客人的网站直接播放hls url，但我们在测试时发现如果同时播放多个串流，下一次再取得串流时cookie会变换成新的值(如下图)，会导致on_play的web hook事件不断被触发。

![image](https://user-images.githubusercontent.com/54010679/113844955-9809d780-97c7-11eb-893c-8bfcfbbbde5d.png)

这个状况目前我们测试：
1.在同一个网域底下"播放两个以上的串流"不会有这个问题发生
2.在不同网域底下如果只播放单一串流也不会造成cookie变换成新的值

这里想跟您请教一下我们能朝哪个方向来检查这个问题

**Comment by xia-chu** [comment]
这个是浏览器限制导致的 在跨域时 浏览器会限制cookie追踪

**Comment by EGK-ZongYan** [comment]
不好意思，今天我们有在做测试发现在同网域底下播四个串流时，会有两组串流Cookie是固定的，另外两组的Cookie会一直变动，之前播两个串流还没有看到这个问题。

**Comment by EGK-ZongYan** [comment]
目前我们会朝向验证由自己伺服器去做，也想请教大神这边看还有什么方向能够解决这个问题。

**Comment by xia-chu** [comment]
不跨域应该不会有这个问题的
还有，如果cookie追踪用不了 可以用url参数做追踪。
代码在这：
![图片](https://user-images.githubusercontent.com/11495632/113963210-c933e780-985b-11eb-9f96-4859966178e5.png)
你可以每次播放hls时url参数的uid都不一样，这样就能标记为一次hls播放了。你可以稍微修改了uid的获取方法，
我现在是根据全部的url参数当做uid的，你可以从url参数中提取uid

**Comment by EGK-ZongYan** [comment]
了解了!! 我們這邊會朝這個方向實作看看，非常感谢!!

**Comment by EGK-ZongYan** [comment]
我们这边已解决这个问题了，非常感谢大神帮助!! 其实我们有在Url上带参数(token key)但每个串流带的都是一样的，这也导致会有此问题发生，现在除了原本的参数外也加上其他资讯让他变成一组唯一的uid。
