### ISSUE TITLE
m3u8 extinf打得不够准确的问题

### ISSUE THREAD

**Issue by HuHeng** [xia-chu/ZLMediaKit#816]
复现步骤
1 ffmpeg -re -i qiu-10min-25fps-gop50.flv -c copy -f flv rtmp://localhost/live/xx
2 查看生成的m3u8， 每个ts的extinf标签显示ts的duration位1.96，正常应该是2s。

分析：
duration计算使用  auto seg_dur = _last_timestamp - _last_seg_timestamp;

但是_last_timestamp更新是在addNewsegment之后，所以最后一帧的时长没算上。

void HlsMaker::inputData(void *data, size_t len, uint32_t timestamp, bool is_idr_fast_packet) {
    if (data && len) {
        if (is_idr_fast_packet) {
            //尝试切片ts
            addNewSegment(timestamp);
        }
        if (!_last_file_name.empty()) {
            //存在切片才写入ts数据
            onWriteSegment((char *) data, len);
            _last_timestamp = timestamp;
        }
    } else {
        //resetTracks时触发此逻辑
        flushLastSegment(true);
    }
}

这个问题不大，但是如果是直播hls直接存储作为点播m3u8的话，这个标签不准确会使得整个点播m3u8的时长出现较大偏差。

**Comment by xia-chu** [comment]
你说的有道理 目前zlm是根据服务器系统时间戳生成extinf标签的 这个确实可能存在跟数据实际时间戳长度不一致的情况

**Comment by xia-chu** [comment]
你们hls用于录制吗

**Comment by HuHeng** [comment]
你的实现应该是音视频的时戳,而不是服务器系统时戳吧.否则不会刚好都是1.96s,刚好差了最后一帧的时长,实际应该是2s才对.因为我的源流就是2s一个I帧.上面那个inpudata的timestamp参数应该就是音视频时戳.如果是服务器时戳,那就太过分了啊.

我目前并没有使用这个项目,只是在调研阶段,同时也是学习一下.

srs的hls时戳是音视频一起用最大的减去最小的,这样更加不准,毕竟hls流不是只看一个ts,它是一整个流,有上下文关系.

nginxrtmp实现是准确的,ffmpeg切片hls这个标签也是准确的.阿里云的直播服务切片也是准确的.

**Comment by xia-chu** [comment]
我忘记了 但是不管哪种方法 只要确保没有累计误差就行，至于每个切片多少几十毫秒 其实关系不大 只要确保这些值累加等于时间戳量即可
