### ISSUE TITLE
ZLMediaKit流媒体/index/api/addFFmpegSource 参数src_url问题

### ISSUE THREAD

**Issue by bohuashan** [xia-chu/ZLMediaKit#821]
比如大华摄像头的SRTP地址是这样的：rtsp://admin:admin123@10.10.68.10:554/cam/realmonitor?channel=1&subtype=0
那么这个接口调用就失败，我想问一下这个参数里面包含？和& =特殊字符，传参的时候需要怎么处理，ZLMediaKIT才能解析，这是一个参数，不是把问号后面的当做参数来解析

**Comment by xia-chu** [comment]
如果url作为http的参数 那么你就要符合http的规范 你需要url转义
