### ISSUE TITLE
[BUG]添加5520*2400鹰眼拉流代理画面不动

### ISSUE THREAD

**Issue by athnkk** [xia-chu/ZLMediaKit#823]
群主你好：
我使用ZL添加鹰眼摄像机拉流代理，码流比较大，相关媒体信息如下：
![图片](https://user-images.githubusercontent.com/29155035/114486574-be54ca80-9c40-11eb-99a8-7ff2b92df871.png)
ZL报如下错误：
![图片](https://user-images.githubusercontent.com/29155035/114486890-3622f500-9c41-11eb-832d-6f4661583239.png)

拉流后使用vlc播放画面卡着不动，我修改RtpReceiver.h文件kMin=100了，并没有解决，是否需要修改socket缓冲区大小tcp_wmem和tcp_rmem，可能是哪边出现问题，能否提供一下思路？是播放器问题还是linux需要修改参数。
vlc消息报错如下：
![图片](https://user-images.githubusercontent.com/29155035/114487274-e4c73580-9c41-11eb-9754-4e2b73008be6.png)

**Comment by xia-chu** [comment]
你这个是UDP推流28181流对吧？

**Comment by athnkk** [comment]
不是，就是通过addStreamProxy添加拉流代理，走得是tcp得

**Comment by athnkk** [comment]
拉得rtsp流

**Comment by xia-chu** [comment]
你这个分辨率有点高 不过按道理 也不至于这样 因为你是tcp拉流 建议wireshark抓包分析下 wireshark可以分析rtp丢包情况的

**Comment by xia-chu** [comment]
你也可以把rtsp暴露到公网 我测试下

**Comment by athnkk** [comment]
rtsp是内网地址，就是想通过zl做一层拉流代理的，我抓个报wireshark看下吧，看下rtp丢包情况
