### ISSUE TITLE
[BUG] getSnap截图API的expire_sec怎么传都是返回之前的图

### ISSUE THREAD

**Issue by 18285160741** [xia-chu/ZLMediaKit#824]
**bug现象**
- getSnap截图API的expire_sec不管传多少都是返回之前的图
![image](https://user-images.githubusercontent.com/37412616/114537745-24634100-9c85-11eb-9874-7acaf5704be9.png)

![image](https://user-images.githubusercontent.com/37412616/114537608-fd0c7400-9c84-11eb-8132-023b2ecbba78.png)

![image](https://user-images.githubusercontent.com/37412616/114537819-3b099800-9c85-11eb-82c4-2033d7f2069d.png)

**操作系统环境**
测试地址如下：
http://39.99.188.174:8282/index/api/getSnap?timeout_sec=5&expire_sec=0&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&url=http://39.99.188.174:8282/rtp/gb_play_34020000001320000001_34020000001320000001.live.mp4

**Comment by xia-chu** [comment]
服务器是Linux还是windows的？

**Comment by xia-chu** [comment]
如果截图失败 就会一直返回之前的截图的

**Comment by 18285160741** [comment]
是Linux的, Ubuntu 18 。而且最近直播也是很卡、之前都是正常的（我用的wvp-GB28181-pro来对接的），不知道为啥

**Comment by 18285160741** [comment]
> 服务器是Linux还是windows的？

是Linux的, Ubuntu 18 。
而且最近直播也是很卡、之前都是正常的（我用的wvp-GB28181-pro来对接的），甚至有时候播放不了（点播失败，状态码400 Bad Request），不知道为啥

**Comment by xia-chu** [comment]
哦 奇怪了 你截图可以换其他协议试试 比如http-ts

**Comment by 18285160741** [comment]
> 哦 奇怪了 你截图可以换其他协议试试 比如http-ts

我昨天挨个试了一下午。各种奇怪的现象。比如rtsp截图返回来的图片一张比一张模糊，现在不管用哪种协议都直接返回默认的logo图了。泪奔

**Comment by xia-chu** [comment]
你可以看看FFmpeg的日志

**Comment by 1120665184** [comment]
我也遇到了相同的问题

**Comment by xia-chu** [comment]
截图失败 可以分析FFmpeg的日志啊 或者zlm的日志。你这里也不提供这些信息 我也无能为力啊。
