### ISSUE TITLE
[BUG] 视频流播放卡顿

### ISSUE THREAD

**Issue by kuaidou** [xia-chu/ZLMediaKit#825]
**bug现象**
- 使用C/C++ API input的视频流， 从rtsp或者http-flv播放时每秒有一个明显的卡顿

https://user-images.githubusercontent.com/20410578/114662092-b4a79180-9d2a-11eb-9f6e-8e71c2a0dfdb.mp4

> 补充说明1：使用其他的rtsp库播放的视频流没有卡顿  
> 补充说明2：使用OBS rtmp推流到ZLMediaSerevr，再使用VLC播放rtsp没有卡顿

**bug产生时的使用场景**
- 使用rtsp server和http server

**bug是否可以复现，怎么复现**
- 在海思板子上，将编码的流input到Device Channel里，然后通过vlc进行播放

**zlm代码git commit hash值**
- a0fc494ee3a1d1d66dd9ed5dfd2cea8525171d13

**操作系统环境**
- 海思3559A aarch64 linux

**Comment by xia-chu** [comment]
你这个bug issue做的很规范 谢谢，希望大家以后都想你一样
你input音视频的时间戳是0还是你自己生成的？

**Comment by wasphin** [comment]
> 你这个bug issue做的很规范 谢谢，希望大家以后都想你一样

可以添加成 issue 模板这样?

**Comment by xia-chu** [comment]
是做的issue模板的

> 
> 
> > 你这个bug issue做的很规范 谢谢，希望大家以后都想你一样
> 
> 可以添加成 issue 模板这样?

**Comment by wasphin** [comment]
之前遇到过的情况是, 编码器做了码流平滑, 导致向外输出时帧频不均匀, 播放端如果不加缓冲效果就类似上面视频中的样子.

**Comment by xia-chu** [comment]
嗯 那就是时间戳没打好，时间戳还是得在编码前就打好的 编码后再打 就可能出现上述问题

**Comment by kuaidou** [comment]
> 你input音视频的时间戳是0还是你自己生成的？   

时间戳是0

**Comment by kuaidou** [comment]
> 嗯 那就是时间戳没打好，时间戳还是得在编码前就打好的 编码后再打 就可能出现上述问题

这个时间戳是如何自己生成，我之前通过传入海思的pts，rtsp视频流都无法播放

**Comment by xia-chu** [comment]
毫秒就行了 你输入系统时间戳的毫秒增量就行

**Comment by xia-chu** [comment]
时间戳是0时 zlm内部会生成时间戳 但是可能编码器输出不平滑 就会像你看到的这样

**Comment by kuaidou** [comment]
好的，谢谢。我试一下

**Comment by xia-chu** [comment]
你这个问题其实不属于bug

**Comment by kuaidou** [comment]
嗯，我测试完，如果可行可以把bug标签去掉

**Comment by kuaidou** [comment]
其实还有个问题，播放这个视频，rtsp的延迟在2-3秒左右。如何优化这方面，将延迟降低到1秒内。

之前通过OBS推流测试MediaServer延迟大概在500ms

**Comment by xia-chu** [comment]
你可以看下wiki 了解下延时是怎么回事

**Comment by kuaidou** [comment]
测试了一下，使用海思的视频流的pts，rtsp播放卡顿明显缓解。但是仍然有如下问题：

1. http-flv播放时仍然出现明显卡顿，和之前的一致。是否http-flv也是需要设置pts，这个在哪里设置  
2. input的pts时间戳，如果是从一个比较大的数传入，rtsp播放会卡住，只能播放第一帧视频

**Comment by xia-chu** [comment]
你如果不能明白和搞定时间戳 就会这样 我上面跟你讲了怎么生成时间戳

**Comment by kuaidou** [comment]
> 你如果不能明白和搞定时间戳 就会这样 我上面跟你讲了怎么生成时间戳

我现在是使用一个增量的时间戳啊，放入inputH264的pts，使用这个播放rtsp现在不卡顿了，但是使用http-flv播放还是之前的那个样子。我不明白这个和生成时间戳的方式有什么关系？

**Comment by kuaidou** [comment]
> 你如果不能明白和搞定时间戳 就会这样 我上面跟你讲了怎么生成时间戳

我现在是使用一个增量的时间戳啊，放入inputH264的pts，使用这个播放rtsp现在不卡顿了，但是使用http-flv播放还是之前的那个样子。我不明白这个和生成时间戳的方式有什么关系？

**Comment by xia-chu** [comment]
接口不是有dts和pts吗？ 你只输入pts？
你有b帧吧？

**Comment by kuaidou** [comment]
我现在dts是0，dts和pts可以是一样的吗？

**Comment by xia-chu** [comment]
如果有B帧就不行 rtsp能播放的原因是 rtsp只需要pts就行，但是flv不一样，他两者都要

**Comment by kuaidou** [comment]
好的，感谢大神百忙之中抽出时间回答我的问题。将dts赋值后，问题解决。谢谢
