### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cylyl** [xia-chu/ZLMediaKit#826]
**Can't compile**
- Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container 3ae55410e6ec
 ---> 74edcab96afe
Step 11/17 : RUN mkdir -p /opt/media
 ---> Running in a127b68a2463
Removing intermediate container a127b68a2463
 ---> 845a95358b8b
Step 12/17 : WORKDIR /opt/media
 ---> Running in 1eaeac2b9e49
Removing intermediate container 1eaeac2b9e49
 ---> a74dc4d63d11
Step 13/17 : RUN git clone --depth=1 https://github.com/xiongziliang/ZLMediaKit &&     cd ZLM
 ---> Running in 49cdfdd147c9
Cloning into 'ZLMediaKit'...
Submodule 'ZLToolKit' (https://gitee.com/xia-chu/ZLToolKit) registered for path '3rdpart/ZLTo
Submodule '3rdpart/media-server' (https://gitee.com/xia-chu/media-server) registered for path
Cloning into '3rdpart/ZLToolKit'...
fatal: unable to access 'https://gitee.com/xia-chu/ZLToolKit/': Failed to connect to gitee.co
fatal: clone of 'https://gitee.com/xia-chu/ZLToolKit' into submodule path '3rdpart/ZLToolKit'
The command '/bin/sh -c git clone --depth=1 https://github.com/xiongziliang/ZLMediaKit &&    se/' returned a non-zero code: 128

**Build**
- build_docker_images.sh

**bug是否可以复现，怎么复现**
- build_docker_images.sh

**zlm代码git commit hash值**
- 5b7974a522abceba6bc7760ea33de3b94ef04434

**操作系统环境**
- CentOS 8
- AMD Ryzen

**Comment by xia-chu** [comment]
用中文跟你交流吗还是英文？
Communicate with you in Chinese or English?

**Comment by cylyl** [comment]
中文也可以

**Comment by xia-chu** [comment]
你是不是挂vpn了？ 为什么访问 gitee.com 访问不了？

**Comment by cylyl** [comment]
可以访问 gitee.com !
我认为只是那个项目不向公众开放？

Cloning into 'ZLMediaKit'...
Submodule 'ZLToolKit' (https://gitee.com/xia-chu/ZLToolKit) registered for path '3rdpart/ZLToolKit'
Submodule '3rdpart/media-server' (https://gitee.com/xia-chu/media-server) registered for path '3rdpart/media-server'
Cloning into '3rdpart/ZLToolKit'...
fatal: unable to access 'https://gitee.com/xia-chu/ZLToolKit/': Failed to connect to gitee.com port 443: Connection timed out
fatal: clone of 'https://gitee.com/xia-chu/ZLToolKit' into submodule path '3rdpart/ZLToolKit' failed
The command '/bin/sh -c git clone --depth=1 https://github.com/xiongziliang/ZLMediaKit &&     cd ZLMediaKit && git submodule update --init --recursive &&     mkdir -p build release/' returned a non-zero code: 128
[x@docker ZLMediaKit]$ bash build_docker_images.sh ^C
[x@docker ZLMediaKit]$ telnet gitee.com 443
Trying 154.213.2.253...                                                                      
Connected to gitee.com.                                                                      
Escape character is '^]'.                                                                    
^]                                                                                           
telnet> quit                                                                                 
Connection closed.

**Comment by cylyl** [comment]
Problem solved!

Scanning dependencies of target MediaServer
[ 98%] Building CXX object server/CMakeFiles/MediaServer.dir/FFmpegSource.cpp.o
[ 98%] Building CXX object server/CMakeFiles/MediaServer.dir/Process.cpp.o
[ 99%] Building CXX object server/CMakeFiles/MediaServer.dir/System.cpp.o
[ 99%] Building CXX object server/CMakeFiles/MediaServer.dir/WebApi.cpp.o
[ 99%] Building CXX object server/CMakeFiles/MediaServer.dir/WebHook.cpp.o
[100%] Building CXX object server/CMakeFiles/MediaServer.dir/main.cpp.o
[100%] Linking CXX executable ../../release/linux/Release/MediaServer
[100%] Built target MediaServer
Removing intermediate container b318b20a0b9d
 ---> 329f9b9e3287
Step 16/17 : ENV PATH /opt/media/ZLMediaKit/release/linux/Release/:$PATH
 ---> Running in 720ddd413099
Removing intermediate container 720ddd413099
 ---> 96237cd39f01
Step 17/17 : CMD MediaServer
 ---> Running in b8a90db21f06
Removing intermediate container b8a90db21f06
 ---> 6e963e6979a6
Successfully built 6e963e6979a6
Successfully tagged gemfield/zlmediakit:20.04-devel-ubuntu16.04
