### ISSUE TITLE
[技术咨询]Auto close stream when nobody played

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#828]
Hi,

How to enable this function: "Auto close stream when nobody played."

![ảnh](https://user-images.githubusercontent.com/59004953/114855557-4ccb7680-9e10-11eb-95c5-45ee081cf1b7.png)

**Comment by xia-chu** [comment]
When nobody play the stream, zlmediakit will send http request to your server, if your server response `close`, zlmediakit will close this stream.

This is the config file:
```ini
[hook]
# enable http hook event
enable=1
# set the url of your server, you can response `close` to close stream
on_stream_none_reader=https://127.0.0.1/index/hook/on_stream_none_reader
```  

This is the hook of `on_stream_none_reader`:
```http
POST /index/hook/on_stream_none_reader HTTP/1.1
Accept: */*
Accept-Language: zh-CN,zh;q=0.8
Connection: keep-alive
Content-Length: 98
Content-Type: application/json
Host: 127.0.0.1
Tools: ZLMediaKit
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

{
   "mediaServerId" : "your_server_id",
   "app" : "live",
   "schema" : "rtmp",
   "stream" : "obs",
   "vhost" : "__defaultVhost__"
}
```

You can response like this:
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 37
Content-Type: application/json; charset=utf-8
Date: Fri, Sep 20 2019 08:51:23 GMT
Keep-Alive: timeout=10, max=100
Server: ZLMediaKit-4.0

{
   "close" : true, # close or not
   "code" : 0
}
```

**Comment by pubpy2015** [comment]
Thanks,

In request i am seeing: "schema" : "rtmp", so it is nobody view stream using rtmp or nobody for all protocols ?
How long (seconds, miliseconds) from nobody played to ZLMediaKit send hook event ?

**Comment by xia-chu** [comment]
For all protocols, and "rtmp" is the protocol last played.
This is the config:
```ini
[general]
streamNoneReaderDelayMS=20000
```

**Comment by pubpy2015** [comment]
Thank you very much
