### ISSUE TITLE
[技术咨询] addFFmpegSource和addStreamProxy的区别

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#829]
**咨询的功能模块**
- MediaServer支持的HTTP API

**咨询的具体内容和问题**
- addFFmpegSource和addStreamProxy都可以动态拉流至流媒体服务器，请问他们各自的应用场景是什么？

**Comment by xia-chu** [comment]
应用场景不一样 ffmpeg拉流支持各种协议和编码 也可以转卖，但是性能差

内置拉流性能好，但是只支持rtsp rtmp hls协议，编码格式也有限
