### ISSUE TITLE
[技术咨询]录像回放NVR以2、4、8倍的速率发送录像流经过ZLM，以hls访问，2、4、8倍都会播放过程中一顿正常又一顿的情况

### ISSUE THREAD

**Issue by sucuiping** [xia-chu/ZLMediaKit#830]
录像回放NVR以2、4、8倍的速率发送录像流经过ZLM，以hls访问，2、4、8倍都会播放过程中一顿正常又一顿的情况，1倍是正常的；zlm运行在CentOS7.6上面
预期效果：任何速率都能正常预览

**Comment by xia-chu** [comment]
倍数播放是需要播放器配合的，倍数的前提是，必须传送数据速度加倍，时间戳也得加倍，如果有音频，时间戳加倍也没用。
如果你能同时满足传送数据速度加倍、时间戳加倍，且没有音频，那么播放器应该能正常加倍播放，否则大概率不能。

**Comment by zhang2349** [comment]
测试发现 rtp倍速推送 用rtsp播放 用ffmpeg库接收解码 发现pts会突然往回跳 类似 1 2 3 4 5 6 7 8 9 10  5 6 7 8 9 10 5 6 7 8 9 10


用httpflv播放 就不会往回跳 如果 往前定位了 就是把前面的流又重新发 httpflv的pts 还是往后走的 不会跳前面去

**Comment by xia-chu** [comment]
rtsp跟flv不一样 rtsp只有pts 没dts，flv两者都有。你推流给zlm，是不允许时间戳回退的，zlm会做处理的

**Comment by xia-chu** [comment]
你倍数推流 你看zlm录制的mp4或hls能不能正常播放，用FFmpeg播放倍速的rtsp没参考性，因为这本来就不符合常规

**Comment by zhang2349** [comment]
从播放效果上看 画面都倍速的 回退 画面也是回退的
就是根据pts显示进度条不对劲

对时间戳处理大概在代码的哪个部分

**Comment by xia-chu** [comment]
stamp.cpp



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhang2349 ***@***.***&gt;
发送时间: 2021年4月21日 16:59
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] [技术咨询]录像回放NVR以2、4、8倍的速率发送录像流经过ZLM，以hls访问，2、4、8倍都会播放过程中一顿正常又一顿的情况 (#830)

**Comment by sucuiping** [comment]
> 倍数播放是需要播放器配合的，倍数的前提是，必须传送数据速度加倍，时间戳也得加倍，如果有音频，时间戳加倍也没用。
> 如果你能同时满足传送数据速度加倍、时间戳加倍，且没有音频，那么播放器应该能正常加倍播放，否则大概率不能。
对应的播放器也是按照快进的倍数播放的，但是hls还是会出现播放一下就顿，感觉是流播放完了等下一个周期的流

**Comment by xia-chu** [comment]
播放器是你们自己做的吗? 如果没音频 那么不应该这样的

**Comment by zhang2349** [comment]
我测试就是直接用的ffmpeg的代码 音频应该是有的G711

**Comment by xia-chu** [comment]
你确定你时间戳也加倍了吗

**Comment by zhang2349** [comment]
是的 录像感觉像是他都已经打好时间戳存着的
倍速只是 不同的发送速度
有时候4倍他来不及发送的时候 实际是没到那个速度就3.几的样子
最终存下来的东西都是一样的

**Comment by yuwei1234** [comment]
大神，问下浏览器中实现回放倍数播放，有什么方案没，我们目前也是4倍的时候出现卡顿

**Comment by yuwei1234** [comment]
> 录像回放NVR以2、4、8倍的速率发送录像流经过ZLM，以hls访问，2、4、8倍都会播放过程中一顿正常又一顿的情况，1倍是正常的；zlm运行在CentOS7.6上面 预期效果：任何速率都能正常预览

你那边解决了吗？用的什么方案呢，我现在也遇到这种问题

**Comment by sucuiping** [comment]
页面访问流的方式修改为ws和http-flv是正常的，我这边只是切换了流的播放方式










在 2024-12-09 13:15:21，"Mr Y" ***@***.***> 写道：

录像回放NVR以2、4、8倍的速率发送录像流经过ZLM，以hls访问，2、4、8倍都会播放过程中一顿正常又一顿的情况，1倍是正常的；zlm运行在CentOS7.6上面 预期效果：任何速率都能正常预览

Has it been resolved on your end? What solution did you use, I'm also encountering this issue now

录像回放NVR以2、4、8倍的速率发送录像流经过ZLM，以hls访问，2、4、8倍都会播放过程中一顿正常又一顿的情况，1倍是正常的；zlm运行在CentOS7.6上面 预期效果：任何速率都能正常预览

你那边解决了吗？用的什么方案呢，我现在也遇到这种问题

TRANS_BY_GITHUB_AI_ASSISTANT
