### ISSUE TITLE
[技术咨询]关于添加Track等待时间的问题

### ISSUE THREAD

**Issue by chenxihai** [xia-chu/ZLMediaKit#831]
程序添加Track，最多添加2个Track，如果只添加视频Track，需要等待5秒（Max_WAIT_MS_ADD_TRACK）才能准备好，也就是不添加音频，至少需要5秒才能打开视频画面。如果同时添加音视频Track，但是没有（AAC）音频输入，至少需要等待10秒（MAX_WAIT_MS_READY）,等待时间更长，大佬们有没有好的建议，减少等待时间，是不是只能修改MediaSink.cpp的参数？修改这个两个参数是否会带来的问题？

**Comment by xia-chu** [comment]
5秒改成2或三可以的 10秒那个一般不会出现 出现说明流不规范



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenxihai ***@***.***&gt;
发送时间: 2021年4月19日 11:31
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] [技术咨询]关于添加Track等待时间的问题 (#831)

**Comment by chenxihai** [comment]
好的，谢谢。现场很多摄像头只有视频，不需要音频，打开画面等待时间长，用户感觉不是很好

**Comment by xia-chu** [comment]
什么协议的？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenxihai ***@***.***&gt;
发送时间: 2021年4月19日 12:18
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] [技术咨询]关于添加Track等待时间的问题 (#831)





 
好的，谢谢。现场很多摄像头只有视频，不需要音频，打开画面等待时间长，用户感觉不是很好

**Comment by chenxihai** [comment]
我使用的是SDK取流，分解出264/265，通过inputFrame方式推流，所以在取流之前初始化video/audio通道，摄像头一般没有音频流（少数需要对讲的才有）

**Comment by xia-chu** [comment]
如果你确定没有更多的track 应该调用mk_media_init_complete接口加快注册速度

**Comment by chenxihai** [comment]
好的，谢谢老大！
