### ISSUE TITLE
[技术咨询]如何自定义文字内容和显示位置

### ISSUE THREAD

**Issue by 18285160741** [xia-chu/ZLMediaKit#832]
**咨询的功能模块**
- 如何自定义文字内容和显示位置

**咨询的具体内容和问题**
- 想要自定义视频上的字幕内容，和显示位置。包括录制和截图都能看到对应的文字。
- 可以的话、希望大佬指点迷津。谢谢

**Comment by xia-chu** [comment]
这个最好在编码端或播放器端做，在服务器端做要转码的，性能开销很大

**Comment by 18285160741** [comment]
> 这个最好在编码端或播放器端做，在服务器端做要转码的，性能开销很大

好的， 谢谢
