### ISSUE TITLE
[功能请求] 兼容交通部 JT / T 1078标准

### ISSUE THREAD

**Issue by swwheihei** [xia-chu/ZLMediaKit#836]
**描述该功能的用处，可以提供相关资料描述该功能**
交通部2016年发布了《JT/T 1078-2016 道路运输车辆卫星定位系统-视频通信协议》，其中也使用RTP封装视频流，但对其格式进行了扩展增加了SIM卡等信息，导致无法使用ZLM进行协议转换。
我可以提供相关标准的PDF文档。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
希望ZLM能够自动识别出该协议，并支持转换成标准的RTSP\RTMP等协议

**Comment by xia-chu** [comment]
内部版本已经支持了 不便开源
