### ISSUE TITLE
[技术咨询]对于含有G7221格式的音频，拉流rtsp并代理失败，如何做到对于不支持的格式直接跳过

### ISSUE THREAD

**Issue by pzhu10** [xia-chu/ZLMediaKit#838]
**咨询的功能模块**
- zlmediakit的PlayerProxy相关功能

**咨询的具体内容和问题**
对于含有G7221格式的音频，拉流rtsp并代理失败，后台会报暂不支持暂不支持该sdp:G7221的错误
如何做到对于不支持的音频格式直接跳过，只转发视频流即可
![image](https://user-images.githubusercontent.com/11349256/115519212-92c68580-a2bb-11eb-9454-5bc4999ef6a9.png)

大神，求指导~

**Comment by Dw9** [comment]
我觉得你需要换个思路会更简单一点，推流端禁止推音频 或者 播放器 禁止播音频。
暂不支持该sdp:G7221 是说这个track不能转换到其他协议，并不是错误。 程序仍会转发rtsp数据...

**Comment by Dw9** [comment]
让作者“大费周章”的去禁止音频转发不是开玩笑嘛

**Comment by xia-chu** [comment]
是的 这个track无法转协议 会被忽略，但是本协议还是照常代理的，完全正常的
