### ISSUE TITLE
RTSP MJPEG [功能请求]

### ISSUE THREAD

**Issue by xno-ai** [xia-chu/ZLMediaKit#839]
Factory.cpp:101 getTrackBySdp | 暂不支持该sdp:JPEG 
像行车记录仪等大量低端视频芯片只有MJPEG格式编码，请问有计划添加MJPEG的支持吗？
RTSP推MJPEG流，复解成HLS等.

**Comment by xia-chu** [comment]
flv应该是不支持mjpeg的 而且flv也要转换成mp4给浏览器播放 flv.js和浏览器应该都不支持mjepg 三条拦路虎 你就别想了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XNO ***@***.***&gt;
发送时间: 2021年4月23日 09:39
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] RTSP MJPEG [功能请求] (#839)

**Comment by xno-ai** [comment]
MJPEG 转HLV 可以吗？

**Comment by xia-chu** [comment]
什么叫hlv?



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XNO ***@***.***&gt;
发送时间: 2021年4月23日 14:32
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] RTSP MJPEG [功能请求] (#839)
