### ISSUE TITLE
[技术咨询] URL鉴权问题

### ISSUE THREAD

**Issue by JoyseeKing** [xia-chu/ZLMediaKit#840]
我们使用的早期版本的zlm  推流鉴权使用 rtsp://xxxx/publish?k=xxxx 这种形式  最近使用过程中在发现一些问题后故更新了新版本发现这种形式出问题了  推流会失败  请问现在的url参数鉴权如何实现

**Comment by JoyseeKing** [comment]
现在加参数推流后 是如下的ERROR：RTSP推流器(__defaultVhost__/live/675779209/a8QginmVGgupl12Wwajy000000/publish)断开:no such track with control url

**Comment by xia-chu** [comment]
能否提供下rtsp抓包文件

**Comment by JoyseeKing** [comment]
我一共记录了两个抓包文件  error中是推流url末尾带?k=xxxx推流的抓包   ok中是不加参数的抓包

[cap.zip](https://github.com/xia-chu/ZLMediaKit/files/6371217/cap.zip)

**Comment by JoyseeKing** [comment]
> 能否提供下rtsp抓包文件

请问我这边推流链接有问题吗

**Comment by Dw9** [comment]
先把抓包软件打开，在推流 得抓到rtsp交互的过程啊。

**Comment by JoyseeKing** [comment]
> 这个抓包不对啊 你们没rtsp的抓包

![image](https://user-images.githubusercontent.com/33854060/116497604-5ce85900-a8da-11eb-930b-325b75f546f5.png)
rtsp流应该是没问题的  不加鉴权不带参数是能推上去 只是带参数之后就推流端报这个错  我不太理解你所说的抓rtsp的包是什么意思 原来那个包是在zlm端抓的包 监听的端口就是rtsps 拉流的端口  这次我在本地复现了下 分别在本地和zlm端抓了包 你看看对不对
[caps.zip](https://github.com/xia-chu/ZLMediaKit/files/6396065/caps.zip)

**Comment by Dw9** [comment]
看了一下抓包流程 服务器在setup的时候校验不通过抛出异常@JoyseeKing 
大佬，在setup的解析的时候由于现在去掉了“？“之后的所有字段 streamid信息丢失.导致在getTrackIndexByControlUrl校验不通过。 @xia-chu

**Comment by Dw9** [comment]
![image](https://user-images.githubusercontent.com/36155473/116520906-e9f4d780-a905-11eb-9d6c-eecc87f9224f.png)
我简单加了几句 可以通过，但不知道会不会在其他地方有问题

**Comment by xia-chu** [comment]
你这样改不行的 很大问题

**Comment by xia-chu** [comment]
能否把rtsp url暴露公网 可以用frp暴露 我测试并修复下

**Comment by JoyseeKing** [comment]
> 能否把rtsp url暴露公网 可以用frp暴露 我测试并修复下

我本地测试的  公网上的版本回退了  你稍等下我改一下版本

**Comment by JoyseeKing** [comment]
> 能否把rtsp url暴露公网 可以用frp暴露 我测试并修复下
公网地址和端口已发送邮箱

**Comment by xia-chu** [comment]
你给的url播放返回401

**Comment by JoyseeKing** [comment]
> 你给的url播放返回401
大佬 我今天又在你邮箱发了一个地址

**Comment by JoyseeKing** [comment]
大佬不知道你有没有收到邮件   这个是推流RTSP出现的问题不是播放的问题 我看您那边操作的日志是播放这个URL   再细致描述一下问题吧  当 RTSP推流带?后边加参数 会报解析参数失败的  RTMP推流不会出现这个问题
