### ISSUE TITLE
[技术咨询] rtsp player receive rtp timeout

### ISSUE THREAD

**Issue by hh-kai** [xia-chu/ZLMediaKit#841]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
rtsp player

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
rtsp player打开的rtsp流，因为不确定什么时候会有数据，所以我设置了media_timeout_ms值很大，确保不超时，但是因为没数据，还是会触发 end of file 异常，会话被关闭，我想让会话一直保存，无论有没有数据，可以通过什么接口修改吗(因为使用的静态库)

**Comment by xia-chu** [comment]
你是rtsp拉流吗？对方rtsp服务器这么奇怪？还能很长时间才给你数据吗

**Comment by hh-kai** [comment]
是rtsp拉流 发送数据是不确定的。改了rtp receive timeout超时 会触发end of file 还是会主动shutdown

**Comment by xia-chu** [comment]
zlm的播放器参数要改源码才行的 在这：
![图片](https://user-images.githubusercontent.com/11495632/116384028-0a5f5c00-a84a-11eb-8002-c2d50f05edbf.png)

**Comment by xia-chu** [comment]
> 这个有考虑添加到config.ini配置项中吗？是可以手动改大这个超时项的吧。是否改大会引入其他问题？

这个配置没暴露在配置文件，由于这个是客户端的相关配置 所以更倾向于用户自己调api修改 而不是通过配置文件
