### ISSUE TITLE
[BUG]调用接口传入摄像头视频流服务崩溃

### ISSUE THREAD

**Issue by AsuKa1989** [xia-chu/ZLMediaKit#844]
**bug现象**
- 在ARM开发板上运行ZLmedia服务，调用ZLmedia接口，传入摄像头的信息。ZLmedia会崩溃，经测试，海康摄像头不会崩溃，大华摄像头会崩溃。其他品牌测试中。
![image](https://user-images.githubusercontent.com/24712939/115987008-cd932b00-a5e5-11eb-8c8e-07ccb90e8d60.png)
![image](https://user-images.githubusercontent.com/24712939/115987111-3aa6c080-a5e6-11eb-96e9-90c8f06058b8.png)

**bug产生时的使用场景**
- 调用ZLmedia接口，传入摄像头的信息。

**bug是否可以复现，怎么复现**
- 编译后。运行./MediaServer，调用ZMmedai接口

**zlm代码git commit hash值**
- 0bb87858a3b0f19435e2be65669905d92bceed36

**操作系统环境**
- 乌班图20.04，64位，ARM，CPU是瑞芯微RK3399

**Comment by xia-chu** [comment]
你gdb调试下 看看崩溃时的函数调用栈

**Comment by xia-chu** [comment]
这个问题是sps pps应该有问题导致的 按道理不会崩溃 由于你是嵌入式平台 所以程序推出了 原因是有些平台 在c函数中不能抛异常

**Comment by workgo7** [comment]
你好，这是拉流时候的抓的包，应该怎么找对应的sps pps。
![160直连arm的抓包](https://user-images.githubusercontent.com/80454341/116640804-f298ec80-a99d-11eb-92f6-b018c185f89b.png)
这是decode成rtsp流：
![160直连arm转rtsp](https://user-images.githubusercontent.com/80454341/116640855-11977e80-a99e-11eb-9eb5-e1fb609a8159.png)

**Comment by xia-chu** [comment]
一般在sdp中 你能不能把rtsp url暴露到公网 我测试下？ 可以用frp暴露

**Comment by workgo7** [comment]
rtsp://47.112.135.104:5082/11
这是公网地址，可以试试看。

**Comment by xia-chu** [comment]
> rtsp://47.112.135.104:5082/11

不对啊 test_player播放完全正常啊 说明zlm完全兼容这个流啊
<img width="1153" alt="图片" src="https://user-images.githubusercontent.com/11495632/117541157-1d8ddb00-b045-11eb-8002-926c609e59a8.png">

**Comment by workgo7** [comment]
我在arm架构下用接口addStreamProxy添加拉流代理还是报错误，x86的就没有问题
![image](https://user-images.githubusercontent.com/80454341/117595980-ca1aaa80-b174-11eb-9257-531494f70ca6.png)
![image](https://user-images.githubusercontent.com/80454341/117596277-98eeaa00-b175-11eb-87d9-f7c9a796cdb1.png)

**Comment by xia-chu** [comment]
这个应该是录制的问题 你注释掉这句代码试试：
![image](https://user-images.githubusercontent.com/11495632/117600507-a4929e80-b17e-11eb-8629-a5d4ddfa7953.png)
