### ISSUE TITLE
[技术咨询]webrtc编译libsrtp2

### ISSUE THREAD

**Issue by isCZW** [xia-chu/ZLMediaKit#846]
**咨询的功能模块**
dev版本的webrtc怎么推拉流

**咨询的具体内容和问题**
dev版本的webrtc怎么推拉流

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by wasphin** [comment]
1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 ``srtp2`` 时需要 ``--enable openssl``, 如果 ``srtp2`` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35 手动定义 ``SRTP_PREFIX`` 指向 ``srtp2`` 安装路经;
1. 编译完成, 运行, 浏览器端打开 ``http://localhost:80/webrtc`` 有相应的 ``play/push`` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
1. 在通过 ``rtsp/rtmp`` 推流到 ``zlm`` 后, 可以使用 ``play`` 进行播放, ``push`` 暂时未测试, 应该类似.

**Comment by chuankunhu** [comment]
> 1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 `srtp2` 时需要 `--enable-openssl`, 如果 `srtp2` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35
>     手动定义 `SRTP_PREFIX` 指向 `srtp2` 安装路经;
> 2. 编译完成, 运行, 浏览器端打开 `http://localhost:80/webrtc` 有相应的 `play/push` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
> 3. 在通过 `rtsp/rtmp` 推流到 `zlm` 后, 可以使用 `play` 进行播放, `push` 暂时未测试, 应该类似.

使用demo时，点击开始，出现下面错误，请问是什么原因
[RTCPusherPlayer] DOMException: Requested device not found

**Comment by xia-chu** [comment]
你没摄像头



发自我的iPhone


------------------ Original ------------------
From: chuankunhu ***@***.***&gt;
Date: Tue,Apr 27,2021 4:28 PM
To: xia-chu/ZLMediaKit ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [xia-chu/ZLMediaKit] webrtc (#846)





   
需要系统有安装/编译 srtp2, 编译 srtp2 时需要 --enable-openssl, 如果 srtp2 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35
 手动定义 SRTP_PREFIX 指向 srtp2 安装路经; 

编译完成, 运行, 浏览器端打开 http://localhost:80/webrtc 有相应的 play/push 页面可以进行测试, 如果端口不是 80 需要相应做调整; 

在通过 rtsp/rtmp 推流到 zlm 后, 可以使用 play 进行播放, push 暂时未测试, 应该类似. 
  
使用demo时，点击开始，出现下面错误，请问是什么原因
 [RTCPusherPlayer] DOMException: Requested device not found

**Comment by orgotF** [comment]
> 1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 `srtp2` 时需要 `--enable-openssl`, 如果 `srtp2` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35 手动定义 `SRTP_PREFIX` 指向 `srtp2` 安装路经;
> 2. 编译完成, 运行, 浏览器端打开 `http://localhost:80/webrtc` 有相应的 `play/push` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
> 3. 在通过 `rtsp/rtmp` 推流到 `zlm` 后, 可以使用 `play` 进行播放, `push` 暂时未测试, 应该类似.

dev分支编译报错，请问是什么问题：
![error](https://user-images.githubusercontent.com/41140485/123386261-0c833400-d5c9-11eb-8a1d-a58aa5f78920.png)

**Comment by SuperChrisliu** [comment]
> 1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 `srtp2` 时需要 `--enable-openssl`, 如果 `srtp2` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35 手动定义 `SRTP_PREFIX` 指向 `srtp2` 安装路经;
> 2. 编译完成, 运行, 浏览器端打开 `http://localhost:80/webrtc` 有相应的 `play/push` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
> 3. 在通过 `rtsp/rtmp` 推流到 `zlm` 后, 可以使用 `play` 进行播放, `push` 暂时未测试, 应该类似.

如果在编译srtp时指定了openssl的路径，那么在编译ZLMediaKit时也必须指定openssl路径，不然会提示srtp找不到。。。很尴尬

**Comment by wzrove** [comment]
> 1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 `srtp2` 时需要 `--enable-openssl`, 如果 `srtp2` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35 手动定义 `SRTP_PREFIX` 指向 `srtp2` 安装路经;
> 2. 编译完成, 运行, 浏览器端打开 `http://localhost:80/webrtc` 有相应的 `play/push` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
> 3. 在通过 `rtsp/rtmp` 推流到 `zlm` 后, 可以使用 `play` 进行播放, `push` 暂时未测试, 应该类似.

> 播放webrtc流的时候报下面错了。大佬救救
```
2022-10-21 16:41:44.435 E MediaServer[11393-event poller 1] SrtpSession.cpp:214 SrtpSession | srtp_create() failed: unspecified failure (srtp_err_status_fail)

2022-10-21 16:41:44.435 W MediaServer[11393-event poller 1] WebRtcSession.cpp:77 onError | 5-133(172.19.112.1:61923) MS_THROW_ERROR

```

**Comment by xia-chu** [comment]
> > 1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 `srtp2` 时需要 `--enable-openssl`, 如果 `srtp2` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35 手动定义 `SRTP_PREFIX` 指向 `srtp2` 安装路经;
> > 2. 编译完成, 运行, 浏览器端打开 `http://localhost:80/webrtc` 有相应的 `play/push` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
> > 3. 在通过 `rtsp/rtmp` 推流到 `zlm` 后, 可以使用 `play` 进行播放, `push` 暂时未测试, 应该类似.
> 
> > 播放webrtc流的时候报下面错了。大佬救救
> 
> ```
> 2022-10-21 16:41:44.435 D MediaServer[11393-event poller 1] SrtpSession.cpp:97 DepLibSRTP | libsrtp version: "libsrtp2 2.3.0"
> 
> 2022-10-21 16:41:44.435 E MediaServer[11393-event poller 1] SrtpSession.cpp:214 SrtpSession | srtp_create() failed: unspecified failure (srtp_err_status_fail)
> 
> 2022-10-21 16:41:44.435 W MediaServer[11393-event poller 1] WebRtcSession.cpp:77 onError | 5-133(172.19.112.1:61923) MS_THROW_ERROR
> ```

编译srtp时有指定 --enable-openssl没

**Comment by wzrove** [comment]
> 

解决了~ 重新拉仓库源码编译了一次后面不报错了。

**Comment by wzrove** [comment]
> > > 1. 需要系统有安装/编译 [srtp2](https://github.com/cisco/libsrtp), 编译 `srtp2` 时需要 `--enable-openssl`, 如果 `srtp2` 未安装到标准目录, 可以参考 https://github.com/xia-chu/ZLMediaKit/blob/f69a23565d3ef98ab181ff2ce1965294a1bbda76/cmake/FindSRTP.cmake#L35 手动定义 `SRTP_PREFIX` 指向 `srtp2` 安装路经;
> > > 2. 编译完成, 运行, 浏览器端打开 `http://localhost:80/webrtc` 有相应的 `play/push` 页面可以进行测试, 如果端口不是 80 需要相应做调整;
> > > 3. 在通过 `rtsp/rtmp` 推流到 `zlm` 后, 可以使用 `play` 进行播放, `push` 暂时未测试, 应该类似.
> > 
> > 
> > > 播放webrtc流的时候报下面错了。大佬救救
> > 
> > 
> > ```
> > 2022-10-21 16:41:44.435 D MediaServer[11393-event poller 1] SrtpSession.cpp:97 DepLibSRTP | libsrtp version: "libsrtp2 2.3.0"
> > 
> > 2022-10-21 16:41:44.435 E MediaServer[11393-event poller 1] SrtpSession.cpp:214 SrtpSession | srtp_create() failed: unspecified failure (srtp_err_status_fail)
> > 
> > 2022-10-21 16:41:44.435 W MediaServer[11393-event poller 1] WebRtcSession.cpp:77 onError | 5-133(172.19.112.1:61923) MS_THROW_ERROR
> > ```
> 
> 编译srtp时有指定 --enable-openssl没

有的按着wiki来的，解决了~ 拉`srtp`仓库源码编译了一次后面不报错了。能播webrtc视频了。
