### ISSUE TITLE
[技术咨询]play rtsp timeout

### ISSUE THREAD

**Issue by RogueCultivators** [xia-chu/ZLMediaKit#847]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

rtsp推流

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

使用代理接口进行rtsp代理  返回play rtsp timeout  但是客户端播放没有问题，docker环境中ip能ping通，
虚拟网卡是否会对这个有影响？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个问题基本能断定就是网络不通 建议再docker中telnet rtsp url的ip和端口，先看看tcp能不能通

**Comment by RogueCultivators** [comment]
telnet: could not resolve 192.168.188.201:28554/telnet: Name or service not known

我通过curl也行

**Comment by xia-chu** [comment]
telnet 指定端口好像是这样 ：
telnet 192.168.188.201 28554

**Comment by RogueCultivators** [comment]
已经处理好了，感谢大佬，docker使用主机网络解决的，估计是因为虚拟网络导致的网络不通


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月28日 17:45:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xia-chu/ZLMediaKit] [技术咨询]play rtsp timeout (#847)




 
telnet 指定端口好像是这样 ：
 telnet 192.168.188.201 28554
