### ISSUE TITLE
建议增加支持webrtc的c客户端sdk

### ISSUE THREAD

**Issue by wuhenfeike** [xia-chu/ZLMediaKit#852]
需求：嵌入式端使用c编码，采集到的音视频数据需要发送到app端。app端采用jni封装c接口。

**Comment by xia-chu** [comment]
zlm的webrtc定位是sfu服务器 只支持ice-lite模式 所以不能部署在NAT内 只能部署在公网上

**Comment by xia-chu** [comment]
你说的c客户端是不是作为rtc播放器或推流器啊

**Comment by wuhenfeike** [comment]
客户端是指rtc播放器和推流器，可以支持下么？

**Comment by xia-chu** [comment]
有点难 因为zlm对ice的支持是有限的 只支持ice-lite模式 如果要支持完整的ice，要引入诸如libnice之类的库 很麻烦
既然是客户端 你为什么不直接用谷歌的代码呢

**Comment by wuhenfeike** [comment]
google的太繁重，如果跑在嵌入式设备上不太可行。

**Comment by xia-chu** [comment]
在zlm支持full ice前 你说的这个基本不可实现
