### ISSUE TITLE
[技术咨询]使用ws协议播放flv连接断线

### ISSUE THREAD

**Issue by wozl** [xia-chu/ZLMediaKit#854]
您好，这边我使用您的产品有一个问题，就是网络不稳定或者网络稳定的情况下，ws协议拉取流进行播放会在7-8分钟后客户端会自动断开连接，后台日志是recv close request from client。
您这边的有心跳检测，客户端不主动发送心跳就会自动断开连接吗？
我使用的播放器是B站开源的flv.js，直接填写的服务器地址，协议ws，拉取flv格式的流。

**Comment by xia-chu** [comment]
这个是客户端主动关闭的 你是不是后台播放ws-flv?

**Comment by wozl** [comment]
> 这个是客户端主动关闭的 你是不是后台播放ws-flv?

嗯嗯，是的。我目前的业务架构是这样的，摄像头推流岛Nginx,然后Nginx转为rtmp后再推流给您的ZLM服务器，前端客户端是web，使用flv.js通过ws协议再去找zlm拉取后缀为flv的视频流。

**Comment by xia-chu** [comment]
后台播放可能会导致浏览器回收websocket资源



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wozl ***@***.***&gt;
发送时间: 2021年5月10日 09:07
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] [技术咨询]使用ws协议播放flv连接断线 (#854)

**Comment by wozl** [comment]
> 后台播放可能会导致浏览器回收websocket资源 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wozl ***@***.***&gt; 发送时间: 2021年5月10日 09:07 收件人: xia-chu/ZLMediaKit ***@***.***&gt; 抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[xia-chu/ZLMediaKit] [技术咨询]使用ws协议播放flv连接断线 (#854)

嗯嗯，好的，谢谢您的恢复，这边我再去研究研究问题吧，应该是和您的ZLM没有关系。

**Comment by Z-VegetableBird** [comment]
你好。请问下后来有什么解决办法嘛？我在浏览器播放的时候也出现了这个问题
