### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by xlangyun** [xia-chu/ZLMediaKit#856]
请推荐下讲解该流媒体服务器代码的文章，尤其是GB28181的流转发这块，多谢。
后续是否有支持GB35114的计划

**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
issue模板的意义是让提问者提正规的issue 你看你提的issue正规吗？后面哪些东西留着过年啊？
