### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by cruiseou** [xia-chu/ZLMediaKit#857]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
想把zlm安装成windows服务  可以吗
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
可以 有人已经这么做了 你可以了解下怎么做成服务 我之前接过这样一个pr 但是测试没通过 就没合并 你可以自己研究下
