### ISSUE TITLE
桌面共享[技术咨询]

### ISSUE THREAD

**Issue by colaicode** [xia-chu/ZLMediaKit#863]
使用ffmpeg进行桌面录制然后推流到ZLM，然后使用ffplay进行播放，发现延时很严重
<img width="720" alt="Snipaste_2021-05-15_13-54-36" src="https://user-images.githubusercontent.com/25426335/118350038-1efc5d80-b587-11eb-8fed-cdeca6086faf.png">

**Comment by xia-chu** [comment]
看下wiki关注延时的篇章



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: colaicode ***@***.***&gt;
发送时间: 2021年5月15日 14:09
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] 桌面共享[技术咨询] (#863)





 
使用ffmpeg进行桌面录制然后推流到ZLM，然后使用ffplay进行播放，发现延时很严重
