### ISSUE TITLE
[功能请求]有计划支持AV1吗？

### ISSUE THREAD

**Issue by ziyaofeng** [xia-chu/ZLMediaKit#866]
有计划支持AV1吗？

配合WebRTC，方便实现浏览器端的视频应用

**Comment by xia-chu** [comment]
如果只是webrtc 支持AV1，那么很简单的。后面还有rtsp rtmp hls mp4 等协议支持av1 那么就比较麻烦了

**Comment by ziyaofeng** [comment]
是啊，确实不容易

**Comment by xia-chu** [comment]
后续webrtc肯定会支持av1的 有精力再慢慢让rtsp rtmp hls mp4等支持av1

**Comment by Haoxw** [comment]
？

> 后续webrtc肯定会支持av1的 有精力再慢慢让rtsp rtmp hls mp4等支持av1

您好，请问最新的版本AV1有进展吗？

**Comment by xia-chu** [comment]
webrtc/rtsp已经支持AV1了 只不过不支持转其他协议
