### ISSUE TITLE
[技术咨询]截图功能

### ISSUE THREAD

**Issue by cruiseou** [xia-chu/ZLMediaKit#868]
**咨询的功能模块**
截图功能
/index/api/getSnap

**咨询的具体内容和问题**
请问 这里面的参数 url 如何定义 用postmen 试了下 时好时坏的 有时候截不到图片

**Comment by xia-chu** [comment]
url是你需要截图的流地址，这个地址可以是zlm的流地址也可以是第三方服务器的 也就是这个getSnap接口既可以给zlm自己截图 也可以给第三方服务器截图 支持的url可以很多种，包括直播的、点播的甚至是本地磁盘文件，只要FFmpeg支持就行

**Comment by xia-chu** [comment]
切记有些URL FFmpeg不支持的 ，包括ws-flv地址，同时一些非标准的流，FFmpeg也不支持，包括265的rtmp
