### ISSUE TITLE
[技术咨询] HLS和restful的端口能否分开配置

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#870]
**咨询的功能模块**
- HTTP部分端口配置

**咨询的具体内容和问题**
- 目前所有HTTP请求都是使用同一端口，如果使用HLS在公网播放视频的话，需要暴露HTTP端口，这样的话，restful api的端口等于也暴露在公网之上了，是否能够将restful api的端口单独配置

**Comment by xia-chu** [comment]
目前不支持 确实有这个风险，这个可能后面可以考虑加上
