### ISSUE TITLE
[技术咨询]多个站点共用同一个ZLMediaKit服务，HTTP HOOK API如何设置

### ISSUE THREAD

**Issue by janver** [xia-chu/ZLMediaKit#872]
HTTP HOOK API  的 http header 是否可以带上 Vhost 参数，这样就可以根据 Vhost 反向代理到对应的站点。
或者有其它更好方法，高手们请指教一下。

**Comment by xia-chu** [comment]
http hook大部分接口的json body都有vhost参数，另外也有MediaServerID参数，这样参数应该足矣做业务分发，
我建议你业务服务器先接收zlm的hook，你的业务服务器根据hook参数内容再分发

**Comment by janver** [comment]
主要是想用 iis 的 url rewrite 来分发， 业务系统不处理分发，但 url rewrite 不能根据 json body 中的 vhost参数 重定向

**Comment by xia-chu** [comment]
嗯 可以实现下 你告诉我http头格式





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: janver ***@***.***&gt;
发送时间: 2021年5月19日 16:16
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] [技术咨询]多个站点共用同一个ZLMediaKit服务，HTTP HOOK API如何设置 (#872)





 
主要是想用 iis 的 url rewrite 来分发， 业务系统不处理分发，但 url rewrite 不能根据 json body 中的 vhost参数 重定向

**Comment by janver** [comment]
// zml 的 http header 加 X-VHOST
X-VHOST: xxx.baidu.com

//  iis url rewrite 就可以这样实现
<system.webServer>
    <rewrite>
        <rules>
            <rule name="zml_hook" stopProcessing="true">
                <match url="^api/mediaserver/hook/(.*)" />
                <conditions>
                    <add input="{HTTP_X_VHOST}" pattern="^(.+)$" />
                </conditions>
                <action type="Rewrite" url="https://{C:1}/{R:0}" />
            </rule>
        </rules>
    </rewrite>
</system.webServer>

**Comment by xia-chu** [comment]
好的 周末我实现下
