### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by 13659294036** [xia-chu/ZLMediaKit#873]
正在研究的项目ipc设备支持websocket协议，希望zlm可以支持websocket-rtsp
看文档，zml暂时不支持websocket-rtsp想问一下目前zlm不支持websocket-rtsp原因
如果做二次开发，自己实现websocket-rtsp,难度大吗？

**Comment by xia-chu** [comment]
zlm支持任何tcp协议转换成websocket

**Comment by xia-chu** [comment]
```c++
auto rtspSrv = std::make_shared<TcpServer>();
rtspSrv->start<WebSocketSession<RtspSession, HttpSession, WebSocketHeader::BINARY> >(rtspPort);
```

**Comment by xia-chu** [comment]
借助WebSocketSession模板，zlm支持现有任何TcpSession类协议转换成websocket

**Comment by 13659294036** [comment]
目前zlm暂时不支持websocket-rtsp，需要简单的修改代码实现是吗

**Comment by xia-chu** [comment]
我已经给你贴上代码了啊 你把那句代码放到main函数就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 13659294036 ***@***.***&gt;
发送时间: 2021年5月19日 13:48
收件人: xia-chu/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xia-chu/ZLMediaKit] [功能请求] (#873)





 
目前zlm暂时不支持websocket-rtsp，需要简单的修改代码实现是吗

**Comment by 13659294036** [comment]
好的，多谢

**Comment by 13659294036** [comment]
如果加上你这句代码，服务器是不是不能同时支持tcp-rtsp和websocket-rtsp？如果可以同时支持那就是说跟main函数原有的rtspSrv->start<RtspSession>(rtspPort);可以同时存在并启动两个服务。不好意思我是刚接触这方面的东西，有些不太理解，多谢回复

**Comment by xia-chu** [comment]
> ```c++
> auto rtspSrvWS = std::make_shared<TcpServer>();
> rtspSrvWS->start<WebSocketSession<RtspSession, HttpSession, WebSocketHeader::BINARY> >(1554);
> ```

改成这样1554就是rtsp-ws服务器了
