### ISSUE TITLE
[技术咨询] HLS修改存储目录后，无法播放

### ISSUE THREAD

**Issue by mayomeng** [xia-chu/ZLMediaKit#874]
**咨询的功能模块**
- HLS存储目录配置

**咨询的具体内容和问题**
- 当http.rootPath和hls.filePath配置为同一目录时，可以正常通过HLS播放视频，否则无法通过HLS播放视频，请问这两个配置有什么关系，既然必须为同一目录，为什么还要分为两个配置项？

**Comment by mayomeng** [comment]
我试着将http.rootPath修改为和hls.filePath同样的目录后，能够正常通过HLS播放视频了，请问这两个配置有什么关系吗？如果必须配置为一样的目录，为什么还要分成两个配置项？

**Comment by xia-chu** [comment]
因为存在这种可能性 就是zlm生产hls文件 但是用nginx这种第三方的http服务器
