### ISSUE TITLE
[BUG] "git submodule update --init" fail

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#875]
D:\MediaServer\ZLMediaKit>git submodule update --init
Submodule 'ZLToolKit' (https://gitee.com/xia-chu/ZLToolKit) registered for path '3rdpart/ZLToolKit'
Submodule '3rdpart/media-server' (https://gitee.com/xia-chu/media-server) registered for path '3rdpart/media-server'
Cloning into 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://gitee.com/xia-chu/ZLToolKit' into submodule path 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit' failed
Failed to clone '3rdpart/ZLToolKit'. Retry scheduled
Cloning into 'D:/MediaServer/ZLMediaKit/3rdpart/media-server'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://gitee.com/xia-chu/media-server' into submodule path 'D:/MediaServer/ZLMediaKit/3rdpart/media-server' failed
Failed to clone '3rdpart/media-server'. Retry scheduled
Cloning into 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://gitee.com/xia-chu/ZLToolKit' into submodule path 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit' failed
Failed to clone '3rdpart/ZLToolKit' a second time, aborting

**Comment by wasphin** [comment]
If the https://gitee.com is not pingable/available, maybe you can try to set an instead url like this:
```
git config url.https://github.com/xia-chu/ZLToolKit.instreadof    https://gitee.com/xia-chu/ZLToolKit
git config url.https://github.com/xia-chu/media-server.instreadof https://gitee.com/xia-chu/media-server
```

**Comment by pubpy2015** [comment]
Thanks but the error still exist:

D:\MediaServer>git clone https://github.com/xia-chu/ZLMediaKit.git
Cloning into 'ZLMediaKit'...
remote: Enumerating objects: 18405, done.
remote: Counting objects: 100% (1683/1683), done.
remote: Compressing objects: 100% (609/609), done.
remote: Total 18405 (delta 1151), reused 1559 (delta 1067), pack-reused 16722Receiving objects: 100% (18405/18405), 124.21 MiB | 2.71 MiB/s
Receiving objects: 100% (18405/18405), 125.09 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (13805/13805), done.

D:\MediaServer>git config url.https://github.com/xia-chu/ZLToolKit.instreadof    https://gitee.com/xia-chu/ZLToolKit
fatal: not in a git directory

D:\MediaServer>cd zlmediakit

D:\MediaServer\ZLMediaKit>git config url.https://github.com/xia-chu/ZLToolKit.instreadof    https://gitee.com/xia-chu/ZLToolKit

D:\MediaServer\ZLMediaKit>git config url.https://github.com/xia-chu/media-server.instreadof https://gitee.com/xia-chu/media-server

D:\MediaServer\ZLMediaKit>git submodule update --init
Submodule 'ZLToolKit' (https://gitee.com/xia-chu/ZLToolKit) registered for path '3rdpart/ZLToolKit'
Submodule '3rdpart/media-server' (https://gitee.com/xia-chu/media-server) registered for path '3rdpart/media-server'
Cloning into 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://gitee.com/xia-chu/ZLToolKit' into submodule path 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit' failed
Failed to clone '3rdpart/ZLToolKit'. Retry scheduled
Cloning into 'D:/MediaServer/ZLMediaKit/3rdpart/media-server'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://gitee.com/xia-chu/media-server' into submodule path 'D:/MediaServer/ZLMediaKit/3rdpart/media-server' failed
Failed to clone '3rdpart/media-server'. Retry scheduled
Cloning into 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://gitee.com/xia-chu/ZLToolKit' into submodule path 'D:/MediaServer/ZLMediaKit/3rdpart/ZLToolKit' failed
Failed to clone '3rdpart/ZLToolKit' a second time, aborting

D:\MediaServer\ZLMediaKit>

**Comment by xia-chu** [comment]
Please open the file named `.gitmodules`, and modfy it :
```bash
[submodule "ZLToolKit"]
	path = 3rdpart/ZLToolKit
	url = https://github.com/xia-chu/ZLToolKit
[submodule "3rdpart/media-server"]
	path = 3rdpart/media-server
	url = https://github.com/xia-chu/media-server

```

and save it, then exec in shell ：
```bash
git submodule sync && git submodule update --init
```

**Comment by pubpy2015** [comment]
Successed!
Thanks
