### ISSUE TITLE
[功能请求] Get recording status in getMediaList API

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#876]
**描述该功能的用处，可以提供相关资料描述该功能**

Only call getMediaList API will get all infomations of stream

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

For get stream status, i must call getMediaList API
For check recording status of each stream, i must call isRecording API.
If want checking status system contain 100 streams, I must call 1 x (getMediaList) + 100 x (isRecording)
=> maybe make CPU usage high

**描述你期望实现该功能的方式和最终效果**

add isRecording in response of getMediaList API

**Comment by xia-chu** [comment]
ok thank for you feedback, I'll make it over the weekend
